### ISSUE TITLE
大佬建议你开个tg群，方便一起开发

### ISSUE THREAD

**Issue by OJBKSS-dev** [Jrohy/trojan#1]
首先，很高兴作者能够发起此项目，我觉得有必要为此开发WEB UI界面代替命令行，这样也更佳直观，更佳具有价值，tg:https://t.me/ojbkssr

**Comment by Jrohy** [comment]
安全起见不会建群，web ui暂时不考虑，后面如果加了web可能会考虑下

**Comment by OJBKSS-dev** [comment]
好的，尊重作者选择，我也会默默关注，感谢付出
