### ISSUE TITLE
支持流量周期套餐刷新吗

### ISSUE THREAD

**Issue by vinyo** [Jrohy/trojan#10]
支持流量周期套餐刷新吗

**Comment by Jrohy** [comment]
暂不支持，后面可能会加

**Comment by shengshengman0** [comment]
> 支持流量周期套餐刷新吗

开机场吗？

**Comment by vinyo** [comment]
@shengshengman0 想开

**Comment by Jrohy** [comment]
@vinyo  机场其实不太适合，并没有系统用户概念只有admin用户才能登录, 比较适合个人用

**Comment by shengshengman0** [comment]
> @vinyo 机场其实不太适合，并没有系统用户概念只有admin用户才能登录, 比较适合个人用

这个是不是只有第一个登陆的才是admin，其他人再访问web界面是登不进面板的

**Comment by Jrohy** [comment]
@shengshengman0 是的目前只记录了admin的密码

**Comment by Jrohy** [comment]
@shengshengman0 目前新版支持普通用户登录进去看使用流量了
