### ISSUE TITLE
如何完整卸载Trojan脚本所安装的所有应用

### ISSUE THREAD

**Issue by DaedalusT** [Jrohy/trojan#101]
用whereis查看docker，dockerd，containerd，删除重启以后再运行脚本，依旧提示ID重复

**Comment by Jrohy** [comment]
Docker不用卸载都行把，运行卸载命令就好

**Comment by DaedalusT** [comment]
> Docker不用卸载都行把，运行卸载命令就好

不知道你有没有试过运行完脚本后，再使用“一键卸载”命令，第二次安装的时候运行安装MariaDB的时候，docker会提示Image ID reused，我之后试了docker rm，无论如何，MariaDB一直显示“启动中”却无法启动

**Comment by Jrohy** [comment]
@DaedalusT 确实有问题脚本卸载部分，没有移除mariadb容器

**Comment by Jrohy** [comment]
@DaedalusT 已修复卸载数据库的bug
