### ISSUE TITLE
可否考虑将web访问路径多加个层次

### ISSUE THREAD

**Issue by aceslup** [Jrohy/trojan#102]
该项目正常访问/就是后台了。多数情况下，/是个展示页面，用于正常伪装。这个后台不是想让人直接看的，加个类似/admin的层次，做nginx转发的时候，可以稍微隐藏下后台，也可减少不必要的攻击。

**Comment by Jrohy** [comment]
你可以修改下web端口，让出80给nginx来运行，然后nginx通过 路由proxy到trojan web后台
https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3

**Comment by aceslup** [comment]
尝试过，遇到以下几个问题。
1. 伪装页面js/css等文件，也是/js 或 /css 开头，就会冲突了。这是我为何比较建议后端多加一层的原因，比如/admin/js，这样和伪装不冲突。
2. proxy_pass转发的web面板，trojan管理选项走 ws://域名/trojan/log接口好像不方便工作。

**Comment by aceslup** [comment]
目前还遇到个问题想请教。
3. trojan管理的，启动，停止、重启，底层是不是通过类似systemctl start|stop|restart trojan来实现。
4. trojan管理的，更新，底层实现是更新的是您的trojan，还是trojan原作者的
5. 您的一键脚本安装后，trojan管理的启动功能似乎不能正常工作。故才想了解问题3。

**Comment by Jrohy** [comment]
web后台是systemctl status trojan-web

**Comment by Jrohy** [comment]
```
        location /admin {
            proxy_pass   http://localhost:81/;
        }
        location /js {
            proxy_pass   http://localhost:81/js;
        }
        location /css {
            proxy_pass   http://localhost:81/css;
        }
        location /vendor {
            proxy_pass   http://localhost:81/vendor;
        }
        location /trojan  {
            proxy_pass   http://localhost:81/trojan;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
        location /common  {
            proxy_pass   http://localhost:81/common;
        }
        location /auth  {
            proxy_pass   http://localhost:81/auth;
        }
```
简单测了下这样nginx这样配置可以

**Comment by aceslup** [comment]
> web后台是systemctl status trojan-web
> 更新是指trojan核心更新，管理程序更新要运行更新脚本
> trojan管理是通过systemctl start|stop|restart trojan来实现的
我看了下一键脚本，trojan二进制文件是您的github上的，应该是加入了web面板特性，目前您的版本是v2.6.5，trojan核心版本是v1.15.1。点击更新trojan核心的话，trojan二进制文件不会被覆盖么？

**Comment by aceslup** [comment]
> ```
>         location /admin {
>             proxy_pass   http://localhost:81/;
>         }
>         location /js {
>             proxy_pass   http://localhost:81/js;
>         }
>         location /css {
>             proxy_pass   http://localhost:81/css;
>         }
>         location /vendor {
>             proxy_pass   http://localhost:81/vendor;
>         }
>         location /trojan  {
>             proxy_pass   http://localhost:81/trojan;
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "Upgrade";
>             proxy_set_header Host $host;
>         }
>         location /common  {
>             proxy_pass   http://localhost:81/common;
>         }
>         location /auth  {
>             proxy_pass   http://localhost:81/auth;
>         }
> ```
> 
> 简单测了下这样nginx这样配置可以

我来尝试一下，稍等反馈。多谢。

**Comment by Jrohy** [comment]
不会的，只会更新trojan核心， trojan二进制文件无法自己更新自己(被占用)

**Comment by aceslup** [comment]
> 不会的，只会更新trojan核心， trojan二进制文件无法自己更新自己(被占用)

这个疑惑，我似乎明白了。两个不是同一个。我还是看得没仔细。
/usr/local/bin/trojan web
/usr/bin/trojan/trojan

**Comment by aceslup** [comment]
> ```
>         location /admin {
>             proxy_pass   http://localhost:81/;
>         }
>         location /js {
>             proxy_pass   http://localhost:81/js;
>         }
>         location /css {
>             proxy_pass   http://localhost:81/css;
>         }
>         location /vendor {
>             proxy_pass   http://localhost:81/vendor;
>         }
>         location /trojan  {
>             proxy_pass   http://localhost:81/trojan;
>             proxy_http_version 1.1;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection "Upgrade";
>             proxy_set_header Host $host;
>         }
>         location /common  {
>             proxy_pass   http://localhost:81/common;
>         }
>         location /auth  {
>             proxy_pass   http://localhost:81/auth;
>         }
> ```
> 
> 简单测了下这样nginx这样配置可以

折腾一番，有以下总结：
6. 伪页如果含有/js或/css等，并不能正常显示，除非更改伪页代码（该方案可行，伪页代码一般不多）
7. 过https伪页，trojan管理可停止无法重启（毕竟https走的是trojan，trojan死了https就死了）；过http伪页，trojan管理可用（直接走trojan-web，trojan死不死和它没关系）
8. 本意只是想只暴露443，使用https伪页进行用户管理。不对trojan核心管理，我的想法应该与您开发的trojan管理特性相违背了。这是我的使用问题。

**Comment by aceslup** [comment]
发现一个新问题。
删除最后一个用户后，页面会出现mysql连接失败。但此时的面板依旧能正常使用的。重新添加用户，则不再提示。

**Comment by Jrohy** [comment]
不能没有用户的，没有用户空表trojan核心好像会报错，所以全新安装的时候都会帮建个用户

**Comment by aceslup** [comment]
> 不能没有用户的，没有用户空表trojan核心好像会报错，所以全新安装的时候都会帮建个用户

再请教个事，一键脚本何时安装了trojan核心呢？只看到有trojan-web管理程序

**Comment by aceslup** [comment]
```
server {
    listen  127.0.0.1:80 default_server;
    server_name  _;
    return  444;
}
server {
    listen  127.0.0.1:80;
    server_name  伪装的域名;
    root  html;
    location /admin {
        proxy_pass  http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
    }
    location ~* ^/(js|css|vendor|common|auth)/ {
        proxy_pass  http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $http_host;
    }
    location /trojan  {
        proxy_pass  http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
    }
}
```
以上是结合作者给出的方案完成的。仅适用以下几个需求，欢迎补充完善：
1. 不想对外公开其他端口，同时想通过https伪页进行用户管理
2. 伪页中无 src="(js|css|vendor|common|auth|trojan)" 这类资源的页面
3. 不使用trojan管理功能。日志可正常查看
