### ISSUE TITLE
重装后不能翻

### ISSUE THREAD

**Issue by alegoho** [Jrohy/trojan#103]
因为某些原因VPS重装后再装回这个面板，但手机和电脑客户端怎么也翻不了，路由上的插件设置完就可以翻，我已经换了一个域名，请问是什么问题？

**Comment by DaedalusT** [comment]
不贴log别人怎么帮

**Comment by alegoho** [comment]
Apr 24 09:25:30 ecs-TI9en trojan[11232]: [2020-04-24 09:25:30] [ERROR] 14.126.XX.XX:58366 cannot establish connection to remote server 66.220.152.28:443: Network is unreachable
Apr 24 09:25:30 ecs-TI9en trojan[11232]: [2020-04-24 09:25:30] [INFO] 14.126.XX.XX:58366 disconnected, 0 bytes received, 517 bytes sent, lasted for 1 seconds
Apr 24 09:25:31 ecs-TI9en trojan[11232]: [2020-04-24 09:25:31] [INFO] 14.126.XX.XX:58368 authenticated by authenticator (5e82187)
Apr 24 09:25:31 ecs-TI9en trojan[11232]: [2020-04-24 09:25:31] [INFO] 14.126.XX.XX:58368 requested connection to 66.220.152.28:443
Apr 24 09:25:31 ecs-TI9en trojan[11232]: [2020-04-24 09:25:31] [ERROR] 14.126.XX.XX:58368 cannot establish connection to remote server 66.220.152.28:443: Network is unreachable
Apr 24 09:25:31 ecs-TI9en trojan[11232]: [2020-04-24 09:25:31] [INFO] 14.126.XX.XX:58368 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
Apr 24 09:25:32 ecs-TI9en trojan[11232]: [2020-04-24 09:25:32] [INFO] 14.126.XX.XX:58370 authenticated by authenticator (5e82187)
Apr 24 09:25:32 ecs-TI9en trojan[11232]: [2020-04-24 09:25:32] [INFO] 14.126.XX.XX:58370 requested connection to 66.220.152.28:443
Apr 24 09:25:32 ecs-TI9en trojan[11232]: [2020-04-24 09:25:32] [ERROR] 14.126.XX.XX:58370 cannot establish connection to remote server 66.220.152.28:443: Network is unreachable
Apr 24 09:25:32 ecs-TI9en trojan[11232]: [2020-04-24 09:25:32] [INFO] 14.126.XX.XX:58370 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58364 disconnected, 397264 bytes received, 1361 bytes sent, lasted for 8 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58362 disconnected, 3575 bytes received, 336 bytes sent, lasted for 9 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58350 disconnected, 4353 bytes received, 1482 bytes sent, lasted for 10 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58328 disconnected, 40823 bytes received, 5516 bytes sent, lasted for 15 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58358 disconnected, 4419 bytes received, 3311 bytes sent, lasted for 10 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58356 disconnected, 3575 bytes received, 332 bytes sent, lasted for 10 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58354 disconnected, 3575 bytes received, 332 bytes sent, lasted for 10 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58338 disconnected, 495755 bytes received, 1611 bytes sent, lasted for 12 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58360 disconnected, 3575 bytes received, 336 bytes sent, lasted for 9 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58334 disconnected, 4173 bytes received, 330 bytes sent, lasted for 13 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58336 disconnected, 752346 bytes received, 2141 bytes sent, lasted for 13 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58280 disconnected, 518214 bytes received, 1572 bytes sent, lasted for 57 seconds
Apr 24 09:25:37 ecs-TI9en trojan[11232]: [2020-04-24 09:25:37] [INFO] 14.126.XX.XX:58346 disconnected, 3575 bytes received, 332 bytes sent, lasted for 10 seconds
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [ERROR] 14.126.XX.XX:58274 cannot establish connection to remote server 75.126.2.43:443: Connection timed out
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [INFO] 14.126.XX.XX:58274 disconnected, 0 bytes received, 227 bytes sent, lasted for 156 seconds
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [ERROR] 14.126.XX.XX:58266 cannot establish connection to remote server 75.126.2.43:443: Connection timed out
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [INFO] 14.126.XX.XX:58266 disconnected, 0 bytes received, 227 bytes sent, lasted for 168 seconds
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [ERROR] 14.126.XX.XX:58264 cannot establish connection to remote server 75.126.2.43:443: Connection timed out
Apr 24 09:27:11 ecs-TI9en trojan[11232]: [2020-04-24 09:27:11] [INFO] 14.126.XX.XX:58264 disconnected, 0 bytes received, 227 bytes sent, lasted for 168 seconds
Apr 24 09:28:43 ecs-TI9en trojan[11232]: [2020-04-24 09:28:43] [WARN] 13.94.34.24:41309 not trojan request, connecting to 127.0.0.1:80
Apr 24 09:29:40 ecs-TI9en trojan[11232]: [2020-04-24 09:29:40] [WARN] 13.94.34.24:35813 not trojan request, connecting to 127.0.0.1:80

我在面板里复制出来最后这段

**Comment by DaedalusT** [comment]
看下Trojan的运行状态，trojan status

**Comment by alegoho** [comment]
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-24 00:22:35 HKT; 14h ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 11232 (trojan)
    Tasks: 2 (limit: 1150)
   Memory: 6.1M
   CGroup: /system.slice/trojan.service
           └─11232 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

Apr 24 14:50:48 ecs-TI9en trojan[11232]: [2020-04-24 14:50:48] [INFO] 13.XX.XX.240:34051 disconnected, 0 bytes received, 517 bytes sent, lasted for 119 seconds
Apr 24 14:50:49 ecs-TI9en trojan[11232]: [2020-04-24 14:50:49] [INFO] 14.XX.XX.73:33278 authenticated by authenticator (5e82187)
Apr 24 14:50:49 ecs-TI9en trojan[11232]: [2020-04-24 14:50:49] [INFO] 14.XX.XX.73:33278 requested connection to 64.233.189.189:443
Apr 24 14:50:52 ecs-TI9en trojan[11232]: [2020-04-24 14:50:52] [INFO] 14.XX.XX.73:33280 authenticated by authenticator (5e82187)
Apr 24 14:50:52 ecs-TI9en trojan[11232]: [2020-04-24 14:50:52] [INFO] 14.XX.XX.73:33280 requested connection to 172.217.25.3:443
Apr 24 14:50:52 ecs-TI9en trojan[11232]: [2020-04-24 14:50:52] [WARN] 14.XX.XX.73:3681 not trojan request, connecting to 127.0.0.1:80
Apr 24 14:50:53 ecs-TI9en trojan[11232]: [2020-04-24 14:50:53] [INFO] 13.XX.XX.240:37109 disconnected, 0 bytes received, 206 bytes sent, lasted for 123 seconds
Apr 24 14:50:53 ecs-TI9en trojan[11232]: [2020-04-24 14:50:53] [INFO] 14.XX.XX.73:33282 authenticated by authenticator (5e82187)
Apr 24 14:50:53 ecs-TI9en trojan[11232]: [2020-04-24 14:50:53] [INFO] 14.XX.XX.73:33282 requested connection to 172.217.31.238:443
Apr 24 14:50:58 ecs-TI9en trojan[11232]: [2020-04-24 14:50:58] [INFO] 13.XX.XX.240:39499 disconnected, 0 bytes received, 204 bytes sent, lasted for 128 seconds

**Comment by alegoho** [comment]
我在管理页面地址前都有小锁，我在路由SSR PLUS插件上设置好也能翻，但用手机或者电脑客户端就不能翻，上YOUTUBE就提示
无效的证书
此网站的证书可能已过期或者是颁发给其他网站的.
此问题可能意味着有人尝试截取你和远程服务器间的数据通讯.
请检查地址栏内的网址是否正确.

错误码 107 (net::ERR_SSL_PROTOCOL_ERROR)

**Comment by Jrohy** [comment]
说不定过期了，得检查下证书有效性，或者重新签证书

**Comment by alegoho** [comment]
在那里可以查看证书的有效性？重新签证书是在TROJAN命令下那个可以吗？要不要换域名？

**Comment by Jrohy** [comment]
trojan命令里面安装管理里面有

**Comment by alegoho** [comment]
> trojan命令里面安装管理里面有

试过了，还是这样，我还换了几个系统安装，还是一样，这个VPS就第一次安装的时候成功所有设置都可以翻，后面怎么装都是这样

**Comment by alegoho** [comment]
> trojan命令里面安装管理里面有

换了N个系统重装，终于可以了，我也不知道什么问题
