### ISSUE TITLE
 登录界面能够有改进下

### ISSUE THREAD

**Issue by liaobadadi** [Jrohy/trojan#104]
![Clipboard 1](https://user-images.githubusercontent.com/61466838/80089999-69ccc100-8591-11ea-9710-ebaa1600d7ac.jpg)

Trojan 写在登录界面上，能不能该成客户管理系统，或者等等。
希望登录的主页是个导航网站，好123，等等。

**Comment by liaobadadi** [comment]
### 导航页作为主页，平时还能用自己的网站导航，有个登录按钮，然后出来登录框，那就不要太完美

**Comment by liaobadadi** [comment]
![Capture](https://user-images.githubusercontent.com/61466838/80171548-418aa400-861d-11ea-8016-ee1eec3ddef0.PNG)
我的界面这么简单，完全不知道哪里可以改标题

**Comment by Jrohy** [comment]
用admin用户登录进去改
