### ISSUE TITLE
Trojan Panel使用中的问题

### ISSUE THREAD

**Issue by KDLDK586** [Jrohy/trojan#105]
①在运行脚本过程中并无发现错误。但是在搭建完成后访问123.abc.com浏览器地址栏前边不会有绿色 
    的小锁🔒。会不会是SSL证书没有签发成功？
②在使用过程中，如果负载100用户左右最低需要VPS什么样的配置？
③在有些用户使用过程中，目前发现全局模式下使用chrome浏览器访问国内外网站都会有提示            
    “站点不安全”
④建议面板添加账号开通日期，方便计时。

**Comment by KDLDK586** [comment]
目前在安装时提示  
/usr/local/bin/trojan:行1: 未预期的符号 `newline' 附近有语法错误

是我个例还是都有问题？

**Comment by Jrohy** [comment]
没发现过有这问题，是不是下载得不完整，运行安装脚本更新下

**Comment by alegoho** [comment]
> trojan能用就代表证书申请到了，vps最低建议512mb+的

我在管理页面地址前都有小锁，我在路由SSR PLUS插件上设置好也能翻，但用手机或者电脑客户端就不能翻，上YOUTUBE就提示 
无效的证书
此网站的证书可能已过期或者是颁发给其他网站的. 
此问题可能意味着有人尝试截取你和远程服务器间的数据通讯. 
请检查地址栏内的网址是否正确.

错误码 107 (net::ERR_SSL_PROTOCOL_ERROR)

**Comment by yzhang-max** [comment]
证书目录在哪里啊，我在root里找不到

**Comment by Jrohy** [comment]
隐藏目录的，/root/.acme.sh下面
