### ISSUE TITLE
commands out of sync. Did you run multiple statements at once? 连接mysql失败!

### ISSUE THREAD

**Issue by longshaof** [Jrohy/trojan#106]
系统： Ubuntu 19.10 
1.安装了mariadb-server mariadb-client  
2.创建数据表，用户名及密码
mysql -u root -p
CREATE DATABASE trojan;
CREATE USER 'trojanuser'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON trojan.* TO 'trojanuser'@'localhost' IDENTIFIED BY 'password' WITH GRANT OPTION;
FLUSH PRIVILEGES;
exit
3.安装一键脚本
4.脚本安装管理中运行证书申请，及输入自定义mysql连接

在数据自定义连接中，一直报错。（刚开始成功国一次，成功输入用户名及密码）
连接mysql失败, 请重新输入

在脚本查看配置中，报commands out of sync. Did you run multiple statements at once?
连接mysql失败!

查看日志中，有以下这个报警
trojan[9816]: [2020-04-23 10:57:23] [INFO] connecting to MySQL server 127.0.0.1:3306
Apr 23 10:57:23 pc trojan[9816]: [2020-04-23 10:57:23] [FATAL] fatal: Host 'XXX.XXX.XXX.XXX' is not allowed to connect to this MariaDB server

麻烦帮忙看一下，我折腾半天了。另外一台debian 10的vps也没折腾出来。

**Comment by Jrohy** [comment]
用docker版mariadb不能用么，自己安装配置有点麻烦

**Comment by longshaof** [comment]
目前成功了2台vps的配置。非常感谢。安装的docker版mariadb。 
开始以为自己安装mariadb和脚本里的一样的。
