### ISSUE TITLE
还是多用户问题,很重要

### ISSUE THREAD

**Issue by hudingwen** [Jrohy/trojan#108]
你好 还是上次说得说用户如果密码都一样的情况下  
如果两个人密码一样统计流量会写入到两个账号中,
建议你的web管理可以再创建两个字段到users表中 
一个新字段是网站用户真正登录的密码
一个新字段是Trojan使用的明文密码,因为用户获取二维码要这个明文,这个明文刚好对应上password字段加密成的sha224 

为什么我要这样弄呢  因为如果我是直接在数据库加入了一个新用户 管理员登录或者用户就看不到明文密码了,所以这里存在一个漏洞

**Comment by hudingwen** [comment]
我直接在数据加Trojan密码 Trojan可以验证通过 但是管理登录就查看不到了

**Comment by hudingwen** [comment]
还有就是我安装新服务器选择了现有的mysql之后.用这台服务器登录查看不到密码 所以这也是一个大问题

**Comment by hudingwen** [comment]
所以说一旦服务器没了 但是数据库还在 我重装后后用户还在 但是密码就查看不到了  因为sha224是散列哈希  是不能解密的

**Comment by hudingwen** [comment]
![image](https://user-images.githubusercontent.com/36782822/80279802-645aac80-8732-11ea-9577-2a9819e6606c.png)
![image](https://user-images.githubusercontent.com/36782822/80279821-79cfd680-8732-11ea-9aa6-fc4b4ff4877d.png)
第三个用户是我在数据库加上的,Trojan能用  但是不能再看到密码了

**Comment by hudingwen** [comment]
![image](https://user-images.githubusercontent.com/36782822/80280043-0929b980-8734-11ea-8f99-6d7c33b9bc8c.png)
看了官方文档 我们自己拓展还是很强的  只是你用的go语言 我看不太懂  哈哈

**Comment by Jrohy** [comment]
为什么原本trojan不在数据库里面存原始密码呢，应该是出于安全问题， 如果将原始密码加到数据库里面就违背初衷了

**Comment by Jrohy** [comment]
不建议直接改连数据库来修改和增加的，不会改原始的users表

**Comment by hudingwen** [comment]
Trojan密码应该是和你web登录密码分开吧

**Comment by Jrohy** [comment]
web登录密码和原始密码是存在leveldb里面的

**Comment by hudingwen** [comment]
不谈你的web管理就会存在密码相同的情况  存在相同那么统计就会出问题

**Comment by hudingwen** [comment]
那你试试Trojan服务器和mysql分离  然后重装Trojan服务器

**Comment by hudingwen** [comment]
你就会发现密码全部都丢失了

**Comment by Jrohy** [comment]
你要备份和恢复/var/lib/trojan-mysql目录， leveldb的目录

**Comment by hudingwen** [comment]
我是考虑Trojan直接没了 但是数据库我们可以单独隔离出来 特别要商用vnp的时候

**Comment by hudingwen** [comment]
说白了就是，我可以不用你web管理，我直接搭建一个web应用程序来单独管理用户了。嘿嘿

**Comment by hudingwen** [comment]
如果你的密码问题不能得到有效解决，就算不上多用户管理了😂

**Comment by Jrohy** [comment]
原始密码不会存到外置的数据库的

**Comment by hudingwen** [comment]
单个服务器还好  你要是多个服务器  不搞死个人....

**Comment by zhaokelei** [comment]
如果需要迁移数据怎么备份，leveldb和trojan-mysql在哪个目录

**Comment by zhaokelei** [comment]
/var/lib/trojan-manager/  这个目录和数据库备份然后放到新的服务器就可以了吗

**Comment by Jrohy** [comment]
对的，数据库目录在/home/mariadb目录下

**Comment by zhaokelei** [comment]
> 对的，数据库目录在/ home / mariadb目录下

好的

**Comment by hudingwen** [comment]
![3](https://user-images.githubusercontent.com/36782822/80856112-aaa39480-8c79-11ea-8dea-1269b9a8dda8.png)

![2](https://user-images.githubusercontent.com/36782822/80856076-57314680-8c79-11ea-9591-ab9d4000b292.png)
我是这样解决方案的,通过增加Trojan的users表来记录密码,你通过levelDB 多一个程序 不太好迁移 以及多服务的情况下 容易出现问题

**Comment by Jrohy** [comment]
@hudingwen 这样就违背了安全的原始初衷了，将原始密码放到数据库里面

**Comment by lpn418** [comment]
之前用的普通模式安装的，备份了相关内容，新的服务器用docker安装的，发现没有/var/lib/trojan-manager/ 这个目录，这咋恢复呢？

**Comment by Jrohy** [comment]
docker cp拷贝进去

**Comment by lpn418** [comment]
拷贝进docker 里面的文件路径是什么  和正常的一样吗？

**Comment by lpn418** [comment]
我现在是web可以进去，除了密码不显示其它都正常...哪里错了呢

**Comment by hudingwen** [comment]
> @hudingwen这样就违背了安全的原始初衷了，将原始密码放到数据库里面

说真的这个跟安全没关系的 添加用户我都是生成GUID的 就是一个用户唯一标识 这个流量上网和用户登录我都是分开了的

**Comment by Jrohy** [comment]
@hudingwen 因为没用回原来的leveldb数据目录，找不到原始密码

**Comment by hudingwen** [comment]
> @hudingwen 因为没用回原来的leveldb数据目录(/var/lib/trojan-manager)，找不到原始密码

还是建议你把原始密码放在Trojan的users表中 levelDB里面一样有用户明文密码  所以违背了安全是没有说服力的,你就把密码链接密码和用户登录密码分开就OK了

**Comment by Jrohy** [comment]
@hudingwen 不会将原始密码放到数据库里面的，如果放在数据库里面，还不如建议trojan作者不要SHA224 加密好了，直接原始存

**Comment by hudingwen** [comment]
> @hudingwen不会将原始密码放到数据库里面的，如果放在数据库里面，还不如建议trojan作者不要SHA224加密好了，直接原始存

我看他文档说是为了效率问题 并且他加了索引

**Comment by Jrohy** [comment]
后面可能会考虑下
