### ISSUE TITLE
请问可以让trojan和v2ray共存吗?

### ISSUE THREAD

**Issue by wialny** [Jrohy/trojan#11]
两个都是用的您提供的一键安装脚本. 目前在同一个VPS上, 使用不同二级域名可以同时安装, 但无法同时启动, 只能一个停用一个运行.

**Comment by Jrohy** [comment]
是端口冲突吗，看下v2ray配置有没有用到443和80端口

**Comment by wialny** [comment]
对, 应该就是端口冲突. 安装trojan申请证书时也提示过端口被v2ray占用. 
v2ray的kcp协议没法使用, 现在只能用tcp或加DNS. 
所以这样的话就没法和trojan在同一台VPS上公用了对吗?

**Comment by Jrohy** [comment]
kcp不需要用443或者80端口的，可以换成其他端口

**Comment by wialny** [comment]
我的意思是v2ray的kcp协议已经没法使用了, 现在只能使用tcp协议.

在安装trojan的证书时提示过端口被占用
`[Wed Mar 18 07:21:05 UTC 2020] Standalone mode.
[Wed Mar 18 07:21:05 UTC 2020] _checkport='80'
[Wed Mar 18 07:21:05 UTC 2020] _checkaddr

[Wed Mar 18 07:21:05 UTC 2020] Using: ss
[Wed Mar 18 07:21:05 UTC 2020] LISTEN    0         128                      *:80                                                                                                                                                                                                                                                                  *:*        users:(("v2ray",pid=391,fd=5))                                                                                                                                                                                                                                                               
[Wed Mar 18 07:21:06 UTC 2020] tcp port 80 is already used by (("v2ray",pid=391,                                                                                                                                                                                                                                             fd=5))
[Wed Mar 18 07:21:06 UTC 2020] Please stop it first
[Wed Mar 18 07:21:06 UTC 2020] _on_before_issue.
`
在手动关闭v2ray后trojan安装成功. 运行成功运行. 但v2ray无法启动, 只能关闭trojan后再启动v2ray. 反之亦然

**Comment by Jrohy** [comment]
可以试下v2ray其他协议，比如ws + tls

**Comment by wialny** [comment]
v2ray的其他协议都不好使了, ws + tls也要占用443端口
我已经分了两个域名, v2ray使用 1.abc.xyz; trojan使用 2.abc.xyz 但还是不行
先启动v2ray再启动trojan
v2ray正常工作, trojan提示SSL handshake failed with 2.abc.xyz:443 stream truncated
先启动trojan, v2ray无法启动

**Comment by wialny** [comment]
我想让trojan和v2ray在一台VPS上共存是因为trojan的windows客户端没有全局或PAC代理功能. 
而我刚刚发现可以让v2rayN把trojan当成socks服务器代理, 这样就可以通过v2rayN来做全局PAC代理了. 就不用纠结trojan和v2ray共存的问题了

**Comment by twinklstar** [comment]
把Trojan服务器端配置文件里的端口改一下是不是可行

**Comment by MaiReo** [comment]
> 把Trojan服务器端配置文件里的端口改一下是不是可行

建议你在trojan或者v2ray前面加一层反代服务。比如traefik2.0
