### ISSUE TITLE
更新trojan后无法使用，能安装其他vps面板吗

### ISSUE THREAD

**Issue by aisuyi065** [Jrohy/trojan#110]
欢迎使用trojan管理程序

1.trojan管理       	2.用户管理           

3.安装管理           	4.web管理          

5.查看配置           	6.生成json         

请选择: 3

1.更新trojan

2.证书申请

3.安装mysql

请选择: 1
这里选择1更新trojan后就无法使用
后期能对宝塔面板之类的支持吗

**Comment by Jrohy** [comment]
建议纯净系统来安装

**Comment by aisuyi065** [comment]
就是初始化的纯净系统安装的，安装debian9和centos7都是一样，
安装成功后更新trojan就无法使用trojan上网
