### ISSUE TITLE
GCP安装后，无法连接trojan

### ISSUE THREAD

**Issue by seanhk** [Jrohy/trojan#111]
如图，香港节点，之前没有安装web管理界面时可以正常用trojan
安装web管理界面后后无法连接trojan，并且无法访问在线管理平台
系统：debian 9
查看Trojan状态时提示WAR not trojan request .
trojan 版本 1.15.1
web管理版本 2.6.5
是因为服务器的问题无法兼容吗？

**Comment by Jrohy** [comment]
证书申请到了吗，直接用ip能否访问到web界面

**Comment by seanhk** [comment]
> 证书申请到了吗，直接用ip能否访问到web界面

之前一次是可以进行访问到web界面的，但是还是无法连接trojan。但是当我重新安装后，就无法访问到Web界面了。

**Comment by aisuyi065** [comment]
遇到过，安装完直接退出trojan模式，再去打开网页，不要更新trojan和其他设置，就可以上网

**Comment by Jrohy** [comment]
看下web服务状态 systemctl status trojan-web看下是否在运行

**Comment by seanhk** [comment]
> 看下web服务状态 systemctl status trojan-web看下是否在运行
确实正在运行，状态是 running



trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-04-27 03:50:31 UTC; 5h 24min ago
     Docs: https://github.com/Jrohy/trojan
 Main PID: 10589 (trojan)
    Tasks: 5 (limit: 4915)
   Memory: 3.3M
      CPU: 509ms
   CGroup: /system.slice/trojan-web.service
           └─10589 /usr/local/bin/trojan web

Apr 27 07:39:40 hongk trojan[10589]: [GIN] 2020/04/27 - 07:39:40 | 200 |      553.73µs |  189.126.79.188 | GET      /
Apr 27 07:57:36 hongk trojan[10589]: [GIN] 2020/04/27 - 07:57:36 | 401 |     1.36561ms |     72.17.35.42 | POST     /cgi-bin/mainfunction.cgi
Apr 27 08:00:03 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:00:04 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:00:04 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:00:09 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:00:10 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:00:15 hongk systemd[1]: [/etc/systemd/system/trojan-web.service:10] Invalid escape sequences in line, correcting: "/bin/kill -HUP \$MAINPID"
Apr 27 08:20:00 hongk trojan[10589]: [GIN] 2020/04/27 - 08:20:00 | 200 |     422.035µs | 207.180.221.216 | GET      /
Apr 27 08:32:03 hongk trojan[10589]: [GIN] 2020/04/27 - 08:32:03 | 200 |    1.013171ms |   72.203.66.188 | GET      /

**Comment by seanhk** [comment]
> 遇到过，安装完直接退出trojan模式，再去打开网页，不要更新trojan和其他设置，就可以上网

您说的直接退出trojan模式是什么模式呢，我安装完之后按enter完会出现 https://你的域名。
是在此时进行什么操作吗？

**Comment by seanhk** [comment]
> 看下web服务状态 systemctl status trojan-web看下是否在运行

您好，今天重新安装了一下，web管理界面进去了，但是依旧无法连接trojan

**Comment by Jrohy** [comment]
journalctl -f -n 1000 -u trojan 看下trojan日志
