### ISSUE TITLE
是否可以更改流量监控的刷新频率？

### ISSUE THREAD

**Issue by rollgotobed** [Jrohy/trojan#114]
1.不知道现在流量监控是多长时间更新一次，感觉很慢，希望可以在点击刷新的时候实时刷新，或者可以修改间隔时间。
2.重置流量似乎没有作用，在“确定重置以下用户流量?”下是一片空白，仅有两个按钮。

**Comment by Jrohy** [comment]
要选中用户，才能批量重置里显示重置哪些用户的

**Comment by Jrohy** [comment]
点击刷新是获取数据库里的最新数据的，只是这数据有没有更新，是trojan核心控制的，面板只是去读数据库
