### ISSUE TITLE
当web端口修改为非80后, http的这个非80端口正常访问管理界面, 但是https的443端口无法访问到管理页面了

### ISSUE THREAD

**Issue by inaGH** [Jrohy/trojan#119]

**Comment by Jrohy** [comment]
https要用也是用非80端口访问的

**Comment by inaGH** [comment]
是的, 我可以把这个非80端口配个证书也用https访问, 
主要疑惑的还是为啥子原本443能访问到界面, 80改成其他之后就不行了, 会是443默认就代理到80上吧, 改了80就不行了

**Comment by Jrohy** [comment]
估计是443和80这些端口是不用标明的(比如htttps不用写成https://域名:443)

**Comment by inpowerchiu** [comment]
请问我trojan-web里面增加-p 8080后，web管理界面用8080能登录了，但是trojan程序跑不起来。wiki里面nginx配置该在哪个目录下修改呢？不是很懂，能教下吗？
trojan错误信息：
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z trojan[32649]: Error: unknown command "/usr/local/etc/trojan/config.json" for "trojan"
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z trojan[32649]: Run 'trojan --help' for usage.
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z trojan[32649]: unknown command "/usr/local/etc/trojan/config.json" for "trojan"
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Unit trojan.service entered failed state.
May 07 11:36:20 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service failed.
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service holdoff time over, scheduling restart.
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Stopped trojan.
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: start request repeated too quickly for trojan.service
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Failed to start trojan.
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Unit trojan.service entered failed state.
May 07 11:36:22 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
@inpowerchiu nginx得自己安装和配置的，wiki只是列出可用的nginx配置

**Comment by inpowerchiu** [comment]
> @inpowerchiu nginx得自己安装和配置的，wiki只是列出可用的nginx配置
你好，我在bt里面已经安装有了，更改web端口为8080后，是要配合nginx才能使trojan跑起来吗？该怎么修改呢？

以下是宝塔里面的默认配置：
user  www www;
worker_processes auto;
error_log  /www/wwwlogs/nginx_error.log  crit;
pid        /www/server/nginx/logs/nginx.pid;
worker_rlimit_nofile 51200;

events
    {
        use epoll;
        worker_connections 51200;
        multi_accept on;
    }

http
    {
        include       mime.types;
		#include luawaf.conf;

		include proxy.conf;

        default_type  application/octet-stream;

        server_names_hash_bucket_size 512;
        client_header_buffer_size 32k;
        large_client_header_buffers 4 32k;
        client_max_body_size 50m;

        sendfile   on;
        tcp_nopush on;

        keepalive_timeout 60;

        tcp_nodelay on;

        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;
        fastcgi_temp_file_write_size 256k;
		fastcgi_intercept_errors on;

        gzip on;
        gzip_min_length  1k;
        gzip_buffers     4 16k;
        gzip_http_version 1.1;
        gzip_comp_level 2;
        gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml;
        gzip_vary on;
        gzip_proxied   expired no-cache no-store private auth;
        gzip_disable   "MSIE [1-6]\.";

        limit_conn_zone $binary_remote_addr zone=perip:10m;
		limit_conn_zone $server_name zone=perserver:10m;

        server_tokens off;
        access_log off;

server
    {
        listen 888;
        server_name phpmyadmin;
        index index.html index.htm index.php;
        root  /www/server/phpmyadmin;

        #error_page   404   /404.html;
        include enable-php.conf;

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        location ~ /\.
        {
            deny all;
        }

        access_log  /www/wwwlogs/access.log;
    }
include /www/server/panel/vhost/nginx/*.conf;
}

**Comment by inpowerchiu** [comment]
现在把nginx改了80端口，按照wiki上面添加后，访问/admin能跳转到web面板了，可是trojan程序还是不能跑，这是为什么呢？

 trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 四 2020-05-07 15:09:46 CST; 883ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 14269 ExecStart=/usr/local/bin/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 14269 (code=exited, status=1/FAILURE)

5月 07 15:09:46 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
5月 07 15:09:46 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Unit trojan.service entered failed state.
5月 07 15:09:46 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
@inpowerchiu journalctl -u trojan -f 看下trojan详细日志

**Comment by inpowerchiu** [comment]
journalctl -u trojan -f
-- Logs begin at 四 2019-07-11 11:10:15 CST. --
5月 07 15:09:49 iZt4niv59inb4kkbwa9sa3Z trojan[14355]: unknown command "/usr/local/etc/trojan/config.json" for "trojan"
5月 07 15:09:49 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
5月 07 15:09:49 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Unit trojan.service entered failed state.
5月 07 15:09:49 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service failed.
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service holdoff time over, scheduling restart.
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Stopped trojan.
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: start request repeated too quickly for trojan.service
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Failed to start trojan.
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: Unit trojan.service entered failed state.
5月 07 15:09:50 iZt4niv59inb4kkbwa9sa3Z systemd[1]: trojan.service failed.

**Comment by yesmiley** [comment]
443回源就是80，你改了当然就对不上。可以看下trojan的原理设计
