### ISSUE TITLE
半小时一直是这个状态,应该如何处理??

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/trojan#12]
半小时一直是这个状态,应该如何处理??
vps配置是单核256mb

进入WEB管理,新建用户,提示dial tcp 127.0.0.1:3306: connect: connection refused 如何解决?

[mysql] 2020/03/18 01:27:38 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:27:38 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:41 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:41 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:41 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:44 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:44 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:45 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:47 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:47 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:28:47 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:50 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:50 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:50 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:53 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:53 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:53 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:55 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:55 packets.go:36: unexpected EOF
[mysql] 2020/03/18 01:29:55 packets.go:36: unexpected EOF

**Comment by Jrohy** [comment]
256m感觉有点吃紧，你可以看下mysql有没有启动到，我这边自己看了mysql容器启动都要160+ mb内存

**Comment by lqhorochi** [comment]
> 256m感觉有点吃紧，你可以看下mysql有没有启动到，我这边自己看了mysql容器启动都要160+ mb内存

如何查看?命令是????

**Comment by Jrohy** [comment]
查看mysql容器日志
docker logs -f trojan-mysql
查看容器消耗内存
docker stats

**Comment by lqhorochi** [comment]
> 查看mysql容器日志
> docker logs -f trojan-mysql
> 查看容器消耗内存
> docker stats

mysql容器日志
root@333-tj:~# docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Initialization of mysqld failed: 0
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15

容器消耗内存
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
5822e0c86b95        trojan-mysql        0.00%               0B / 0B             0.00%               0B / 0B             0B / 0B             0

**Comment by Jrohy** [comment]
mysql启动失败了，你试下删掉容器docker rm -f trojan-mysql, 清掉mysql目录 rm -rf /home/mysql,然后运行下
docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7

**Comment by Jrohy** [comment]
运行完再docker logs -f trojan-mysql, 看下mysql日志

**Comment by lqhorochi** [comment]
> 运行完再docker logs -f trojan-mysql, 看下mysql日志

root@333-tj:~# docker rm -f trojan-mysql
trojan-mysql
root@333-tj:~# rm -rf /home/mysql
root@333-tj:~# docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7
50fb8c17c842c33e76d5694283fc90a76aa88db40a6d2219031eb41ece630a79
root@333-tj:~# docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Initialization of mysqld failed: 0
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15

**Comment by Jrohy** [comment]
用的什么系统

**Comment by lqhorochi** [comment]
> 用的什么系统

Ubuntu 18.04 X86_X64

**Comment by lqhorochi** [comment]
是不是需要其他系统???
debian?还是CentOS???

**Comment by Jrohy** [comment]
我用vultr的vps测试下

**Comment by Jrohy** [comment]
测了没问题vultr的 ubuntu 18.04, 要不你试下换成centos7看看，开发基本都是在这个系统上面做的测试

**Comment by Jrohy** [comment]
还有是不是这次是不是nat vps呢，有没有限制端口的

**Comment by lqhorochi** [comment]
> 还有这次是不是nat vps呢，有没有限制端口的
不是NAT,没有限制端口
我现在重装系统,用Centos 7.7试下

**Comment by Jrohy** [comment]
嗯，你先不用安装trojan,先直接安装mysql看下能否启动成功
docker安装
`source <(curl -sL https://git.io/docker-install)`
mysql容器安装
`docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7`
查看启动日志
`docker logs -f trojan-mysql`

**Comment by lqhorochi** [comment]
> 嗯，你先不用安装trojan,先直接安装mysql看下能否启动成功
> docker安装
> `source <(curl -sL https://git.io/docker-install)`
> mysql容器安装
> `docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7`
> 查看启动日志
> `docker logs -f trojan-mysql`

Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
WARNING: No swap limit support
docker 19.03.8 install success!
root@333-tj:~# docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7
Unable to find image 'mysql/mysql-server:5.7' locally
5.7: Pulling from mysql/mysql-server
c7127dfa6d78: Pull complete 
cb7ddde5230b: Pull complete 
1528bee07386: Pull complete 
cca3f8362bb0: Pull complete 
Digest: sha256:5a5c0841346322ed514a48a7c2ab5409a8106e35718f3195467e7cf52343f25a
Status: Downloaded newer image for mysql/mysql-server:5.7
bfa81a9e56f65264653adb58c4f00dc1f8eb7288511f49ae96f21dfb334364d6
root@333-tj:~# docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Initialization of mysqld failed: 0
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15

**Comment by Jrohy** [comment]
你这个是不是nat vps

**Comment by lqhorochi** [comment]
> 你这个是不是nat vps

不是NAT VPS
是普通KVM VPS

**Comment by Jrohy** [comment]
不行就自己试下安装非docker版的mysql, 反正有mysql就行

**Comment by lqhorochi** [comment]
> 不行就自己试下安装非docker版的mysql, 反正有mysql就行

有空再优化一下,比如小内存的VPS

**Comment by Jrohy** [comment]
这个没得优化的，耗内存不是程序本身，而是mysql, 小内存就建议不要装mysql， 直接配置文件

**Comment by lqhorochi** [comment]
> 这个没得优化的，耗内存不是程序本身，而是mysql, 小内存就建议不要装mysql， 直接配置文件

好吧,

**Comment by lqhorochi** [comment]
> 这个没得优化的，耗内存不是程序本身，而是mysql, 小内存就建议不要装mysql， 直接配置文件

方便嘛?我给你VPS账号密码,你可以帮我搞一下吗?还是不行

**Comment by lqhorochi** [comment]
> > 这个没得优化的，耗内存不是程序本身，而是mysql, 小内存就建议不要装mysql， 直接配置文件
> 
> 方便嘛?我给你VPS账号密码,你可以帮我搞一下吗?还是不行
方便就留个email

**Comment by Jrohy** [comment]
安装非docker版mysql也是启动不了？

**Comment by Jrohy** [comment]
建议换大一点内存vps(512m+),或者将mysql迁到其他服务器里部署

**Comment by lqhorochi** [comment]
> 建议换大一点内存vps(512m+),或者将mysql迁到其他服务器里部署

debian 8.7 x86_x64可以启动mysql,但是启动不到Trojan

root@333-tj:~# systemctl status trojan.service
● trojan.service - trojan
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/

Mar 18 11:10:18 333-tj.tk systemd[1]: [/etc/systemd/system/trojan.service:9] Executable path is not absolute, ignoring: "/usr/bin/...ig.json"
Mar 18 11:10:18 333-tj.tk systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Mar 18 11:10:18 333-tj.tk systemd[1]: [/etc/systemd/system/trojan.service:9] Executable path is not absolute, ignoring: "/usr/bin/...ig.json"
Mar 18 11:10:18 333-tj.tk systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Mar 18 11:12:26 333-tj.tk systemd[1]: [/etc/systemd/system/trojan.service:9] Executable path is not absolute, ignoring: "/usr/bin/...ig.json"
Mar 18 11:12:26 333-tj.tk systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Mar 18 11:12:26 333-tj.tk systemd[1]: [/etc/systemd/system/trojan.service:9] Executable path is not absolute, ignoring: "/usr/bin/...ig.json"
Mar 18 11:12:26 333-tj.tk systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Jrohy** [comment]
有改过service文件吗/etc/systemd/system/trojan.service

**Comment by lqhorochi** [comment]
> 有改过service文件吗/etc/systemd/system/trojan.service

没有修改过.

**Comment by lqhorochi** [comment]
出现这个错误日志是什么问题呢?

root@333-tj:~# systemctl status trojan-gfw -l
● trojan-gfw.service
   Loaded: loaded (/lib/systemd/system/trojan-gfw.service; enabled)
   Active: active (running) since Wed 2020-03-18 12:01:26 EDT; 18s ago
 Main PID: 13478 (trojan)
   CGroup: /system.slice/trojan-gfw.service
           └─13478 /usr/bin/trojan -c /etc/trojan/config.json

Mar 18 12:01:26 333-tj.tk trojan[13478]: Welcome to trojan 1.14.1
Mar 18 12:01:26 333-tj.tk trojan[13478]: [2020-03-18 12:01:26] [WARN] trojan service (server) started at 0.0.0.0:443
Mar 18 12:01:35 333-tj.tk trojan[13478]: [2020-03-18 12:01:35] [WARN] 179.43.169.182:34396 not trojan request, connecting to 127.0.0.1:80
Mar 18 12:01:35 333-tj.tk trojan[13478]: [2020-03-18 12:01:35] [ERROR] 179.43.169.182:34396 cannot establish connection to remote server 127.0.0.1:80: Connection refused
Mar 18 12:01:35 333-tj.tk trojan[13478]: [2020-03-18 12:01:35] [INFO] 179.43.169.182:34396 disconnected, 0 bytes received, 64 bytes sent, lasted for 0 seconds

**Comment by Jrohy** [comment]
trojan客户端使用有问题？
