### ISSUE TITLE
你好！能告诉一下这个面板web文件目录吗？找半天没有找到

### ISSUE THREAD

**Issue by zhongqiujie13** [Jrohy/trojan#121]
先谢谢作者大大了受累了。

**Comment by ancct** [comment]
> 先谢谢作者大大了受累了。

我告诉你吧，没目录，别想了

**Comment by zhongqiujie13** [comment]
> > 先谢谢作者大大了受累了。
> 
> 我告诉你吧，没目录，别想了

额。。。。。没目录那么面板的文件怎么调用的？

**Comment by ancct** [comment]
文件是二进制文件，已经嵌入到里面了

**Comment by cherishh** [comment]
如果是要修改端口的话，wiki有方法

**Comment by vicdorke** [comment]
wiki的目录怎么没有配置文件？？？
