### ISSUE TITLE
一键安装，无法连接数据库

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#122]
ac18b6f4b11a: Pull complete
Digest: sha256:7f803417b7d35e89c99b3f90a0607bea9d8ef3e749b792f3c90ec30a0c8c1304
Status: Downloaded newer image for mariadb:10.2
48b7885327c203caae5fdc26b58dd1707be2942928df9ca7ece19b2eb82394dd
2020-05-02 14:03:39 mariadb启动中,请稍等...
2020-05-02 14:03:50 mariadb启动中,请稍等...
2020-05-02 14:03:59 mariadb启动中,请稍等...

访问WEB后台，登录，提示无法连接mysql，那里问题。

**Comment by totodata** [comment]
查看trojan安装情况，应该是正常的。
请选择: 4
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2020-05-02 14:06:21 UTC; 52s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 605 (trojan)
   Memory: 4.1M
   CGroup: /system.slice/trojan.service
           └─605 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

May 02 14:06:21 HostKvm-625635 systemd[1]: Started trojan.
May 02 14:06:21 HostKvm-625635 trojan[605]: Welcome to trojan 1.15.1

**Comment by totodata** [comment]
请选择: 3

1.更新trojan

2.证书申请

3.安装mysql

请选择: 3

1.安装docker版mysql(mariadb)

2.输入自定义mysql连接

请选择: 1
docker run --name trojan-mariadb --restart=always -p 1927:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=ZhMrQ -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
setenforce: SELinux is disabled
docker: Error response from daemon: Conflict. The container name "/trojan-mariadb" is already in use by container "48b7885327c203caae5fdc26b58dd1707be2942928df9ca7ece19b2eb82394dd". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
2020-05-02 14:21:39 mariadb启动中,请稍等...
2020-05-02 14:21:41 mariadb启动中,请稍等...
2020-05-02 14:21:43 mariadb启动中,请稍等...
2020-05-02 14:21:45 mariadb启动中,请稍等...
2020-05-02 14:21:47 mariadb启动中,请稍等...
2020-05-02 14:21:49 mariadb启动中,请稍等...


重装，会提示占用。

**Comment by Jrohy** [comment]
已经安装容器了, docker logs -f trojan-mariadb 看数据库日志

**Comment by totodata** [comment]
连接mysql失败, 请重新输入
请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址: 

怎么查看docker安装的数据库秘密啊？明明已经确定时安装时候的密码，死活就是提示不对。密码保存在哪里呢？

**Comment by Jrohy** [comment]
docker安装的要自己安装数据卷的

**Comment by Jrohy** [comment]
怎么安装看项目readme，那句数据库docker run里面有设置密码的

**Comment by totodata** [comment]
docker run --name trojan-mariadb --restart=always -p 3306:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2


密码  trojan

没错吧。可是就是提示连接不上。

**Comment by Jrohy** [comment]
@totodata 估计mariadb没启动成功， 删除重新建吧, docker rm -f trojan-mariadb 
rm -rf /home/mariadb

**Comment by totodata** [comment]
问题好多。一键安装，总是装不好

[root@ecs-Fwj ~]# systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 日 2020-05-03 10:18:22 CST; 235ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 16821 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 16821 (code=exited, status=1/FAILURE)

5月 03 10:18:22 ecs-Fwj systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
5月 03 10:18:22 ecs-Fwj systemd[1]: Unit trojan.service entered failed state.
5月 03 10:18:22 ecs-Fwj systemd[1]: trojan.service failed.
[root@ecs-Fwj ~]# trojan systemctl stop trojan
Error: unknown command "systemctl" for "trojan"
Run 'trojan --help' for usage.
unknown command "systemctl" for "trojan"
[root@ecs-Fwj ~]# /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
Welcome to trojan 1.15.1
[2020-05-03 10:19:11] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2020-05-03 10:19:11] [FATAL] exiting. . .

**Comment by Jrohy** [comment]
证书都没申请。。

**Comment by totodata** [comment]
折腾了好久，终于搞定了。
什么时候能支持用户数据导入导出？

**Comment by xiezhiwengg00** [comment]
> 折腾了好久，终于搞定了。
> 什么时候能支持用户数据导入导出？

能说详细点吗？具体操作步骤

**Comment by xiezhiwengg00** [comment]
> 请选择: 3
> 
> 1.更新trojan
> 
> 2.证书申请
> 
> 3.安装mysql
> 
> 请选择: 3
> 
> 1.安装docker版mysql(mariadb)
> 
> 2.输入自定义mysql连接
> 
> 请选择: 1
> docker run --name trojan-mariadb --restart=always -p 1927:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=ZhMrQ -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
> setenforce: SELinux is disabled
> docker: Error response from daemon: Conflict. The container name "/trojan-mariadb" is already in use by container "48b7885327c203caae5fdc26b58dd1707be2942928df9ca7ece19b2eb82394dd". You have to remove (or rename) that container to be able to reuse that name.
> See 'docker run --help'.
> 2020-05-02 14:21:39 mariadb启动中,请稍等...
> 2020-05-02 14:21:41 mariadb启动中,请稍等...
> 2020-05-02 14:21:43 mariadb启动中,请稍等...
> 2020-05-02 14:21:45 mariadb启动中,请稍等...
> 2020-05-02 14:21:47 mariadb启动中,请稍等...
> 2020-05-02 14:21:49 mariadb启动中,请稍等...
> 
> 重装，会提示占用。
先装mariadb，设密码，再选
2.输入自定义mysql连接，用密码登陆

**Comment by Tianyadan** [comment]
> > 折腾了好久，终于搞定了。
> > 什么时候能支持用户数据导入导出？
> 
> 能说详细点吗？具体操作步骤

配置的用户名和密码可否导出进行备份，重装后可否导入进行恢复？

**Comment by Jrohy** [comment]
@Tianyadan 可以导sql出来再还原的
