### ISSUE TITLE
web登陆后资源占用高，导致无法连接数据库

### ISSUE THREAD

**Issue by lpn418** [Jrohy/trojan#123]
512内存vps，用户多了之后（50个用户左右）经常无法连接数据库且web登陆后CPU占用总是100%，读取数据库还是需要优化下啊

**Comment by Jrohy** [comment]
查询效率确实需要优化，太多用户的话查询可能超时

**Comment by Jrohy** [comment]
2.7版本做了查询优化, 用户密码直接读的mysql而不是leveldb， 提升效率
