### ISSUE TITLE
docker手动安装mysql，提示container被占用，删掉还是如此，怎么办。

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#124]
[root@HostKvm-625635 /]# docker rm -f trojan-mariadb
trojan-mariadb
[root@HostKvm-625635 /]# rm -rf /home/mariadb
[root@HostKvm-625635 /]# docker run --name trojan-mariadb --restart=always -p 3306:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
16d6ee3630ffe9121b432a183fcf00b35ec2d95f1b11cb89387348eef9372138
docker: Error response from daemon: driver failed programming external connectivity on endpoint trojan-mariadb (96dedbdf5c81b0e755e6c16b05876fb1f160566fc12996154570a7ad45086f64): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use.
[root@HostKvm-625635 /]# 

trojan正常运行，web能登陆，就是无法连接，数据库。

docker logs -f trojan-mariadb

查看日志，无任何输出。

**Comment by Jrohy** [comment]
3306已经用了端口

**Comment by totodata** [comment]
杀掉进程，重新安装，无限启动中.........

docker run --name trojan-mariadb --restart=always -p 63177:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=zozOA -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
setenforce: SELinux is disabled
cfd9a240f9982419e2d85d614b43503c3e85ddd62cc03e46b8262c3f6f9330fc
2020-05-03 16:56:28 mariadb启动中,请稍等...
2020-05-03 16:56:39 mariadb启动中,请稍等...
2020-05-03 16:56:48 mariadb启动中,请稍等...

**Comment by Jrohy** [comment]
应该没清掉原来的数据目录/home/mariadb

**Comment by totodata** [comment]
重来，一样重启.....

[root@H]# docker rm -f trojan-mariadb
Error: No such container: trojan-mariadb
[root@H]# rm -rf /home/mariadb
[root@H]# netstat -tunlp | grep 3306
[root@H]# lsof -i:3306
[root@H]# trojan

请选择: 3

1.更新trojan

2.证书申请

3.安装mysql

请选择: 3

1.安装docker版mysql(mariadb)

2.输入自定义mysql连接

请选择: 1
docker run --name trojan-mariadb --restart=always -p 1242:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=WduWq -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
setenforce: SELinux is disabled
aa35f16ce8d6a51f1faf514150f31b2ac7be716848f87863bf80ff0101e2c77d
2020-05-04 14:44:07 mariadb启动中,请稍等...
2020-05-04 14:44:18 mariadb启动中,请稍等...
2020-05-04 14:44:27 mariadb启动中,请稍等...
2020-05-04 14:44:36 mariadb启动中,请稍等...
2020-05-04 14:44:45 mariadb启动中,请稍等...
2020-05-04 14:44:54 mariadb启动中,请稍等...
2020-05-04 14:45:03 mariadb启动中,请稍等...
2020-05-04 14:45:12 mariadb启动中,请稍等...
2020-05-04 14:45:21 mariadb启动中,请稍等...

**Comment by xiezhiwengg00** [comment]
我也是这个問題，我安装mariadb，选擇2.输入自定义mysql连接，输入密码，完成
