### ISSUE TITLE
trojan-qt5客户端已支持GO   本脚本可以支持GO吗?  

### ISSUE THREAD

**Issue by akirayoo** [Jrohy/trojan#126]
毕竟多线程很香啊...

**Comment by Jrohy** [comment]
就是用go写的.

**Comment by akirayoo** [comment]
也就是本脚本原生支持多路复用?

**Comment by Jrohy** [comment]
用的不是 Trojan go的那个版本

**Comment by akirayoo** [comment]
这样啊 ,不知道有没有计划更换为trojan-go后端呢?  毕竟性能更好

**Comment by Jrohy** [comment]
等配套设施完善了再说

**Comment by Jrohy** [comment]
后面会考虑下，可能给予用户选择，喜欢安装哪个版本，或者可以实时切换

**Comment by akirayoo** [comment]
前端已有支持的gui了  而且qv2ray也准备支持go版

**Comment by xiezhiwengg12a** [comment]
有下载连接吗？发过来给我试试

**Comment by akirayoo** [comment]
> 有下载连接吗？发过来给我试试

https://github.com/Trojan-Qt5/Trojan-Qt5

**Comment by proxyBug** [comment]
> 就是用go写的.

所以支持cdn么？大佬？

**Comment by Jrohy** [comment]
@proxyBug 得换成trojan-go才支持
