### ISSUE TITLE
Web 管理页面根目录在哪里？我想放给文件提供下载怎么办呢？

### ISSUE THREAD

**Issue by wedojava** [Jrohy/trojan#129]
我现在需要在管理页面放个简单的下载链接，请问我应该把文件放到哪个目录下面合适？谢谢！

**Comment by Jrohy** [comment]
不存在的，前端是放到二进制文件里面了

**Comment by wedojava** [comment]
啊，那这样的话，我想利用这个web服务提供下载是无法实现的喽？

**Comment by Jrohy** [comment]
嗯可以加个nginx,自己写个简单页面来下载

**Comment by Jrohy** [comment]
然后管理页面改成非80端口，具体参考项目wiki, 怎么改nginx配置和服务端口

**Comment by wedojava** [comment]
好吧，谢谢，总觉得这样解决不是最佳实践，先这样吧，谢谢

Jrohy <notifications@github.com> 于2020年5月9日周六 下午2:50写道：
