### ISSUE TITLE
添加用户Error1045

### ISSUE THREAD

**Issue by 747761541** [Jrohy/trojan#13]
系统: debian9
现象: 使用控制台添加随机用户报错: Error 1045: Access denied for user 'trojan'@'172.17.0.1' (using password: NO)

**Comment by 747761541** [comment]
删除mysql后用控制台自动安装完就好了..
感谢大佬的分享

**Comment by Jrohy** [comment]
mysql启动成功了么，看下mysql日志 docker logs -f trojan-mysql
