### ISSUE TITLE
一键安装, 通过ip方式可以访问到web管理端, 但是通过域名不行.

### ISSUE THREAD

**Issue by Houtx** [Jrohy/trojan#130]
RT.一键安装, 通过ip方式可以访问到web管理端, 但是通过域名不行.
求解.

**Comment by Houtx** [comment]
@Jrohy

**Comment by Houtx** [comment]
Started trojan.
May 08 23:37:11 gulu trojan[13717]: Welcome to trojan 1.15.1
May 08 23:37:11 gulu trojan[13717]: [2020-05-08 23:37:11] [FATAL] fatal: use_certificate_chain_file: No such file or directory
May 08 23:37:11 gulu trojan[13717]: [2020-05-08 23:37:11] [FATAL] exiting. . .
May 08 23:37:11 gulu systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
May 08 23:37:11 gulu systemd[1]: trojan.service: Failed with result 'exit-code'.
May 08 23:37:14 gulu systemd[1]: trojan.service: Service RestartSec=3s expired, scheduling restart.
May 08 23:37:14 gulu systemd[1]: trojan.service: Scheduled restart job, restart counter is at 446.
May 08 23:37:14 gulu systemd[1]: Stopped trojan.
May 08 23:37:14 gulu systemd[1]: Started trojan.
May 08 23:37:14 gulu trojan[13719


还有trojan日志报这个错误

**Comment by Jrohy** [comment]
没申请到证书

**Comment by Houtx** [comment]
> 没申请到证书

谢谢, 通过看日志发现问题了.
还有一个问题, 请问如何伪装首页.(就是一打开域名, 如何展示一个假的首页, 而不是直接显示web管理页面).
@Jrohy

**Comment by Jrohy** [comment]
@Houtx 看项目wiki, 自己安装nginx, 改配置， 然后web管理也换成非80端口
