### ISSUE TITLE
是否可以考虑用sqlite之类的内嵌数据库，进一步减少内存使用...

### ISSUE THREAD

**Issue by linsongze** [Jrohy/trojan#131]
是否可以考虑用sqlite之类的内嵌数据库，进一步减少内存使用...

**Comment by Jrohy** [comment]
向官方trojan提意见

**Comment by linsongze** [comment]
好吧，，sorry..我没怎么看trojan那边，，我刚刚以为是你这边用来保存账号，再同步用户到trojan那边，，想不到是trojan那边直接用的。
