### ISSUE TITLE
【feature request】限制用户同时在线数

### ISSUE THREAD

**Issue by cherishh** [Jrohy/trojan#132]
请问大佬，有计划加入同一用户（同一密码）最大同时登陆数吗，或者自己做应该如何实现？

**Comment by twinklstar** [comment]
> 登

替作者回答你一下吧，首先Trojan的脚本暂不支持登录数量限制，这个功能首先得Trojan内部支持才可以实现（希望不会打脸）

**Comment by cherishh** [comment]
> > 登
> 
> 替作者回答你一下吧，首先Trojan的脚本暂不支持登录数量限制，这个功能首先得Trojan内部支持才可以实现（希望不会打脸）

感谢解答！不过按我理解这个功能可以只在外层（脚本）上实现，并且有先例。shadowsocks本身也不支持限制同时在线数，但市面上大多有这个功能，其实都是在ss外层加的。

**Comment by yyq582922811** [comment]
请问找到解决方案了么

**Comment by cherishh** [comment]
> 请问找到解决方案了么

没有。在trojan core 外层加这个功能可能太麻烦了，看起来作者也没有这个打算，所以还是从流量上下手吧。
