### ISSUE TITLE
能否添加API接口？

### ISSUE THREAD

**Issue by pc10201** [Jrohy/trojan#133]
比如用户的创建，更新，流量限制等

**Comment by cherishh** [comment]
都集成web portal 了，为啥还需要单独的api？使用场景是啥

**Comment by pc10201** [comment]
自动化，对接其他的系统

**Comment by cherishh** [comment]
可是如果不用这套web portal，直接用trojan 自己搭不就完了？中间省了哪些工作

**Comment by pc10201** [comment]
想用它的流量限制和多用户管理功能

**Comment by cherishh** [comment]
还不太理解，这些功能他的portal上也集成了，你是单纯不想用这套portal？

**Comment by mynameisshiy** [comment]
其实他想要的是多trojan节点的管理.每个节点可以多用户管理...如果这个panel可以做到接入其他trojan节后进行管理的话 就非常完美了..

**Comment by cherishh** [comment]
懂了
