### ISSUE TITLE
最新版本2.7.2 提供了用户注册功能?

### ISSUE THREAD

**Issue by Houtx** [Jrohy/trojan#136]
![image](https://user-images.githubusercontent.com/17922172/81780481-2c70a900-9529-11ea-98b3-6febc226aa72.png)

最新版本2.7.2 提供了用户注册功能?
我更新了一下, 并没有注册页面

**Comment by ancct** [comment]
第一次登录需要注册

**Comment by Jrohy** [comment]
是的是第一次登录时注册admin的页面，console会报错，修复了这个问题

**Comment by Houtx** [comment]
@Jrohy 后面考虑添加正常的用户注册功能么

**Comment by Jrohy** [comment]
@Jrohy 不考虑
