### ISSUE TITLE
请问为什么有的用户没有流量统计数据

### ISSUE THREAD

**Issue by hlz781105** [Jrohy/trojan#138]
比如我同时建了3个用户，有的用户有流量统计数据，有的用户没有流量统计。

**Comment by Jrohy** [comment]
是不是密码一样了，trojan区分不出密码一样是哪个用户的

**Comment by hlz781105** [comment]
密码不一样，用户名也不一样。
好像是用软路由的可以统计流量，用Trojan-Qt5客户端的统计不了。

**Comment by Potterli20** [comment]
那是客户端的问题
