### ISSUE TITLE
我发现了一个致命的问题，不知道有没有其他人提出。

### ISSUE THREAD

**Issue by bwsnb** [Jrohy/trojan#139]
进入web端设置了管理员密码之后，再次手动进去 https://www.***.com/#/register  这个页面,可以强行修改管理员密码。 我觉得这是个非常危险的问题。

**Comment by Jrohy** [comment]
只有登录状态下才能进/register页面，但普通用户登录后也能进register页面去改admin密码，确实是个很严重的问题，应该设置过admin密码就不能再进注册页面

**Comment by Jrohy** [comment]
2.7.3版本已修复

**Comment by bwsnb** [comment]
直接覆盖安装更新吗？ 用户数据会不会丢失

**Comment by Jrohy** [comment]
直接更新就行，不会丢数据的，可以重复更新的(不过更新一样的文件就没意义)， 直接运行`source <(curl -sL https://git.io/trojan-install)`来更
