### ISSUE TITLE
分享链接怎么用?

### ISSUE THREAD

**Issue by 747761541** [Jrohy/trojan#14]
trojan分享链接怎么用? 网上搜了半天没有搜到

**Comment by Jrohy** [comment]
桌面系统推荐这个客户端: https://github.com/TheWanderingCoel/Trojan-Qt5

**Comment by Jrohy** [comment]
可以扫二维码或者trojan://链接导入

**Comment by 747761541** [comment]
> 可以扫二维码或者trojan://链接导入

非常感谢, 请问有没有安卓端?

**Comment by Jrohy** [comment]
安卓这个: https://github.com/trojan-gfw/igniter/releases
