### ISSUE TITLE
如何升级旧版mysql到新的mariadb

### ISSUE THREAD

**Issue by zhucaidan** [Jrohy/trojan#140]
请问大佬未来的升级脚本可否增加一个选项给早期安装的用户升级备份升级数据库，
转换旧版的mysql数据到新版的mariadb，因为512M小鸡的话经常爆内存，SWAP也被mysql填满

**Comment by Jrohy** [comment]
导出sql来，再卸载原来的mysql容器，docker rm -f trojan-mysql, 然后再安装数据库，再导sql进去就好

**Comment by zhucaidan** [comment]
请问哪种docker安装mariadb比较好。。支持面板的

**Comment by Jrohy** [comment]
没有说那种，直接用最新版就行19.08

**Comment by Jrohy** [comment]
可以用这个一键安装最新版docker 
https://github.com/Jrohy/docker-install

**Comment by zhucaidan** [comment]
额。。我的意思是mariadb的安装命令是什么呢？包括端口那种的
不太确定面板读取的是哪个端口的数据

**Comment by Jrohy** [comment]
面板读取的是trojan的配置文件里面写的端口
