### ISSUE TITLE
可以多节点吗？直接多个节点用同一个数据库可以吗？

### ISSUE THREAD

**Issue by a1379478560** [Jrohy/trojan#141]
如题

**Comment by Jrohy** [comment]
不支持，多个节点可以用同一个数据库的，起的数据库名不一样来区分

**Comment by a1379478560** [comment]
谢谢大佬，有计划支持多节点吗？

**Comment by bbhxwl** [comment]
> 谢谢大佬，有计划支持多节点吗？

自己开发了一下实现了。

**Comment by a1379478560** [comment]
不会啊，不是人人都是大佬啊

**Comment by a1379478560** [comment]
> > 谢谢大佬，有计划支持多节点吗？
> 
> 自己开发了一下实现了。

不会啊，不是人人都是大佬啊

**Comment by a1379478560** [comment]
> > 谢谢大佬，有计划支持多节点吗？
> 
> 自己开发了一下实现了。

你已经实现了？能发下地址吗？我star一下。在你资料里没找到

**Comment by bbhxwl** [comment]
> > > 谢谢大佬，有计划支持多节点吗？
> > 
> > 
> > 自己开发了一下实现了。
> 
> 你已经实现了？能发下地址吗？我star一下。在你资料里没找到

昨天紧急开发的，我自己内部用，ssr 开会以来墙的太快。换v2了。今天刚做好批量开号。

**Comment by 925001777** [comment]
如何批量开号？单从mysql数据库增加貌似不太好使

**Comment by bbhxwl** [comment]
> 如何批量开号？单从mysql数据库增加貌似不太好使

本来就是基于文件的，不能用mysql吧
