### ISSUE TITLE
建议密码采用用户名:密码的形式

### ISSUE THREAD

**Issue by CnSuperYoung** [Jrohy/trojan#144]
如题，数据库存储的密码可以采用用户名：密码的形式，这样就不怕有人密码相同了

**Comment by ancct** [comment]
> 如题，数据库存储的密码可以采用用户名：密码的形式，这样就不怕有人密码相同了

用户无法改密码，要做出这个功能，还得用户能自己改密码才行

**Comment by Jrohy** [comment]
现在加了重复密码的限制了，新增用户
