### ISSUE TITLE
请问多用户可以和BT面板共存吗？

### ISSUE THREAD

**Issue by ancct** [Jrohy/trojan#146]
搭建个BT面板，设置好网站，http正常访问，运维与正常网站无二。然后某个路径设置成trojan后台登录，能正常添加用户设置流量？

**Comment by Jrohy** [comment]
端口不冲突应该可以，应该要加个nginx， 改web端口，具体怎么配看下项目wiki

**Comment by 10N99** [comment]
修改Nginx一只这个提示
ERROR:
nginx: [emerg] "location" directive is not allowed here in /www/server/nginx/conf/nginx.conf:60
nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by 10N99** [comment]
修改后 后台面板 无法打开

**Comment by Jrohy** [comment]
改了端口要加端口才能访问 @10N99

**Comment by 10N99** [comment]
> 改了端口要加端口权限访问@ 10N99

就是加了端口 也打不开

**Comment by 10N99** [comment]
谢谢 已经设置ok了
