### ISSUE TITLE
有证书，trojan可用 web没有 怎么回事

### ISSUE THREAD

**Issue by Yangchao97** [Jrohy/trojan#147]

**Comment by Jrohy** [comment]
systemctl status trojan-web, 看下是不是没启动

**Comment by Yangchao97** [comment]
● trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since 三 2020-05-20 06:00:55 UTC; 12min ago
     Docs: https://github.com/Jrohy/trojan
  Process: 3880 ExecStart=/usr/local/bin/trojan web (code=exited, status=0/SUCCESS)
 Main PID: 3880 (code=exited, status=0/SUCCESS)

**Comment by Yangchao97** [comment]
好像是权限的问题

**Comment by Jrohy** [comment]
systemctl restart trojan-web有作用不

**Comment by Yangchao97** [comment]
systemctl restart trojan-web 起作用了
