### ISSUE TITLE
安装完查看状态trojan.service failed.之前安装没有这个问题，请问怎么解决，感谢

### ISSUE THREAD

**Issue by iCirno** [Jrohy/trojan#15]
4.查看trojan状态

请选择: 4
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-03-19 16:28:35 UTC; 331ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 2068 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 2068 (code=exited, status=1/FAILURE)

Mar 19 16:28:35 twumr systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Mar 19 16:28:35 twumr systemd[1]: Unit trojan.service entered failed state.
Mar 19 16:28:35 twumr systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
重启有用不，操作了啥变成这样了

**Comment by iCirno** [comment]
> 
> 
> 重启有用不，操作了啥变成这样了

重启没用。GCP的机子，按教程一路下来的，啥也没动。
root@twumr:~# trojan
Welcome to trojan 1.14.1
[2020-03-20 02:51:55] [FATAL] fatal: config.json: cannot open file
[2020-03-20 02:51:55] [FATAL] exiting. . . 
root@twumr:~#

**Comment by Jrohy** [comment]
什么系统呢

**Comment by iCirno** [comment]
新开的机器，Debian9 64，域名解析，证书绑定均成功。
重新安装一遍发现一个问题：
[Fri Mar 20 03:02:55 UTC 2020] Using: ss
[Fri Mar 20 03:02:55 UTC 2020] LISTEN     0      32768       :::80                      :::*                   users:(("trojan",pid=1863,fd=3))
[Fri Mar 20 03:02:55 UTC 2020] tcp port 80 is already used by 80                      
[Fri Mar 20 03:02:55 UTC 2020] Please stop it first
防火墙设置如下
![图片](https://user-images.githubusercontent.com/30268212/77132954-45665c00-6a9c-11ea-9451-65a06cca61f0.png)
是不是80端口被占用。。。

**Comment by Jrohy** [comment]
是的，这里可能有bug, 先`systemctl stop trojan-web`, 再安装管理那里证书申请

**Comment by Jrohy** [comment]
申请完证书，再启动web服务systemctl start trojan-web, 我修复一下这脚本bug

**Comment by iCirno** [comment]
> 
> 
> 申请完证书，再启动web服务systemctl start trojan-web, 现在已修复这安装脚本bug

ok，非常感谢，已经可用了
