### ISSUE TITLE
大佬麻烦问下，查流量的文件在哪里呢。

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/trojan#150]
大佬麻烦问下，查流量的文件存在哪里呢。谢谢大佬。

**Comment by bbhxwl** [comment]
默认程序有进程守护和开机自启动吗？

**Comment by Jrohy** [comment]
流量信息存在数据库里面

**Comment by Jrohy** [comment]
> 默认程序有进程守护和开机自启动吗？

有的

**Comment by bbhxwl** [comment]
> 流量信息存在数据库里面

大佬能麻烦指点一下位置么。是啥数据库？

**Comment by Jrohy** [comment]
默认安装mariadb

**Comment by bbhxwl** [comment]
> mariadb

mariadb 文件位置能告知一下么？

**Comment by Jrohy** [comment]
/home/mariadb

**Comment by bbhxwl** [comment]
> /home/mariadb

装完了v2ray，也能正常运行，也没看到有这个文件夹呢。/home/mariadb

**Comment by Jrohy** [comment]
@bbhxwl 本项目是trojan, 不是v2ray..

**Comment by bbhxwl** [comment]
> @bbhxwl 本项目是trojan, 不是v2ray..

我晕，问错地方了，不好意思，一会去v2ray，都标星星了
