### ISSUE TITLE
mariadb 数据库无法登录

### ISSUE THREAD

**Issue by tangcloud** [Jrohy/trojan#151]
感谢大佬的脚本
脚本运行可以正常使用,web面板也可以正常访问,但是mariadb root 用户无法登录数据库 
![image](https://user-images.githubusercontent.com/65888761/82788481-22409a00-9e9b-11ea-85f7-043c562f9143.png)密码不是trojan 吗??

**Comment by Jrohy** [comment]
不是的，看下trojan配置文件里面写的密码

**Comment by tangcloud** [comment]
额 我说的是数据库的密码  trojan 是可以正常使用 我说的是访问数据库的密码

**Comment by Jrohy** [comment]
是的，就是指mariadb的密码，写在了trojan的配置文件里面

**Comment by Jrohy** [comment]
trojan配置文件路径: /usr/local/etc/trojan/config.json

**Comment by tangcloud** [comment]
找到了 谢谢大佬
