### ISSUE TITLE
虽然可以理解，没有冒犯的意思，但是还是想问下这个项目有没有留后门？

### ISSUE THREAD

**Issue by ShotoZhao** [Jrohy/trojan#155]
rt，谢谢

**Comment by Jrohy** [comment]
开源可以自己检查下代码

**Comment by Jrohy** [comment]
编译出来的信不过，可以自己编译的，先前端进行编译，编译出dist文件夹里面的全部文件拷贝到本项目里的web/templates(没有先自己创建), 然后运行build.sh脚本即可编译(build.sh里面得注释掉上传release的代码)

**Comment by ShotoZhao** [comment]
> 编译出来的信不过，可以自己编译的，先前端进行编译，编译出dist文件夹里面的全部文件拷贝到本项目里的web/templates(没有先自己创建), 然后运行build.sh脚本即可编译(build.sh里面得注释掉上传release的代码)

大佬牛逼（破音）

**Comment by hahaleyile** [comment]
这问题问的。。
开源留后门，要么艺高人胆大，要么不完全开源。
比如搞client-server模式的，只开源client代码。
或者在开源项目里面放二进制文件或者代码里涉及下二进制文件的
再说了，就算真有人有那个心思，会说自己留后门了吗

**Comment by ShotoZhao** [comment]
人家说了 有二进制。问了总比不问好

**Comment by hahaleyile** [comment]
> 人家说了 有二进制。问了总比不问好

不好意思，整个项目我之前都clone下来看过了，没找到所谓的二进制文件。您要是方便能指定一下是哪个文件吗？项目文件倒是有引用其他项目
