### ISSUE TITLE
如何多机部署？

### ISSUE THREAD

**Issue by chaseSpace** [Jrohy/trojan#156]
一台服务器是固定流量，人多了这台服务器就不够用了，多机部署的方案是怎样的？可以实现统一账号管理。而且客户端是可以修改连接域名的，所以每个服务器单独一个二级域名也不可行（统一账户后，用户自己修改二级域名从而连接到更高级线路），我的本来设想的是每个不同带宽的服务器使用一个单独的二级域名用于区分。

**Comment by Jrohy** [comment]
暂不支持多机机部署后统一管理

**Comment by lllrrr2** [comment]
可以导入导出用户帐号密码就好了
