### ISSUE TITLE
通过命令使用letsencrypt申请证书后无法访问管理端

### ISSUE THREAD

**Issue by chaseSpace** [Jrohy/trojan#157]
命令执行正常，但完成后用申请证书的域名访问不了管理端。

**Comment by chaseSpace** [comment]
填写我自己申请的证书路径是可以的

**Comment by chaseSpace** [comment]
日志：
5月 27 13:06:01 2020051472712 trojan[812]: [2020-05-27 13:06:01] [FATAL] fatal: use_certificate_chain_file: No such file or directory
5月 27 13:06:01 2020051472712 trojan[812]: [2020-05-27 13:06:01] [FATAL] exiting. . .
5月 27 13:06:01 2020051472712 systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
5月 27 13:06:01 2020051472712 systemd[1]: Unit trojan.service entered failed state.
5月 27 13:06:01 2020051472712 systemd[1]: trojan.service failed.
5月 27 13:06:04 2020051472712 systemd[1]: trojan.service holdoff time over, scheduling restart.
5月 27 13:06:04 2020051472712 systemd[1]: Stopped trojan.
5月 27 13:06:04 2020051472712 systemd[1]: Started trojan.
5月 27 13:06:04 2020051472712 trojan[995]: Welcome to trojan 1.15.1
5月 27 13:06:04 2020051472712 trojan[995]: [2020-05-27 13:06:04] [FATAL] fatal: use_certificate_chain_file: No such file or directory
5月 27 13:06:04 2020051472712 trojan[995]: [2020-05-27 13:06:04] [FATAL] exiting. . .
5月 27 13:06:04 2020051472712 systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
5月 27 13:06:04 2020051472712 systemd[1]: Unit trojan.service entered failed state.
5月 27 13:06:04 2020051472712 systemd[1]: trojan.service failed.

**Comment by chaseSpace** [comment]
辛苦了~

**Comment by Jrohy** [comment]
没申请到证书吧，证书文件不存在

**Comment by chaseSpace** [comment]
是的我知道，但是您能帮你看下具体原因吗？谢谢～

**Comment by Jrohy** [comment]
申请证书时的日志发下

**Comment by chaseSpace** [comment]
现在不太方便，大概二十分钟后发出来

**Comment by chaseSpace** [comment]
hk-980f924c-22b1.ddasdas.手动打码 解析到的ip: [45.144.137.打码]
[2020年 05月 27日 星期三 13:41:21 CST] Lets find script dir.
[2020年 05月 27日 星期三 13:41:21 CST] _SCRIPT_='/root/.acme.sh/acme.sh'
[2020年 05月 27日 星期三 13:41:21 CST] _script='/root/.acme.sh/acme.sh'
[2020年 05月 27日 星期三 13:41:21 CST] _script_home='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v2.8.6
[2020年 05月 27日 星期三 13:41:21 CST] Using config home:/root/.acme.sh
[2020年 05月 27日 星期三 13:41:21 CST] Running cmd: issue
[2020年 05月 27日 星期三 13:41:21 CST] _main_domain='hk-980f924c-22b1.ddasdas.手动打码'
[2020年 05月 27日 星期三 13:41:21 CST] _alt_domains='no'
[2020年 05月 27日 星期三 13:41:21 CST] Using config home:/root/.acme.sh
[2020年 05月 27日 星期三 13:41:21 CST] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[2020年 05月 27日 星期三 13:41:21 CST] DOMAIN_PATH='/root/.acme.sh/hk-980f924c-22b1.ddasdas.手动打码_ecc'
[2020年 05月 27日 星期三 13:41:21 CST] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[2020年 05月 27日 星期三 13:41:21 CST] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[2020年 05月 27日 星期三 13:41:21 CST] GET
[2020年 05月 27日 星期三 13:41:21 CST] url='https://acme-v02.api.letsencrypt.org/directory'
[2020年 05月 27日 星期三 13:41:21 CST] timeout=
[2020年 05月 27日 星期三 13:41:21 CST] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[2020年 05月 27日 星期三 13:41:22 CST] ret='0'
[2020年 05月 27日 星期三 13:41:22 CST] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[2020年 05月 27日 星期三 13:41:22 CST] ACME_NEW_AUTHZ
[2020年 05月 27日 星期三 13:41:22 CST] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[2020年 05月 27日 星期三 13:41:22 CST] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[2020年 05月 27日 星期三 13:41:23 CST] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[2020年 05月 27日 星期三 13:41:23 CST] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[2020年 05月 27日 星期三 13:41:23 CST] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[2020年 05月 27日 星期三 13:41:23 CST] ACME_VERSION='2'
[2020年 05月 27日 星期三 13:41:23 CST] Le_NextRenewTime
[2020年 05月 27日 星期三 13:41:23 CST] _on_before_issue
[2020年 05月 27日 星期三 13:41:23 CST] _chk_main_domain='hk-980f924c-22b1.ddasdas.手动打码'
[2020年 05月 27日 星期三 13:41:23 CST] _chk_alt_domains
[2020年 05月 27日 星期三 13:41:23 CST] Le_LocalAddress
[2020年 05月 27日 星期三 13:41:23 CST] d='hk-980f924c-22b1.ddasdas.手动打码'
[2020年 05月 27日 星期三 13:41:23 CST] Check for domain='hk-980f924c-22b1.ddasdas.手动打码'
[2020年 05月 27日 星期三 13:41:23 CST] _currentRoot='no'
[2020年 05月 27日 星期三 13:41:23 CST] Standalone mode.
[2020年 05月 27日 星期三 13:41:23 CST] _checkport='80'
[2020年 05月 27日 星期三 13:41:23 CST] _checkaddr
[2020年 05月 27日 星期三 13:41:23 CST] Using: ss
[2020年 05月 27日 星期三 13:41:23 CST] LISTEN     0      128       [::]:80                    [::]:*                   users:(("trojan",pid=22922,fd=3))
[2020年 05月 27日 星期三 13:41:23 CST] tcp port 80 is already used by 80                    [
[2020年 05月 27日 星期三 13:41:23 CST] Please stop it first
[2020年 05月 27日 星期三 13:41:23 CST] _on_before_issue.
重启trojan成功!

**Comment by Jrohy** [comment]
端口80被占用了，先停了trojan-web, 再去申请证书: `systemctl stop trojan-web`, 申请完证书后再启动回去

**Comment by chaseSpace** [comment]
按你说的解决了，Thanks♪(･ω･)ﾉ

**Comment by chaseSpace** [comment]
我用另一个二级域名申请遇到了新的错误，我看了最后的日志仍然是找不到证书文件，我把生成证书的日志贴出来：
请输入申请证书的域名: cn2-gia-42ab3a31-69c4.ddasdas.手动打码
cn2-gia-42ab3a31-69c4.ddasdas.手动打码 解析到的ip: [212.95.154.打码]
[Wed May 27 06:16:57 UTC 2020] Lets find script dir.
[Wed May 27 06:16:57 UTC 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Wed May 27 06:16:57 UTC 2020] _script='/root/.acme.sh/acme.sh'
[Wed May 27 06:16:57 UTC 2020] _script_home='/root/.acme.sh'
[Wed May 27 06:16:57 UTC 2020] Using default home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.6
[Wed May 27 06:16:57 UTC 2020] Using config home:/root/.acme.sh
[Wed May 27 06:16:57 UTC 2020] Running cmd: issue
[Wed May 27 06:16:57 UTC 2020] _main_domain='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:57 UTC 2020] _alt_domains='no'
[Wed May 27 06:16:57 UTC 2020] Using config home:/root/.acme.sh
[Wed May 27 06:16:57 UTC 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed May 27 06:16:58 UTC 2020] DOMAIN_PATH='/root/.acme.sh/cn2-gia-42ab3a31-69c4.ddasdas.手动打码_ecc'
[Wed May 27 06:16:58 UTC 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Wed May 27 06:16:58 UTC 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Wed May 27 06:16:58 UTC 2020] GET
[Wed May 27 06:16:58 UTC 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Wed May 27 06:16:58 UTC 2020] timeout=
[Wed May 27 06:16:58 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:16:58 UTC 2020] ret='0'
[Wed May 27 06:16:58 UTC 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Wed May 27 06:16:58 UTC 2020] ACME_NEW_AUTHZ
[Wed May 27 06:16:58 UTC 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed May 27 06:16:58 UTC 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Wed May 27 06:16:58 UTC 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed May 27 06:16:58 UTC 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Wed May 27 06:16:58 UTC 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed May 27 06:16:58 UTC 2020] ACME_VERSION='2'
[Wed May 27 06:16:58 UTC 2020] Le_NextRenewTime
[Wed May 27 06:16:58 UTC 2020] _on_before_issue
[Wed May 27 06:16:58 UTC 2020] _chk_main_domain='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:58 UTC 2020] _chk_alt_domains
[Wed May 27 06:16:58 UTC 2020] Le_LocalAddress
[Wed May 27 06:16:58 UTC 2020] d='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:58 UTC 2020] Check for domain='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:58 UTC 2020] _currentRoot='no'
[Wed May 27 06:16:58 UTC 2020] Standalone mode.
[Wed May 27 06:16:58 UTC 2020] _checkport='80'
[Wed May 27 06:16:58 UTC 2020] _checkaddr
[Wed May 27 06:16:58 UTC 2020] Using: ss
[Wed May 27 06:16:58 UTC 2020] d
[Wed May 27 06:16:58 UTC 2020] _saved_account_key_hash is not changed, skip register account.
[Wed May 27 06:16:58 UTC 2020] Read key length:ec-256
[Wed May 27 06:16:58 UTC 2020] _createcsr
[Wed May 27 06:16:58 UTC 2020] Single domain='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:58 UTC 2020] Getting domain auth token for each domain
[Wed May 27 06:16:58 UTC 2020] d
[Wed May 27 06:16:58 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed May 27 06:16:58 UTC 2020] payload='{"identifiers": [{"type":"dns","value":"cn2-gia-42ab3a31-69c4.ddasdas.手动打码"}]}'
[Wed May 27 06:16:58 UTC 2020] RSA key
[Wed May 27 06:16:58 UTC 2020] HEAD
[Wed May 27 06:16:58 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed May 27 06:16:58 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Wed May 27 06:16:58 UTC 2020] _ret='0'
[Wed May 27 06:16:58 UTC 2020] POST
[Wed May 27 06:16:58 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed May 27 06:16:58 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:16:59 UTC 2020] _ret='0'
[Wed May 27 06:16:59 UTC 2020] code='201'
[Wed May 27 06:16:59 UTC 2020] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/87218363/3520997138'
[Wed May 27 06:16:59 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/87218363/3520997138'
[Wed May 27 06:16:59 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/4838816576'
[Wed May 27 06:16:59 UTC 2020] payload
[Wed May 27 06:16:59 UTC 2020] POST
[Wed May 27 06:16:59 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/4838816576'
[Wed May 27 06:16:59 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:16:59 UTC 2020] _ret='0'
[Wed May 27 06:16:59 UTC 2020] code='200'
[Wed May 27 06:16:59 UTC 2020] d='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:59 UTC 2020] Getting webroot for domain='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:59 UTC 2020] _w='no'
[Wed May 27 06:16:59 UTC 2020] _currentRoot='no'
[Wed May 27 06:16:59 UTC 2020] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g","token":"PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM"'
[Wed May 27 06:16:59 UTC 2020] token='PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM'
[Wed May 27 06:16:59 UTC 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:16:59 UTC 2020] keyauthorization='PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0'
[Wed May 27 06:16:59 UTC 2020] dvlist='cn2-gia-42ab3a31-69c4.ddasdas.手动打码#PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0#https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g#http-01#no'
[Wed May 27 06:16:59 UTC 2020] d
[Wed May 27 06:16:59 UTC 2020] vlist='cn2-gia-42ab3a31-69c4.ddasdas.手动打码#PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0#https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g#http-01#no,'
[Wed May 27 06:16:59 UTC 2020] d='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:59 UTC 2020] ok, let's start to verify
[Wed May 27 06:16:59 UTC 2020] Verifying: cn2-gia-42ab3a31-69c4.ddasdas.手动打码
[Wed May 27 06:16:59 UTC 2020] d='cn2-gia-42ab3a31-69c4.ddasdas.手动打码'
[Wed May 27 06:16:59 UTC 2020] keyauthorization='PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0'
[Wed May 27 06:16:59 UTC 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:16:59 UTC 2020] _currentRoot='no'
[Wed May 27 06:16:59 UTC 2020] Standalone mode server
[Wed May 27 06:16:59 UTC 2020] content='PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0'
[Wed May 27 06:16:59 UTC 2020] ncaddr
[Wed May 27 06:16:59 UTC 2020] startserver: 3763
[Wed May 27 06:16:59 UTC 2020] Le_HTTPPort='80'
[Wed May 27 06:16:59 UTC 2020] Le_Listen_V4
[Wed May 27 06:16:59 UTC 2020] Le_Listen_V6
[Wed May 27 06:16:59 UTC 2020] _content_len='87'
[Wed May 27 06:16:59 UTC 2020] _NC='socat TCP-LISTEN:80,crlf,reuseaddr,fork'
[Wed May 27 06:17:00 UTC 2020] serverproc='4569'
[Wed May 27 06:17:01 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:01 UTC 2020] payload='{}'
[Wed May 27 06:17:01 UTC 2020] POST
[Wed May 27 06:17:01 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:01 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:17:01 UTC 2020] _ret='0'
[Wed May 27 06:17:01 UTC 2020] code='200'
[Wed May 27 06:17:01 UTC 2020] trigger validation code: 200
[Wed May 27 06:17:01 UTC 2020] sleep 2 secs to verify
[Wed May 27 06:17:03 UTC 2020] checking
[Wed May 27 06:17:03 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:03 UTC 2020] payload
[Wed May 27 06:17:03 UTC 2020] POST
[Wed May 27 06:17:03 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:03 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:17:03 UTC 2020] _ret='0'
[Wed May 27 06:17:03 UTC 2020] code='200'
[Wed May 27 06:17:03 UTC 2020] cn2-gia-42ab3a31-69c4.ddasdas.手动打码:Verify error:Fetching http://cn2-gia-42ab3a31-69c4.ddasdas.手动打码/.well-known/acme-challenge/PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM: Error getting validation data
[Wed May 27 06:17:03 UTC 2020] Debug: get token url.
[Wed May 27 06:17:03 UTC 2020] GET
[Wed May 27 06:17:03 UTC 2020] url='http://cn2-gia-42ab3a31-69c4.ddasdas.手动打码/.well-known/acme-challenge/PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM'
[Wed May 27 06:17:03 UTC 2020] timeout=1
[Wed May 27 06:17:03 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Wed May 27 06:17:04 UTC 2020] ret='0'
[Wed May 27 06:17:04 UTC 2020] Skip for removelevel:
[Wed May 27 06:17:04 UTC 2020] pid='4569'
[Wed May 27 06:17:04 UTC 2020] No need to restore nginx, skip.
[Wed May 27 06:17:04 UTC 2020] _clearupdns
[Wed May 27 06:17:04 UTC 2020] dns_entries
[Wed May 27 06:17:04 UTC 2020] skip dns.
[Wed May 27 06:17:04 UTC 2020] _on_issue_err
[Wed May 27 06:17:04 UTC 2020] Please add '--debug' or '--log' to check more details.
[Wed May 27 06:17:04 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed May 27 06:17:05 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:05 UTC 2020] payload='{}'
[Wed May 27 06:17:05 UTC 2020] POST
[Wed May 27 06:17:05 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4838816576/yaI39g'
[Wed May 27 06:17:05 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed May 27 06:17:05 UTC 2020] _ret='0'
[Wed May 27 06:17:05 UTC 2020] code='400'
PBKyMiRoIZbp01mCD8WrhS-UdqHr0HOzmTSxdpuWpIM.1VMQFbmMY5nnNMgPuCOBJLvM_mGjBdgpdWQT7SLUGs0
[Wed May 27 06:17:05 UTC 2020] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.1c FIPS  28 May 2019
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on May 14 2019 05:11:55
   running on Linux version #1 SMP Tue May 12 16:57:42 UTC 2020, release 3.10.0-1127.8.2.el7.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #undef WITH_LIBWRAP
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
重启trojan成功!

**Comment by Jrohy** [comment]
看起来验证失败

**Comment by chaseSpace** [comment]
OK，不管这个了，我是在自建的centos-docker环境中搭建的trojan，不在docker中就没这问题，你看下另外一个问题，我重新提个issue。
