### ISSUE TITLE
web管理端偶尔弹出【连接mysql失败】的提示，但可以正常操作

### ISSUE THREAD

**Issue by chaseSpace** [Jrohy/trojan#158]
日志如下：
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [ERROR] 打码.109.111.0:7032 SSL handshake failed: stream truncated
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [INFO] 打码.109.111.0:7032 disconnected, 0 bytes received, 0 bytes sent, lasted for 16 seconds
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [ERROR] 打码.109.111.0:7034 SSL handshake failed: stream truncated
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [INFO] 打码.109.111.0:7034 disconnected, 0 bytes received, 0 bytes sent, lasted for 16 seconds
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [ERROR] 打码.109.111.0:7098 SSL handshake failed: stream truncated
5月 27 14:43:15 vpszi trojan[26680]: [2020-05-27 14:43:15] [INFO] 打码.109.111.0:7098 disconnected, 0 bytes received, 0 bytes sent, lasted for 9 seconds
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7190 not trojan request, connecting to 127.0.0.1:80
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7188 not trojan request, connecting to 127.0.0.1:80
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7189 not trojan request, connecting to 127.0.0.1:80
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7198 not trojan request, connecting to 127.0.0.1:80
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7197 not trojan request, connecting to 127.0.0.1:80
5月 27 14:43:16 vpszi trojan[26680]: [2020-05-27 14:43:16] [WARN] 打码.109.111.0:7199 not trojan request, connecting to 127.0.0.1:80

这个目前我没看到有其他的影响，你可以根据优先级来排查这个问题哈。

**Comment by chaseSpace** [comment]
访问的https

**Comment by Jrohy** [comment]
能在web页面看到用户账号那些么

**Comment by chaseSpace** [comment]
账号的操作正常

**Comment by Jrohy** [comment]
f12看下什么接口报的连接mysql失败，报这个就是连接mysql有问题了

**Comment by chaseSpace** [comment]
ok，现在没报了，下次我逮到发出来

**Comment by chaseSpace** [comment]
可以加一个分组功能，给用户分组，分组有增删改查的功能；另外怎么赞助你

**Comment by Jrohy** [comment]
赞助就没必要了有风险，分组暂时不考虑
