### ISSUE TITLE
在安装docker版的mysql时出现问题 系统debian10 

### ISSUE THREAD

**Issue by Rivenstyle** [Jrohy/trojan#16]
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
errors pretty printing info
docker  install success!

docker run --name trojan-mysql --restart=always -p 55487:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=kXrwj -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7

iptables v1.8.2 (nf_tables): 
 RULE_INSERT failed (No such file or directory): rule in chain INPUT

iptables v1.8.2 (nf_tables): 
 RULE_INSERT failed (No such file or directory): rule in chain INPUT

iptables v1.8.2 (nf_tables): 
 RULE_INSERT failed (No such file or directory): rule in chain OUTPUT

iptables v1.8.2 (nf_tables): 
 RULE_INSERT failed (No such file or directory): rule in chain OUTPUT
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
mysql启动中, 请稍等...

**Comment by Jrohy** [comment]
用vultr的debian10 测了docker安装没问题，用的这个安装脚本:https://github.com/Jrohy/docker-install, 你可以试下官方的`sh <(curl -sL https://get.docker.com)`

**Comment by Rivenstyle** [comment]
你好，我用搬瓦工和cloudcone的vps测试debian10都不可以，我用安装脚本安装后显示新的错误
docker run --name trojan-mysql --restart=always -p 46845:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=ssKdP -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7
bash: iptables: command not found
bash: iptables: command not found
bash: iptables: command not found
bash: iptables: command not found
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by Jrohy** [comment]
看到一些帖子说这个iptables报的错是debian10 的bug, https://github.com/saltstack/salt/issues/55110,  如果官方安装脚本也不行可以换下其他系统，或者不用docker 自己安装非docker版的mysql，到时管理程序指定一下mysql链接就好

**Comment by Jrohy** [comment]
你试试用官方脚本来安装`sh <(curl -sL https://get.docker.com)`, 先安装docker成功再说，安装完 docker info看下能否运行

**Comment by Rivenstyle** [comment]
应该是debian10系统的问题，我打算尝试一下centos8

**Comment by Jrohy** [comment]
我用cloudcone vps的debian10 系统测了安装docker和mysql那环节没问题😂

**Comment by Rivenstyle** [comment]
测试 搬瓦工 centos8也不行 debian9可以，cloudcone很奇怪我第一遍装可以，第二遍就不行了

**Comment by Rivenstyle** [comment]
建议作者可以在脚本里检测依赖，面板也加上ssl

**Comment by Jrohy** [comment]
@Rivenstyle docker没什么依赖的，只要内核大于3.10,一般用二进制文件就能安装

**Comment by Rivenstyle** [comment]
安装已经成功，感谢作者，请问可以在配置文件里设置只监听某个域名吗，禁止直接ip访问面板

**Comment by Jrohy** [comment]
@Rivenstyle 不支持
