### ISSUE TITLE
Ubuntu系统最近CPU占用总是100% 重启Trojan后才恢复

### ISSUE THREAD

**Issue by 248655** [Jrohy/trojan#163]
如题，很苦恼啊。开始用的centos系统，也是CPU老是100%，重启之后命令就没用了。后来换了ubuntu现在还是CPU时不时会100%。没用面板的时候用最初的并没有到100%过。
补充一下，CPU满了之后web也失效了。

**Comment by Jrohy** [comment]
top看下资源占用

**Comment by 248655** [comment]
> top看下资源占用

等下次卡的时候我top一下看看，现在的话都很正常。非常感谢你能回帖

**Comment by 248655** [comment]
> top看下资源占用
今天又开始了
![QQ图片20200529173820](https://user-images.githubusercontent.com/23613788/83245368-35bd6f00-a1d3-11ea-8422-9cb2dcea5e72.png)
![CPU](https://user-images.githubusercontent.com/23613788/83245375-381fc900-a1d3-11ea-864d-02da0d1b88bc.png)

**Comment by 248655** [comment]
今天WEB没有崩溃，Trojan是完全连不上了

**Comment by Jrohy** [comment]
ps 9892 看下时trojan还是trojan-web

**Comment by 248655** [comment]
是trojan，每24小时出现一次，我用的服务器是谷歌云，阿里云的倒是没有出现这个问题。

**Comment by Jrohy** [comment]
官方trojan仓库反馈下

**Comment by 248655** [comment]
好的 谢谢你

**Comment by Jrohy** [comment]
我用的谷歌云centos7 没发现这问题

**Comment by 248655** [comment]
我之前用的也是centos7，但是重启之后Trojan命令就会失效，不能执行。我晚上再尝试下。

**Comment by Jrohy** [comment]
现在新版已经对gcp安装进行优化了，应该不会出现trojan命令找不到的问题，会自动添加/usr/local/bin的path环境变量

**Comment by 248655** [comment]
好的 看到更新了，我晚上试试 非常感谢你的解答
