### ISSUE TITLE
大神·请问错误日志中频频出现以下两个。

### ISSUE THREAD

**Issue by jamesNg0123** [Jrohy/trojan#167]
SSL handshake failed: stream truncated

**Comment by jamesNg0123** [comment]
SSL handshake failed: Connection reset by peer

**Comment by jamesNg0123** [comment]
经常出现这2个问题·都是证书握手失败，断流和重启。请问该怎样解决呢？

**Comment by Jrohy** [comment]
能翻么，还是只是偶尔报这个

**Comment by jamesNg0123** [comment]
能翻，但是会断流。不稳定····

**Comment by Jrohy** [comment]
临近特殊时期，有可能墙强化了

**Comment by jamesNg0123** [comment]
哦·能否使用nat中转机，进行流量转发。这样是否会更稳定呢？

**Comment by Jrohy** [comment]
得自己试下了

**Comment by jamesNg0123** [comment]
好的·感谢！
