### ISSUE TITLE
2.7.7证书问题 申请成功了 https还是打不开

### ISSUE THREAD

**Issue by akudamatata** [Jrohy/trojan#169]
日志奉上 我是Centos8  两台Centos7.x都成功了
1.Let's Encrypt 证书

2.自定义证书路径

请选择使用证书方式: 1
本机ip: IP地址
请输入申请证书的域名: 域名
域名 解析到的ip: [IP地址]
[Sun May 31 17:02:51 CST 2020] Lets find script dir.
[Sun May 31 17:02:51 CST 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sun May 31 17:02:51 CST 2020] _script='/root/.acme.sh/acme.sh'
[Sun May 31 17:02:51 CST 2020] _script_home='/root/.acme.sh'
https://github.com/acmesh-official/acme.sh
v2.8.6
[Sun May 31 17:02:51 CST 2020] Using config home:/root/.acme.sh
[Sun May 31 17:02:51 CST 2020] Running cmd: issue
[Sun May 31 17:02:51 CST 2020] _main_domain='域名'
[Sun May 31 17:02:51 CST 2020] _alt_domains='no'
[Sun May 31 17:02:51 CST 2020] Using config home:/root/.acme.sh
[Sun May 31 17:02:51 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun May 31 17:02:51 CST 2020] DOMAIN_PATH='/root/.acme.sh/域名_ecc'
[Sun May 31 17:02:51 CST 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun May 31 17:02:51 CST 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun May 31 17:02:51 CST 2020] GET
[Sun May 31 17:02:51 CST 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun May 31 17:02:51 CST 2020] timeout=
[Sun May 31 17:02:51 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun May 31 17:02:52 CST 2020] ret='0'
[Sun May 31 17:02:52 CST 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sun May 31 17:02:52 CST 2020] ACME_NEW_AUTHZ
[Sun May 31 17:02:52 CST 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun May 31 17:02:52 CST 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sun May 31 17:02:52 CST 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sun May 31 17:02:52 CST 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sun May 31 17:02:52 CST 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun May 31 17:02:52 CST 2020] ACME_VERSION='2'
[Sun May 31 17:02:52 CST 2020] _on_before_issue
[Sun May 31 17:02:52 CST 2020] _chk_main_domain='域名'
[Sun May 31 17:02:52 CST 2020] _chk_alt_domains
[Sun May 31 17:02:52 CST 2020] Le_LocalAddress
[Sun May 31 17:02:52 CST 2020] d='域名'
[Sun May 31 17:02:52 CST 2020] Check for domain='域名'
[Sun May 31 17:02:52 CST 2020] _currentRoot='no'
[Sun May 31 17:02:52 CST 2020] Standalone mode.
[Sun May 31 17:02:52 CST 2020] _checkport='80'
[Sun May 31 17:02:52 CST 2020] _checkaddr
[Sun May 31 17:02:52 CST 2020] Using: ss
[Sun May 31 17:02:52 CST 2020] d
[Sun May 31 17:02:52 CST 2020] _saved_account_key_hash is not changed, skip register account.
[Sun May 31 17:02:52 CST 2020] Read key length:
[Sun May 31 17:02:52 CST 2020] Creating domain key
[Sun May 31 17:02:52 CST 2020] Using config home:/root/.acme.sh
[Sun May 31 17:02:52 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun May 31 17:02:52 CST 2020] Use length 256
[Sun May 31 17:02:52 CST 2020] Using ec name: prime256v1
[Sun May 31 17:02:52 CST 2020] The domain key is here: /root/.acme.sh/域名_ecc/域名.key
[Sun May 31 17:02:52 CST 2020] _createcsr
[Sun May 31 17:02:52 CST 2020] Single domain='域名'
[Sun May 31 17:02:52 CST 2020] Getting domain auth token for each domain
[Sun May 31 17:02:52 CST 2020] d
[Sun May 31 17:02:52 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun May 31 17:02:52 CST 2020] payload='{"identifiers": [{"type":"dns","value":"域名"}]}'
[Sun May 31 17:02:52 CST 2020] RSA key
[Sun May 31 17:02:52 CST 2020] HEAD
[Sun May 31 17:02:52 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun May 31 17:02:52 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Sun May 31 17:02:53 CST 2020] _ret='0'
[Sun May 31 17:02:53 CST 2020] POST
[Sun May 31 17:02:53 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun May 31 17:02:53 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun May 31 17:02:54 CST 2020] _ret='0'
[Sun May 31 17:02:54 CST 2020] code='201'
[Sun May 31 17:02:54 CST 2020] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/87569058/3575163806'
[Sun May 31 17:02:54 CST 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/87569058/3575163806'
[Sun May 31 17:02:54 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/4927254860'
[Sun May 31 17:02:54 CST 2020] payload
[Sun May 31 17:02:54 CST 2020] POST
[Sun May 31 17:02:54 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/4927254860'
[Sun May 31 17:02:54 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun May 31 17:02:55 CST 2020] _ret='0'
[Sun May 31 17:02:55 CST 2020] code='200'
[Sun May 31 17:02:55 CST 2020] d='域名'
[Sun May 31 17:02:55 CST 2020] Getting webroot for domain='域名'
[Sun May 31 17:02:55 CST 2020] _w='no'
[Sun May 31 17:02:55 CST 2020] _currentRoot='no'
[Sun May 31 17:02:55 CST 2020] entry='"type":"http-01","status":"valid","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/4927254860/o04U0A","token":"D0CDJ7Ap3GV1i-i3ElLXjcANPoFrtQikdG08Ir5iydo","validationRecord":[{"url":"http://域名/.well-known/acme-challenge/D0CDJ7Ap3GV1i-i3ElLXjcANPoFrtQikdG08Ir5iydo","hostname":"域名","port":"80","addressesResolved":["IP地址"],"addressUsed":"IP地址"'
[Sun May 31 17:02:55 CST 2020] token='D0CDJ7Ap3GV1i-i3ElLXjcANPoFrtQikdG08Ir5iydo'
[Sun May 31 17:02:55 CST 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/4927254860/o04U0A'
[Sun May 31 17:02:55 CST 2020] keyauthorization='D0CDJ7Ap3GV1i-i3ElLXjcANPoFrtQikdG08Ir5iydo.Jn-Wr2bvbpaA59YKCLuG6HndFdFhJ-k2L3aIwTF8UYI'
[Sun May 31 17:02:55 CST 2020] 域名 is already verified.
[Sun May 31 17:02:55 CST 2020] keyauthorization='verified_ok'
[Sun May 31 17:02:55 CST 2020] dvlist='域名#verified_ok#https://acme-v02.api.letsencrypt.org/acme/chall-v3/4927254860/o04U0A#http-01#no'
[Sun May 31 17:02:55 CST 2020] d
[Sun May 31 17:02:55 CST 2020] vlist='域名#verified_ok#https://acme-v02.api.letsencrypt.org/acme/chall-v3/4927254860/o04U0A#http-01#no,'
[Sun May 31 17:02:55 CST 2020] d='域名'
[Sun May 31 17:02:55 CST 2020] 域名 is already verified, skip http-01.
[Sun May 31 17:02:55 CST 2020] ok, let's start to verify
[Sun May 31 17:02:55 CST 2020] 域名 is already verified, skip http-01.
[Sun May 31 17:02:55 CST 2020] pid
[Sun May 31 17:02:55 CST 2020] No need to restore nginx, skip.
[Sun May 31 17:02:55 CST 2020] _clearupdns
[Sun May 31 17:02:55 CST 2020] dns_entries
[Sun May 31 17:02:55 CST 2020] skip dns.
[Sun May 31 17:02:55 CST 2020] Verify finished, start to sign.
[Sun May 31 17:02:55 CST 2020] i='2'
[Sun May 31 17:02:55 CST 2020] j='8'
[Sun May 31 17:02:55 CST 2020] Lets finalize the order, Le_OrderFinalize: https://acme-v02.api.letsencrypt.org/acme/finalize/87569058/3575163806
[Sun May 31 17:02:55 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/finalize/87569058/3575163806'
[Sun May 31 17:02:55 CST 2020] payload='{"csr": "MIIBHTCBxAIBADAhMR8wHQYDVQQDDBZoay5ib29tYm9vbWJvb20uY29tLmNuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6LrRRTQfBS_6VJ8Oo9nbpEUuGpbFgHfovxHxCcb301KJfEoihuVxUhbIxxODXxGlRfq08Y6gIQo2hnbQjmjukKBBMD8GCSqGSIb3DQEJDjEyMDAwCwYDVR0PBAQDAgXgMCEGA1UdEQQaMBiCFmhrLmJvb21ib29tYm9vbS5jb20uY24wCgYIKoZIzj0EAwIDSAAwRQIhAN1qWxXvFHvXZA2zk3EupqXTbuM2Srq9-IOWTm0No88jAiACnIaDqb6EGNvsB5qWQtyLfi6GSGjZUEpOPEjWoEIRwA"}'
[Sun May 31 17:02:55 CST 2020] POST
[Sun May 31 17:02:55 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/finalize/87569058/3575163806'
[Sun May 31 17:02:55 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun May 31 17:02:57 CST 2020] _ret='0'
[Sun May 31 17:02:57 CST 2020] code='200'
[Sun May 31 17:02:57 CST 2020] Order status is valid.
[Sun May 31 17:02:57 CST 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0414fb8415fd0c8a90308609726e72336de3'
[Sun May 31 17:02:57 CST 2020] Download cert, Le_LinkCert: https://acme-v02.api.letsencrypt.org/acme/cert/0414fb8415fd0c8a90308609726e72336de3
[Sun May 31 17:02:57 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/cert/0414fb8415fd0c8a90308609726e72336de3'
[Sun May 31 17:02:57 CST 2020] payload
[Sun May 31 17:02:57 CST 2020] POST
[Sun May 31 17:02:57 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/cert/0414fb8415fd0c8a90308609726e72336de3'
[Sun May 31 17:02:57 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun May 31 17:02:57 CST 2020] _ret='0'
[Sun May 31 17:02:57 CST 2020] code='200'
[Sun May 31 17:02:58 CST 2020] Found cert chain
[Sun May 31 17:02:58 CST 2020] _end_n='27'
[Sun May 31 17:02:58 CST 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/0414fb8415fd0c8a90308609726e72336de3'
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:14:fb:84:15:fd:0c:8a:90:30:86:09:72:6e:72:33:6d:e3
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: May 31 08:02:56 2020 GMT
            Not After : Aug 29 08:02:56 2020 GMT
        Subject: CN = 域名
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:e8:ba:d1:45:34:1f:05:2f:fa:54:9f:0e:a3:d9:
                    db:a4:45:2e:1a:96:c5:80:77:e8:bf:11:f1:09:c6:
                    f7:d3:52:89:7c:4a:22:86:e5:71:52:16:c8:c7:13:
                    83:5f:11:a5:45:fa:b4:f1:8e:a0:21:0a:36:86:76:
                    d0:8e:68:ee:90
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                A6:8F:E9:C8:CC:35:BC:B7:4F:A3:77:0C:8B:7E:8B:14:4F:15:CF:55
            X509v3 Authority Key Identifier: 
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name: 
                DNS:域名
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : F0:95:A4:59:F2:00:D1:82:40:10:2D:2F:93:88:8E:AD:
                                4B:FE:1D:47:E3:99:E1:D0:34:A6:B0:A8:AA:8E:B2:73
                    Timestamp : May 31 09:02:56.776 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:1F:9A:50:2A:DC:DB:F6:AD:9E:CF:71:CD:
                                AC:57:86:48:AD:36:39:A1:B6:9C:9D:30:F9:0D:3E:AD:
                                4B:4F:D5:94:02:20:09:FA:6D:6D:DF:40:F7:8A:C8:FE:
                                A4:23:7A:E1:41:AF:10:4A:11:6F:26:8E:E6:17:C2:33:
                                F7:1C:4D:07:61:75
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : B2:1E:05:CC:8B:A2:CD:8A:20:4E:87:66:F9:2B:B9:8A:
                                25:20:67:6B:DA:FA:70:E7:B2:49:53:2D:EF:8B:90:5E
                    Timestamp : May 31 09:02:56.760 2020 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:7F:AA:1E:43:25:42:11:A2:75:BA:8C:FA:
                                91:6F:A6:34:D6:D1:AC:7A:78:58:C0:E0:BB:4D:10:AE:
                                2D:18:DF:AF:02:21:00:98:F0:81:BF:C3:AA:EE:77:BE:
                                1C:EE:33:38:69:5D:01:3E:1F:B5:94:BC:F3:25:6A:EB:
                                70:70:08:37:7C:A8:F9
    Signature Algorithm: sha256WithRSAEncryption
         2d:b5:43:d4:2a:93:dd:cc:4e:31:ea:8a:32:4f:f6:41:6d:d8:
         17:55:43:91:0f:fa:97:ed:52:cb:0e:04:ae:80:70:ae:ca:c3:
         b4:48:c3:c5:63:fa:09:3e:b7:1f:97:53:92:70:1f:96:20:0a:
         8e:ec:cc:25:0a:42:0c:0f:2e:68:63:b9:a0:a2:77:a7:17:e7:
         97:e4:4f:73:5f:9e:ce:fb:a7:47:79:1c:57:ef:af:52:aa:b4:
         79:c8:69:dc:be:f2:83:6f:43:92:2d:c9:35:ac:63:49:5c:5f:
         40:11:a8:b9:d0:06:b4:3a:3c:92:6e:91:7c:36:96:2c:51:ee:
         60:b4:da:c8:d2:cb:16:24:6b:5f:6f:58:f1:4a:7d:7b:39:36:
         f1:8c:a3:b1:4a:ea:45:9a:b8:76:3b:07:ff:39:83:57:c6:33:
         2f:1b:50:ac:02:c2:da:10:52:49:9f:4f:55:8f:db:b0:a2:a8:
         8a:df:f8:de:05:68:c3:9e:1a:f8:2d:86:89:91:e6:55:44:46:
         ba:40:e8:97:c2:57:e8:d2:4d:7d:7c:99:a7:a7:93:53:5a:44:
         7f:a6:79:74:d8:7c:f1:18:57:9a:79:ba:d7:af:04:a8:bf:97:
         16:a0:f6:1b:5b:6f:21:90:f1:f1:df:cf:bb:cb:c0:9d:3a:d9:
         59:53:44:55
[Sun May 31 17:02:58 CST 2020] Cert success.
-----BEGIN CERTIFICATE-----
MIIEmDCCA4CgAwIBAgISBBT7hBX9DIqQMIYJcm5yM23jMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDA1MzEwODAyNTZaFw0y
MDA4MjkwODAyNTZaMCExHzAdBgNVBAMTFmhrLmJvb21ib29tYm9vbS5jb20uY24w
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAToutFFNB8FL/pUnw6j2dukRS4alsWA
d+i/EfEJxvfTUol8SiKG5XFSFsjHE4NfEaVF+rTxjqAhCjaGdtCOaO6Qo4ICajCC
AmYwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSmj+nIzDW8t0+jdwyLfosUTxXPVTAf
BgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRjMGEw
LgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5vcmcw
LwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5vcmcv
MCEGA1UdEQQaMBiCFmhrLmJvb21ib29tYm9vbS5jb20uY24wTAYDVR0gBEUwQzAI
BgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nw
cy5sZXRzZW5jcnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQDwlaRZ
8gDRgkAQLS+TiI6tS/4dR+OZ4dA0prCoqo6ycwAAAXJp+EEIAAAEAwBGMEQCIB+a
UCrc2/atns9xzaxXhkitNjmhtpydMPkNPq1LT9WUAiAJ+m1t30D3isj+pCN64UGv
EEoRbyaO5hfCM/ccTQdhdQB2ALIeBcyLos2KIE6HZvkruYolIGdr2vpw57JJUy3v
i5BeAAABcmn4QPgAAAQDAEcwRQIgf6oeQyVCEaJ1uoz6kW+mNNbRrHp4WMDgu00Q
ri0Y368CIQCY8IG/w6rud74c7jM4aV0BPh+1lLzzJWrrcHAIN3yo+TANBgkqhkiG
9w0BAQsFAAOCAQEALbVD1CqT3cxOMeqKMk/2QW3YF1VDkQ/6l+1Syw4EroBwrsrD
tEjDxWP6CT63H5dTknAfliAKjuzMJQpCDA8uaGO5oKJ3pxfnl+RPc1+ezvunR3kc
V++vUqq0echp3L7yg29Dki3JNaxjSVxfQBGoudAGtDo8km6RfDaWLFHuYLTayNLL
FiRrX29Y8Up9ezk28YyjsUrqRZq4djsH/zmDV8YzLxtQrALC2hBSSZ9PVY/bsKKo
it/43gVow54a+C2GiZHmVURGukDol8JX6NJNfXyZp6eTU1pEf6Z5dNh88RhXmnm6
168EqL+XFqD2G1tvIZDx8d/Pu8vAnTrZWVNEVQ==
-----END CERTIFICATE-----
[Sun May 31 17:02:58 CST 2020] Your cert is in  /root/.acme.sh/域名_ecc/域名.cer 
[Sun May 31 17:02:58 CST 2020] Your cert key is in  /root/.acme.sh/域名_ecc/域名.key 
[Sun May 31 17:02:58 CST 2020] v2 chain.
[Sun May 31 17:02:58 CST 2020] The intermediate CA cert is in  /root/.acme.sh/域名_ecc/ca.cer 
[Sun May 31 17:02:58 CST 2020] And the full chain certs is there:  /root/.acme.sh/域名_ecc/fullchain.cer 
[Sun May 31 17:02:58 CST 2020] _on_issue_success
重启trojan成功!

**Comment by Jrohy** [comment]
看下trojan-web服务状态，systemctl status trojan-web ,看有没有启动

**Comment by akudamatata** [comment]
> 看下trojan-web服务状态，systemctl status trojan-web ,看有没有启动
启动了呢
● trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2020-05-31 17:29:05 CST; 29s ago
     Docs: https://github.com/Jrohy/trojan
 Main PID: 1283 (trojan)
    Tasks: 4 (limit: 2861)
   Memory: 15.6M
   CGroup: /system.slice/trojan-web.service
           └─1283 /usr/local/bin/trojan web

May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] GET    /trojan/user/page         --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] POST   /trojan/user              --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] POST   /trojan/user/update       --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] DELETE /trojan/user              --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] POST   /trojan/data              --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] DELETE /trojan/data              --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] GET    /common/version           --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] GET    /common/serverInfo        --> tro>
May 31 17:29:05 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] POST   /common/loginInfo         --> tro>
May 31 17:29:07 iZj6ch224i91j7rseytjzvZ trojan[1283]: [GIN-debug] Listening and serving HTTP on :80

**Comment by Jrohy** [comment]
用ip能访问不，还是只是https + 域名不能

**Comment by akudamatata** [comment]
> 用ip能访问不，还是只是https + 域名不能

IP访问 https和http都没问题
域名访问 https不可以 http没问题

**Comment by Jrohy** [comment]
是子域名么

**Comment by akudamatata** [comment]
> 是子域名么

是的哦 已经解析好了 hk.xxxxx.com.cn

**Comment by Jrohy** [comment]
子域名本机ping，都是解释到vps ip么

**Comment by akudamatata** [comment]
> 子域名本机ping，都是解释到vps ip么

确定解析到了 ping已经生效了 我发现https://ip 访问 Chrome提示证书不安全

**Comment by Jrohy** [comment]
只有https://域名， 没有https://ip的

**Comment by Jrohy** [comment]
这个https，是trojan本身提供的(使用了443端口)，感觉对子域名的支持不太好，如果要https://域名来访问建议用非子域名

**Comment by Jrohy** [comment]
@akudamatata 可以试试子域名搭建的trojan，能否翻

**Comment by akudamatata** [comment]
> @akudamatata 可以试试子域名搭建的trojan，能否翻

好的 谢谢 辛苦了

**Comment by akudamatata** [comment]
> @akudamatata 可以试试子域名搭建的trojan，能否翻

我重装成了Centos7 就一切正常了 三个子域名和三个服务器均搭建成功  Centos8就不行

**Comment by akudamatata** [comment]
> 这个https，是trojan本身提供的(使用了443端口)，感觉对子域名的支持不太好，如果要[https://域名](https://%E5%9F%9F%E5%90%8D) 来访问建议用非子域名

我重装成了Centos7 就一切正常了 三个子域名和三个服务器均搭建成功 Centos8就不行
