### ISSUE TITLE
Centos 8 貌似不兼容

### ISSUE THREAD

**Issue by akudamatata** [Jrohy/trojan#171]
CentOS 8已经放弃了对Docker容器官方技术支持   
一键或者手动安装都会失败  
在证书申请成功和域名解析成功的情况下  Https依旧无法访问域名 
Trojan-web服务正常 
Centos 8貌似不兼容Docker了   默认使用Podman作为新一代的容器管理工具
Centos7.X全都没问题 一键脚本一键过
折腾一整天8系统 终于弄明白了

**Comment by Jrohy** [comment]
docker 可以二进制方式安装的， 这个一键安装https://github.com/Jrohy/docker-install
