### ISSUE TITLE
给WEB添加一个favicon图标

### ISSUE THREAD

**Issue by lloyd18** [Jrohy/trojan#172]
不知道作者有没有想法

**Comment by Jrohy** [comment]
如果帮设计一个出来也是可以的

**Comment by lloyd18** [comment]
图标吗，不是我设计的，网上找的。![Trojan horse_3px](https://user-images.githubusercontent.com/10294460/83377600-9da8cb00-a408-11ea-8ca2-260bda11aa4d.png)
![10-5木马](https://user-images.githubusercontent.com/10294460/83377601-a13c5200-a408-11ea-864c-2e943872b9c3.png)
