### ISSUE TITLE
第一次用，体验真不错，提几个小建议

### ISSUE THREAD

**Issue by lloyd18** [Jrohy/trojan#174]
1.WEB管理的80端口建议可以自定义，毕竟VPS单纯用来做梯子还是有点浪费。
2.提供关闭WEB管理的选项，SSH管理已经足够，节点地址就是管理地址，容易泄密。
3.添加一个favicon。(抱歉又提一次)
4.交互式脚本需要回车键来确认

**Comment by Jrohy** [comment]
1. 参考wiki更改web端口
2. 部署完后可以关闭web的, 只用命令行添加脚本, systemctl stop trojan-web

**Comment by Jrohy** [comment]
命令行输入免回车是专门做的优化，只要可供选择的项数量在10以内(即需要输入一位数字，而不可能出现输入两位数字)则可免回车

**Comment by lloyd18** [comment]
谢谢解答，初来乍到，还不知道又wiki

**Comment by lloyd18** [comment]
> 1. 参考wiki更改web端口
> 2. 部署完后可以关闭web的, 只用命令行添加脚本, systemctl stop trojan-web
如果改动WEB管理端口，trojan的配置文件要改吗，还有这个    "password": null,是没密码的意思？
![Snipaste_2020-06-01_14-55-36](https://user-images.githubusercontent.com/10294460/83383574-ffbcfc80-a417-11ea-807b-6eeceb1f856c.png)

**Comment by Jrohy** [comment]
不需要改trojan配置文件的， 密码使用数据库里面的，不是配置文件的

**Comment by lloyd18** [comment]
> 不需要改trojan配置文件的， 密码使用数据库里面的，不是配置文件的

明白，感谢

**Comment by nickzheng87** [comment]
加油哦~~~~~支持~~~~~我也想参加这个开发
