### ISSUE TITLE
请问怎样在后台可以查询到用户的浏览记录呢?>

### ISSUE THREAD

**Issue by nickzheng87** [Jrohy/trojan#175]
你好,我想知道怎样在后台查询用户的浏览记录..

**Comment by Jrohy** [comment]
在Web界面看日志，trojan有记录就有得看

**Comment by nickzheng87** [comment]
你好,那么哪里可以改进入后台页面的端口?现在443就可以直接看到后台有点不方便

**Comment by Jrohy** [comment]
查看项目wiki, 改web端口

**Comment by nickzheng87** [comment]
好！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jrohy <notifications@github.com>
发送时间: Tuesday, June 2, 2020 12:12:48 AM
收件人: Jrohy/trojan <trojan@noreply.github.com>
抄送: Li Zheng <S3804583@student.rmit.edu.au>; Author <author@noreply.github.com>
主题: Re: [Jrohy/trojan] 请问怎样在后台可以查询到用户的浏览记录呢?> (#175)


查看项目wiki, 改web端口

**Comment by onlyJinx** [comment]
@Jrohy 请问如何区别那个用户浏览了那些网页? 我用原版的trojan可以根据密码判断那个用户浏览了什么网页, 但是在这个taojan-web的时候好像密码被加密了? 我无法判断什么人浏览了什么网页.

![image](https://user-images.githubusercontent.com/21324835/84151182-8ebfb980-aa95-11ea-8e9e-b41090216455.png)

**Comment by Jrohy** [comment]
@onlyJinx 这个就是原版trojan的日志，没做任何处理的

**Comment by onlyJinx** [comment]
@Jrohy 那应该是数据库的原因了，我用非数据库版本的话是直接显示原始密码的，然后我用密码来判断的，我在想如果是数据库版本的话有没有什么办法区分出是那个用户就看了那些网页呢？
