### ISSUE TITLE
怎么备份用户数据

### ISSUE THREAD

**Issue by LoGav** [Jrohy/trojan#177]
遇到更换VPS,多用户面板怎么备份用户配置文件?

**Comment by Jrohy** [comment]
导出sql来，后面再导进去就好

**Comment by nickzheng87** [comment]
怎么导呢大神?可否教一下?是哪个表呢?

**Comment by Jrohy** [comment]
trojan数据库，可以用navicat等工具导出导入

**Comment by nickzheng87** [comment]
大神,刚下了navicat..但不知道怎样连marioDB...

**Comment by Jrohy** [comment]
就是mysql连接就行

**Comment by nickzheng87** [comment]
db的用户名和密码是??

**Comment by Jrohy** [comment]
看下trojan配置里面，里面的mysql一项有写

**Comment by nickzheng87** [comment]
docker run --name trojan-mariadb --restart=always -p 3306:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2


我用这个密码 trojan不行呢..

**Comment by Jrohy** [comment]
不是这个，密码是随机生成的，看Trojan配置文件

**Comment by nickzheng87** [comment]
貌似找不到配置文件...可以告诉路径在哪里吗?

**Comment by Jrohy** [comment]
这个目录下面：/usr/local/etc/trojan

**Comment by nickzheng87** [comment]
OK了,谢谢你

**Comment by LoGav** [comment]
小白表示一脸懵逼

**Comment by LoGav** [comment]
登陆端口和用户名密码都在/usr/local/etc/trojan 文件,直接登陆导出txt格式,在新VPS导入就可以

**Comment by rickartmiriam** [comment]
> 登陆端口和用户名密码都在/usr/local/etc/trojan 文件,直接登陆导出txt格式,在新VPS导入就可以

你弄懂了吗？我还是没有找到该备份哪个？

**Comment by rickartmiriam** [comment]
> 导出sql来，后面再导进去就好

这个路径是？

**Comment by chnexpats** [comment]
**[ERR] 1364 - Field 'passwordShow' doesn't have a default value** 
From the first version multi-user Trojan to the latest multi-users Trojan Tables via navicat as .txt file, thanks for a help big brother. cheers.

**Comment by Amos-Dan** [comment]
cat /usr/local/etc/trojan/config.json 				        #找到mariadb用户名及密码
docker ps -a										#列出docker程序，之后复制mariadb的ID
docker exec -it c77431aa3e2e bash					#进入容器，其中63db36bc53cd为mariadb的ID
mysqldump -u root -p trojan > trojan.sql			        #备份数据库,docker内运行
docker cp 920201fac97f:trojan.sql /etc				#从容器复制到主机，系统root运行
docker cp /etc/trojan.sql c77431aa3e2e:trojan.sql	        #﻿从主机复制到容器，系统root运行
mysql -u root -p trojan < trojan.sql				       #恢复数据库，docker内运行

**Comment by qq2246367036** [comment]
已经按照上诉大佬方法成功备份，感谢！

**Comment by Jrohy** [comment]
新版已支持直接导入导出sql

**Comment by Amos-Dan** [comment]
嗯，非常棒，已经试用啦。
场景如下：
合并两台vps里的配置文件。
方法：
1.使用导出命令，分别导出并下载两台vps的配置文件；
2.本地打开两个配置文件，将其中一个配置文件中insert之后的部分拷贝到另一个配置文件底部；
3.编辑value值，从1开始依次往后排序，保证value值无重复即可；
4.上载到目标vps，执行导入命令。
所以，可否支持追加导入呢？大佬。

**Comment by Jrohy** [comment]
自己手动合并sql就好

**Comment by Amos-Dan** [comment]
嗯嗯，已经非常方便。

**Comment by weichenxyz** [comment]
![image](https://user-images.githubusercontent.com/76722402/103475505-99062400-4de8-11eb-9809-902268cc5ac5.png)

**Comment by weichenxyz** [comment]
> 看下trojan配置里面，里面的mysql一项有写

![image](https://user-images.githubusercontent.com/76722402/103475505-99062400-4de8-11eb-9809-902268cc5ac5.png)
大佬，用navicat连接服务器时提示这个咋办
