### ISSUE TITLE
Docker版的Trojan-web能不能新增一个修改端口的地方

### ISSUE THREAD

**Issue by qq-admin** [Jrohy/trojan#18]
Trojan的443端口，倒是可以在装完之后，修改/usr/local/etc/trojan/config.json里的配置更改端口，但是Trojan-web没有配置文件，没法修改端口，能否给个修改web端口的机会？

**Comment by Jrohy** [comment]
/etc/systemd/system/trojan-web.service 改里面的文件， 在/usr/local/bin/trojan web后面加上-p xxx端口，你可以看下帮助`trojan help web`, 改完service文件记得systemctl daemon-reload一下

**Comment by qq-admin** [comment]
我试试

**Comment by Jrohy** [comment]
你可以trojan web -p xxx 来测试，只要端口不冲突就能起

**Comment by qq-admin** [comment]
完美，问题解决了。

**Comment by qq-admin** [comment]
大佬有计划支持用户注册登陆和多节点管理么？

**Comment by Jrohy** [comment]
暂时没，那是机场的事，这个不适合机场
