### ISSUE TITLE
请问大大这个错误是什么意思

### ISSUE THREAD

**Issue by nickzheng87** [Jrohy/trojan#180]
![image](https://user-images.githubusercontent.com/62922885/83593852-15116280-a5a1-11ea-97a8-426794221bb1.png)
这个是后台错误,请问大大是什么意思呢?对服务有影响吗?

**Comment by Jrohy** [comment]
能翻不

**Comment by nickzheng87** [comment]
可以的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Jrohy <notifications@github.com>
发送时间: Wednesday, June 3, 2020 1:53:03 PM
收件人: Jrohy/trojan <trojan@noreply.github.com>
抄送: Li Zheng <S3804583@student.rmit.edu.au>; Author <author@noreply.github.com>
主题: Re: [Jrohy/trojan] 请问大大这个错误是什么意思 (#180)


能翻不
