### ISSUE TITLE
项目在在centos重启无法连接web

### ISSUE THREAD

**Issue by ckbkdj** [Jrohy/trojan#181]
1.项目通过一键脚本部署后,按照操作重启服务,web页面长时间打不开
2.过很长时间,提示sql连接失败
3.系统界面的查看配置与 生成json无法使用

**Comment by ckbkdj** [comment]
> 项目通过一键脚本部署后,按照操作重启服务,web页面打不开

过很长时间,提示sql连接失败

**Comment by Jrohy** [comment]
是不是连不上数据库

**Comment by Jrohy** [comment]
还有证书没申请到的话https是无法打开的，纯ip就可以

**Comment by ckbkdj** [comment]
,现在可以登录了.但还是提示mysql连接失败.创建用户没问题

**Comment by Jrohy** [comment]
能看到创建的用户吗

**Comment by ckbkdj** [comment]
可以,创建用户后目前没出现mysql连接失败了.
