### ISSUE TITLE
trojan-go?

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#183]
[Go实现的Trojan代理，支持自动证书申请/多路复用/路由功能/CDN中转/Shadowsocks混淆插件，多平台，无依赖](https://github.com/p4gefau1t/trojan-go)

**Comment by Potterli20** [comment]
如何合并？

**Comment by Jrohy** [comment]
暂不支持trojan-go

**Comment by Potterli20** [comment]
> 
> 
> 暂不支持trojan-go

那有考虑？

**Comment by Jrohy** [comment]
有，想看下能否做成随时切换的形式

**Comment by Potterli20** [comment]
> 
> 
> 有，想看下能否做成随时切换的形式

好麻烦了

**Comment by Potterli20** [comment]
emmm对了，如果用了trojan-go可以多用户？

**Comment by Jrohy** [comment]
可以的

**Comment by Potterli20** [comment]
> 
> 
> 可以的

那可以也，麻烦了，我在等

**Comment by newsouther** [comment]
我也很期待go面板

**Comment by newsouther** [comment]
估计要明年

**Comment by lqhorochi** [comment]
希望支持trojan-go,整合一下多用户.加油

**Comment by ancct** [comment]
同支持！

**Comment by Potterli20** [comment]
技术主也很累的叭，没有支持收益

**Comment by Jrohy** [comment]
@Potterli20  2.8版本支持trojan 和trojan-go 在线随时切换了

**Comment by Os-glthub** [comment]
> @ Potterli20 2.8版本支持trojan和trojan-go在线随时切换了

你好，在线转换能否做的醒目点的地方，web界面和Ubuntu环境里没看见转换键

**Comment by Jrohy** [comment]
@Os-glthub 进去trojan管理页面有类型选择

**Comment by Os-glthub** [comment]
> @Os-glthub 进去trojan管理页面有类型选择

<img width="343" alt="微信截图_20200711111839" src="https://user-images.githubusercontent.com/52124855/87215328-4df2e300-c368-11ea-85eb-6dbb9977a910.png">

**Comment by Os-glthub** [comment]
> @Os-glthub 进去trojan管理页面有类型选择
这样就可以了吗
<img width="789" alt="微信截图_20200711112044" src="https://user-images.githubusercontent.com/52124855/87215373-98745f80-c368-11ea-9e67-0731fdff331c.png">

**Comment by Jrohy** [comment]
是的

**Comment by Os-glthub** [comment]
> 是的

谢谢大佬
