### ISSUE TITLE
如何配置多域名？

### ISSUE THREAD

**Issue by xdkaka** [Jrohy/trojan#185]
当前服务器有多个网卡对应多个IP,想每个域名对应一个IP
思路如下：
1、直接配置trojan，但是发现trojan的SSL只能配置一个证书，有其他方式配置吗？
2、安装宝塔这种nginx面板，不同的域名反向代理到trojan，但是发现宝塔和trojan不共存，即便改了默认端口，没有端口冲突，启动trojan一直提醒如下错误
`请选择: 4
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 日 2020-06-07 12:51:00 CST; 408ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 21941 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 21941 (code=exited, status=1/FAILURE)

6月 07 12:51:00 vultr.guest systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
6月 07 12:51:00 vultr.guest systemd[1]: Unit trojan.service entered failed state.
6月 07 12:51:00 vultr.guest systemd[1]: trojan.service failed.
`

**Comment by Jrohy** [comment]
只能配置一个证书的Trojan
