### ISSUE TITLE
docker安装的怎么修改trojan配置文件

### ISSUE THREAD

**Issue by zhaokelei** [Jrohy/trojan#186]
docker安装的怎么修改trojan配置文件

**Comment by xxgoo** [comment]
> 也是同样的路径，安装vi来修改，或者docker cp拷贝出来后再改

请问docker安装后，Trojan-web端口号怎么改？没找到wiki里说的那个路径文件。

**Comment by Jrohy** [comment]
@xxgoo 有的，看下dockerfile:
https://github.com/Jrohy/trojan/blob/216e0142e2b89173360456e0989ffa16786417f7/asset/Dockerfile#L11-L17
