### ISSUE TITLE
更新面板为最新2.7.7后，在trojan-web当中已经没有新增用户功能了嘛？

### ISSUE THREAD

**Issue by GimmGoo** [Jrohy/trojan#188]
如题，如果没有新增用户功能，每次只能ssh连接到VPS，用代码添加会不会非常不方便？希望能恢复在web面板新增用户功能

**Comment by GimmGoo** [comment]
issue取消，问题出现在更新后没有退出账号重新登录的话不会刷新，只能显示用户列表，已经首页的部分数据

**Comment by Jrohy** [comment]
admin用户才有权限新增的

**Comment by GimmGoo** [comment]
我知道，我是管理员，问题出现在更新后没有退出账号重新登录的话不会刷新，只能显示用户列表，已经首页的部分数据。退出登录后，重新进能看到
