### ISSUE TITLE
添加Trojan-go，发现问题

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#189]
我发现，添加Trojan-go，发现问题
问题是Trojan的版本不变了
还是说需要删了，重新弄？
这是？
我看到更新那里变了
但是我直升上去的

**Comment by Jrohy** [comment]
目前还没完成的，估计2.8才行

**Comment by Potterli20** [comment]
> 目前还没完成的，估计2.8才行

哦哦，明白了
