### ISSUE TITLE
重启VPS后web页面提示服务器端错误，后台trojan启动失败

### ISSUE THREAD

**Issue by 747761541** [Jrohy/trojan#19]
操作系统： centOS7

问题现象：
首次安装或卸载重装后一切功能正常

重启VPS后，web页面提示服务器端错误

后台查看trojan状态提示： 
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2020-03-21 23:07:10 EDT; 54ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 3881 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 3881 (code=exited, status=1/FAILURE)

Mar 21 23:07:10 byhome systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Mar 21 23:07:10 byhome systemd[1]: Unit trojan.service entered failed state.
Mar 21 23:07:10 byhome systemd[1]: trojan.service failed.

重启trojan错误相同

**Comment by Jrohy** [comment]
看下mysql能否连接上, docker logs -f trojan-mysql 看下显示日志有没有退出
