### ISSUE TITLE
Trojan 1.16.0 问题反馈

### ISSUE THREAD

**Issue by Qlmuby** [Jrohy/trojan#192]
Trojan 版本更新到1.16.0，在个别机器上安装出现No route to host错误，网站无法访问，上一版本无此问题。

**Comment by Jrohy** [comment]
会不会是证书问题，trojan能否使用呢

**Comment by Qlmuby** [comment]
> 会不会是证书问题，trojan能否使用呢
应该不是证书的问题，证书申请正常，https访问也正常，Trojan能用。

**Comment by Jrohy** [comment]
看下web服务状态是否启动，systemctl status tojan-web,还有直接用ip能否访问呢
