### ISSUE TITLE
docker 安装使用trojan tls 如何手动指定证书

### ISSUE THREAD

**Issue by biozzl** [Jrohy/trojan#193]
docker 安装使用trojan tls 如何手动指定证书
进入bash后，输入了host的证书路径 提示无效

**Comment by Jrohy** [comment]
要将证书文件docker cp进容器里面才有的，容器里面环境和宿主机环境不一样的

**Comment by biozzl** [comment]
> 要将证书文件docker cp进容器里面才有的，容器里面环境和宿主机环境不一样的

怎么操作啊？能指点下么？

**Comment by Jrohy** [comment]
自己查询docker cp命令
