### ISSUE TITLE
最新脚本安装有报错

### ISSUE THREAD

**Issue by cheneyxx** [Jrohy/trojan#195]
[/etc/systemd/system/trojan.service:9] Executable path is not absolute, ignoring: "/usr/bin/trojan/trojan" "/usr/local/etc/trojan/config.json"
Jun 17 06:21:26 cheneyx systemd[1]: trojan.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Jrohy** [comment]
试下2.8版本的能否成功安装
