### ISSUE TITLE
卡在mysql启动中..............................10分钟过去了

### ISSUE THREAD

**Issue by Os-glthub** [Jrohy/trojan#2]
首先第一次安装是成功的，执行过一次卸载Trojan命令后，卡在MySQL启动中
<img width="498" alt="1" src="https://user-images.githubusercontent.com/52124855/75337280-a482e780-58c7-11ea-93c4-a3814ba28df3.png">

**Comment by Jrohy** [comment]
卸载命令没卸载干净，今晚修复，你手动清下/home/mysql下面的文件就行

**Comment by Jrohy** [comment]
手动清了后再进入安装管理那里有每个环节的安装入口

**Comment by Jrohy** [comment]
还有容器也没删，先手动移除原来的mysql容器docker rm -f trojan-mysql, 然后再删除/home/mysql目录就真正卸载干净了，脚本少了对mysql的卸载操作

**Comment by Os-glthub** [comment]
谢谢大神答复，我偷懒，等你更新卸载命令。

**Comment by Jrohy** [comment]
@Os-glthub 脚本已更新

**Comment by Os-glthub** [comment]
收到，谢谢大神
