### ISSUE TITLE
Docker版的如何有效更改mysql配置？

### ISSUE THREAD

**Issue by qq-admin** [Jrohy/trojan#20]
> 问题背景：服务器配置较小，无法安装docker版的mysql，运行不动，所以想连另一台服务器上的mysql，指定不同的数据库。

**能否在安装Trojan的时候，给出指定账号、数据库名的选项？**
我在安装完Trojan后去配置文件修改mysql配置，结果导致无法科学上网，网页打开倒是正常。

**Comment by Jrohy** [comment]
安装管理那里可以指定mysql链接的, 建议vps内存512m+来安装

**Comment by qq-admin** [comment]
自定义链接只能指定mysql的IP和端口，不能指定连接用户和数据库名

**Comment by Jrohy** [comment]
确实，如果有必要可以自己改下trojan的配置文件就好

**Comment by Jrohy** [comment]
主要不想提示用户输入太多次了

**Comment by qq-admin** [comment]
我等Trojan部署好了去修改/usr/local/etc/trojan/config.json，然后重启，Trojan看状态倒是正常启动的，且web管理页面通过443可以正常打开，但是用Trojan-Qt5连接后无法科学上网

**Comment by Jrohy** [comment]
web页面通过443？， trojan只能用443端口通信的，有改动端口么

**Comment by qq-admin** [comment]
可以增加一个提示
选择MySQL配置方式：
1 - 简单模式 
2 - 复杂模式（可配置用户名、库名）

**Comment by qq-admin** [comment]
端口没有改动，直接通过https://域名打开可以正常进入管理后台

**Comment by Jrohy** [comment]
web服务是独立的，所以trojan怎么改不影响的

**Comment by qq-admin** [comment]
但是很奇怪啊，我改了数据库连接后无法科学上网。
安装时配置A-mysql中的trojan库，我把这个库复制到B-mysql的trojan_test，然后修改Trojan的配置文件，连接到B-mysql，重启Trojan后，通过命令行4.查看配置，看不到密码了。
删除用户重新创建，结果Trojan-Qt5连接后就无法科学上网

**Comment by Jrohy** [comment]
你可以先stop了trojan 用命令行运行trojan来看实时日志
```systemctl stop trojan
/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json```
然后再连接来看下有没有产生连接日志

**Comment by qq-admin** [comment]
好的，我下次再试试。不过真的建议安装时加上MySQL账号和库名的配置。

**Comment by Jrohy** [comment]
一般都有root账号，所以直接指定root账号密码来操作，然后检测没有trojan数据库就自动创建的

**Comment by Jrohy** [comment]
@qq-admin 2.5.1版本开始支持加入mysql账号和库名配置
