### ISSUE TITLE
再打扰一下大佬。问一下这个首页面板的总共和下载这两个数据在哪个json里面version和serveinfo没找到

### ISSUE THREAD

**Issue by tomlongcool** [Jrohy/trojan#200]
![image](https://user-images.githubusercontent.com/54193935/85294119-d51f0a80-b4d0-11ea-81d7-a0166c910bb8.png)

**Comment by tomlongcool** [comment]
我知道是以byte为单位，但是没找到这个数

**Comment by Jrohy** [comment]
user接口
