### ISSUE TITLE
求帮助，弄了10几遍还是不行，是不是证书弄得多了

### ISSUE THREAD

**Issue by LeneSamils** [Jrohy/trojan#205]
Jun 25 15:51:59 guest trojan[4830]: Welcome to trojan 1.16.0
Jun 25 15:51:59 guest trojan[4830]: [2020-06-25 15:51:59] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Jun 25 15:51:59 guest trojan[4830]: [2020-06-25 15:51:59] [FATAL] exiting. . .
Jun 25 15:51:59 guest systemd[1]: Unit trojan.service entered failed state.
Jun 25 15:51:59 guest systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
感觉没申请到证书，看下申请证书包的错

**Comment by LeneSamils** [comment]
感谢大神的回复，我就会用各位大大分享的，屁也不会，我自己的原因，前两次成功啦，觉得和你们的不一样，就多次重装。是不是二级域名是不是也申请不到证书了？刚换个ip解析不到国内，又换回来了，正在解析呢。

**Comment by LeneSamils** [comment]
请输入申请证书的域名: a.123.xyz
a.123.xyz 解析到的ip: [108.61.246.111]
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  193k  100  193k    0     0   447k      0 --:--:-- --:--:-- --:--:--  446k
[Thu Jun 25 19:03:54 CST 2020] Installing from online archive.
[Thu Jun 25 19:03:54 CST 2020] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Thu Jun 25 19:03:56 CST 2020] Extracting master.tar.gz
[Thu Jun 25 19:03:56 CST 2020] Installing to /root/.acme.sh
[Thu Jun 25 19:03:56 CST 2020] Installed to /root/.acme.sh/acme.sh
[Thu Jun 25 19:03:56 CST 2020] Installing alias to '/root/.bashrc'
[Thu Jun 25 19:03:56 CST 2020] OK, Close and reopen your terminal to start using acme.sh
[Thu Jun 25 19:03:56 CST 2020] Installing alias to '/root/.cshrc'
[Thu Jun 25 19:03:56 CST 2020] Installing alias to '/root/.tcshrc'
[Thu Jun 25 19:03:56 CST 2020] Installing cron job
no crontab for root
no crontab for root
[Thu Jun 25 19:03:56 CST 2020] Good, bash is found, so change the shebang to use bash as preferred.
[Thu Jun 25 19:03:57 CST 2020] OK
[Thu Jun 25 19:03:57 CST 2020] Install success!
[Thu Jun 25 19:03:59 CST 2020] Lets find script dir.
[Thu Jun 25 19:03:59 CST 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Thu Jun 25 19:03:59 CST 2020] _script='/root/.acme.sh/acme.sh'
[Thu Jun 25 19:03:59 CST 2020] _script_home='/root/.acme.sh'
[Thu Jun 25 19:03:59 CST 2020] Using default home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.7
[Thu Jun 25 19:03:59 CST 2020] Using config home:/root/.acme.sh
[Thu Jun 25 19:03:59 CST 2020] Running cmd: issue
[Thu Jun 25 19:03:59 CST 2020] _main_domain='a.123.xyz'
[Thu Jun 25 19:03:59 CST 2020] _alt_domains='no'
[Thu Jun 25 19:03:59 CST 2020] Using config home:/root/.acme.sh
[Thu Jun 25 19:03:59 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Jun 25 19:03:59 CST 2020] DOMAIN_PATH='/root/.acme.sh/a.123.xyz_ecc'
[Thu Jun 25 19:03:59 CST 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Thu Jun 25 19:03:59 CST 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu Jun 25 19:03:59 CST 2020] GET
[Thu Jun 25 19:03:59 CST 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Thu Jun 25 19:03:59 CST 2020] timeout=
[Thu Jun 25 19:03:59 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Jun 25 19:03:59 CST 2020] ret='0'
[Thu Jun 25 19:03:59 CST 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Thu Jun 25 19:03:59 CST 2020] ACME_NEW_AUTHZ
[Thu Jun 25 19:03:59 CST 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Jun 25 19:03:59 CST 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Jun 25 19:03:59 CST 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Thu Jun 25 19:03:59 CST 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Thu Jun 25 19:03:59 CST 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Jun 25 19:03:59 CST 2020] ACME_VERSION='2'
[Thu Jun 25 19:04:00 CST 2020] _on_before_issue
[Thu Jun 25 19:04:00 CST 2020] _chk_main_domain='a.123.xyz'
[Thu Jun 25 19:04:00 CST 2020] _chk_alt_domains
[Thu Jun 25 19:04:00 CST 2020] Le_LocalAddress
[Thu Jun 25 19:04:00 CST 2020] d='a.123.xyz'
[Thu Jun 25 19:04:00 CST 2020] Check for domain='a.123.xyz'
[Thu Jun 25 19:04:00 CST 2020] _currentRoot='no'
[Thu Jun 25 19:04:00 CST 2020] Standalone mode.
[Thu Jun 25 19:04:00 CST 2020] _checkport='80'
[Thu Jun 25 19:04:00 CST 2020] _checkaddr
[Thu Jun 25 19:04:00 CST 2020] Using: ss
[Thu Jun 25 19:04:00 CST 2020] d
[Thu Jun 25 19:04:00 CST 2020] config file is empty, can not read CA_KEY_HASH
[Thu Jun 25 19:04:00 CST 2020] Using config home:/root/.acme.sh
[Thu Jun 25 19:04:00 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Jun 25 19:04:00 CST 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Thu Jun 25 19:04:00 CST 2020] Use default length 2048
[Thu Jun 25 19:04:00 CST 2020] length='2048'
[Thu Jun 25 19:04:00 CST 2020] Using config home:/root/.acme.sh
[Thu Jun 25 19:04:00 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Jun 25 19:04:00 CST 2020] Use length 2048
[Thu Jun 25 19:04:00 CST 2020] Using RSA: 2048
[Thu Jun 25 19:04:00 CST 2020] Create account key ok.
[Thu Jun 25 19:04:00 CST 2020] RSA key
[Thu Jun 25 19:04:00 CST 2020] Registering account
[Thu Jun 25 19:04:00 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Jun 25 19:04:00 CST 2020] payload='{"termsOfServiceAgreed": true}'
[Thu Jun 25 19:04:00 CST 2020] HEAD
[Thu Jun 25 19:04:00 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Thu Jun 25 19:04:00 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Thu Jun 25 19:04:00 CST 2020] _ret='0'
[Thu Jun 25 19:04:00 CST 2020] POST
[Thu Jun 25 19:04:00 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Thu Jun 25 19:04:00 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Jun 25 19:04:01 CST 2020] _ret='0'
[Thu Jun 25 19:04:01 CST 2020] code='201'
[Thu Jun 25 19:04:01 CST 2020] Registered
[Thu Jun 25 19:04:01 CST 2020] _accUri='https://acme-v02.api.letsencrypt.org/acme/acct/89721531'
[Thu Jun 25 19:04:01 CST 2020] Calc CA_KEY_HASH='bfyQ4N9agr7Hgzm4OmktMJbeuggqoXHYxR7OSuYDTkc='
[Thu Jun 25 19:04:01 CST 2020] ACCOUNT_THUMBPRINT='ojUKcz_2GBdVU5zp88gdtwbv2ekkC2z27qgT6DZbl7Y'
[Thu Jun 25 19:04:01 CST 2020] Read key length:
[Thu Jun 25 19:04:01 CST 2020] Creating domain key
[Thu Jun 25 19:04:01 CST 2020] Using config home:/root/.acme.sh
[Thu Jun 25 19:04:01 CST 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Thu Jun 25 19:04:01 CST 2020] Use length 256
[Thu Jun 25 19:04:01 CST 2020] Using ec name: prime256v1
[Thu Jun 25 19:04:01 CST 2020] The domain key is here: /root/.acme.sh/a.123.xyz_ecc/a.123.xyz.key
[Thu Jun 25 19:04:01 CST 2020] _createcsr
[Thu Jun 25 19:04:01 CST 2020] Single domain='a.123.xyz'
[Thu Jun 25 19:04:01 CST 2020] Getting domain auth token for each domain
[Thu Jun 25 19:04:02 CST 2020] d
[Thu Jun 25 19:04:02 CST 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Jun 25 19:04:02 CST 2020] payload='{"identifiers": [{"type":"dns","value":"a.123.xyz"}]}'
[Thu Jun 25 19:04:02 CST 2020] POST
[Thu Jun 25 19:04:02 CST 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Thu Jun 25 19:04:02 CST 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Thu Jun 25 19:04:02 CST 2020] _ret='0'
[Thu Jun 25 19:04:02 CST 2020] code='429'
[Thu Jun 25 19:04:02 CST 2020] Le_LinkOrder
[Thu Jun 25 19:04:02 CST 2020] Le_OrderFinalize
[Thu Jun 25 19:04:02 CST 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: a.123.xyz: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Thu Jun 25 19:04:02 CST 2020] pid
[Thu Jun 25 19:04:02 CST 2020] No need to restore nginx, skip.
[Thu Jun 25 19:04:02 CST 2020] _clearupdns
[Thu Jun 25 19:04:02 CST 2020] dns_entries
[Thu Jun 25 19:04:02 CST 2020] skip dns.
[Thu Jun 25 19:04:02 CST 2020] _on_issue_err
[Thu Jun 25 19:04:02 CST 2020] Please add '--debug' or '--log' to check more details.
[Thu Jun 25 19:04:02 CST 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Thu Jun 25 19:04:02 CST 2020] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.2k-fips  26 Jan 2017
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Aug  4 2017 04:57:10
   running on Linux version #1 SMP Wed Jun 3 14:28:03 UTC 2020, release 3.10.0-1127.10.1.el7.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
重启trojan成功!
------------------------------------------------------
还是不行啊

**Comment by LeneSamils** [comment]
> 感觉没申请到证书，看下申请证书包的错

大神给小妹看看吧

**Comment by LeneSamils** [comment]
确实申请不到证书了，我在换下域名吧

**Comment by LeneSamils** [comment]
换域名能申请到证书了，但是开启bbr加速vps就上不去了

**Comment by Jrohy** [comment]
是换了内核后就登录不上vps?

**Comment by Jrohy** [comment]
一般都是建议先弄加速内核，安装加速成功后再安装代理比较稳

**Comment by LeneSamils** [comment]
> 一般都是建议先弄加速内核，安装加速成功后再安装代理比较稳

晚上好大神，我试试

**Comment by LeneSamils** [comment]
好了，换个系统解决了，感谢大神的帮助
