### ISSUE TITLE
Trojan经常性自动停止再启动

### ISSUE THREAD

**Issue by eggydutch** [Jrohy/trojan#206]
如图，查看日志Trojan经常自动停止后再启动，请问这是正常的情况还是有Bug？

![troj](https://user-images.githubusercontent.com/59375032/85945355-d1c3cd00-b96f-11ea-9f3d-22a37a3deedf.png)

**Comment by Jrohy** [comment]
不正常

**Comment by eggydutch** [comment]
> 不正常

好的，知道了，谢谢大佬回复
