### ISSUE TITLE
证书相关问题

### ISSUE THREAD

**Issue by YuanFeis** [Jrohy/trojan#209]
#### 请教大佬关于证书的一些问题
- 使用脚本正常安装，没有任何其他操作，证书是否会过期
- 如果证书会过期是否可以重新申请
- 如果需要重新申请时间间隔是否是3个月
- 脚本提供的相关命令是否支持自动重新申请

- 如果有时间感谢大佬的解答~

**Comment by Jrohy** [comment]
脚本使用的是acme.sh工具来申请的，申请完默认就安装了定时更新证书的定时任务， 可以运行crontab -l来查看

**Comment by YuanFeis** [comment]
好的~感谢大佬。祝工作顺利，生活愉快。
