### ISSUE TITLE
web网页也使用证书加密

### ISSUE THREAD

**Issue by letmekillthemall** [Jrohy/trojan#21]
既然trojan搭建过程已经申请了证书，希望大佬能让web网页重用这个证书，不再是HTTP裸奔

**Comment by Jrohy** [comment]
确实可以，但主要443被trojan占了，开https得换用其他端口

**Comment by Jrohy** [comment]
要输入域名+端口的形式来打开https，愿意不

**Comment by letmekillthemall** [comment]
这似乎也不妥，如果服务器开了额外的端口，那就失去了web服务器的伪装了

**Comment by Jrohy** [comment]
测试了可以做到输入域名(http) 自动跳转到https的服务

**Comment by Jrohy** [comment]
v2.1版本以支持https来启动web，自己权衡是否用这种方式来启动

**Comment by Jrohy** [comment]
如果要以https来启动的话, 修改/etc/systemd/system/trojan-web.service 配置文件
在/usr/local/bin/trojan web 后面添加 --ssl -p [https的启动端口]
然后
systemctl daemon-reload
systemctl restart trojan-web

**Comment by letmekillthemall** [comment]
我发现直接用[http**s**://域名]来访问时浏览器显示是加密状态，我想知道这个加密是否对之后访问web网页的全过程也加密了，还是仅仅跟Trojan握手过程加密了，如果是前者的话，那很抱歉让大佬您白忙活了😂

**Comment by Jrohy** [comment]
全加密的，可以f12看看每个请求链接，也没有外部请求

**Comment by letmekillthemall** [comment]
我去查了一些资料，从443端口进去跟Trojan建立了SSL安全会话以后，就算跳转了80端口也是受到加密的，所以给web的80端口再加一个证书加密有点画蛇添足，以后只要注意从**https://域名**进管理网页就好了，大佬把README的“浏览器访问 http://域名 可在线web页面管理trojan用户”也改一下吧

**Comment by Jrohy** [comment]
确实， 我改成直接https://域名来访问， web 服务其他端口的https算是额外功能
