### ISSUE TITLE
证书时间快到了，请问能自动续签证书吗？如果不能需要如何操作？

### ISSUE THREAD

**Issue by ancct** [Jrohy/trojan#210]
证书时间快到了，请问能自动续签证书吗？如果不能需要如何操作？

**Comment by Jrohy** [comment]
运行下crontab -l看下有没有设置定时任务，正常安装acme.sh会设置定时续证书的任务的

**Comment by cckkrr** [comment]
你好，运行了crontab -l之后，显示如下：
0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web
请问这是会自动续签的意思吗

**Comment by Jrohy** [comment]
@cckkrr 是的

**Comment by rickartmiriam** [comment]
@Jrohy  大神，我也出来这个 
root@kuai1selfuse:~# crontab -l
0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web

应该是自动续签了吗？那为什么我一天了都用不了，运行日志一直提示：
SSL handshake failed: sslv3 alert certificate expired

重新去申请SSL，提示：
[Fri 04 Sep 2020 11:59:57 AM EDT] LISTEN    0         511                0.0.0.0:80               0.0.0.0:*        users:(("nginx",pid=425,fd=6),("nginx",pid=424,fd=6))                          
[Fri 04 Sep 2020 11:59:57 AM EDT] tcp port 80 is already used by (("nginx",pid=425,fd=6),("nginx",pid=424,fd=6))                          
[Fri 04 Sep 2020 11:59:57 AM EDT] Please stop it first
[Fri 04 Sep 2020 11:59:57 AM EDT] _on_before_issue.
重启trojan成功!

就是用不了。。。

**Comment by Jrohy** [comment]
@rickartmiriam 手动关了nginx再来申请

**Comment by rickartmiriam** [comment]
@Jrohy 不好意思，小白用户，手动关nginx？谢谢

**Comment by rickartmiriam** [comment]
是这样关闭 Nginx吗? 输入命令 systemctl stop trojan-web 关了，再去证书申请的，还是提示下面：
[Sat 05 Sep 2020 09:02:24 AM EDT] Using: ss
[Sat 05 Sep 2020 09:02:24 AM EDT] LISTEN    0         511                0.0.0.0:80               0.0.0.0:*        users:(("nginx",pid=425,fd=6),("nginx",pid=424,fd=6))                          
[Sat 05 Sep 2020 09:02:24 AM EDT] tcp port 80 is already used by (("nginx",pid=425,fd=6),("nginx",pid=424,fd=6))                          
[Sat 05 Sep 2020 09:02:24 AM EDT] Please stop it first
[Sat 05 Sep 2020 09:02:24 AM EDT] _on_before_issue.
重启trojan成功!

然后重启 systemctl start trojan-web

最后还是没有成功，运行日志还是提示：
SSL handshake failed: sslv3 alert certificate expired

用不了，到底是这么回事？

**Comment by rickartmiriam** [comment]
@Jrohy 谢谢提示，弄了两天时间终于弄好了：

给大家一个参考：
1. 先停止nginx:  systemctl stop nginx
2. 去重新申请证书：trojan tls

**Comment by rickartmiriam** [comment]
@Jrohy  还有个问题：
按照你上面所说，我运行命令出来的是
root@kuai1selfuse:~# crontab -l
0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web

这个应该就是自动续签证书了，为什么不能我的不会自动续签呢，已经有两台发生了这个问题，都要我手动去重新申请证书，是哪里有什么问题吗？能自动续签证书的话，就更好了。
