### ISSUE TITLE
更新 2.8.0 切换 trojan-go 后，trojan web 无法打开

### ISSUE THREAD

**Issue by coaens** [Jrohy/trojan#211]
大佬，我更新完 2.8.0，在 web 切换 trojan-go 后，trojan web 就进不去了，试了几次都是这样，麻烦看下是不是有这个问题呢？

**Comment by Jrohy** [comment]
切换到trojan-go后运行`journalctl -u trojan -f -n 100`, 看下trojan-go报的日志，看是否启动成功

**Comment by Jrohy** [comment]
因为https是trojan提供的，假如trojan无法正常启动，https就没法用，用ip就没这个问题
