### ISSUE TITLE
web後台管理一直出現 "授權失敗 請重新登錄"

### ISSUE THREAD

**Issue by joxjpu** [Jrohy/trojan#212]
大神你好，首先感謝你提供這麼好的腳本供大家使用
請問一下，web管理頁面 我今天早上要登入時，突然出現 "授權失敗 請重新登錄" 請問這要怎麼解決?
1. 使用VPS是 Ubuntu 18.04 x64 ; 昨晚有額外安裝 "一键更改 Trojan-Panel 面板端口并设置伪装站点" 這腳本；但是裝完後Web管理都是可以上；今天早上才不行
2. 有嘗試修改admin 密碼；但是一樣出現 "授權失敗"
請問還有甚麼方法可以嘗試解決嗎
![20200704094052](https://user-images.githubusercontent.com/67811980/86502855-7a43b800-bdda-11ea-960c-d509b3f5f134.png)
3. 連線一切使用都是正常，只是不能登入web
![20200704094052](https://user-images.githubusercontent.com/67811980/86502863-97788680-bdda-11ea-834f-6fdfdcb7d9e9.png)

**Comment by Jrohy** [comment]
通常是密码不对，‘’一键更改 Trojan-Panel 面板端口并设置伪装站点‘’， 这个脚本是哪里的呢，发来看下

**Comment by joxjpu** [comment]
連結 : https://www.v2rayssr.com/trojanpanel.html

wget -N --no-check-certificate "https://raw.githubusercontent.com/V2RaySSR/Trojan_panel_web/master/trojan-web-panel.sh" && chmod +x trojan-web-panel.sh && ./trojan-web-panel.sh

**Comment by Jrohy** [comment]
我测试下

**Comment by joxjpu** [comment]
> 通常是密码不对，‘’一键更改 Trojan-Panel 面板端口并设置伪装站点‘’， 这个脚本是哪里的呢，发来看下

謝謝；但是我嘗試修改過密碼( web生成管理 -> 重置web管理員密碼)；還是一樣的狀況

**Comment by Jrohy** [comment]
测试了没问题的, 用 http://域名:81, 或者http://ip:81 来访问， 也可以自己改端口也行

**Comment by joxjpu** [comment]
可能我不知道動到甚麼吧
最終我還是重新安裝trojan就正常了~~ 哈  謝謝你

**Comment by jiangdefucom** [comment]
这个提示是登录超时了吧，经常遇到的

**Comment by letmekillthemall** [comment]
> 可能我不知道动到甚么吧
> 最终我还是重新安装trojan就正常了~~ 哈 谢谢你

同步一下时区，可能你的服务器时区没有改成你本机相同时区，然后超时，用这个命令：
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

**Comment by ZhiboWong** [comment]
> > 可能我不知道动到甚么吧
> > 最终我还是重新安装trojan就正常了~~ 哈 谢谢你
> 
> 同步一下时区，可能你的服务器时区没有改成你本机相同时区，然后超时，用这个命令： cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

不是时区的问题，我也多次碰到此问题。每次都要去后台改密码，改了密码后会好几天，过几天又不行了。
