### ISSUE TITLE
Trojan和Trojan-go共用的一个配置文件吗

### ISSUE THREAD

**Issue by zhaokelei** [Jrohy/trojan#213]
Trojan和Trojan-go共用的一个配置文件吗

**Comment by Jrohy** [comment]
是的

**Comment by hahaleyile** [comment]
您好，想指定使用某一个配置文件，该怎么做？

**Comment by Jrohy** [comment]
@hahaleyile 不支持

**Comment by hahaleyile** [comment]
> @hahaleyile 不支持

冒昧问一下，我尝试后发现该项目并不是完全支持trojan-go，有些配置项会报错，是这样吗？

**Comment by Jrohy** [comment]
会不会配置有写错了，换成trojan-go也就是trojan-go本身来识别配置了

**Comment by Jrohy** [comment]
mysql配置写错了，"username":"root"后面少了,逗号, 检查下json配置

**Comment by hahaleyile** [comment]
> mysql配置写错了，"username":"root"后面少了,逗号, 检查下json格式

谢谢，我再试试
