### ISSUE TITLE
网站访问不了，客户端连上也没网怎么办重装了好几遍还是不成

### ISSUE THREAD

**Issue by Mistuha** [Jrohy/trojan#215]
status=1/FAILURE
Jul 07 11:49:16 ideal-hats-1.localdomain systemd[1]: Unit trojan.service entered failed state.
Jul 07 11:49:16 ideal-hats-1.localdomain systemd[1]: trojan.service failed.
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: trojan.service holdoff time over, scheduling restart.
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: Started trojan.
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: Starting trojan...
Jul 07 11:49:19 ideal-hats-1.localdomain trojan[16085]: Welcome to trojan 1.16.0
Jul 07 11:49:19 ideal-hats-1.localdomain trojan[16085]: [2020-07-07 11:49:19] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Jul 07 11:49:19 ideal-hats-1.localdomain trojan[16085]: [2020-07-07 11:49:19] [FATAL] exiting. . .
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: Unit trojan.service entered failed state.
Jul 07 11:49:19 ideal-hats-1.localdomain systemd[1]: trojan.service failed.
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: trojan.service holdoff time over, scheduling restart.
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: Started trojan.
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: Starting trojan...
Jul 07 11:49:23 ideal-hats-1.localdomain trojan[16095]: Welcome to trojan 1.16.0
Jul 07 11:49:23 ideal-hats-1.localdomain trojan[16095]: [2020-07-07 11:49:23] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Jul 07 11:49:23 ideal-hats-1.localdomain trojan[16095]: [2020-07-07 11:49:23] [FATAL] exiting. . .
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: Unit trojan.service entered failed state.
Jul 07 11:49:23 ideal-hats-1.localdomain systemd[1]: trojan.service failed.
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: trojan.service holdoff time over, scheduling restart.
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: Started trojan.
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: Starting trojan...
Jul 07 11:49:26 ideal-hats-1.localdomain trojan[16105]: Welcome to trojan 1.16.0
Jul 07 11:49:26 ideal-hats-1.localdomain trojan[16105]: [2020-07-07 11:49:26] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Jul 07 11:49:26 ideal-hats-1.localdomain trojan[16105]: [2020-07-07 11:49:26] [FATAL] exiting. . .
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: Unit trojan.service entered failed state.
Jul 07 11:49:26 ideal-hats-1.localdomain systemd[1]: trojan.service failed.

**Comment by WeskerC** [comment]
Maybe u can try another os, that’s how I solved the problem.

**Comment by Mistuha** [comment]
> 也许您可以尝试其他操作系统，这就是我解决问题的方式。

u use what os? Bandwagon centos 7 and debian 9 unsuccessful

**Comment by Mistuha** [comment]
> Maybe u can try another os, that’s how I solved the problem.

u use what os? Bandwagon centos 7 and debian 9 unsuccessful

**Comment by Jrohy** [comment]
证书没申请到

**Comment by Mistuha** [comment]
> 证书没申请到

[root@ideal-hats-1 ~]# curl https://get.acme.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   775    0   775    0     0   3551      0 --:--:-- --:--:-- --:--:--  3555
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  193k  100  193k    0     0   618k      0 --:--:-- --:--:-- --:--:--  620k
[Wed Jul  8 00:13:50 EDT 2020] Installing from online archive.
[Wed Jul  8 00:13:50 EDT 2020] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Wed Jul  8 00:13:51 EDT 2020] Extracting master.tar.gz
[Wed Jul  8 00:13:51 EDT 2020] Installing to /root/.acme.sh
[Wed Jul  8 00:13:51 EDT 2020] Installed to /root/.acme.sh/acme.sh
[Wed Jul  8 00:13:51 EDT 2020] Installing alias to '/root/.bashrc'
[Wed Jul  8 00:13:51 EDT 2020] OK, Close and reopen your terminal to start using acme.sh
[Wed Jul  8 00:13:51 EDT 2020] Installing alias to '/root/.cshrc'
[Wed Jul  8 00:13:51 EDT 2020] Installing alias to '/root/.tcshrc'
[Wed Jul  8 00:13:51 EDT 2020] Installing cron job
0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web
[Wed Jul  8 00:13:51 EDT 2020] Good, bash is found, so change the shebang to use bash as preferred.
[Wed Jul  8 00:13:52 EDT 2020] OK
[Wed Jul  8 00:13:52 EDT 2020] Install success!
手动申请了一下证书还是不成

**Comment by Jrohy** [comment]
不是这么申请的，这只是安装, 运行trojan命令安装管理那里申请证书

**Comment by Mistuha** [comment]
> 不是这么申请的，这只是安装, 运行trojan命令安装管理那里申请证书

[Wed Jul  8 00:18:28 EDT 2020] Lets find script dir.
[Wed Jul  8 00:18:28 EDT 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:18:28 EDT 2020] _script='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:18:28 EDT 2020] _script_home='/root/.acme.sh'
[Wed Jul  8 00:18:28 EDT 2020] Using default home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.7
[Wed Jul  8 00:18:28 EDT 2020] Using config home:/root/.acme.sh
[Wed Jul  8 00:18:28 EDT 2020] Running cmd: issue
[Wed Jul  8 00:18:28 EDT 2020] _main_domain='mistuha.com'
[Wed Jul  8 00:18:28 EDT 2020] _alt_domains='no'
[Wed Jul  8 00:18:28 EDT 2020] Using config home:/root/.acme.sh
[Wed Jul  8 00:18:28 EDT 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:18:28 EDT 2020] DOMAIN_PATH='/root/.acme.sh/mistuha.com_ecc'
[Wed Jul  8 00:18:28 EDT 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:18:28 EDT 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:18:28 EDT 2020] GET
[Wed Jul  8 00:18:28 EDT 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:18:28 EDT 2020] timeout=
[Wed Jul  8 00:18:28 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul  8 00:18:28 EDT 2020] ret='0'
[Wed Jul  8 00:18:28 EDT 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Wed Jul  8 00:18:28 EDT 2020] ACME_NEW_AUTHZ
[Wed Jul  8 00:18:28 EDT 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:18:28 EDT 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Wed Jul  8 00:18:28 EDT 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed Jul  8 00:18:28 EDT 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Wed Jul  8 00:18:28 EDT 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Jul  8 00:18:28 EDT 2020] ACME_VERSION='2'
[Wed Jul  8 00:18:28 EDT 2020] Le_NextRenewTime
[Wed Jul  8 00:18:28 EDT 2020] _on_before_issue
[Wed Jul  8 00:18:28 EDT 2020] _chk_main_domain='mistuha.com'
[Wed Jul  8 00:18:28 EDT 2020] _chk_alt_domains
[Wed Jul  8 00:18:28 EDT 2020] Le_LocalAddress
[Wed Jul  8 00:18:28 EDT 2020] d='mistuha.com'
[Wed Jul  8 00:18:28 EDT 2020] Check for domain='mistuha.com'
[Wed Jul  8 00:18:28 EDT 2020] _currentRoot='no'
[Wed Jul  8 00:18:28 EDT 2020] Standalone mode.
[Wed Jul  8 00:18:28 EDT 2020] _checkport='80'
[Wed Jul  8 00:18:28 EDT 2020] _checkaddr
[Wed Jul  8 00:18:28 EDT 2020] Using: ss
[Wed Jul  8 00:18:28 EDT 2020] LISTEN     0      128         :::80                      :::*                   users:(("trojan",pid=14622,fd=3))
[Wed Jul  8 00:18:28 EDT 2020] tcp port 80 is already used by 80
[Wed Jul  8 00:18:28 EDT 2020] Please stop it first
[Wed Jul  8 00:18:28 EDT 2020] _on_before_issue.
 一直这样  我用在阿里云那边申请的SSL证书可以吗 那种key  pem的格式

**Comment by Mistuha** [comment]
> 不是这么申请的，这只是安装, 运行trojan命令安装管理那里申请证书

[Wed Jul  8 00:28:06 EDT 2020] Lets find script dir.
[Wed Jul  8 00:28:06 EDT 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:28:06 EDT 2020] _script='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:28:06 EDT 2020] _script_home='/root/.acme.sh'
[Wed Jul  8 00:28:06 EDT 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.7
[Wed Jul  8 00:28:06 EDT 2020] Running cmd: issue
[Wed Jul  8 00:28:06 EDT 2020] _main_domain='mistuha.com'
[Wed Jul  8 00:28:06 EDT 2020] _alt_domains='no'
[Wed Jul  8 00:28:06 EDT 2020] Using config home:/root/.acme.sh
[Wed Jul  8 00:28:06 EDT 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:28:06 EDT 2020] DOMAIN_PATH='/root/.acme.sh/mistuha.com_ecc'
[Wed Jul  8 00:28:06 EDT 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:28:06 EDT 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:28:06 EDT 2020] GET
[Wed Jul  8 00:28:06 EDT 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:28:06 EDT 2020] timeout=
[Wed Jul  8 00:28:06 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul  8 00:28:06 EDT 2020] ret='0'
[Wed Jul  8 00:28:06 EDT 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Wed Jul  8 00:28:06 EDT 2020] ACME_NEW_AUTHZ
[Wed Jul  8 00:28:06 EDT 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:28:06 EDT 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Wed Jul  8 00:28:06 EDT 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed Jul  8 00:28:06 EDT 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Wed Jul  8 00:28:06 EDT 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Jul  8 00:28:06 EDT 2020] ACME_VERSION='2'
[Wed Jul  8 00:28:06 EDT 2020] Le_NextRenewTime
[Wed Jul  8 00:28:07 EDT 2020] _on_before_issue
[Wed Jul  8 00:28:07 EDT 2020] _chk_main_domain='mistuha.com'
[Wed Jul  8 00:28:07 EDT 2020] _chk_alt_domains
[Wed Jul  8 00:28:07 EDT 2020] Le_LocalAddress
[Wed Jul  8 00:28:07 EDT 2020] d='mistuha.com'
[Wed Jul  8 00:28:07 EDT 2020] Check for domain='mistuha.com'
[Wed Jul  8 00:28:07 EDT 2020] _currentRoot='no'
[Wed Jul  8 00:28:07 EDT 2020] Standalone mode.
[Wed Jul  8 00:28:07 EDT 2020] _checkport='80'
[Wed Jul  8 00:28:07 EDT 2020] _checkaddr
[Wed Jul  8 00:28:07 EDT 2020] Using: ss
[Wed Jul  8 00:28:07 EDT 2020] d
[Wed Jul  8 00:28:07 EDT 2020] _saved_account_key_hash is not changed, skip register account.
[Wed Jul  8 00:28:07 EDT 2020] Read key length:ec-256
[Wed Jul  8 00:28:07 EDT 2020] _createcsr
[Wed Jul  8 00:28:07 EDT 2020] Single domain='mistuha.com'
[Wed Jul  8 00:28:07 EDT 2020] Getting domain auth token for each domain
[Wed Jul  8 00:28:07 EDT 2020] d
[Wed Jul  8 00:28:07 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:28:07 EDT 2020] payload='{"identifiers": [{"type":"dns","value":"mistuha.com"}]}'
[Wed Jul  8 00:28:07 EDT 2020] RSA key
[Wed Jul  8 00:28:07 EDT 2020] HEAD
[Wed Jul  8 00:28:07 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Jul  8 00:28:07 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Wed Jul  8 00:28:07 EDT 2020] _ret='0'
[Wed Jul  8 00:28:07 EDT 2020] POST
[Wed Jul  8 00:28:07 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:28:07 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul  8 00:28:07 EDT 2020] _ret='0'
[Wed Jul  8 00:28:07 EDT 2020] code='429'
[Wed Jul  8 00:28:07 EDT 2020] Le_LinkOrder
[Wed Jul  8 00:28:07 EDT 2020] Le_OrderFinalize
[Wed Jul  8 00:28:07 EDT 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: mistuha.com: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Jul  8 00:28:07 EDT 2020] pid
[Wed Jul  8 00:28:07 EDT 2020] No need to restore nginx, skip.
[Wed Jul  8 00:28:07 EDT 2020] _clearupdns
[Wed Jul  8 00:28:07 EDT 2020] dns_entries
[Wed Jul  8 00:28:07 EDT 2020] skip dns.
[Wed Jul  8 00:28:07 EDT 2020] _on_issue_err
[Wed Jul  8 00:28:07 EDT 2020] Please add '--debug' or '--log' to check more details.
[Wed Jul  8 00:28:07 EDT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Jul  8 00:28:07 EDT 2020] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1e-fips 11 Feb 2013
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Aug  4 2017 04:57:10
   running on Linux version #1 SMP Sat Mar 18 12:50:10 EDT 2017, release 4.10.4-1.el7.elrepo.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
重启trojan成功!

**Comment by Jrohy** [comment]
停了web服务systemctl stop trojan-web
再申请证书

**Comment by Mistuha** [comment]
> 停了web服务systemctl stop trojan-web
> 再申请证书

[Wed Jul  8 00:43:02 EDT 2020] Lets find script dir.
[Wed Jul  8 00:43:02 EDT 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:43:02 EDT 2020] _script='/root/.acme.sh/acme.sh'
[Wed Jul  8 00:43:02 EDT 2020] _script_home='/root/.acme.sh'
[Wed Jul  8 00:43:02 EDT 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.7
[Wed Jul  8 00:43:02 EDT 2020] Running cmd: issue
[Wed Jul  8 00:43:02 EDT 2020] _main_domain='mistuha.com'
[Wed Jul  8 00:43:02 EDT 2020] _alt_domains='no'
[Wed Jul  8 00:43:02 EDT 2020] Using config home:/root/.acme.sh
[Wed Jul  8 00:43:02 EDT 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:43:02 EDT 2020] DOMAIN_PATH='/root/.acme.sh/mistuha.com_ecc'
[Wed Jul  8 00:43:02 EDT 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:43:02 EDT 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Wed Jul  8 00:43:02 EDT 2020] GET
[Wed Jul  8 00:43:02 EDT 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Wed Jul  8 00:43:02 EDT 2020] timeout=
[Wed Jul  8 00:43:02 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul  8 00:43:02 EDT 2020] ret='0'
[Wed Jul  8 00:43:02 EDT 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Wed Jul  8 00:43:02 EDT 2020] ACME_NEW_AUTHZ
[Wed Jul  8 00:43:02 EDT 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:43:02 EDT 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Wed Jul  8 00:43:02 EDT 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Wed Jul  8 00:43:02 EDT 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Wed Jul  8 00:43:02 EDT 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Jul  8 00:43:02 EDT 2020] ACME_VERSION='2'
[Wed Jul  8 00:43:02 EDT 2020] Le_NextRenewTime
[Wed Jul  8 00:43:02 EDT 2020] _on_before_issue
[Wed Jul  8 00:43:02 EDT 2020] _chk_main_domain='mistuha.com'
[Wed Jul  8 00:43:02 EDT 2020] _chk_alt_domains
[Wed Jul  8 00:43:02 EDT 2020] Le_LocalAddress
[Wed Jul  8 00:43:02 EDT 2020] d='mistuha.com'
[Wed Jul  8 00:43:02 EDT 2020] Check for domain='mistuha.com'
[Wed Jul  8 00:43:02 EDT 2020] _currentRoot='no'
[Wed Jul  8 00:43:02 EDT 2020] Standalone mode.
[Wed Jul  8 00:43:02 EDT 2020] _checkport='80'
[Wed Jul  8 00:43:02 EDT 2020] _checkaddr
[Wed Jul  8 00:43:02 EDT 2020] Using: ss
[Wed Jul  8 00:43:02 EDT 2020] d
[Wed Jul  8 00:43:02 EDT 2020] _saved_account_key_hash is not changed, skip register account.
[Wed Jul  8 00:43:02 EDT 2020] Read key length:ec-256
[Wed Jul  8 00:43:02 EDT 2020] _createcsr
[Wed Jul  8 00:43:02 EDT 2020] Single domain='mistuha.com'
[Wed Jul  8 00:43:03 EDT 2020] Getting domain auth token for each domain
[Wed Jul  8 00:43:03 EDT 2020] d
[Wed Jul  8 00:43:03 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:43:03 EDT 2020] payload='{"identifiers": [{"type":"dns","value":"mistuha.com"}]}'
[Wed Jul  8 00:43:03 EDT 2020] RSA key
[Wed Jul  8 00:43:03 EDT 2020] HEAD
[Wed Jul  8 00:43:03 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Wed Jul  8 00:43:03 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Wed Jul  8 00:43:03 EDT 2020] _ret='0'
[Wed Jul  8 00:43:03 EDT 2020] POST
[Wed Jul  8 00:43:03 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Wed Jul  8 00:43:03 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Wed Jul  8 00:43:03 EDT 2020] _ret='0'
[Wed Jul  8 00:43:03 EDT 2020] code='429'
[Wed Jul  8 00:43:03 EDT 2020] Le_LinkOrder
[Wed Jul  8 00:43:03 EDT 2020] Le_OrderFinalize
[Wed Jul  8 00:43:03 EDT 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: mistuha.com: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429
}
[Wed Jul  8 00:43:03 EDT 2020] pid
[Wed Jul  8 00:43:03 EDT 2020] No need to restore nginx, skip.
[Wed Jul  8 00:43:03 EDT 2020] _clearupdns
[Wed Jul  8 00:43:03 EDT 2020] dns_entries
[Wed Jul  8 00:43:03 EDT 2020] skip dns.
[Wed Jul  8 00:43:03 EDT 2020] _on_issue_err
[Wed Jul  8 00:43:03 EDT 2020] Please add '--debug' or '--log' to check more details.
[Wed Jul  8 00:43:03 EDT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Wed Jul  8 00:43:03 EDT 2020] Diagnosis versions:
openssl:openssl
OpenSSL 1.0.1e-fips 11 Feb 2013
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.3.2 on Aug  4 2017 04:57:10
   running on Linux version #1 SMP Sat Mar 18 12:50:10 EDT 2017, release 4.10.4-1.el7.elrepo.x86_64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #define WITH_READLINE 1
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/
重启trojan成功!

停了申请就这样 再启动还是不行

**Comment by Jrohy** [comment]
申请次数太多了，估计得换个证书，或者第二天才申请

**Comment by Mistuha** [comment]
> 申请次数太多了，估计得换个证书，或者第二天才申请

多谢大佬，换了个域名解决了，可以用了，太感谢了
