### ISSUE TITLE
请问能不能限制一个用户的登录客户端数量

### ISSUE THREAD

**Issue by kyoa** [Jrohy/trojan#216]
如题，需要自己开发也可以，麻烦给指点一下方向

**Comment by Jrohy** [comment]
@kyoa trojan-go 貌似支持限制客户端数量和限速, 可以在线切换成trojan-go后改下配置文件试试
https://p4gefau1t.github.io/trojan-go/advance/api/

**Comment by kyoa** [comment]
> @kyoa trojan-go 貌似支持限制客户端数量和限速, 可以在线切换成trojan-go后改下配置文件试试
> https://p4gefau1t.github.io/trojan-go/advance/api/

好的，谢谢，我看一下

**Comment by kyoa** [comment]
> @kyoa trojan-go 貌似支持限制客户端数量和限速, 可以在线切换成trojan-go后改下配置文件试试
> https://p4gefau1t.github.io/trojan-go/advance/api/

这个有个问题，没有进行持久化，一重启设定就失效了。
但是从外部持久化的话，初始化又是问题，请问有没有除了修改trojan-go代码之外的思路？

**Comment by Jrohy** [comment]
有考虑过，持久化到数据库，每次重启完trojan-go后读数据库来做初始化

**Comment by kyoa** [comment]
> 有考虑过，持久化到数据库，每次重启完trojan-go后读数据库来做初始化

你指的是通过你这个服务端持久化，重启trojan-go之后，再用trojan-go api命令进行初始化么？

**Comment by Jrohy** [comment]
是的

**Comment by kyoa** [comment]
> 是的

我就是想避免这个，不过想想看倒也问题不大，否则还得去改trojan-go甚至trojan

**Comment by Jrohy** [comment]
当然如果是trojan-go官方支持就最好了，毕竟人为重启好控制，但开机自启后去做初始化就不太好做

**Comment by kyoa** [comment]
嗯，明白了

**Comment by kyoa** [comment]
> 当然如果是trojan-go官方支持就最好了，毕竟人为重启好控制，但开机自启后去做初始化就麻烦点

咨询了trojan-go的作者，他那边就是故意设计成这样的，持久化交给对接的API客户端去做，不过有个gRPC接口可以调用，不需要通过命令行
