### ISSUE TITLE
最新版本断流

### ISSUE THREAD

**Issue by hcnyf** [Jrohy/trojan#217]
rt，最新版本有断流问题，有时候YouTube看着个视频加载到一半就不加载了，然后一直转圈，需要刷新网页才行。
服务器是用的debian10，用的trojan-go。

**Comment by Jrohy** [comment]
得向trojan-go仓库反馈了这个问题

**Comment by hcnyf** [comment]
> 得向trojan-go仓库反馈了这个问题

但是好像我手动安装在trojan-go仓库下的就不会断流（用的时间不长，这个待测试），不过网速比你这个脚本安装的慢，不知道是不是配置问题，有空我试试用你这个脚本生成的配置适当改一下去运行一下我手动安装的trojan-go

**Comment by hcnyf** [comment]
null
