### ISSUE TITLE
用户相关

### ISSUE THREAD

**Issue by luoqiz** [Jrohy/trojan#22]
web页面添加用户失败，用户展示也失败。命令行可以添加用户、也可以显示用户列表。

![image](https://user-images.githubusercontent.com/22161059/77247806-7e0a5f00-6c6f-11ea-98fe-24b631660086.png)

**Comment by Jrohy** [comment]
网络超时吗报错

**Comment by Jrohy** [comment]
看network那里接口能否拿到后台结果

**Comment by luoqiz** [comment]
我用trojan管理脚本添加了域名后，服务器的web页面已经访问不到了
![image](https://user-images.githubusercontent.com/22161059/77247500-cf651f00-6c6c-11ea-8673-b21150e18633.png)

**Comment by Jrohy** [comment]
看下web服务状态:  systemctl status trojan-web

**Comment by Jrohy** [comment]
添加域名是指证书申请吗

**Comment by luoqiz** [comment]
对

**Comment by Jrohy** [comment]
systemctl status trojan-web 看下状态是否在正常运行

**Comment by luoqiz** [comment]
我比你快了一步，重启服务器了。
登录正常，trojan信息显示不了，用户信息也没显示
![image](https://user-images.githubusercontent.com/22161059/77247742-d3923c00-6c6e-11ea-91e4-25b29fa7c0a3.png)

![image](https://user-images.githubusercontent.com/22161059/77247748-e73da280-6c6e-11ea-98f0-61f4ca191cd1.png)

貌似前端 userList 属性出错
![image](https://user-images.githubusercontent.com/22161059/77247756-f9b7dc00-6c6e-11ea-96d9-e4e7517e1bb7.png)

**Comment by Jrohy** [comment]
mysql是不是没启动到，看mysql日志 docker logs -f trojan-mysql

**Comment by luoqiz** [comment]
启动了

![image](https://user-images.githubusercontent.com/22161059/77247828-b7db6580-6c6f-11ea-9291-67bae66162ca.png)

**Comment by Jrohy** [comment]
运行docker logs -f 命令会自动退出吗，如果会自动退出mysql就是启动有问题

**Comment by luoqiz** [comment]
自动退出的，我发现一个问题，貌似内存不够了

![image](https://user-images.githubusercontent.com/22161059/77247894-451eba00-6c70-11ea-8f3d-54726d9546b1.png)

**Comment by Jrohy** [comment]
那应该是了，vps如果没有512m + 内存不好启动的， mysql启动我看了下都要150m+内存

**Comment by Jrohy** [comment]
可以将mysql搬到其他机器，或者换大内存的vps, 如果才256m内存的就不建议装mysql了，建议直接用trojan配置文件。

**Comment by luoqiz** [comment]
我的512的内存，直接用trojan配置文件是不是用不了web页面了？

**Comment by Jrohy** [comment]
512的应该可以的，用trojan配置文件，web界面就没什么意义了，web界面读的是mysql的数据

**Comment by Jrohy** [comment]
上面的不是内存不足，是连不上数据库， mysql启动不了，会自动退出的话

**Comment by luoqiz** [comment]
数据库脚本在哪？

**Comment by Jrohy** [comment]
数据文件在/home/mysql这个目录，如果启动不了mysql建议清了mysql后重新安装mysql
rm -rf /home/mysql
docker rm -f trojan-mysql
在安装管理那里可以安装mysql

**Comment by luoqiz** [comment]
显示都已正常，但是无法连接
![image](https://user-images.githubusercontent.com/22161059/77249524-8d43d980-6c7c-11ea-9055-384534bbd550.png)

**Comment by Jrohy** [comment]
这个是启动失败的

**Comment by luoqiz** [comment]
嗯，是的。我以为是你写的控制trojan有问题，重装了以后解决了。关于你写的脚本，我发现docker安装有问题，执行不成功。后来我自己安装了docker-mysql测试没问题，不知是哪的原因。我用的谷歌云centos7. 希望后续能添加用户使用期限和多节点trojan管理。

**Comment by luoqiz** [comment]
到目前使用没问题了，非常感谢大佬。

**Comment by luoqiz** [comment]
默认管理端口是80，我想在这个端口监听自己的多域名网站，如何修改端口号使其运行在nginx之后？

**Comment by Jrohy** [comment]
看项目README web服务那里有介绍怎么改端口的，修改trojan-web.service。

**Comment by Jrohy** [comment]
@luoqiz  新建了wiki，怎么修改端口看这里[修改web端口](https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3)

**Comment by luoqiz** [comment]
收到。
