### ISSUE TITLE
请问如何使用trojan-go

### ISSUE THREAD

**Issue by jinyuqilin1** [Jrohy/trojan#221]
大神您好，请问怎样使用trojan-go的命令呢？服务器中找不到trojan-go文件的位置

**Comment by Jrohy** [comment]
在线web页面切换到trojan-go后就行, trojan和trojan-go使用相同的配置文件的

**Comment by Jrohy** [comment]
路径
/usr/local/etc/trojan/config.json

**Comment by jinyuqilin1** [comment]
谢谢回答！！那如果我想限制单用户的连接设备数，我该怎样做呢？

**Comment by jinyuqilin1** [comment]
我看到之前有问您的，但是不知道在哪个文件夹执行./trojan-go，麻烦指点一下！谢谢

**Comment by Jrohy** [comment]
都是这个路径的可执行文件/usr/bin/trojan/trojan, 你可以运行systemctl status trojan就能看到

**Comment by jinyuqilin1** [comment]
感谢回答！可是这个trojan文件也限制不了用户数量啊

**Comment by Jrohy** [comment]
https://p4gefau1t.github.io/trojan-go/advance/api/
有没有填错对应的password呢

**Comment by jinyuqilin1** [comment]
哦哦，我看到啦！但是当我运行./trojan -api-addr 127.0.0.1:10000 -api list 的时候显示
![image](https://user-images.githubusercontent.com/20551318/87614580-fe832d00-c742-11ea-9ddf-d5ccb1756db2.png)

**Comment by jinyuqilin1** [comment]
换到trojan的端口又显示connection closed.
![image](https://user-images.githubusercontent.com/20551318/87614716-69346880-c743-11ea-9dba-e6faa7be3f9d.png)

**Comment by jinyuqilin1** [comment]
大神您好，我现在连接上了，但是好像trojan不能更改用户连接数。。
![image](https://user-images.githubusercontent.com/20551318/87615528-84a07300-c745-11ea-881c-397c3cb2a179.png)

**Comment by jinyuqilin1** [comment]
成功了，谢谢您的指导！
![image](https://user-images.githubusercontent.com/20551318/87616103-e7ded500-c746-11ea-8995-3696c17ae331.png)

**Comment by 10N99** [comment]
> 换到trojan的端口又显示连接已关闭。
> ![图片](https://user-images.githubusercontent.com/20551318/87614716-69346880-c743-11ea-9dba-e6faa7be3f9d.png)

和你同样的问题  怎么解决的阿

**Comment by jinyuqilin1** [comment]
config文件开启的端口和连接的端口要一致

**Comment by 10N99** [comment]
> config文件开启的端口和连接的端口要一致

一致的啊 还是不行。

**Comment by jinyuqilin1** [comment]
我端口校正后就没问题了

**Comment by gimgoo** [comment]
这个路径/usr/bin/trojan/trojan的可执行文件还是trojan不是trojan-go，trojan-go有自己的可执行文件。这样跟没换一样哇？

**Comment by Jrohy** [comment]
@gimgoo 可执行文件名字和配置文件路径都是一样的
