### ISSUE TITLE
能否让web管理界面80端口自动跳转443?

### ISSUE THREAD

**Issue by onlyJinx** [Jrohy/trojan#222]
如题..

![un](https://user-images.githubusercontent.com/21324835/87845727-7052a680-c8fc-11ea-9a5d-54f99ab8ce16.png)

**Comment by Os-glthub** [comment]
<img width="365" alt="1" src="https://user-images.githubusercontent.com/52124855/87846696-5ddc6b00-c904-11ea-981f-30481ba8fd6b.png">
<img width="788" alt="2" src="https://user-images.githubusercontent.com/52124855/87846699-616ff200-c904-11ea-8bfe-3ce69b94c831.png">
<img width="328" alt="3" src="https://user-images.githubusercontent.com/52124855/87846700-62a11f00-c904-11ea-8710-708d7b14b501.png">
<img width="517" alt="4" src="https://user-images.githubusercontent.com/52124855/87846735-9da35280-c904-11ea-947c-b5c0edfe6981.png">
大神你好，请教下，这个问题怎么修复，搜索了一下，好像是Nginx部署问题

**Comment by onlyJinx** [comment]
大火酱的原版trojan不支持CDN, trojan-go才支持, 不知道你用的那个版本

**Comment by Jrohy** [comment]
@onlyJinx 不支持，因为443端口被trojan使用了，做不了自动跳转

**Comment by onlyJinx** [comment]
@Jrohy 好的, 谢啦
@Os-glthub 你问问题啥关键信息都没给, 不好回答, 你新开一个issue吧
