### ISSUE TITLE
J大 请教下 我在web界面切换了trojan-go，如何套嵌CDN呢？

### ISSUE THREAD

**Issue by xunqiuhuiyi** [Jrohy/trojan#225]
J大 请教下 我在web界面切换了trojan-go，如何套嵌CDN呢？
我是需要重新在vps上安装一个trojan-go，还是直接切换以后修改配置呢？

**Comment by Jrohy** [comment]
切换了trojan-go后自己修改下配置，参考官方教程

**Comment by xunqiuhuiyi** [comment]
好的 谢谢J大

**Comment by xunqiuhuiyi** [comment]
> 切换了trojan-go后自己修改下配置，参考官方教程

J大 想请问下2.8更新的web设置里显示输入的网址，这个是什么意思啊？我输入了一个新的域名 没反应

**Comment by Jrohy** [comment]
这个一般不用管的，一般是生成的分享链接域名显示不正常的才需要设置

**Comment by xunqiuhuiyi** [comment]
> 这个一般不用管的，一般是生成的分享链接域名显示不正常的才需要设置

懂了，谢谢J大！赞！👍！

**Comment by yesmiley** [comment]
话说trojan-go 套cdn 是不是只能用官方客户端，翻了好几个都没找到可以改配置的地方（包括Windows-QV2ray, Android-Clash, iOS-ShadowRocket） @Jrohy

**Comment by Jrohy** [comment]
@yesmiley 套cdn没试过了，得自己测下

**Comment by yesmiley** [comment]
> @yesmiley 套cdn没试过了，得自己测下

好嘞，我自己再研究下，thanks

**Comment by ckbkdj** [comment]
> > @yesmiley 套cdn没试过了，得自己测下
> 
> 好嘞，我自己再研究下，thanks

你成功了么

**Comment by ckbkdj** [comment]
> > 这个一般不用管的，一般是生成的分享链接域名显示不正常的才需要设置
> 
> 懂了，谢谢J大！赞！👍！

你成功了么CF
