### ISSUE TITLE
【安全建议】建议尽可能隐藏面板

### ISSUE THREAD

**Issue by lbroot** [Jrohy/trojan#227]
我注意到当前一键脚本安装成功后存在以下几个问题：
1，域名打开首页即是“Trojan管理面板”，**太明显了**
2，面板可以以http协议访问，而**没有强制https**
我不太确定墙目前有多少种工作方式，但知道许多机场的官网在更换域名后会很快的被墙不排除墙根据sni头主动扫描首页的可能。
我希望进行如下改进：
1，**安装前要求用户输入一个path，面板需要通过 example.com/path 的形式访问**
2，对首页的直接访问返回令人迷惑的结果，比如403
3，**对非来自trojan转发的访问请求返回302跳转到https协议上**

安全第一呦~~

**Comment by lbroot** [comment]
好家伙，我没注意到wiki，原来已经给了相关建议。

不过这个path我觉得还是作为一个默认功能在安装时即提供更好。

**Comment by Jrohy** [comment]
1. 可以改标题的，admin用户登入面板来改
2. 做不了强制跳转https, 因为443端口给trojan使用了

**Comment by lbroot** [comment]
作者大大好，按照您的wiki我已经完全配置好了path来保护面板。
你说的nginx只监听了80端口故无法做跳转，我找到一种变通的方法进行实现，即对非本地转发的流量统一返回302。

site.conf发在这里以供后人参考：
`{
    listen 80;
    server_name example.com;
    index index.html;
    root /usr/share/nginx/www;
    server_tokens off;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    if ( $remote_addr != 127.0.0.1 ){
    rewrite ^/(.*)$ https://example.com/$1 redirect;
}
        location /admin {
            proxy_pass   http://localhost:81/;
        }
        location ~* ^/(js|css|vendor|common|auth|trojan)/ {
            proxy_pass  http://localhost:81;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
}
`

在强制https和path的保护下，面板会更加的安全。
