### ISSUE TITLE
日志里面全是这种东西，这些IP全都不认识，全国各地都有

### ISSUE THREAD

**Issue by xiaoxue508** [Jrohy/trojan#228]
Jul 25 06:01:01 debian trojan[30523]: [2020-07-25 06:01:01] [WARN] 112.224.65.75:58649 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:02 debian trojan[30523]: [2020-07-25 06:01:02] [WARN] 113.128.105.2:38214 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:04 debian trojan[30523]: [2020-07-25 06:01:04] [WARN] 27.224.136.251:38692 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:04 debian trojan[30523]: [2020-07-25 06:01:04] [WARN] 123.160.232.151:38812 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:20 debian trojan[30523]: [2020-07-25 06:01:20] [WARN] 124.90.53.232:38810 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:22 debian trojan[30523]: [2020-07-25 06:01:22] [WARN] 180.95.238.239:41682 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:24 debian trojan[30523]: [2020-07-25 06:01:24] [WARN] 49.118.203.137:22169 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:24 debian trojan[30523]: [2020-07-25 06:01:24] [WARN] 111.162.137.85:41930 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:01:24 debian trojan[30523]: [2020-07-25 06:01:24] [WARN] 117.15.92.244:41926 not trojan request, connecting to 127.0.0.1:80
Jul 25 06:14:31 debian trojan[30523]: [2020-07-25 06:14:31] [ERROR] 45.33.80.76:47888 SSL handshake failed: stream truncated
Jul 25 06:23:48 debian trojan[30523]: [2020-07-25 06:23:48] [ERROR] Lost connection to MySQL server during query

**Comment by Jrohy** [comment]
这些是trojan打印的

**Comment by xiaoxue508** [comment]
> 这些是trojan打印的

额，大佬，这是些什么东西啊，小鸡被黑?

**Comment by zjt2005** [comment]
是爬虫吧...你既然做了伪装网站肯定是要有访客的啊
还有就是看一看有没有设置搜索引擎全站屏蔽，搞不好你被百度收录了 :)

**Comment by xiaoxue508** [comment]
> 是爬虫吧...你既然做了伪装网站肯定是要有访客的啊
> 还有就是看一看有没有设置搜索引擎全站屏蔽，搞不好你被百度收录了 :)

老板，怎么设置搜索引擎屏蔽

**Comment by ancct** [comment]
> 是爬虫吧...你既然做了伪装网站肯定是要有访客的啊
> 还有就是看一看有没有设置搜索引擎全站屏蔽，搞不好你被百度收录了:)

已被收录的路过，而且还排名第一呢……
We're sorry but vue-admin doesn't work properly without JavaScript enabled. Please enable it to continue.  MY TITLE. login.

**Comment by zjt2005** [comment]
> > 是爬虫吧...你既然做了伪装网站肯定是要有访客的啊
> > 还有就是看一看有没有设置搜索引擎全站屏蔽，搞不好你被百度收录了 :)
> 
> 老板，怎么设置搜索引擎屏蔽

这个Web页面是用Go语言写得，不方便去添加noindex标记...
如果怀疑是因为搜索引擎的流量的话你可以搜索 `site:[你的域名]`来看看有没有被收录，有的话就去取消他

* 百度站长平台： [https://ziyuan.baidu.com/](https://ziyuan.baidu.com/siteclose/)
* 谷歌搜索管理： [https://search.google.com/](https://search.google.com/search-console/welcome)

其实我觉得问题不大，爬虫都被伪装网站挡下来了，不会对你的速度或者安全性有什么大的影响。
