### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by QuteSaltyFish** [Jrohy/trojan#229]
你好，我的vps被限定了端口地址。。。请问有没有像v2ray-ui那样能够配置端口号的功能呢

**Comment by Jrohy** [comment]
都是建议用443端口的，如果真要改自己改下配置文件

**Comment by yesmiley** [comment]
web管理的端口好像只能是80？没找到能改的地方

**Comment by Jrohy** [comment]
@yesmiley 参考wiki端口修改

**Comment by yesmiley** [comment]
> @yesmiley 参考wiki端口修改

Okay, Thanks.
