### ISSUE TITLE
web端的登录密码无法重置

### ISSUE THREAD

**Issue by cdwangtao** [Jrohy/trojan#23]
web端的登录密码第二天无法登录，也无法重置

**Comment by Jrohy** [comment]
是请求超时了吗

**Comment by cdwangtao** [comment]
提示用户或密码，昨天我装的两台vps，密码都设置一样的，今天两个都没法登录！密码默认会自动加密传给后台的
![1584941601(1)](https://user-images.githubusercontent.com/28557120/77285140-4fda5d00-6d0b-11ea-9c5b-f52a4b290d92.jpg)

**Comment by Jrohy** [comment]
应该是admin密码错了，所以授权失败

**Comment by Jrohy** [comment]
今天我出个新版可以在命令行里重置web端管理员密码

**Comment by cdwangtao** [comment]
好的 谢谢！

**Comment by cdwangtao** [comment]
> 今晚我出个新版可以在命令行里重置web端管理员密码

我想起了 我添加用户的时候 用户名也用的admin，会不会因为与登录的用户名一样了，导致登录密码受影响了

**Comment by Jrohy** [comment]
这里确实有Bug,今晚一并修复了

**Comment by Jrohy** [comment]
@cdwangtao 新版已修复，更新下`source <(curl -sL https://git.io/trojan-install)`

**Comment by Jrohy** [comment]
更新完后先运行trojan命令去web管理重置掉admin密码
然后去用户管理或者web页面删掉当初创建的admin用户

**Comment by cdwangtao** [comment]
> 更新完后先运行trojan命令去web管理重置掉admin密码
> 然后去用户管理或者web页面删掉当初创建的admin用户

已更新，感谢，可以正常使用了！

**Comment by yao32** [comment]
在gcp搭了trojan，但在手机上的小火箭app没多久就一直超时连接不上，电脑端是用一会后面也会连不上，只能搭其他的！我搭了好几个都这样的情况！有时候搭完ssh怎么都进不去，只能删掉重来！

**Comment by jmysr118** [comment]
你好
同样的问题，也已经更新了最新版 2.8.5 还是出现如下提示
请选择: 1
请输入admin用户密码: aa123123
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x83c98e]

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x17, 0x0)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:1117 +0x3e
trojan/core.SetValue(0xbd7103, 0xa, 0xc0002b6040, 0x38, 0xd6d040, 0xc000288140)
	/home/go/trojan/core/leveldb.go:28 +0xc5
trojan/trojan.ResetAdminPass()
	/home/go/trojan/trojan/web.go:29 +0x1c5
trojan/trojan.WebMenu()
	/home/go/trojan/trojan/web.go:16 +0xfb
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:63 +0x48c
trojan/cmd.glob..func6(0x1235fc0, 0x126c750, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x1235fc0, 0xc0000201e0, 0x0, 0x0, 0x1235fc0, 0xc0000201e0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1235fc0, 0x443a4a, 0x11f49c0, 0xc000000180)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20

**Comment by Jrohy** [comment]
@jmysr118 将这个目录改下名字/var/lib/trojan-manager, 然后再去web页面会要求输入admin密码的

**Comment by jmysr118** [comment]
> @ jmysr118将这个目录改下名字/ var / lib / trojan-manager，然后再去web页面会会要求输入admin密码的

谢谢您的解答，已经成功重置密码了。

**Comment by 19974028957** [comment]
这边重置密码之后添加不了用户,是需要重启嘛

**Comment by k1349691865** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
