### ISSUE TITLE
我这个Web管理平台正常么？

### ISSUE THREAD

**Issue by Gslw** [Jrohy/trojan#230]
1.没有服务器状态，我看说是能切换Trojan-GO也没看到

![1](https://user-images.githubusercontent.com/18265684/88472259-74597680-cf43-11ea-9fd7-b004a3746c75.JPG)

2.没有添加删除用户按钮，即使服务器上添加也刷新不出来。

![2](https://user-images.githubusercontent.com/18265684/88472338-36108700-cf44-11ea-94e6-4bce2a0e42bd.jpg)

**Comment by Jrohy** [comment]
用admin用户登陆就有了

**Comment by Gslw** [comment]
> 用admin用户登陆就有了

谢谢，搞定！
