### ISSUE TITLE
功能建议：批量停用/启用某些用户

### ISSUE THREAD

**Issue by RobinsonChina** [Jrohy/trojan#231]
对于一些用户，可能需要批量暂时禁用他们，目前的操作方法是将他们允许的流量调低，但是对于大量的用户来说操作起来十分麻烦，如果可以批量打勾选中，进行停用/启用就好了！

**Comment by lbroot** [comment]
**同样希望这个功能**
我将它描述为：“**多选用户并批量设定（某一个值的）流量使用限制**”

**Comment by Jrohy** [comment]
@lbroot 这个可以有，批量改流量限制

**Comment by Jrohy** [comment]
@lbroot @RobinsonChina  已增加批量限制流量功能, 更新下

**Comment by lbroot** [comment]
作者你这更新的好勤快啊哈哈哈，可以说是非常感谢了

**Comment by RobinsonChina** [comment]
> @lbroot @RobinsonChina 已增加批量限制流量功能, 更新下

非常感谢
