### ISSUE TITLE
【功能建议】希望在下一个版本允许自定义Trojan端口

### ISSUE THREAD

**Issue by lbroot** [Jrohy/trojan#232]
我的443端口受到占用，故想使用其他端口。
实际上目前也可以使用其他端口，只需要修改trojan的 config.json就可以了。
**但有一个小问题，你的面板把配置分享的端口写死了，导入配置后还需手动修改正确端口：**
Troajn/user.go 128行：fmt.Println("分享链接: " + util.Green(fmt.Sprintf("trojan://%s@%s:**443**", string(pass), domain)))
希望之后可以从config.json读取端口并用于生成分享链接。
感谢作者。

**Comment by Jrohy** [comment]
确实有问题，后面版本优化下这个

**Comment by Jrohy** [comment]
2.8.1以做优化, 更新下

**Comment by yang12me** [comment]
请问：如何修改端口

**Comment by Jrohy** [comment]
@yang12me 自己修改下trojan配置文件来改端口

**Comment by oso21** [comment]
解决443端口公用问题请看https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html，希望可以增加一个功能：允许自行设置或启动获取分享连接的端口，以便解决trojan形式上使用443端口，实际上是使用其他端口的问题。

**Comment by lbroot** [comment]
> 解决443端口公用问题请看[https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html，](https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html%EF%BC%8C)
> 希望可以增加一个功能：允许自行设置或启动获取分享连接的端口，以便解决trojan形式上使用443端口，实际上是使用其他端口的问题。

你这个方案很值得学习，不过对于只是为了代理这个目的，有些过于麻烦。我认为trojan跑在非443端口也是没有什么安全问题的...所以遇到占用问题直接换端口是最便捷的解决方案。

另外sni分流有个专门为trojan开发的项目，https://github.com/liberal-boy/tls-shunt-proxy 开箱即用，不需要编译nginx，方便了很多。

**Comment by jiangdefucom** [comment]
> 2.8.1已做优化, 更新下

我发现更新后，使用SNI做转发的也跟着显示更改后的端口。。。这咋整？
