### ISSUE TITLE
web 登录失败

### ISSUE THREAD

**Issue by Os-glthub** [Jrohy/trojan#235]
<img width="709" alt="无标题" src="https://user-images.githubusercontent.com/52124855/88825092-bf9caf00-d1f9-11ea-9af5-b84cbcf58cf6.png">

**Comment by Jrohy** [comment]
一般是密码错了，忘记密码可以运行trojan命令，web管理那里改admin密码

**Comment by Os-glthub** [comment]
密码正确，登录不进

**Comment by Jrohy** [comment]
@Os-glthub 重设密码试试

**Comment by Os-glthub** [comment]
> @Os-glthub 重设密码试试

重置了还是不行。不折腾了。也不影响使用。。。。
