### ISSUE TITLE
WordPress 与 trojan面板

### ISSUE THREAD

**Issue by SkrHelios** [Jrohy/trojan#236]
请问是否可以使面板和WordPress共存呢

**Comment by Jrohy** [comment]
可以参考wiki改下端口，加上个nginx

**Comment by SkrHelios** [comment]
加上个nginx  ：按照“配置NGINX”那条wiki？

**Comment by Jrohy** [comment]
@SkrHelios 是的

**Comment by SkrHelios** [comment]
请问在一键安装脚本时选哪个：
1.Let's Encrypt 证书

2.自定义证书路径

我是已安装了WordPress 是选第一个还是第二个

**Comment by Jrohy** [comment]
没有证书就选第一个

**Comment by SkrHelios** [comment]
有证书选择第二个？

**Comment by SkrHelios** [comment]
然后指向证书

**Comment by Jrohy** [comment]
是的

**Comment by SkrHelios** [comment]
我使用了分流的方法 两个都打不开 面板端口81 #
![屏幕快照 2020-07-31 下午8 47 41](https://user-images.githubusercontent.com/63626798/89036514-68204f80-d36f-11ea-85e2-fe5adf43d43c.png)
![屏幕快照 2020-07-31 下午8 48 06](https://user-images.githubusercontent.com/63626798/89036528-6ce50380-d36f-11ea-8eb6-76db456a36e1.png)
![屏幕快照 2020-07-31 下午8 48 13](https://user-images.githubusercontent.com/63626798/89036532-6e163080-d36f-11ea-98fa-6ee2f264e80d.png)
![屏幕快照 2020-07-31 下午8 48 34](https://user-images.githubusercontent.com/63626798/89036535-6eaec700-d36f-11ea-898c-200fdf65b171.png)

**Comment by Jrohy** [comment]
参考wiki nginx配置来修改

**Comment by SkrHelios** [comment]
更改etc/nginx/nginx.conf这个？

**Comment by Jrohy** [comment]
有两处localhost的配置不用变的

**Comment by SkrHelios** [comment]
ok
谢谢Jrohy 我新手不太熟练 麻烦到你了😁

**Comment by SkrHelios** [comment]
贴到哪里etc/nginx/nginx.conf的下面 还是整个文件删了改成那个模板

**Comment by Jrohy** [comment]
加到server里面

**Comment by SkrHelios** [comment]
流程：WordPress安装 然后安装trojan面板（自定义证书，安装docker版MySQL）再改面板的端口 和NGINX（加上wiki里的那段） 就这样的对吧

**Comment by Jrohy** [comment]
嗯得自己试下了

**Comment by SkrHelios** [comment]
![屏幕快照 2020-07-31 下午10 57 38](https://user-images.githubusercontent.com/63626798/89047720-5ba4f280-d381-11ea-9b60-44936c9ad558.png)
这样？

**Comment by SkrHelios** [comment]
![](https://user-images.githubusercontent.com/63626798/89047720-5ba4f280-d381-11ea-9b60-44936c9ad558.png)
是这样配置的吗

**Comment by Jrohy** [comment]
example.com换成自己域名

**Comment by SkrHelios** [comment]
放的地方是对的吧？

**Comment by Jrohy** [comment]
得自己测试了

**Comment by SkrHelios** [comment]
失败了 
![屏幕快照 2020-08-01 下午3 16 59](https://user-images.githubusercontent.com/63626798/89096570-1973c380-d40a-11ea-896c-a4b77fef4172.png)
![屏幕快照 2020-08-01 下午3 17 05](https://user-images.githubusercontent.com/63626798/89096572-1b3d8700-d40a-11ea-87cd-92de3009c93b.png)
请问怎么解决

**Comment by SkrHelios** [comment]
https://www.v2rayssr.com/trojanwordpress.html
参考这个教程的话 有没有其他的方案

**Comment by SkrHelios** [comment]
https://www.v2rayssr.com/trojanwordpress.html
https://www.chengxiaobai.cn/record/trojan-shared-443-port-scheme.html
参考这2个教程的话 有没有其他的方案
