### ISSUE TITLE
新增功能建议：给新增的用户记录日期等数据

### ISSUE THREAD

**Issue by RobinsonChina** [Jrohy/trojan#237]
有些用户和其他人合租机场，这些用户可能存在一些租期，如果可以在Trojan面板记录下每个用户加入的日期的话会很方便。
也可以考虑给每个用户后面加一个备注栏，让管理员自行记录（例如该用户某月某日到期，等等）

**Comment by jiangdefucom** [comment]
这个倒是比较简单，新增时间字段和备注字段即可实现
我觉得还可以新增用户使用的图表信息，可以直观地了解用户的使用情况（参照宝塔面板系统监控）

**Comment by jiangdefucom** [comment]
建议可以设置到期时间:)
