### ISSUE TITLE
记录连接到Trojan服务用户的在线状态

### ISSUE THREAD

**Issue by RobinsonChina** [Jrohy/trojan#238]
尊敬的开发者，您好。
为了方便了解自己的Trojan账户没有被盗或者遭到滥用，可以考虑在Trojan面板里显示每个用户的在线状态，以及同时在线的IP数量。也可以记录下每个用户的总在线时长。考虑到一些人的个人隐私，可以由管理员选择开启或禁用这项功能。
我不知道Trojan协议是否能知道一个用户有没有连接上，如果没有的话，可以考虑这种方式：长达三分钟没有数据交换则视为用户下线。

**Comment by alegoho** [comment]
支持
