### ISSUE TITLE
建议用户字段新增自定义节点域名

### ISSUE THREAD

**Issue by tomatogarden** [Jrohy/trojan#239]
面板可以自定义数据库，所以多个节点可以共用1个数据库，从而实现使用同一帐号同一密码可以连接所有节点
但面板的分享链接中显示的节点域名是固定，所以提出标题中的建议，虽然自己改造的话也不难，觉得还是提一下帮助面板更完善吧。

**Comment by yesmiley** [comment]
这个域名可以是任何一个绑定到ip的域名
理论上你绑定N个，填写的时候改一个就行了

**Comment by tomatogarden** [comment]
> 这个域名可以是任何一个绑定到ip的域名
> 理论上你绑定N个，填写的时候改一个就行了

拜托注意审题

**Comment by yesmiley** [comment]
> > 这个域名可以是任何一个绑定到ip的域名
> > 理论上你绑定N个，填写的时候改一个就行了
> 
> 拜托注意审题

问题是两周过去了，你这想法也没得到实现，所以出于好心给你点建议。
拜托注意明白我的用意？

**Comment by tomatogarden** [comment]
> > > 这个域名可以是任何一个绑定到ip的域名
> > > 理论上你绑定N个，填写的时候改一个就行了
> > 
> > 
> > 拜托注意审题
> 
> 问题是两周过去了，你这想法也没得到实现，所以出于好心给你点建议。
> 拜托注意明白我的用意？

好吧，谢谢
