### ISSUE TITLE
普通用户无法登录面板，查看流量

### ISSUE THREAD

**Issue by BrunuhVille** [Jrohy/trojan#24]
目前只有管理员可以登录面板，能否添加普通用户的登录（查看流量）支持
感谢！

**Comment by Jrohy** [comment]
后面版本会放出权限

**Comment by Jrohy** [comment]
@BrunuhVille 2.4.0 版本已支持普通用户的登录了，更新下`source <(curl -sL https://git.io/trojan-install)
`
