### ISSUE TITLE
希望能支持sqlite，只用一两个用户安装数据库实在太占内存了

### ISSUE THREAD

**Issue by beiyuqu** [Jrohy/trojan#240]

**Comment by Jrohy** [comment]
官方trojan不支持

**Comment by jiangdefucom** [comment]
只用一两个用户还装什么面板呀，直接改config中的password得了

**Comment by yesmiley** [comment]
占用率还行吧，我800m运存还装了几个别的程序也能剩下一半

**Comment by Jrohy** [comment]
专门测试过各种mysql和mariadb, 最后测试出目前的mariadb10.2比较省内存(70多m左右)，如果vps是512m的都是没问题的

**Comment by debj031634** [comment]
mariadb的本地访问默认密码多少啊，想其他web服务直接利用数据库

**Comment by Jrohy** [comment]
@debj031634 看下trojan配置文件
