### ISSUE TITLE
trojan-go泛域名证书有问题

### ISSUE THREAD

**Issue by qiangxinglin** [Jrohy/trojan#242]
手动申请的泛域名证书, trojan模式下一切正常(梯子+伪装流量)
切换成trojan-go之后, https访问各种站点都会提示"This site can’t provide a secure connection"
`
log: tls handshake failed | sni mismatched: a.example.com, expected: b.example.com
`
看了trojan-go的repo, 0.8.0之后已支持泛域名证书, 不知道问题出在哪里?

**Comment by qiangxinglin** [comment]
查到问题了, 在config里面把sni写成泛域名即可
猜测是trojan-go的`verify_hostname`原因
他的config file路径在哪?

**Comment by qiangxinglin** [comment]
另外 trojan-go模式的log里的user能否改一下格式?
目前显示的是SHA值, 改成用户名会直观许多

**Comment by Jrohy** [comment]
@qiangxinglin 向官方trojan-go反馈，改日志格式
