### ISSUE TITLE
密码问题

### ISSUE THREAD

**Issue by mccyz233** [Jrohy/trojan#244]
如果在管理面板之外的地方添加账号可行吗？密码加密方式和口令如何做到

**Comment by Jrohy** [comment]
通过trojan命令来添加用户密码

**Comment by jiangdefucom** [comment]
楼主是想自己搞个面板管理吧？

**Comment by mccyz233** [comment]
> 通过trojan命令来添加用户密码

就是用户不能自己注册创建账号，需要我手动输入，使用外接数据库并且前端写入数据可行吗？

**Comment by mccyz233** [comment]
> 楼主是想自己搞个面板管理吧？

就是感觉都需要我自己添加用户有点麻烦

**Comment by jiangdefucom** [comment]
> > 通过trojan命令来添加用户密码
> 
> 就是用户不能自己注册创建账号，需要我手动输入，使用外接数据库并且前端写入数据可行吗？

研究下[trojan-web](https://github.com/Jrohy/trojan-web)

**Comment by mccyz233** [comment]
> > > 通过trojan命令来添加用户密码
> > 
> > 
> > 就是用户不能自己注册创建账号，需要我手动输入，使用双向数据库和前端写入数据可行吗？
> 
> 研究下[trojan-web](https://github.com/Jrohy/trojan-web)

谢谢，研究出来了

**Comment by mccyz233** [comment]
> > > > 通过trojan命令来添加用户密码
> > > 
> > > 
> > > 就是用户不能自己注册创建账号，需要我手动输入，使用双向数据库和前端写入数据可行吗？
> > 
> > 
> > 研究下[trojan-web](https://github.com/Jrohy/trojan-web)
> 
> 谢谢，研究出来了，我主要是不知道密码的令牌上是怎么运作的，现在了解了

**Comment by jiangdefucom** [comment]
> > > > > 通过trojan命令来添加用户密码
> > > > 
> > > > 
> > > > 就是用户不能自己注册创建账号，需要我手动输入，使用双向数据库和前端写入数据可行吗？
> > > 
> > > 
> > > 研究下[trojan-web](https://github.com/Jrohy/trojan-web)
> > 
> > 
> > 谢谢，研究出来了，我主要是不知道密码的令牌上是怎么运作的，现在了解了

分享一下呗

**Comment by mccyz233** [comment]
> > > > > > 通过trojan命令来添加用户密码
> > > > > 
> > > > > 
> > > > > 就是用户不能自己注册创建账号，需要我手动输入，使用双向数据库和前端写入数据可行吗？
> > > > 
> > > > 
> > > > 研究下[trojan-web](https://github.com/Jrohy/trojan-web)
> > > 
> > > 
> > > 谢谢，研究出来了，我主要是不知道密码的令牌上是怎么运作的，现在了解了
> 
> 分享一下呗

密码是sha224 ，令牌是base64
