### ISSUE TITLE
希望面板可以调用iptables等功能来禁用一些不良网站

### ISSUE THREAD

**Issue by RobinsonChina** [Jrohy/trojan#248]
有时候使用这个Trojan用于教育目的，希望能在面板上提供一个功能，把指定的url解析到127.0.0.1或者用类似的功能，
来禁用p*****b等一些不想用户访问的网站。
谢谢，祝J大身体健康，阖家辛福。

**Comment by po888375** [comment]
这个可以在客户端设置吧，比如v2rayn里面的阻断路由里面填写要阻断的ip或者域名
