### ISSUE TITLE
【建议】移除Trojan-Web 的页面图标

### ISSUE THREAD

**Issue by yesmiley** [Jrohy/trojan#249]
Trojan-Web 提供了修改页面标题的功能，这使得我们可以在一定程度上将其伪装成其他管理系统。
然而页面的图标却是Trojan的LOGO，瞬间使得伪装毫无意义。

**Comment by haiquanhuang** [comment]
是的，同感，还找不到修改的方式

**Comment by Jrohy** [comment]
@yesmiley 2.8.6版本已移除, 更新下

**Comment by yesmiley** [comment]
谢谢 @Jrohy
