### ISSUE TITLE
Trojan-go log [error]

### ISSUE THREAD

**Issue by qiangxinglin** [Jrohy/trojan#250]
切换到trojan-go之后, 日志里有很多这个, 这个是trojan-go的问题么?
`[ERROR] github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:123 trojan failed to accept conn | websocket is disabled. redirecting http request from xxx`

**Comment by Jrohy** [comment]
是的trojan-go的日志
