### ISSUE TITLE
trojan 面板的密码储存在哪里？？

### ISSUE THREAD

**Issue by ztfot** [Jrohy/trojan#251]
我想找trojan面板的密码储存
web页面密码，但是我不知道放在哪里了
有人知道的话能分享一下嘛，谢谢

**Comment by Jrohy** [comment]
Leveldb目录：/var/lib/trojan-manager

**Comment by ztfot** [comment]
> /var/lib/trojan-manager

/var/lib/trojan-manager# ls
000004.ldb  000170.ldb  000924.ldb  CURRENT      LOCK  LOG.old
000165.ldb  000175.ldb  003825.log  CURRENT.bak  LOG   MANIFEST-003826
里面有多个文件，并没有发现

**Comment by Jrohy** [comment]
leveldb的文件，应该只能用代码来读取

**Comment by ztfot** [comment]
> leveldb的文件，应该只能用代码来读取

如何使用代码读取？

**Comment by Jrohy** [comment]
@ztfot https://github.com/Jrohy/trojan/blob/master/core/leveldb.go 参考项目代码
