### ISSUE TITLE
dial tcp 127.0.0.1:3306: connect: connection refused

### ISSUE THREAD

**Issue by freenaser** [Jrohy/trojan#252]
您好，请问一下，添加账户信息的时候出现上述提示且添加信息无效是为何？

**Comment by Jrohy** [comment]
连不上数据库

**Comment by freenaser** [comment]
> 
> 
> 连不上数据库

数据库安装时选的1，现在这种情况是需要重装么？为什么会出现这种情况呢？

**Comment by Jrohy** [comment]
如果选择1安装docker版mysql,mysql端口应该是随机而不是3306

**Comment by Jrohy** [comment]
docker ps看下mariadb状态

**Comment by freenaser** [comment]
> 
> 
> docker ps看下mariadb状态

已解决，感谢您提供的方向。
