### ISSUE TITLE
请问，已经装好的docker-trojan怎么更换域名？

### ISSUE THREAD

**Issue by fengmikaelson** [Jrohy/trojan#256]
域名到期了，要换一个，应该怎么更换配置？

**Comment by Jrohy** [comment]
运行trojan命令证书申请

**Comment by fengmikaelson** [comment]
> 运行trojan命令证书申请

请问替换域名后，web端能访问，trojan似乎没生效。

查看日志显示

Aug 24 08:39:41 fancy-buzz-1.localdomain trojan[2264]: [INFO]  2020/08/24 08:39:41 trojan-go v0.8.1 initializing
Aug 24 08:39:41 fancy-buzz-1.localdomain trojan[2264]: [FATAL] 2020/08/24 08:39:41 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
Aug 24 08:39:41 fancy-buzz-1.localdomain systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Aug 24 08:39:41 fancy-buzz-1.localdomain systemd[1]: Unit trojan.service entered failed state.
Aug 24 08:39:41 fancy-buzz-1.localdomain systemd[1]: trojan.service failed.


是否还有配置需要修改呢？

**Comment by Jrohy** [comment]
申请证书成功了吗新域名

**Comment by fengmikaelson** [comment]
刚才我多执行了几次，然后重启了几次，就突然可以了。也不懂怎么回事。
