### ISSUE TITLE
再次打开时会提示错误信息再返回首页，会看到页面内容

### ISSUE THREAD

**Issue by haiquanhuang** [Jrohy/trojan#257]
能不能修改成看不到页面内容？

**Comment by Jrohy** [comment]
什么错误信息，截下图

**Comment by haiquanhuang** [comment]
![WechatIMG108](https://user-images.githubusercontent.com/43022398/91532345-c6295e00-e940-11ea-8681-1bd2405e6125.jpeg)
不好意思，我没描述清楚这个是什么意思。
经常打开页面，会先提示这个错误，然后再跳到登录页面，可以正常使用的
就是想建议修改一下这个问题，毕竟是能直接看到网页的内容

**Comment by Jrohy** [comment]
是登录token超时了，没权限请求接口，所以也拿不到数据的，然后跳回登录页面

**Comment by jinwyp** [comment]
> 是登录token超时了，没权限请求接口，所以也拿不到数据的，然后跳回登录页面

要解决这个问题有两个方法
第一种就是就是不用单页面, 传统多页面, go后端把登录和登陆后的路由分开，登录后的路由需要后端路由验证在输入页面
第二种就是还是保持单页面， 统一加个 loading 画面, ajax数据返回成功才显示页面, token超时之前显示loading, 这样token无效就看不到页面具体内容了
