### ISSUE TITLE
不知能不能支持多域名

### ISSUE THREAD

**Issue by tomatogarden** [Jrohy/trojan#258]
当前Trojan服务器域名只能设置1个，不知Trojan能不能支持多域名？（貌似跟面板无关，应该去Trojan官方问。。。）

**Comment by Jrohy** [comment]
看配置文件来看估计不支持

**Comment by jinwyp** [comment]
不支持 因为一台机器只有一个443端口, 当然trojan也可以跑在非443端口，但那样就没意义了, 非443 端口容易被墙识别.

如果运行在非443端口 是可以支持多域名的, 通过nginx 配置sni 指令 识别域名分法, 具体可以看 https://www.youtube.com/watch?v=pRoVtUBmCU4
