### ISSUE TITLE
安裝的時候發生下列問題

### ISSUE THREAD

**Issue by a0932027686** [Jrohy/trojan#259]
0curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out
chmod: cannot access '/usr/local/bin/trojan': No such file or directory

**Comment by a0932027686** [comment]
正在安装trojan管理程序..
Hit:1 https://download.docker.com/linux/debian buster InRelease
Hit:2 http://ftp.tw.debian.org/debian buster InRelease
Hit:3 http://ftp.tw.debian.org/debian buster-updates InRelease
Hit:4 http://security.debian.org buster/updates InRelease
Hit:5 http://download.proxmox.com/debian/pve buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bash-completion is already the newest version (1:2.8-6).
socat is already the newest version (1.7.3.2-2).
xz-utils is already the newest version (5.2.4-1).
0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded.
正在下载管理程序v2.8.7版本...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   632  100   632    0     0    865      0 --:--:-- --:--:-- --:--:--   864
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection timed out
chmod: cannot access '/usr/local/bin/trojan': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0   1542      0 --:--:-- --:--:-- --:--:--  1542
-bash: trojan: command not found
安装trojan管理程序成功!

**Comment by Jrohy** [comment]
vps访问github网络有点问题，下载不了github release asset文件

**Comment by a0932027686** [comment]
要改DNS 嗎? 還是等等 ?

**Comment by a0932027686** [comment]
我是重新安裝的

**Comment by Jrohy** [comment]
curl -L https://github.com/Jrohy/trojan/releases/download/v2.8.7/trojan -o /usr/local/bin/trojan

**Comment by Jrohy** [comment]
可以直接试试运行命令来下载安装

**Comment by a0932027686** [comment]
我試過了,也把 port 443 kill了 , 但我有裝偽裝站點 , 是不是要刪乾淨 , 請問怎麼做 ? 我懷疑443被占用 .

**Comment by Jrohy** [comment]
也可以手动下载文件， 然后放置到/usr/local/bin/下面(需要chmod +x 授予可运行权限), 这样就变成trojan全局命令了

**Comment by a0932027686** [comment]
我搞定了  , 是我自己的愚蠢 , 謝謝你的trojan , 有問題再找你
