### ISSUE TITLE
希望可以增加域名伪装

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Jrohy/trojan#26]
如题，控制面板登录直接用域名感觉不太安全，可否把这两个都放开可自定义，谢谢

**Comment by Jrohy** [comment]
用来登录的域名能伪装的吗，这个访问域名得能ping通服务器ip的，不像v2ray那种ws的域名伪装

**Comment by FantasticSkyBaby** [comment]
我的意思是 输入域名a.com跳转到b.com, 管理面板的登录域名可自定义路径a.com/xxx

**Comment by Jrohy** [comment]
不支持的

**Comment by FantasticSkyBaby** [comment]
你是用的nginx吗

**Comment by Jrohy** [comment]
不是的, 用的 [gin](https://github.com/gin-gonic/gin) 框架

**Comment by Jrohy** [comment]
一般不会考虑依赖第三方的，还要涉及到第三方服务管理和配置修改, 而且还增加稳定性的风险

**Comment by FantasticSkyBaby** [comment]
好的 谢谢哈
