### ISSUE TITLE
访问https提示证书已过期

### ISSUE THREAD

**Issue by FantasticSkyBaby** [Jrohy/trojan#264]
你好，怎么能重新申请证书呢，关闭web面板，操作trojan tls 步骤无效

**Comment by Jrohy** [comment]
申请证书时报什么错

**Comment by Jrohy** [comment]
你可以运行crontsb -l里面的amce.sh相关命令看看报什么错

**Comment by FantasticSkyBaby** [comment]
[Fri Sep  4 01:45:40 EDT 2020] LISTEN     0      511          *:80                       *:*                   users:(("nginx",pid=492,fd=6),("nginx",pid=491,fd=6))
[Fri Sep  4 01:45:40 EDT 2020] tcp port 80 is already used by (("nginx",pid=492,fd=6),("nginx",pid=491,fd=6))
[Fri Sep  4 01:45:40 EDT 2020] Please stop it first
[Fri Sep  4 01:45:40 EDT 2020] _on_before_issue.
[Fri Sep  4 01:45:40 EDT 2020] Error

好像端口被占用了，我可以手动修改申请证书服务端口号吗

**Comment by Jrohy** [comment]
关了nginx再来申请

**Comment by FantasticSkyBaby** [comment]
40 22 * * * systemctl stop trojan-web; nginx -s stop; "/root/.acme.sh"/acme.sh —cron —home "/root/.acme.sh" > /dev/null; systemctl start trojan-web; nginx -p /path/to/nginx.conf; >> /root/logs.log 2>&1

我尝试在定时任务中加入nginx开关，但是没有成功，报错
/bin/sh: 1: nginx: not found

**Comment by Hikpy** [comment]
> 关了nginx再来申请
trojan web 怎么关掉哦，更新证书显示80端口被占用，强杀trojan web 又起来了。只能脚本卸载 重新来

**Comment by FantasticSkyBaby** [comment]
> 关了nginx再来申请
> trojan web 怎么关掉哦，更新证书显示80端口被占用，强杀trojan web 又起来了。只能脚本卸载 重新来

systemctl stop trojan-web

**Comment by FantasticSkyBaby** [comment]
@Hikpy systemctl stop trojan-web

**Comment by jinwyp** [comment]
这是个bug 通过trojan tls 重新申请证书 没有把 trojan-web 停止， 需要手动先停止 然后运行trojan tls 才可以， 否则会提示 80端口占用， acme.sh 的 standalone mode 无法重新申请证书

**Comment by FantasticSkyBaby** [comment]
> 这是个bug 通过trojan tls 重新申请证书 没有把 trojan-web 停止， 需要手动先停止 systemctl stop trojan-web 然后运行trojan tls 才可以， 否则会提示 80端口占用， acme.sh 的 standalone mode 无法重新申请证书

作者的定时任务命令里面带了停止trojan-web 可以看下crontsb -l

**Comment by FantasticSkyBaby** [comment]
@Jrohy 是否可以把申请证书的端口改为一个不太常用的端口呢

**Comment by Jrohy** [comment]
acme.sh申请证书不可以用常用端口

**Comment by FantasticSkyBaby** [comment]
> acme.sh申请证书不可以用常用端口

不可以用常用端口吗，那怎么会和80端口有冲突呢

**Comment by Jrohy** [comment]
只能80 或者443端口申请

**Comment by FantasticSkyBaby** [comment]
> acme.sh申请证书不可以自定义端口

我把关闭Nginx也加到定时任务中
40 22 * * * systemctl stop trojan-web; nginx -s stop; "/root/.acme.sh"/acme.sh —cron —home "/root/.acme.sh" > /dev/null; systemctl start trojan-web; nginx -p /path/to/nginx.conf; >> /root/logs.log 2>&1

“/bin/sh: 1: nginx: not found”

但是提示nginx: not found  这个是Nginx没设置成环境变量原因吗

**Comment by Jrohy** [comment]
nginx时这样关的吗，一般是systemctl stop nginx这样关吧

**Comment by FantasticSkyBaby** [comment]
👍

**Comment by jinwyp** [comment]
> > 这是个bug 通过trojan tls 重新申请证书 没有把 trojan-web 停止， 需要手动先停止 systemctl stop trojan-web 然后运行trojan tls 才可以， 否则会提示 80端口占用， acme.sh 的 standalone mode 无法重新申请证书
> 
> 作者的定时任务命令里面带了停止trojan-web 可以看下crontsb -l

这个和定时任务没关系啊 ，就是手动申请证书 trojan tls 的时候 没有先把 trojan-web停止 这样80被占用啊

**Comment by FantasticSkyBaby** [comment]
> > > 这是个bug通过trojan tls重新申请证书没有把trojan-web停止，需要手动先停止systemctl stop trojan-web然后运行trojan tls才可以，否则会提示80端口占用，acme.sh的独立模式无法重新申请证书
> > 
> > 
> > 作者的定时任务命令里面带了停止trojan-web可以看下crontsb -l
> 
> 这个和定时任务没关系啊，就是手动申请证书trojan tls的时候没有先把trojan-web停止这样80被占用啊

我停掉了，我是还有nginx服务导致80端口占用

**Comment by jinwyp** [comment]
> > > > 这是个bug通过trojan tls重新申请证书没有把trojan-web停止，需要手动先停止systemctl stop trojan-web然后运行trojan tls才可以，否则会提示80端口占用，acme.sh的独立模式无法重新申请证书
> > > 
> > > 
> > > 作者的定时任务命令里面带了停止trojan-web可以看下crontsb -l
> > 
> > 
> > 这个和定时任务没关系啊，就是手动申请证书trojan tls的时候没有先把trojan-web停止这样80被占用啊
> 
> 我停掉了，我是还有nginx服务导致80端口占用


用我的脚本吧 最好的一键脚本  把这些问题都修正了  直接就是nginx + trojan-web 伪装站点
https://github.com/jinwyp/one_click_script

**Comment by FantasticSkyBaby** [comment]
> > > > > 这是个bug通过trojan tls重新申请证书没有把trojan-web停止，需要手动先停止systemctl stop trojan-web然后运行trojan tls才可以，否则会提示80端口占用，acme.sh的独立模式无法重新申请证书
> > > > 
> > > > 
> > > > 作者的定时任务命令里面带了停止trojan-web可以看下crontsb -l
> > > 
> > > 
> > > 这个和定时任务没关系啊，就是手动申请证书trojan tls的时候没有先把trojan-web停止这样80被占用啊
> > 
> > 
> > 我停掉了，我是还有nginx服务导致80端口占用
> 
> 用我的脚本吧最好的一键脚本把这些问题都修正了直接就是nginx + trojan-web伪装站点
> https://github.com/jinwyp/one_click_script

谢谢分享，学习学习

**Comment by FantasticSkyBaby** [comment]
@Jrohy 大佬我这样写可以么，

0 16 * 1 * systemctl stop trojan-web; systemctl stop nginx.service; "/root/.acme.sh"/acme.sh —cron —home "/root/.acme.sh" > /dev/null; systemctl start trojan-web; systemctl start nginx.service;

**Comment by Jrohy** [comment]
@FantasticSkyBaby 你可以删掉> /dev/null，然后运行下整句命令来测试，没报错就没问题

**Comment by FantasticSkyBaby** [comment]
可以了，附上可用定时任务命令

0 16 * 1 * systemctl stop trojan-web; systemctl stop nginx.service; "/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh"; systemctl start trojan-web; systemctl start nginx.service;

**Comment by jinwyp** [comment]
> 可以了，附上可用定时任务命令
> 
> 0 16 * 1 * systemctl stop trojan-web; systemctl stop nginx.service; "/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh"; systemctl start trojan-web; systemctl start nginx.service;

acme.sh 脚本有2种模式 一种就是独立模式 就是需要80 端口 ，一种就是nginx 模式 不用停止其他服务 nginx 运行就可以申请 

acme.sh 本身就自带了crontab 自动更新证书 如果用了nginx 根本不用停止nginx
目前证书在 60 天以后会自动更新, 你无需任何操作. 今后有可能会缩短这个时间, 不过都是自动的, 你不用关心.

https://github.com/acmesh-official/acme.sh/wiki/%E8%AF%B4%E6%98%8E
