### ISSUE TITLE
问下脚本安装是不是需要手动先安装数据库啊？

### ISSUE THREAD

**Issue by jinwyp** [Jrohy/trojan#265]
看了下脚本里面没有安装数据mysql 是需要自己安装数据mysql吗？

**Comment by Jrohy** [comment]
也可以自己安装, 脚本也有内置安装docker版mariadb

**Comment by jinwyp** [comment]
> 也可以自己安装, 脚本也有内置安装docker版mariadb

安装数据的脚本在哪里啊？ install.sh里面没有看到啊， 难道在go源代码里面？

**Comment by Jrohy** [comment]
@jinwyp 是的go源码进行安装的
