### ISSUE TITLE
trojan web 怎么关掉哦，更新证书显示80端口被占用，强杀trojan web 又起来了。只能脚本卸载 重新来

### ISSUE THREAD

**Issue by Hikpy** [Jrohy/trojan#266]
trojan web 怎么关掉哦，更新证书显示80端口被占用，强杀trojan web 又起来了。只能脚本卸载 重新来

**Comment by Hikpy** [comment]
我知道了 下面的命令
systemctl stop trojan-web


哈哈哈哈，感谢

**Comment by Hikpy** [comment]
开启 trojan web 
systemctl start trojan-web
建议写到说明里边

**Comment by jinwyp** [comment]
这是个bug 通过trojan tls 重新申请证书 没有吧 trojan-web 停止， 需要手动先停止 然后运行trojan tls 才可以

**Comment by jinwyp** [comment]
2.8.8 已经修正该问题
