### ISSUE TITLE
提个建议，把初始化安装和trojanweb功能分开

### ISSUE THREAD

**Issue by jinwyp** [Jrohy/trojan#268]
现在trojan-web 通过命令行运行后实际有两个功能，一个是初始化安装步骤，一个提供trojanweb的网站管理密码功能， 

希望能把这个两个功能独立
 trojanweb 这个网站功能增加一个配置文件，里面包括mysql 连接，证书地址，默认管理员地址 ， 
主要这样其他脚本或宝塔就很容易方便整合trojanweb的功能， 而初始化安装等步骤都交给其他脚本或宝塔处理， 

还有建议把这个项目名字直接改成trojanweb， 与原版的trojan区分开来 容易造成误解和命令行配置与原版混淆。

问个问题
1  现在初始化完成后， trojanweb 的mysql 连接，证书地址，默认管理员地址 ，存在什么地方？ 
2 证书地址是不是直接修改的原版的trojan的配置文件？ trojanweb不需要用到证书地址？

**Comment by Jrohy** [comment]
都是读trojan核心的配置文件的, 证书是trojan核心提供

**Comment by jinwyp** [comment]
> 都是读trojan核心的配置文件的, 证书是trojan核心提供

1 mysql 的配置也是读的原版trojan的配置？  
 2 默认的管理员账号密码存在哪个表？

**Comment by Jrohy** [comment]
是读trojan配置文件的， admin密码存在leveldb里，其他则存到mysql里

**Comment by jinwyp** [comment]
> 是读trojan配置文件的， admin密码存在leveldb里，其他则存到mysql里

运行 trojan web 时能否指定原trojan的配置文件路径？  不使用 默认的/usr/local/etc/trojan/config.json 地址

**Comment by Jrohy** [comment]
@jinwyp 不支持
