### ISSUE TITLE
有大佬知道nginx在哪里吗，想修改下nginx做点其他转发的事情

### ISSUE THREAD

**Issue by ouyangyaxiong** [Jrohy/trojan#273]

**Comment by Jrohy** [comment]
没有nginx的，想改路由加nginx参考wiki

**Comment by ouyangyaxiong** [comment]
> 没有nginx的，想改路由加nginx参考wiki

好的 感谢大佬，另外我也好奇这个问题 →  #121
代码里面没看到web界面相关的静态资源 能否解答下？

**Comment by Jrohy** [comment]
静态文件因为都是字符串已经合进去release里面的assets文件了, 运行实质就是./trojan即可运行, 无需额外的前端文件

**Comment by jinwyp** [comment]
推荐我的一键脚本 集成nginx 和伪装网站 https://github.com/jinwyp/one_click_script
