### ISSUE TITLE
我从阿里云申请的证书，不知道下载哪种类型的证书

### ISSUE THREAD

**Issue by chouxiang99** [Jrohy/trojan#274]
![image](https://user-images.githubusercontent.com/45085951/92582929-2d8dc900-f2c4-11ea-9591-efd619f291fc.png)

Tomcat | 帮助下载
-- | --
Apache | 帮助下载
Nginx | 帮助下载
IIS | 帮助下载
JKS | 帮助下载
其他 | 下载
根证书I下载

能告知我应该下载哪一个证书嘛？还是说随便哪个都可以

**Comment by jinwyp** [comment]
nginx就可以

**Comment by chouxiang99** [comment]
好的  谢谢解答
