### ISSUE TITLE
更改配制文件

### ISSUE THREAD

**Issue by vipwuping** [Jrohy/trojan#275]
我想更改 WEB 首页的标题，在哪里更改，别外 WEB管理页面 80 端口访问的时侯直接强制跳转到 HTTPS  443端口上  这样更加安全

**Comment by Jrohy** [comment]
改web标题进去系统里面可以修改的， 强制跳转加个nginx 参考项目wiki

**Comment by jinwyp** [comment]
用的脚本 集成 nginx 方便安装 https://github.com/jinwyp/one_click_script/
