### ISSUE TITLE
发现一个比较严重的Bug

### ISSUE THREAD

**Issue by Qlmuby** [Jrohy/trojan#278]
首先我是docker安装的，直接安装我没有测试，不知是否也存在。

此bug可以重现，当类型选择为trojan-go时，在用户管理里删除节点后，再不重启VPS的情况下，此节点可以继续正常使用，而类型切换成trojan时，则一切正常没有出现此bug。

**Comment by Jrohy** [comment]
得向trojan-go官方反馈了
