### ISSUE TITLE
GCP su 安裝報錯 -- 已解決

### ISSUE THREAD

**Issue by vlpeng** [Jrohy/trojan#28]
欢迎使用trojan管理程序
1.trojan管理            2.用户管理           
3.安装管理              4.web管理          
5.查看配置              6.生成客户端配置文件      
请选择: 3
1.更新trojan
2.证书申请
3.安装mysql
请选择: 3
1.安装docker版mysql
2.输入自定义mysql连接
请选择: 1
docker run --name trojan-mysql --restart=always -p 30324:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=
LEDmW -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7
f72dcb414d4abc5449212b655a3093b08c065ab98f63aefcfc85282f050ba721
mysql启动中, 请稍等...
[mysql] 2020/03/24 11:34:11 packets.go:36: unexpected EOF
[mysql] 2020/03/24 11:34:11 packets.go:36: unexpected EOF
[mysql] 2020/03/24 11:34:11 packets.go:36: unexpected EOF

報錯截屏
[https://i.imgur.com/ghQ6Lq0.png](url)

**Comment by Jrohy** [comment]
不是报错，这是等待mysql启动过程中。等一下等启动完自动创表的

**Comment by vlpeng** [comment]
不知道為何，端口 443沒啟動
nc -v 申請證書域名 443
nc: connectx to 申請證書域名 port 443 (tcp) failed: Connection refused

要檢查哪裡確認？還是重啟 trojan？

● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-03-24 11:57:11 UTC; 2s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 9920 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 9920 (code=exited, status=1/FAILURE)
Mar 24 11:57:11 trojan systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Mar 24 11:57:11 trojan trojan[9920]: [2020-03-24 11:57:11] [FATAL] fatal: use_certificate_chain_file: No such file 
or directory
Mar 24 11:57:11 trojan trojan[9920]: [2020-03-24 11:57:11] [FATAL] exiting. . .
Mar 24 11:57:11 trojan systemd[1]: Unit trojan.service entered failed state.
Mar 24 11:57:11 trojan systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
trojan启动失败了，是自定义证书路径的吗

**Comment by vlpeng** [comment]
1) 是自定义证书路径

2) 请选择: 3
重启trojan成功!
欢迎使用trojan管理程序

3) [root@trojan bin]# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                   
 PORTS                                NAMES
04622ea820ca        jrohy/trojan             "init"                   2 minutes ago       Up 2 minutes             
                                      trojan
cb69cc342d94        mysql/mysql-server:5.7   "/entrypoint.sh mysq…"   17 minutes ago      Up 17 minutes (healthy)  
 33060/tcp, 0.0.0.0:62406->3306/tcp   trojan-mysql

**Comment by Jrohy** [comment]
自定义证书，有没有指错文件呢，有指错可以去修改下trojan配置文件

**Comment by vlpeng** [comment]
怪，我自定義證書了，還是一樣443端口起不來，我重搞一台CentOS好了，我這台在 GCP上面搞的 CentOS7

**Comment by Jrohy** [comment]
看起来是trojan没认出你指定的证书，一个是cert一个key, 有没有指错或者指反了，脚本输入路径后只会做文件判断是否存在，不会检验证书有效性的。

**Comment by vlpeng** [comment]
我指到這
/root/域名.crt
/root/域名.key
我重新啟動vm，乾淨安裝看看
PS: 我是跟著油管步驟做的

**Comment by Jrohy** [comment]
再不行你直接用脚本自带的let's encrypt 来签证试试

**Comment by Jrohy** [comment]
一般使用证书都是推荐脚本自带的let's encrypt来签，最稳

**Comment by yao32** [comment]
> 我指到這
> 
> /root/域名.crt
> 
> /root/域名.key
> 
> 我重新啟動vm，乾淨安裝看看
> 
> PS: 我是跟著油管步驟做的

他有YouTube教程么？给个链接，我去看看

**Comment by vlpeng** [comment]
油管後帶這段URI
watch?v=L6dq4NSLWps&t=16s

**Comment by yao32** [comment]
> 油管後帶這段URI
> 
> watch?v=L6dq4NSLWps&t=16s

谢谢

**Comment by vlpeng** [comment]
@Jrohy 
GCP 是 bash profile的問題，導致 ACME腳本沒跑完整，我找時間再測試

我在小鳥測試完全沒問題，但是流量限制這個在油管貌似行不通，參閱以下截屏說明
5兆用量跑完之後，無法請求 ipip
[https://i.imgur.com/7bCiGlx.png](url)

也無法請求 ifconfig
[https://i.imgur.com/k98qIOI.png](url)

但，油管繼續播放....
[https://i.imgur.com/u1gB3pH.png](url)

即便新增一個 tab 重新播放油管，還是可以播放 ...
[https://i.imgur.com/5PYWO6G.png](url)

連自己的小馬UI也被屏住
[https://i.imgur.com/QoPooul.png](url)

但，事實上總流量已經爆 120兆了
[https://i.imgur.com/K8kiHTc.png](url)

流量限制，我是限定5兆而已 ....
[https://i.imgur.com/Plwn4IR.png](url)

此外，mode 選全局 global，curl ifconfig.io 貌似還是會走本地端口 IP，不會走小馬的隧道

以上

**Comment by Jrohy** [comment]
@vlpeng 这应该是bug, 向官方仓库反馈下，我测了超流量后twitter和fb都不行，单单就油管可以

**Comment by vlpeng** [comment]
@Jrohy 這標題我改下，GCP可以，是我 su的時候出錯導致，這腳本沒問題，大推

**Comment by vlpeng** [comment]
nice repository !!!!
