### ISSUE TITLE
请问这里支不支持套用cloudflare。

### ISSUE THREAD

**Issue by 31415926pai** [Jrohy/trojan#283]
请问这里支不支持套用cloudflare。如果支持具体怎么操作？是直接让cloudflare解析域名，在申请证书时不代理，安装好后再打开cloudflare的DNS代理。还是怎么操作？谢谢各位大佬。

**Comment by 31415926pai** [comment]
不想使用trojan go，看到过go配合cloudflare的教程。

**Comment by jinwyp** [comment]
用我这个支持 https://github.com/jinwyp/one_click_script

**Comment by 31415926pai** [comment]
谢谢分享。
