### ISSUE TITLE
BUG报告：不输入密码，或者错误密码均可以连接成功

### ISSUE THREAD

**Issue by jackxin900** [Jrohy/trojan#285]
version: v2.8.8
gitVersion: a97327e
buildDate: 20200908-0914
goVersion: go1.14 linux/amd64

客户端上不输入密码，或者输入错误密码均可以连接，且不会被计入到用户使用数据中。

**Comment by stone-sir** [comment]
顶一下，确实有这个问题

**Comment by JancerWu** [comment]
这个问题也太严重了吧

**Comment by Jrohy** [comment]
用的什么客户端呢，没测试出有这问题

**Comment by jackxin900** [comment]
> 用的什么客户端呢，没测试出有这问题

Windows客户端用的是Qv2ray，ios用的是shadowrocket。空密码可以连接成功，但是无法打开正常网页，数据包应该被drop了。面板修改用户密码后，如果不重启vps，则修改前和修改后的密码都可以连接，并打开网页。

**Comment by Jrohy** [comment]
确实有这个问题，后面版本修改账密后都加下自动重启trojan操作

**Comment by jackxin900** [comment]
> 确实有这个问题，后面版本修改账密后都加下自动重启trojan操作

我 update 到了最新，这个问题貌似已经解决了。
