### ISSUE TITLE
SSL证书到期不自动续吗？连接不了了，怎么更新。

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#286]
Sep 30 15:51:24 ecs-Fwj trojan[4235]: [2020-09-30 15:51:24] [ALL] 106.122.100.115:40363 incoming connection
Sep 30 15:51:24 ecs-Fwj trojan[4235]: [2020-09-30 15:51:24] [ERROR] 106.122.100.115:40363 SSL handshake failed: sslv3 alert certificate expired
Sep 30 15:51:24 ecs-Fwj trojan[4235]: [2020-09-30 15:51:24] [INFO] 106.122.100.115:40363 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Sep 30 15:51:33 ecs-Fwj trojan[4235]: [2020-09-30 15:51:33] [ALL] 106.122.100.115:40361 incoming connection
Sep 30 15:51:33 ecs-Fwj trojan[4235]: [2020-09-30 15:51:33] [ERROR] 106.122.100.115:40361 SSL handshake failed: sslv3 alert certificate expired
Sep 30 15:51:33 ecs-Fwj trojan[4235]: [2020-09-30 15:51:33] [INFO] 106.122.100.115:40361 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
Sep 30 15:51:37 ecs-Fwj trojan[4235]: [2020-09-30 15:51:37] [ALL] 106.122.100.115:40362 incoming connection
Sep 30 15:51:38 ecs-Fwj trojan[4235]: [2020-09-30 15:51:38] [ERROR] 106.122.100.115:40362 SSL handshake failed: Connection reset by peer
Sep 30 15:51:38 ecs-Fwj trojan[4235]: [2020-09-30 15:51:38] [INFO] 106.122.100.115:40362 disconnected, 0 bytes received, 0 bytes sent, lasted for 1 seconds

**Comment by Jrohy** [comment]
可以看crontab -l手动运行下续签命令看看报什么错

**Comment by totodata** [comment]
重新更新可以了。手动安装，到了连接数据库那一步，一直连接不上，卡住了

连接mysql失败, 请重新输入
请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址: 
请输入mysql的用户名(回车使用root): root
请输入mysql root用户的密码: trojan
连接mysql失败, 请重新输入

**Comment by joxjpu** [comment]
請教一下  最後這是怎麼解決呀  因為我也發生同樣情況

[ERROR] 118.163.152.85:40266 SSL handshake failed: sslv3 alert bad certificate

**Comment by Wangsh6166** [comment]
> 請教一下 最後這是怎麼解決呀 因為我也發生同樣情況
> 
> [ERROR] 118.163.152.85:40266 SSL handshake failed: sslv3 alert bad certificate

我这边重启后就好了。
