### ISSUE TITLE
关于自定义的问题

### ISSUE THREAD

**Issue by Jungle-Leesin** [Jrohy/trojan#29]
我想问一下配置的证书路径在哪里，以及我想修改一下主页面，可否提供一下主页面的文件路路径

**Comment by Jrohy** [comment]
证书路径看下trojan的配置文件(/usr/local/etc/$NAME/config.json)，有记录的
至于页面前端文件是编译成字符串放进去release发布的二进制文件里面，是修改不了的。 运行时也不会释放出来，请求什么页面直接是返回字符串再gzip压缩一下给浏览器的。

**Comment by Jungle-Leesin** [comment]
好的，多谢

**Comment by Jungle-Leesin** [comment]
我把面板端口改成其他的之后，可否再装nginx来配置正常的https网站，这样我输入域名则通过nginx跳转到我自己的网站，输入域名：端口则跳转到面板界面

**Comment by Jrohy** [comment]
高级玩法可以试试

**Comment by Jungle-Leesin** [comment]
好的，谢谢
