### ISSUE TITLE
bug 报告  更改密码后，必须要重启面板才能生效

### ISSUE THREAD

**Issue by stone-sir** [Jrohy/trojan#292]
流量到了，不停止
更改密码后，必须要重启面板才能生效

**Comment by Jrohy** [comment]
流量到了不停止是trojan本身的问题，改面板密码不需要重启面板才生效的

**Comment by jackxin900** [comment]
> 流量到了不停止是trojan本身的问题，改面板密码不需要重启面板才生效的
更改用户的密码后，不重启服务器，则两个密码都可以连接。而且使用空密码也可以显示连接上服务器。

**Comment by Jrohy** [comment]
@jackxin900 如果是trojan用户密码，这个也是trojan本身的问题，面板只是改数据库数据

**Comment by stone-sir** [comment]
@Jrohy 
bug报告：建议增加面板修改trojan或trojan-go的任何设置（修改密码，限制流量）自动重启trojan或trojan-go
面板流量到达设置值时自动重启trojan以可行的方式。

问题：面板修改trojan密码时要重启trojan才能发挥作用，不然错误密码，空密码可以连接
流量到了，不会自动停止，要重启trojan才能充分发挥作用

**Comment by Jrohy** [comment]
修改密码必须重启才生效的问题后面版本修复下，但流量到了不会停止的问题确实得trojan本身自己解决了，毕竟流量能否用都是trojan本身决定，外部也不好一直监听着每一个用户流量是不是用完

**Comment by jackxin900** [comment]
> 修改密码必须重启才生效的问题后面版本修复下，但流量到了不会停止的问题确实得trojan本身自己解决了，毕竟流量能否用都是trojan本身决定，外部也不好一直监听着每一个用户流量是不是用完

流量控制会超过限定一点才会断开连接，总体来说是很正常的。well functioned

**Comment by Jrohy** [comment]
2810版本已修复此问题，更新下
