### ISSUE TITLE
怎么切换到trojan-go

### ISSUE THREAD

**Issue by imdm** [Jrohy/trojan#293]
通过source <(curl -sL https://git.io/trojan-install) 一键安装的，管理程序版本是2.8.8
通过域名进入web管理后台没有看到trojan管理的选项，无法切换trojan版本，是最新版本不支持trojan-go了吗

**Comment by Jrohy** [comment]
进去web页面切换

**Comment by Jrohy** [comment]
2.8.9 已增加命令行里切换trojan类型(trojan管理里)

**Comment by HOMHOG** [comment]
> 进去web页面切换

请问web页去掉trojan管理了吗

**Comment by Jrohy** [comment]
没有的，要用admin用户才能看到

**Comment by HOMHOG** [comment]
> 没有的，要用admin用户才能看到

谢谢 已经看到了
