### ISSUE TITLE
建意在脚本中加入伪装的域名，trojan的管理WEB太明显了，很容易被人发现

### ISSUE THREAD

**Issue by ice2015** [Jrohy/trojan#299]

**Comment by Jrohy** [comment]
可以trojan改端口， 加个nginx换成其他路由，参考wiki

**Comment by ice2015** [comment]
看到呢，谢谢大佬

**Comment by JancerWu** [comment]
web端口换了控制面板不能访问了。这里有点不太明白，我之前的理解是这样的（因为想和博客一起用）
带证书的blog与trojan伪装共用方案：
为了trojan的安全性，443端口必须给它，将其伪装由默认80端口改为其他任意端口，如6666，nginx做相应配置；同时，为了让blog持证上岗，但已经失去了443端口，不得已80端口硬着头皮上，在80端口上配置SSL，需要注意一点的是如果用户访问http连接的话会提示“the plain http request was sent to https”意思就是http请求转到https了，其实nginx官网认为这个是正常现象定义了个497的状态，只要在nginx再配置一下：error_page 497 https://$server_name:80$request_uri;   
// 自动跳转域名后面会带着:80很丑也是没办法了

**Comment by Jrohy** [comment]
80端口 /就给博客， 其他路由可以反向代理给trojan-web, 不用带80的，trojan本身ssl证书的，非trojan流量就转到默认的80端口

**Comment by JancerWu** [comment]
那比如我现在web的端口改成了6666，我通过什么访问控制面板呢，ip+:6666不行

**Comment by Jrohy** [comment]
systemctl status trojan-web看下启动成功了没

**Comment by JancerWu** [comment]
启动成功了，6666端口在监听，但是ip+:6666访问不了

**Comment by Jrohy** [comment]
trojan web -p 123

**Comment by JancerWu** [comment]
还是不行

**Comment by JancerWu** [comment]
老哥，只要知道域名就能畅联的bug不敢用了

**Comment by Jrohy** [comment]
@JancerWu 需要密码验证才能连的trojan

**Comment by ice2015** [comment]
建意大佬在WIKI中的nignx里的脚本用stream写个好些，这样比较灵活，

**Comment by ice2015** [comment]
还有“在/usr/local/bin/trojan web 后面添加 -p port”应要配合nignx分流才可能正常的，最好说明一定，免得我们这些小白折腾，哈哈

**Comment by JancerWu** [comment]
trojan web的网站根目录在哪里，小白折腾nginx

**Comment by Jrohy** [comment]
前端文件合进去release里面的文件的，不在宿主机外面目录

**Comment by JancerWu** [comment]
那我改完trojan web端口后怎么用nginx分流正常访问控制面板

**Comment by JancerWu** [comment]
大佬能在wiki里面详细写一下nginx分流配置吗，小白表示控制面板访问不了了，现在只能通过bash改，有点麻烦。改了web端口后，log显示正常端口正在监听，但是通过ip+端口号访问不了web端页面

**Comment by Jrohy** [comment]
@JancerWu 会不会墙的原因，你可以在linux用curl访问ip:port试试

**Comment by Jrohy** [comment]
即使没有证书，也是能通过ip+端口来访问的

**Comment by JancerWu** [comment]
@Jrohy VPS上用curl访问可以，端口开了呀，我把firewall关了也没用

**Comment by JancerWu** [comment]
@Jrohy 感谢，可能是端口被墙了，重新换了几个端口，总算有一个成了

**Comment by isegon** [comment]
改web访问路径试了半天也没成功，有大佬成功么？求Demo

**Comment by JancerWu** [comment]
@isegon 我之前也是，多换几个端口试试就好了
