### ISSUE TITLE
其实可以参考一下这个一键安装的脚本,整合一下

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/trojan#3]
其实可以参考一下这个一键安装的脚本,整合一下,完善一点.

原地址:https://github.com/mark-logs-code-hub/trojan-wiz

脚本地址
wget -N --no-check-certificate https://raw.githubusercontent.com/mark-logs-code-hub/trojan-wiz/master/ins.sh && chmod +x ins.sh && sudo bash ins.sh

**Comment by Jrohy** [comment]
需要什么功能呢

**Comment by lqhorochi** [comment]
> 需要什么功能呢

1.自动续签证书
2.整合多合一加速内核
3.Trojan版本更新
4.脚本更新
5.IP自签证
6.支持IPV6
7.加入VPS系统优化脚本
暂时就想到这些,哈

**Comment by Jrohy** [comment]
续签证书, acme.sh自己有，
多合一加速内核不会去搞的, 这个留个专门的弄比较好(https://github.com/chiakge/Linux-NetSpeed)，
trojan版本更新已经有了， 脚本更新可以自己运行下安装脚本即可更新，
ipv6暂不考虑支持

**Comment by Jrohy** [comment]
可能后期会加入web(估计是用caddy而不是nginx), 等docker化完成后

**Comment by lqhorochi** [comment]
> 续签证书, acme.sh自己有，
> 多合一加速内核不会去搞的, 这个留个专门的弄比较好([https://github.com/chiakge/Linux-NetSpeed)，](https://github.com/chiakge/Linux-NetSpeed)%EF%BC%8C)
> trojan版本更新已经有了， 脚本更新可以自己运行下安装脚本即可更新，
> ipv6暂不考虑支持

也行,ipv6感觉还可以,在vps上手动添加DNS一些解析
来来去去就是上谷歌,油管,脸书,推特等,ipv6基本都支持的不错
