### ISSUE TITLE
希望在数据库的用户名能修改

### ISSUE THREAD

**Issue by Telle87** [Jrohy/trojan#30]
搭建的时候遇到自定义数据库名必须为root的问题，这个权限有点高，且有些远程数据库不能以root为用户名，所以希望数据库用户名能自定义

**Comment by Jrohy** [comment]
你可以直接修改trojan配置文件就好， 主要不想提示用户那么多次输入

**Comment by KDLDK586** [comment]
多个panal共用一个数据库时怎么处理？每个服务器都有不同的用户群。数据库不能自定义用户名和数据库名称。改完config.json后web页面提示无法连接MySQL。

**Comment by Jrohy** [comment]
@KDLDK586 可以的，检查下建的数据库用指定用户能否连接上(用navicat或者mysql命令行）来测试, Web界面连的数据库信息就是读取trojan配置文件里面的

**Comment by Jrohy** [comment]
@KDLDK586 看了代码确实写死了数据库名，后面优化下，全部读取trojan配置文件里的数据库信息

**Comment by Jrohy** [comment]
@KDLDK586 测试了是可以的，只要保证新建的数据库有users初始化表就好

**Comment by Jrohy** [comment]
https://trojan-gfw.github.io/trojan/authenticator
创users表语句, 必须保证新数据库有这个表，否则都会报连上不数据库

**Comment by KDLDK586** [comment]
那么我可以在不同名称的数据库中来创建这个users表吗，
如何连接到不同名称的数据库中。

**Comment by Jrohy** [comment]
可以的，在trojan配置文件里改数据库名就好

**Comment by KDLDK586** [comment]
好的   感谢！

**Comment by Jrohy** [comment]
@Telle87 @KDLDK586 2.5.1开始支持了，自定义mysql链接可以改数据库名和用户名
