### ISSUE TITLE
trojan无法启动

### ISSUE THREAD

**Issue by JancerWu** [Jrohy/trojan#300]
查看日志出错如下：
trojan.service: main process exited, code=exited, status=1/FAILURE
Unit trojan.service entered failed state.
trojan.service failed.

**Comment by Jrohy** [comment]
trojan restart 没用?

**Comment by JancerWu** [comment]
没用，日志里面就是报这个错

**Comment by JancerWu** [comment]
状态里面 vendor preset: disabled 跟这个有关系吗

**Comment by Jrohy** [comment]
证书申请到了吗

**Comment by JancerWu** [comment]
我自己有证书的，原来trojan是配好能用的，就是想加个面板。不过刚刚改成重新内置选择1重现在线申请证书终于可以了，可能是证书路径有问题？我粘贴的。。可能还是有问题吧。谢谢，总算能用了
