### ISSUE TITLE
v2.8.8升级v2.8.8后面板日志是空的

### ISSUE THREAD

**Issue by zhucaidan** [Jrohy/trojan#301]
v2.8.8升级v2.8.9后面板中的Trojan管理日志是空的，重启了VPS也还是空的不显示任何数据

**Comment by Ksdb104** [comment]
same problem +1

**Comment by Jrohy** [comment]
确实存在此问题

**Comment by Jrohy** [comment]
更新下2810版本，已修复此问题

**Comment by zhucaidan** [comment]
好的

**Comment by Jrohy** [comment]
@chnexpats 是不是不是用admin用户来登录, admin用户才有权限

**Comment by chnexpats** [comment]
> @chnexpats 是不是不是用admin用户来登录, admin用户才有权限

是 admin, 刚看了下当前面板版本是 2.8.1 更新只是 通过 trojan 日子面板里的 update 看了下是 1.16.0 这个应该不是 面板的版本，请问 Jrohy 如何更新面板版本？谢谢

**Comment by Jrohy** [comment]
`trojan updateWeb`

**Comment by chnexpats** [comment]
> `trojan updateWeb`

这个之前我试过提示 Error: unknown command "updateWeb" for "trojan"，我安装这个是 伪装了网站的，我再研究下 感谢 Jrohy 回复那么快 Lol

**Comment by Jrohy** [comment]
旧版还没这个命令的话就运行`source <(curl -sL https://git.io/trojan-install)`

**Comment by chnexpats** [comment]
> 旧版还没这个命令的话就运行`source <(curl -sL https://git.io/trojan-install)`

谢谢 Jrohy 分享，用这个命令更新成功 Thanks again.
