### ISSUE TITLE
面板的访问端口能修改吗？

### ISSUE THREAD

**Issue by lyg367090** [Jrohy/trojan#303]
或者干脆默认访问地址就不要搞在80或是443上面……毕竟感觉有点傻……只要访问一下这个IP就知道这肯定是一个Trojan节点了
>_<

**Comment by Jrohy** [comment]
参考wiki改端口，也可以加个nginx改访问路径的

**Comment by lyg367090** [comment]
谢谢

**Comment by PeterWang-dev** [comment]
> 参考wiki改端口，也可以加个nginx改访问路径的

已经参考wiki改了，但是我之前配置文件里的exec行中没有service后没有web而是直接跟的配置文件json路径，我在中间加了web -p 10100 后trojan就启动失败了，journal中显示是-p参数未定义？？？

**Comment by Jrohy** [comment]
@PeterWang-dev 改的是trojan-web的service文件，有没有改错

**Comment by PeterWang-dev** [comment]
> @PeterWang-dev 改的是trojan-web的service文件，有没有改错

已解决，感谢

**Comment by stone-sir** [comment]
> > @ PeterWang-dev改的是trojan-web的服务文件，有没有改错
> 
> 已解决，感谢

兄弟你好，这个wiki是指哪里啊？谢谢了
