### ISSUE TITLE
https无法访问面板

### ISSUE THREAD

**Issue by gimgoo** [Jrohy/trojan#305]
如题，如果使用https，无法访问面板，报错：
`无法访问此网站网址为 https://xxxxxxx/#/login 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_HTTP2_PROTOCOL_ERROR`

但是使用http可以。重启trojan与重启VPS均无法解决

**Comment by gimgoo** [comment]
请问nginx配置文件路径是什么？

**Comment by Jrohy** [comment]
是不是证书没申请到，依赖于trojan使用的证书的

**Comment by gimgoo** [comment]
trojan已经可以正常使用了。如果证书没申请到，trojan用不了的。
我也想过会不会证书有问题，后来我又申请了两次证书，还是无法访问https，只能访问http。
其实，刚开始，也就是搭建好以后的一会儿，是可以https的，但是不到1个小时，后面访问已经不能使用https了

**Comment by Jrohy** [comment]
默认是没有nginx的，加nginx的话要改面板启动端口

**Comment by daxiaamo** [comment]
我也出现了一样的情况，只能通过Http访问管理面板

**Comment by ulifuqiang** [comment]
@Jrohy 你好，有法手动上传其他地方申请的证书不？传到什么位置？谢谢

**Comment by Jrohy** [comment]
传到什么位置你喜欢，可以自定义证书路径的 @ulifuqiang

**Comment by ulifuqiang** [comment]
@Jrohy 目前https不能访问是不是证书问题呀，确定443没有屏蔽

**Comment by Jrohy** [comment]
@ulifuqiang 证书申请成功了吗，trojan能否使用，得trojan能使用，https才能访问, 因为是trojan提供的

**Comment by ulifuqiang** [comment]
@Jrohy 都是英文的，我也不确认证书有没有成功，trojan能使用，有没有https访问面板都都可以吗？

**Comment by Jrohy** [comment]
有没有https访问面板都行的

**Comment by ulifuqiang** [comment]
第一次选的自动申请证书，之后改手动证书，路径写绝对路径就是嘛

**Comment by ulifuqiang** [comment]
阿里云那边下载nginx的证书就可以了吧 @Jrohy

**Comment by Jrohy** [comment]
换证书后trojan使用正常能翻就行

**Comment by ulifuqiang** [comment]
@Jrohy 真的是申请证书失败了，我手动设置证书就正常了。
