### ISSUE TITLE
问一下这个是什么情况，突然用不了了

### ISSUE THREAD

**Issue by sunrisely** [Jrohy/trojan#309]
![image](https://user-images.githubusercontent.com/50516355/97771499-65084b80-1b78-11eb-9a36-1dab03039c75.png)

**Comment by Jrohy** [comment]
删掉目录/var/lib/trojan-manager试试

**Comment by sunrisely** [comment]
> 删掉目录/ var / lib / trojan-manager尝试

好的 谢谢

**Comment by LoS-Light** [comment]
我也遇到同样的问题
删掉目录/var/lib/trojan-manager
后还是无法解决
怎办
