### ISSUE TITLE
自动生成客户端配置文件时，该如何一併填入多路复用以及路由这些特性?

### ISSUE THREAD

**Issue by LoS-Light** [Jrohy/trojan#310]
client.json
如果我希望自动生成客户端配置文件时，
也一併填入多路复用以及路由这个特性，
"mux": {
    "enabled": false,
    "concurrency": 8,
    "idle_timeout": 60
},
"router":{
    "enabled": true,
    "bypass": [
        "geoip:cn",
        "geoip:private",
        "geosite:cn",
        "geosite:geolocation-cn"
    ],
    "block": [
        "geosite:category-ads"
    ],
    "proxy": [
        "geosite:geolocation-!cn"
    ]
}
我该怎麽做，谢谢。

**Comment by Jrohy** [comment]
手动加下

**Comment by LoS-Light** [comment]
因为有多位用户需要处理，手动加入的话挺麻烦的，
但如果现阶段自动化做不到的话，也只能这样了。
谢谢。
