### ISSUE TITLE
web界面可以输出trojan-go的链接吗，如果有的话，怎么做才可以。

### ISSUE THREAD

**Issue by hmx27** [Jrohy/trojan#311]
日志有trojan-go的选项，但新建分享也就只出trojan的链接，并非随着日志切换什么类型就输出什么类型的链接，是有什么用意么？

**Comment by Jrohy** [comment]
trojan-go分享连接可以是一样的格式的

**Comment by hmx27** [comment]
请问作者有考虑新建链接可以多一个生成选项(trojan和trojan-go任选其一)，或者跟着日志切换的类型来生成对应的链接，这样会更好，反正你都不用websocket，哈哈~

**Comment by Jrohy** [comment]
不支持， 用trojan://适用性会更好点

**Comment by hmx27** [comment]
那我换成trojan-go的话，还是会支持trojan-go的特性吧？例如多路复用那些

**Comment by Jrohy** [comment]
支持的，只不过有些特性要自己改json, 比如ws

**Comment by hmx27** [comment]
懂了，多谢作者
