### ISSUE TITLE
trojan启动报错，什么问题

### ISSUE THREAD

**Issue by luowei729** [Jrohy/trojan#312]
Nov 06 09:53:38 sandaiyun-2020111947 systemd[1]: Started trojan.
Nov 06 09:53:38 sandaiyun-2020111947 trojan[20225]: Welcome to trojan 1.16.0
Nov 06 09:53:38 sandaiyun-2020111947 trojan[20225]: [2020-11-06 09:53:38] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Nov 06 09:53:38 sandaiyun-2020111947 trojan[20225]: [2020-11-06 09:53:38] [FATAL] exiting. . .
Nov 06 09:53:38 sandaiyun-2020111947 systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 09:53:38 sandaiyun-2020111947 systemd[1]: trojan.service: Unit entered failed state.
Nov 06 09:53:38 sandaiyun-2020111947 systemd[1]: trojan.service: Failed with result 'exit-code'.
Nov 06 09:53:42 sandaiyun-2020111947 systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
Nov 06 09:53:42 sandaiyun-2020111947 systemd[1]: Stopped trojan.

**Comment by Jrohy** [comment]
没申请到证书

**Comment by Arbaba2022** [comment]
I have the same problem, while the certificate is fine and entered correctly. There was no problem for a few days, but today this problem has arisen for my trojan
