### ISSUE TITLE
mariadb启动中,请稍等...

### ISSUE THREAD

**Issue by xhrzg2017** [Jrohy/trojan#313]
德国小鸡mariadb启动中,请稍等...

**Comment by Jrohy** [comment]
什么系统昵，vps够不够内存

**Comment by xhrzg2017** [comment]
> 什么系统昵，vps够不够内存
web面板数值
德国小鸡
swap: 0/8.82 GB
CPU: 32.52%
内存: 191.93 MB/976.56 MB
硬盘: 4.01 GB/9.72 GB

**Comment by Jrohy** [comment]
不行就自行安装mysql, 可以自定义mysql地址的
