### ISSUE TITLE
后台报错，一旦某个链接ssl握手失败，Trojan会一直进行下去，导致cpu100%工作，最后卡死

### ISSUE THREAD

**Issue by fengcheng6** [Jrohy/trojan#315]
-- Logs begin at Sun 2020-11-08 08:29:14 EST. --
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37810 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37808 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37758 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37756 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37754 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37752 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37718 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37760 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:37720 SSL handshake failed: Connection timed out
Nov 09 07:59:37 hoste8ab037f52 trojan[16498]: [2020-11-09 07:59:37] [ERROR] 39.187.72.145:38034 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38076 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38124 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38126 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38046 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38048 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38050 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38128 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38130 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38132 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38134 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38108 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38120 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38122 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38136 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38092 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38090 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38366 SSL handshake failed: Connection timed out
Nov 09 08:03:59 hoste8ab037f52 trojan[16498]: [2020-11-09 08:03:59] [ERROR] 39.187.72.145:38376 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38442 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38428 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38448 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38450 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38452 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38454 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38432 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38430 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38444 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38456 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38446 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38370 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38460 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38458 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38462 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38486 SSL handshake failed: Connection timed out
Nov 09 08:08:21 hoste8ab037f52 trojan[16498]: [2020-11-09 08:08:21] [ERROR] 39.187.72.145:38470 SSL handshake failed: Connection timed out

**Comment by Jrohy** [comment]
官方trojan还是trojan-go, 出现这种情况得向官方仓库反馈

**Comment by fengcheng6** [comment]
官方Trojan

**Comment by fengcheng6** [comment]
> 官方trojan还是trojan-go, 出现这种情况得向官方仓库反馈
官方Trojan

**Comment by Clarenceguoshuai** [comment]
**55555555555******************

**Comment by MargaretteMoss** [comment]
这每一条记录的端口号都不同，这个IP在攻击你的服务器吧？
