### ISSUE TITLE
关于管理面板的问题

### ISSUE THREAD

**Issue by stone-sir** [Jrohy/trojan#318]
大佬你好，这个管理面板可以更改网页根路径吗？用了nginx想把web通过路径放到其它网站后面，谢谢了

**Comment by Jrohy** [comment]
参考项目wiki改nginx配置

**Comment by stone-sir** [comment]
大佬你好，能说得详细点吗？网页根路径在哪里改，项目wiki是指哪里啊，谢谢啦

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

**Comment by stone-sir** [comment]
谢谢大佬，这个是指默认路径是admin对吧？这个可以改吗？

**Comment by Jrohy** [comment]
可以改的

**Comment by stone-sir** [comment]
这个是直接改就好了吗？还是要做其它操作呢？谢谢

**Comment by Jrohy** [comment]
加进自己配置就好
