### ISSUE TITLE
第2步安装trojan，输入命令跑完以后无法继续了，报错

### ISSUE THREAD

**Issue by jwjoewoo** [Jrohy/trojan#321]

**Comment by jwjoewoo** [comment]
/usr/local/bin/trojan: line 1: Not: command not found

**Comment by Jrohy** [comment]
什么vps的什么系统，/usr/local/bin环境变量可能没设置到

**Comment by jwjoewoo** [comment]
> 什么vps的什么系统，/usr/local/bin环境变量可能没设置到

您好，是Cent OS 7。我是小白用户可能描述的不够清楚。我是按照网上教程一步一步操作，前几天是可以成功搭建的。昨晚我重新搞了个VPS，还是谷歌云的，配置都一样，昨天搭建不成功。后来看trojan的运行状态是failed。但是运行trojan命令，能出来那6个选项。

**Comment by Jrohy** [comment]
是不是证书没申请到, 提供下失败的日志

**Comment by jwjoewoo** [comment]
> 是不是证书没申请到, 提供下失败的日志

您是说域名的证书吗？我好像看到过一个我的域名证书申请次数太多的提示。

**Comment by jwjoewoo** [comment]
> 是不是证书没申请到, 提供下失败的日志

我今天晚上再跑一下，把失败的日志想办法弄出来。

**Comment by Jrohy** [comment]
申请太多的话就第二天再试或者换域名

**Comment by jwjoewoo** [comment]
> 申请太多的话就第二天再试或者换域名

好的，感谢大神指点！

**Comment by jwjoewoo** [comment]
> 是不是证书没申请到, 提供下失败的日志
[Thu Nov 19 09:23:09 UTC 2020] Create new order error. Le_OrderFinalize not found. {
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many certificates already issued for exact set of domains: joewoo.mons
ter: see https://letsencrypt.org/docs/rate-limits/",
  "status": 429


● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-11-19 09:29:35 UTC; 914ms ago
  Process: 4068 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 4068 (code=exited, status=1/FAILURE)
Nov 19 09:29:35 web systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Nov 19 09:29:35 web systemd[1]: Unit trojan.service entered failed state.
Nov 19 09:29:35 web systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
估计是没申请到证书所以启动失败了

**Comment by jwjoewoo** [comment]
> 估计是没申请到证书所以启动失败了

嗯，换了个域名好了~谢谢

**Comment by Qlmuby** [comment]
> 什么vps的什么系统，/usr/local/bin环境变量可能没设置到

/usr/local/bin/trojan: line 1: Not: command not found
我也遇到这个问题了，上次安装也是没问题，vps，系统都没变，什么原因突然间会导致这变量设置不到？

**Comment by Jrohy** [comment]
@Qlmuby 你可以运行这命令来检查下环境变量存不存在`echo $PATH|grep /usr/local/bin`,
不存在则运行`echo 'export PATH=$PATH:/usr/local/bin' >> /etc/bashrc; source /etc/bashrc`

**Comment by Qlmuby** [comment]
> @Qlmuby 你可以运行这命令来检查下环境变量存不存在`echo $PATH|grep /usr/local/bin`,
> 不存在则运行`echo 'export PATH=$PATH:/usr/local/bin' >> /etc/bashrc; source /etc/bashrc`

root@eb2ec0:~# echo $PATH|grep /usr/local/bin
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin

执行后返回了这个

**Comment by Jrohy** [comment]
有返回这个trojan命令还不能用? 什么厂商的vps

**Comment by Qlmuby** [comment]
> 有返回这个trojan命令还不能用? 什么厂商的vps

root@eb2ec0:~# docker exec -it trojan bash
/usr/local/bin/trojan: line 1: Not: command not found

是的，到这步还是出现这个错误。

**Comment by Jrohy** [comment]
原来你在容器环境运行，我检查下镜像

**Comment by Qlmuby** [comment]
> 原来你在容器环境运行，我检查下镜像

好的，麻烦大佬了

**Comment by Jrohy** [comment]
@Qlmuby 重新pull镜像`docker pull jrohy/trojan`， 之前镜像弄得有问题.

**Comment by Qlmuby** [comment]
> @Qlmuby 重新pull镜像`docker pull jrohy/trojan`， 之前镜像弄得有问题.

这回好了，没问题了，谢谢大佬。
