### ISSUE TITLE
面板安全问题

### ISSUE THREAD

**Issue by Jiaocz** [Jrohy/trojan#322]
众所周知，虽然分享链接中仅有密码，但是如果用户知道用户名，他还是可以登录到面板去看自己用了多少东西，就像这样
![image](https://user-images.githubusercontent.com/14857984/99816699-fc186000-2b86-11eb-9f4d-a1951284a71c.png)
但是只要我把这个位置改为```true```
![image](https://user-images.githubusercontent.com/14857984/99816811-17836b00-2b87-11eb-826a-f2d62f2605e1.png)
然后刷新，我就变成admin了，好神奇啊（捂脸）
并且有**完全的面板管理权**，虽然用户列表还是只能看到自己，但是也能搞些事情了，看看能不能解决一下吧……

**Comment by Jrohy** [comment]
下个版本看怎么改进下

**Comment by Jrohy** [comment]
2.8.12版本加了后台接口来判断当前登录用户是否为管理员，可以更新下

**Comment by Jiaocz** [comment]
经过测试，用户列表确实会没有增加用户，但是管理Trojan页面仍然没有被隐藏并且可以管理，希望可以跟进优化，Issue先不关闭了

**Comment by Jrohy** [comment]
下个版本彻底修复

**Comment by Jrohy** [comment]
2.9.0已发布进行修复，更新下

**Comment by Jiaocz** [comment]
更新了，isAdmin已经没了，然后暂时就没有新的方法去提权了。
不过可能有一个小问题，就是如果一个用户有同admin的密码那么他可能能修改用户，不知道是不是我的问题，可以抽空看一下应该影响不大。

**Comment by Jrohy** [comment]
未发现有这问题，admin是独立存储的，存到leveldb里，其他用户就存到mysql里
