### ISSUE TITLE
申请证书失败，换了好多脚本，均是同一个地方失败，求大神帮忙

### ISSUE THREAD

**Issue by ralfc6** [Jrohy/trojan#324]
oracle vps ubuntu 18.04
原来装过，后来不好用，卸载后，就安不上了。

报错都是：
xx.xx.ml:Verify error:Fetching http://xx.xx.ml/.well-known/acme-challenge/rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo: Error getting validation data

debug信息：
root@instance-20200516-0120:~# ~/.acme.sh/acme.sh  --issue  -d xx.xx.xx  --webroot /usr/share/nginx/html/  --debug
[Sun Nov 15 16:29:48 UTC 2020] Lets find script dir.
[Sun Nov 15 16:29:48 UTC 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Sun Nov 15 16:29:48 UTC 2020] _script='/root/.acme.sh/acme.sh'
[Sun Nov 15 16:29:48 UTC 2020] _script_home='/root/.acme.sh'
[Sun Nov 15 16:29:48 UTC 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.8
[Sun Nov 15 16:29:48 UTC 2020] Running cmd: issue
[Sun Nov 15 16:29:48 UTC 2020] _main_domain='xx.xx.xx'
[Sun Nov 15 16:29:48 UTC 2020] _alt_domains='no'
[Sun Nov 15 16:29:48 UTC 2020] Using config home:/root/.acme.sh
[Sun Nov 15 16:29:48 UTC 2020] default_acme_server
[Sun Nov 15 16:29:48 UTC 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Sun Nov 15 16:29:48 UTC 2020] DOMAIN_PATH='/root/.acme.sh/xx.xx.xx'
[Sun Nov 15 16:29:49 UTC 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Sun Nov 15 16:29:49 UTC 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Sun Nov 15 16:29:49 UTC 2020] GET
[Sun Nov 15 16:29:49 UTC 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Sun Nov 15 16:29:49 UTC 2020] timeout=
[Sun Nov 15 16:29:49 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:29:50 UTC 2020] ret='0'
[Sun Nov 15 16:29:50 UTC 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Sun Nov 15 16:29:50 UTC 2020] ACME_NEW_AUTHZ
[Sun Nov 15 16:29:50 UTC 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Nov 15 16:29:50 UTC 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Sun Nov 15 16:29:50 UTC 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Sun Nov 15 16:29:50 UTC 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Sun Nov 15 16:29:50 UTC 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun Nov 15 16:29:50 UTC 2020] ACME_VERSION='2'
[Sun Nov 15 16:29:50 UTC 2020] Le_NextRenewTime
[Sun Nov 15 16:29:50 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Sun Nov 15 16:29:50 UTC 2020] _on_before_issue
[Sun Nov 15 16:29:50 UTC 2020] _chk_main_domain='xx.xx.xx'
[Sun Nov 15 16:29:50 UTC 2020] _chk_alt_domains
[Sun Nov 15 16:29:50 UTC 2020] Le_LocalAddress
[Sun Nov 15 16:29:51 UTC 2020] d='xx.xx.xx'
[Sun Nov 15 16:29:51 UTC 2020] Check for domain='xx.xx.xx'
[Sun Nov 15 16:29:51 UTC 2020] _currentRoot='/usr/share/nginx/html/'
[Sun Nov 15 16:29:51 UTC 2020] d
[Sun Nov 15 16:29:51 UTC 2020] _saved_account_key_hash is not changed, skip register account.
[Sun Nov 15 16:29:51 UTC 2020] Read key length:
[Sun Nov 15 16:29:51 UTC 2020] _createcsr
[Sun Nov 15 16:29:51 UTC 2020] Single domain='xx.xx.xx'
[Sun Nov 15 16:29:51 UTC 2020] Getting domain auth token for each domain
[Sun Nov 15 16:29:51 UTC 2020] d
[Sun Nov 15 16:29:51 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Nov 15 16:29:51 UTC 2020] payload='{"identifiers": [{"type":"dns","value":"xx.xx.xx"}]}'
[Sun Nov 15 16:29:51 UTC 2020] RSA key
[Sun Nov 15 16:29:51 UTC 2020] HEAD
[Sun Nov 15 16:29:51 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Sun Nov 15 16:29:51 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  -I  '
[Sun Nov 15 16:29:52 UTC 2020] _ret='0'
[Sun Nov 15 16:29:52 UTC 2020] POST
[Sun Nov 15 16:29:52 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Sun Nov 15 16:29:52 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:29:54 UTC 2020] _ret='0'
[Sun Nov 15 16:29:54 UTC 2020] code='201'
[Sun Nov 15 16:29:54 UTC 2020] Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/102407353/6227989906'
[Sun Nov 15 16:29:54 UTC 2020] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/102407353/6227989906'
[Sun Nov 15 16:29:54 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/8625517914'
[Sun Nov 15 16:29:54 UTC 2020] payload
[Sun Nov 15 16:29:54 UTC 2020] POST
[Sun Nov 15 16:29:54 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz-v3/8625517914'
[Sun Nov 15 16:29:54 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:29:56 UTC 2020] _ret='0'
[Sun Nov 15 16:29:56 UTC 2020] code='200'
[Sun Nov 15 16:29:56 UTC 2020] d='xx.xx.xx'
[Sun Nov 15 16:29:56 UTC 2020] Getting webroot for domain='xx.xx.xx'
[Sun Nov 15 16:29:56 UTC 2020] _w='/usr/share/nginx/html/'
[Sun Nov 15 16:29:56 UTC 2020] _currentRoot='/usr/share/nginx/html/'
[Sun Nov 15 16:29:56 UTC 2020] entry='"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew","token":"rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo"'
[Sun Nov 15 16:29:56 UTC 2020] token='rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo'
[Sun Nov 15 16:29:56 UTC 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:29:56 UTC 2020] keyauthorization='rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo.z4UZ8v80tlHnE4e_dR0G6q0SnmwlihSVdr1rWLfpYMU'
[Sun Nov 15 16:29:56 UTC 2020] dvlist='xx.xx.xx#rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo.z4UZ8v80tlHnE4e_dR0G6q0SnmwlihSVdr1rWLfpYMU#https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew#http-01#/usr/share/nginx/html/'
[Sun Nov 15 16:29:56 UTC 2020] d
[Sun Nov 15 16:29:56 UTC 2020] vlist='xx.xx.xx#rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo.z4UZ8v80tlHnE4e_dR0G6q0SnmwlihSVdr1rWLfpYMU#https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew#http-01#/usr/share/nginx/html/,'
[Sun Nov 15 16:29:56 UTC 2020] d='xx.xx.xx'
[Sun Nov 15 16:29:56 UTC 2020] ok, let's start to verify
[Sun Nov 15 16:29:56 UTC 2020] Verifying: xx.xx.xx
[Sun Nov 15 16:29:56 UTC 2020] d='xx.xx.xx'
[Sun Nov 15 16:29:56 UTC 2020] keyauthorization='rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo.z4UZ8v80tlHnE4e_dR0G6q0SnmwlihSVdr1rWLfpYMU'
[Sun Nov 15 16:29:56 UTC 2020] uri='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:29:56 UTC 2020] _currentRoot='/usr/share/nginx/html/'
[Sun Nov 15 16:29:56 UTC 2020] wellknown_path='/usr/share/nginx/html//.well-known/acme-challenge'
[Sun Nov 15 16:29:56 UTC 2020] writing token:rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo to /usr/share/nginx/html//.well-known/acme-challenge/rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo
[Sun Nov 15 16:29:56 UTC 2020] Changing owner/group of .well-known to root:root
[Sun Nov 15 16:29:56 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:29:56 UTC 2020] payload='{}'
[Sun Nov 15 16:29:56 UTC 2020] POST
[Sun Nov 15 16:29:56 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:29:56 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:29:58 UTC 2020] _ret='0'
[Sun Nov 15 16:29:58 UTC 2020] code='200'
[Sun Nov 15 16:29:58 UTC 2020] trigger validation code: 200
[Sun Nov 15 16:29:58 UTC 2020] sleep 2 secs to verify
[Sun Nov 15 16:30:00 UTC 2020] checking
[Sun Nov 15 16:30:00 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:30:00 UTC 2020] payload
[Sun Nov 15 16:30:00 UTC 2020] POST
[Sun Nov 15 16:30:00 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:30:00 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:30:02 UTC 2020] _ret='0'
[Sun Nov 15 16:30:02 UTC 2020] code='200'
[Sun Nov 15 16:30:02 UTC 2020] xx.xx.xx:Verify error:Fetching http://xx.xx.xx/.well-known/acme-challenge/rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo: Error getting validation data
[Sun Nov 15 16:30:02 UTC 2020] Debug: get token url.
[Sun Nov 15 16:30:02 UTC 2020] GET
[Sun Nov 15 16:30:02 UTC 2020] url='http://xx.xx.xx/.well-known/acme-challenge/rmXN-x4Ei97Wo-zXX466ZmXpz_uK2RrhYsrQDT4cJVo'
[Sun Nov 15 16:30:02 UTC 2020] timeout=1
[Sun Nov 15 16:30:02 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Sun Nov 15 16:30:03 UTC 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Sun Nov 15 16:30:03 UTC 2020] ret='28'
[Sun Nov 15 16:30:03 UTC 2020] Debugging, skip removing: /usr/share/nginx/html//.well-known
[Sun Nov 15 16:30:03 UTC 2020] pid
[Sun Nov 15 16:30:03 UTC 2020] No need to restore nginx, skip.
[Sun Nov 15 16:30:03 UTC 2020] _clearupdns
[Sun Nov 15 16:30:03 UTC 2020] dns_entries
[Sun Nov 15 16:30:03 UTC 2020] skip dns.
[Sun Nov 15 16:30:03 UTC 2020] _on_issue_err
[Sun Nov 15 16:30:03 UTC 2020] Please add '--debug' or '--log' to check more details.
[Sun Nov 15 16:30:03 UTC 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Sun Nov 15 16:30:03 UTC 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:30:03 UTC 2020] payload='{}'
[Sun Nov 15 16:30:03 UTC 2020] POST
[Sun Nov 15 16:30:03 UTC 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/8625517914/1BJiew'
[Sun Nov 15 16:30:03 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Sun Nov 15 16:30:05 UTC 2020] _ret='0'
[Sun Nov 15 16:30:05 UTC 2020] code='400'
[Sun Nov 15 16:30:05 UTC 2020] Diagnosis versions:

**Comment by ralfc6** [comment]
已解决了，是vps故障恢复后，自动迁移到另外的机器上，默认的iptables又启用了，导致连接网站验证不通过，apt-get purge netfilter-persistent
reboot 
关闭就好了

**Comment by beaglezeng** [comment]
> 已解决了，是 vps 故障恢复后，自动迁移到另外的机器上，默认的 iptables 又启用了，导致连接网站验证不通过，apt-get purge netfilter-persistent reboot 关闭就好了

感谢，我也遇到这问题

**Comment by vicdorke** [comment]
太感谢了

**Comment by kinhungbaby** [comment]
> 已解决了，是vps故障恢复后，自动迁移到另外的机器上，默认的iptables又启用了，导致连接网站验证不通过，apt-get purge netfilter-persistent reboot 关闭就好了

来自3年后的感谢
