### ISSUE TITLE
解析到的ip: [127.0.0.1] 输入的域名和本机ip不一致, 请重新输入!

### ISSUE THREAD

**Issue by rickartmiriam** [Jrohy/trojan#326]
请输入申请证书的域名:
xxxxxx解析到的ip: [127.0.0.1]
输入的域名和本机ip不一致, 请重新输入!

老是提示这个，请大神指导下该如何解决。有时换个域名重新解析又好了，就是浪费了很多域名。

**Comment by lrainys** [comment]
编辑 /ETC/HOSTS   把127.0.0.1 域名   更改成       你的公网IP地址  域名
IPV6那行注释掉    保存   就可以了
