### ISSUE TITLE
多域名 443 端口配置

### ISSUE THREAD

**Issue by luoqiz** [Jrohy/trojan#33]
服务器使用nginx处理其他两个域名服务，均使用ssl，可是升级后trojan web 现在默认占用了443，应该如何配置多域名？（建议作为可配置项）

**Comment by Jrohy** [comment]
是trojan本身占了443的(不建议换其他端口，否则可能就没伪装效果)。 nginx配置要自己测试了

**Comment by luoqiz** [comment]
已明白原理，nginx 放在 trojan 之后可以解决
