### ISSUE TITLE
能否增加周期性流量管理？

### ISSUE THREAD

**Issue by istraw** [Jrohy/trojan#330]
vps每个月都有重置流量的日期，但是这个面板没有，流量统计会一直叠加上去，我想了解每个周期内哪个用户用的流量最大，还有限制流量也能按周期性就很棒了，希望作者能否考虑一下这个功能，谢谢。

**Comment by Jrohy** [comment]
新版已支持

**Comment by rickartmiriam** [comment]
更新到2.9.5版本了，设置了每月1号重置流量，好像还是没有自动重置哦，请问下是怎么回事？

**Comment by Jrohy** [comment]
要设置到期日期的才会重置流量 @rickartmiriam
