### ISSUE TITLE
Web服务正常 一段时间后trojan无法连接

### ISSUE THREAD

**Issue by ckbkdj** [Jrohy/trojan#332]
Nov 27 11:10:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:10:22 buffered data has been written into the database
Nov 27 11:10:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:10:27 buffered data has been written into the database
Nov 27 11:10:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:10:52 buffered data has been written into the database
Nov 27 11:10:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:10:57 buffered data has been written into the database
Nov 27 11:11:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:11:22 buffered data has been written into the database
Nov 27 11:11:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:11:27 buffered data has been written into the database
Nov 27 11:11:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:11:52 buffered data has been written into the database
Nov 27 11:11:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:11:57 buffered data has been written into the database
Nov 27 11:12:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:12:22 buffered data has been written into the database
Nov 27 11:12:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:12:27 buffered data has been written into the database
Nov 27 11:12:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:12:52 buffered data has been written into the database
Nov 27 11:12:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:12:57 buffered data has been written into the database
Nov 27 11:13:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:13:22 buffered data has been written into the database
Nov 27 11:13:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:13:27 buffered data has been written into the database
Nov 27 11:13:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:13:52 buffered data has been written into the database
Nov 27 11:13:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:13:57 buffered data has been written into the database
Nov 27 11:14:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:14:22 buffered data has been written into the database
Nov 27 11:14:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:14:27 buffered data has been written into the database
Nov 27 11:14:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:14:52 buffered data has been written into the database
Nov 27 11:14:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:14:57 buffered data has been written into the database
Nov 27 11:15:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:15:22 buffered data has been written into the database
Nov 27 11:15:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:15:27 buffered data has been written into the database
Nov 27 11:15:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:15:52 buffered data has been written into the database
Nov 27 11:15:57 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:15:57 buffered data has been written into the database
Nov 27 11:16:22 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:16:22 buffered data has been written into the database
Nov 27 11:16:27 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:16:27 buffered data has been written into the database
Nov 27 11:16:52 core-gig-1.localdomain trojan[3151]: [INFO]  2020/11/27 11:16:52 buffered data has been written into the database

这是我看到的日志 没有出现什么异常 , 出现连接不上后 重启trojan 立刻正常 , 怀疑在某一时刻 tojran无故卡死,   用的trojan-go

**Comment by Jrohy** [comment]
建议向官方仓库反馈下
