### ISSUE TITLE
我们这个切换到go版能套cdn吗？

### ISSUE THREAD

**Issue by ulifuqiang** [Jrohy/trojan#334]
@Jrohy 是不是直接切换go版，然后改解析就行了？

**Comment by Jrohy** [comment]
切换成go版后，得自己修改下配置文件，面板不支持改cdn的

**Comment by ulifuqiang** [comment]
@Jrohy 有相关教程吗

**Comment by Jrohy** [comment]
@ulifuqiang 参考官网教程: https://p4gefau1t.github.io/trojan-go/advance/websocket/
