### ISSUE TITLE
之前用的原版trojan的数据库可以无缝迁移吗

### ISSUE THREAD

**Issue by Bilchus** [Jrohy/trojan#336]
试了一下 全新安装面板使用之前的数据库信息是报错的  但是原版数据库里密码是加密的 不能反向解密

**Comment by Jrohy** [comment]
运行trojan upgrade试下升级

**Comment by Bilchus** [comment]
> 运行trojan upgrade试下升级

OK了 trojan upgrade db 升级是成功了 虽然密码不显示 确实没办法反向解密密码
