### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by kun-qian** [Jrohy/trojan#338]
Hello Buddy,

Today I came across a connection issue and find the following logs:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x8552de]

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x17, 0x0)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:1117 +0x3e
trojan/core.GetValue(0xbe8c1c, 0xa, 0x0, 0x0, 0xd4d0a0, 0xc00024b4d0)
	/home/go/trojan/core/leveldb.go:14 +0x1fa
trojan/trojan.Type(0xd4d060, 0xc000010020)
	/home/go/trojan/trojan/trojan.go:110 +0x3a
trojan/trojan.ControllMenu()
	/home/go/trojan/trojan/trojan.go:18 +0x65
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:57 +0x46a
trojan/cmd.glob..func6(0x111f400, 0x115c4e0, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x25
github.com/spf13/cobra.(*Command).execute(0x111f400, 0xc0000201d0, 0x0, 0x0, 0x111f400, 0xc0000201d0)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x111f400, 0x44716a, 0x10dd840, 0xc000000300)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x25

Do you have any idea?

**Comment by Jrohy** [comment]
rename `/var/lib/trojan-manager ` to try

**Comment by kun-qian** [comment]
I don't get the point. What do you mean rename? from what to what?

**Comment by Jrohy** [comment]
or delete /var/lib/trojan-manager

**Comment by kun-qian** [comment]
Problem solved.  Any explanations? Thanks

**Comment by kun-qian** [comment]
solved
