### ISSUE TITLE
参考Wiki修改web端口问题

### ISSUE THREAD

**Issue by Tim-tse** [Jrohy/trojan#339]
如图所示，我这样改端口是不是有问题？
运行以下命令后，域名加端口访问不了，谢谢各位大神。另外nginx配置文件在那呢？
`systemctl daemon-reload
systemctl restart trojan-web`
![11000](https://user-images.githubusercontent.com/63907602/101847228-b9e2ad00-3b8d-11eb-801c-912484640713.png)

**Comment by Jrohy** [comment]
nginx得自己手动安装的，无法访问的话你换个端口试试

**Comment by Tim-tse** [comment]
改端口格式写的没错吧？那我在换个端口多试试。谢谢

**Comment by Tim-tse** [comment]
![11](https://user-images.githubusercontent.com/63907602/101902276-5b4d1b80-3bed-11eb-8fdf-42d46e998a3b.png)
原来的端口格式少了空格，按现在这种格式换了好几个都不行。进不了后台

**Comment by Jrohy** [comment]
你可以随便运行命令`trojan web -p 1234`来测试能否进管理系统的
