### ISSUE TITLE
安装更新脚本无法同步最近内核以及WEB管理 - 设置使用期限时间等

### ISSUE THREAD

**Issue by trojson** [Jrohy/trojan#341]
嗨 Jrohy 刚发现内核以及WEB管理有更新，用脚本执行一次显示已经下载最新的版本 v2.8.12 但界面还是原来的一样，请问在哪里设置时间以及使用期限? 还是全新安装？ 目前状态 trojan

**Comment by Jrohy** [comment]
使用期限还不支持
