### ISSUE TITLE
使用bbr加速后打不开web网页

### ISSUE THREAD

**Issue by tguncle** [Jrohy/trojan#342]
成功部署trojan后 使用bbr安装 之后进入不了web页面
重新添加了一次证书之后 web正常访问
错误码是无法访问127.0.0.1的一个端口 当时忘记记录了

**Comment by Jrohy** [comment]
有修改web端口么

**Comment by Jrohy** [comment]
一般建议先安装bbr再安装fq软件，安装bbr可能要升级内核有风险

**Comment by tguncle** [comment]
没有修改web端口 可能是顺序的问题 懂了 谢谢~
