### ISSUE TITLE
安装BBRPLUS 就安装不上面板，不安装bbrplus 就可以安装。大佬怎么解决？

### ISSUE THREAD

**Issue by happyaguang** [Jrohy/trojan#343]
板瓦公  centos-7-x86_64-bbr

**Comment by Jrohy** [comment]
同样是搬瓦工的centos7安装bbr-plus没问题，证书有没有申请成功，trojan能否使用

**Comment by happyaguang** [comment]
先安装bbrplus，在安装面板，会一直提示  mariadb启动中。无限循环。

**Comment by happyaguang** [comment]
先安装bbr-plus，再安装面板，会一直循环提示mariadb启动中。
使用的bbr-plus脚本
wget -N --no-check-certificate "https://raw.githubusercontent.com/chiakge/Linux-NetSpeed/master/tcp.sh" && chmod +x tcp.sh && ./tcp.sh

**Comment by Jrohy** [comment]
看来是装不成功数据库，你可以自己用非docker方式来安装数据库，到时指定下mysql链接就好(自定义mysql地址)
