### ISSUE TITLE
请教使用期限功能的含义

### ISSUE THREAD

**Issue by RobinsonChina** [Jrohy/trojan#344]
是不是说给一个用户添加了7天的使用期限，那七天后这个用户就被禁用了？然后如果在这个周期里的日期出现了1号就重置已用流量？

**Comment by Jrohy** [comment]
对的

**Comment by RobinsonChina** [comment]
明白了，请问后续是否考虑允许自定义重置已用流量的日期，谢谢

**Comment by Jrohy** [comment]
会考虑下

**Comment by RobinsonChina** [comment]
谢谢

**Comment by Jrohy** [comment]
@RobinsonChina  2.9.3版本已添加流量重置日修改，更新下

**Comment by RobinsonChina** [comment]
谢谢，已更新，还有最后一个问题，如果没有给某个用户设置限期，那么到了重置流量的日期是不是就不会重置那位用户的流量？

**Comment by Jrohy** [comment]
对的没设置限期的用户就不会重置流量的
