### ISSUE TITLE
关于限制流量和限制时间的问题咨询？

### ISSUE THREAD

**Issue by Tim-tse** [Jrohy/trojan#345]
如题，想了解限制规则，假如我同时限制了时间和流量，那么这个流量是总流量（一直累积用完）还是次月重新计算？谢谢

**Comment by Tim-tse** [comment]
不好意思，344楼回复没看懂.

**Comment by Jrohy** [comment]
会在流量重置日重置使用流量的，默认重置日为1号，也可以自己修改

**Comment by Tim-tse** [comment]
哦明白了，我的理解是，如果限制这个用户100GB流量，如果不限制使用日期，那么用完后就不能用了，如果同时限制流量和日期，相当于包月使用，到期流量归零。然后可以继续循环使用？我的理解对吗？

**Comment by Jrohy** [comment]
对的

**Comment by Tim-tse** [comment]
谢谢
