### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by vvvcedarceba** [Jrohy/trojan#346]
希望能增加对不同账号链接速度的限制
谢谢

**Comment by Jrohy** [comment]
trojan不支持

**Comment by trojson** [comment]
Jrohy 能否后期加入 dark mode 类似 github 暗黑模式 看着眼睛不会那么刺，感谢！

**Comment by Jrohy** [comment]
会考虑下 @trojson

**Comment by Jrohy** [comment]
@trojson 
<img width="953" alt="微信截图_20201221172434" src="https://user-images.githubusercontent.com/12463263/102761189-8e439c00-43b1-11eb-83e2-395baab3973a.png"> 别人有现成的dark主题，但不知道如何做到在线切换😂

**Comment by trojson** [comment]
Cool 😄 可否自行拉取代码？或者首次启动的时候选择主题模式。后续通过 wget 拉取代码实现修改整体效果！这个挺好先观望下，感谢！

**Comment by Jrohy** [comment]
使用的https://github.com/Arattian/element-theme-dark这个仓库，如果能有前端大佬来协助下就好😀

**Comment by trojson** [comment]
好的 Jrohy 感谢分享，先了解下 ！

**Comment by l3617** [comment]
那个，脚本支持非443的端口安装使用吗

**Comment by l3617** [comment]
> 使用的https://github.com/Arattian/element-theme-dark 这个仓库，如果能有前端大佬来协助下就好😀



> trojan不支持

那个，脚本支持非443的端口安装使用吗，nat鸡能安装使用吗
