### ISSUE TITLE
在nas docker中搭建遇到“重启trojan失败!”問題

### ISSUE THREAD

**Issue by SeanChangX** [Jrohy/trojan#347]
请问若我要在nas docker中搭建，出现
“
重启trojan失败!                                                                                                                                             
Failed to get D-Bus connection: Operation not permitted
”
出现
“请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址:”
请问这要怎么解决？

**Comment by Jrohy** [comment]
不行可以裸机部署试试

**Comment by SeanChangX** [comment]
> 什么系统呢， 不行可以裸机部署试试
Synology，不知道是不是我两个容器之间的设定有问题？请问有什么需要注意的设定吗？

**Comment by Jrohy** [comment]
没试过了，得自己尝试下

**Comment by SeanChangX** [comment]
请问如果是正常的docker，也是需要两个container对吗？他们之间要怎么连结呢？

**Comment by Jrohy** [comment]
第一次安装会提示输入mysql地址来连的

**Comment by SeanChangX** [comment]
请问预设的账号密码是多少，还是说要怎么设定？

Jrohy <notifications@github.com> 於 2020年12月23日 週三 11:56 寫道：

**Comment by Jrohy** [comment]
root/trojan，你可以自己改docker run里面的密码来自定义的

**Comment by SeanChangX** [comment]
您好，我mysql的没问题了，但是出现以下画面提示：
“
Failed to get D-Bus connection: Operation not permitted                                                                                                                                                     
重启trojan失败!
”
请问这是否代表我需要开埠给他通行，请问是那个埠呢？还是说是有其他什么问题是我没注意到的。

**Comment by Jrohy** [comment]
是不是这个系统没有systemctl来管理服务的，没有可能不兼容

**Comment by SeanChangX** [comment]
我想我可能找到解答了，可能是因为容器的设计原则，我需让他以 特权模式 运行容器，就可以用systemctl启动服务了。

**Comment by juilletVent** [comment]
> 我想我可能找到解答了，可能是因为容器的设计原则，我需让他以 特权模式 运行容器，就可以用systemctl启动服务了。

我也遇到同样的问题，这个选项解决了我的问题，thx
