### ISSUE TITLE
NGINX 伪装 大佬这个功能完成了吗

### ISSUE THREAD

**Issue by xnknown** [Jrohy/trojan#35]
大佬 这个功能完成了吗

_Originally posted by @Jungle-Leesin in https://github.com/Jrohy/trojan/issues/29#issuecomment-603658349_

**Comment by Jungle-Leesin** [comment]
弄是弄了，但是我感觉不对

**Comment by Jrohy** [comment]
不清楚伪装是怎么伪装法，加了nginx就是伪装吗，要怎么配置才算。

**Comment by Jungle-Leesin** [comment]
里面的配置不知道，但是网上的trojan原理是将443端口的正常流量转发给nginx进行处理

**Comment by Jrohy** [comment]
不会加nginx的，程序本身就可以代理前端，外部不可控的不会加进来.不像写shell脚本，很多东西可以自己用代码实现的完全没必要引进来

**Comment by Jrohy** [comment]
> 里面的配置不知道，但是网上的trojan原理是将443端口的正常流量转发给nginx进行处理

可能这就是没用到443端口，但web界面还是能用https来访问的原因

**Comment by Jungle-Leesin** [comment]
我差不多弃用trojan了，感觉还项目现在不是太成熟

**Comment by Jrohy** [comment]
@Jungle-Leesin 哪方面呢

**Comment by xnknown** [comment]
大佬们  这里有新的参照 https://www.v2rayssr.com/trojan-panel.html
我看不懂  @Jrohy @Jungle-Leesin

**Comment by xnknown** [comment]
不过面板功能。。。

**Comment by xnknown** [comment]
加油 大佬们!
