### ISSUE TITLE
拉取数据库失败

### ISSUE THREAD

**Issue by 10N99** [Jrohy/trojan#350]
连接远程数据库提示
“sql: expected 7 destination arguments in Scan, not 9”
连接后就出现这个，然后出现创建账户和密码，创建完成后 数据库里可以查看到新的账号，但是看不到数据库里之前的账户，
之前所有服务器拉取都没有问题，新服务器就出现了，是不是最新版本有问题？

**Comment by Jrohy** [comment]
运行trojan upgrade db升级下数据库

**Comment by Jrohy** [comment]
新版本是多两个字段的，是不是trojan程序没升级数据库却升级了，是不是共用数据库了

**Comment by 10N99** [comment]
> 新版本是多两个字段的，是不是trojan程序没升级数据库却升级了，是不是共用数据库了

我的数据库是单独搭在一台服务器上的，所以要怎么办呢？

**Comment by Jrohy** [comment]
所有trojan后台都要升级的，连同一个数据库的，否则就会报错了，数据库升了级trojan管理程序不升级

**Comment by Jrohy** [comment]
可以所有都运行一下trojan updateWeb，可以重复升级的

**Comment by 10N99** [comment]
> 可以所有都运行一下trojan updateWeb，可以重复升级的

非常感谢 现在可以了
