### ISSUE TITLE
关于用户密码管理存在的问题以及优化建议。

### ISSUE THREAD

**Issue by MargaretteMoss** [Jrohy/trojan#351]
1. 本系统单独使用`password`作为密码，所以导致需要每个用户都必须有不一样的密码。这逻辑是有问题的，用户名有排他性可以理解，密码不需要排他性。相比之下，trojan原版使用`username:password`作为密码是合理的，至于客户端需要填`username:password`会导致刚开始使用的时候的混淆，这也是客户端设计上的问题。客户端完全可是设计成用户名和密码框，然后后台合并之后再提交服务器，就可以避免这个混淆，但是这不是服务端管理程序考虑的问题。

2. passShow这个字段不应该存在。数据库不应该明文存储用户的密码这是最基本的要求，这会给用户和系统带来很大的安全隐患。至于管理员需要查看用户密码更是没有必要，密码本就是用户个人的，管理员无权查看。如果用户忘记了密码找管理员重置即可，管理员无需查询现有密码。

**Comment by ancct** [comment]
666！好严谨的思路！

**Comment by Jrohy** [comment]
分享连接都需要原始密码的，而且添加用户只有管理员有权限, 所以管理员肯定知道密码的才能做分享

**Comment by Jrohy** [comment]
密码必须不同是因为trojan本身分不清什么用户的流量，密码相同的情况下，这样就导致流量统计有问题

**Comment by zhucaidan** [comment]
trojan是按密码判断用户的而不是用户名，所以不同密码就相当于用户名，生成连接的时候你看看就知道了

**Comment by MargaretteMoss** [comment]
@Jrohy 感谢回复。

> 分享连接都需要原始密码的，而且添加用户只有管理员有权限, 所以管理员肯定知道密码的才能做分享

好的，既然passShow字段是用于生成共享连接，那第二点就仁者见仁吧。


> 密码必须不同是因为trojan本身分不清什么用户的流量，密码相同的情况下，这样就导致流量统计有问题

第一点我说的应该比较清楚了，可以将数据库中的用户名和密码用冒号拼接在一起作为trojan的密码，这样就可以为每一个用户得到唯一的trojan认证密码。此时共享链接的格式为：`trojan://username:password@domain:port`。[trojan-panel](https://github.com/trojan-gfw/trojan-panel)就是这样实现的，可以参考一下哈。

**Comment by MargaretteMoss** [comment]
> trojan是按密码判断用户的而不是用户名，所以不同密码就相当于用户名，生成连接的时候你看看就知道了

这个我知道，我是准备从trojan-panel升级到这个系统的时候发现不兼容，所以才有此issue。有官方的解决方案可以用还是应该采用官方的解决方案，以保证兼容性，对吧？

**Comment by MargaretteMoss** [comment]
> 666！好严谨的思路！

还行，哈哈。

**Comment by Jrohy** [comment]
问题是trojan分享连接是不带用户名信息的，即使你这边面板用username:password来确认唯一用户，trojan核心还是只读password来确认用户

**Comment by MargaretteMoss** [comment]
@Jrohy 这个问题也解决一下就好了：[web页面子路径问题](https://github.com/Jrohy/trojan-web/issues/10)。只有这样原版trojan-panel才可以无缝切换到您的项目。

**Comment by MargaretteMoss** [comment]
> 问题是trojan分享连接是不带用户名信息的，即使你这边面板用username:password来确认唯一用户，trojan核心还是只读password来确认用户

转个弯，数据库里面存储的base64直接用'username:password'来encoding。

**Comment by Jrohy** [comment]
最好重新搭建，属于不同项目

**Comment by MargaretteMoss** [comment]
> 最好重新搭建，属于不同项目

数据库中的password字段原先保存的是'password‘编码，现在改为'username:password'的编码，对于本项目的实现来说没有难度，这样直接就和原项目兼容了。我的trojan已经运行了1年多了，挺多用户在里面的，弃用的话，得不偿失呀。

**Comment by MargaretteMoss** [comment]
> @Jrohy 这个问题也解决一下就好了：[web页面子路径问题](https://github.com/Jrohy/trojan-web/issues/10)。只有这样原版trojan-panel才可以无缝切换到您的项目。



> 最好重新搭建，属于不同项目

这个issue和是否同一个项目也没有关系。要保证面板的安全性就必须要添加子路径，就必然遭遇这个问题。

**Comment by Jrohy** [comment]
你可以参考wiki加个nginx, /路由给自己丢个静态页面， /xxx路由给web管理程序

**Comment by MargaretteMoss** [comment]
> 你可以参考wiki加个nginx, /路由给自己丢个静态页面， /xxx路由给web管理程序

这个有看到，但是我的主页不是简单的静态页面而是博客，也有资源文件，这样配置导致主页无法正常访问了。

**Comment by MargaretteMoss** [comment]
> > 最好重新搭建，属于不同项目
> 
> 数据库中的password字段原先保存的是'password‘编码，现在改为'username:password'的编码，对于本项目的实现来说没有难度，这样直接就和原项目兼容了。我的trojan已经运行了1年多了，挺多用户在里面的，弃用的话，得不偿失呀。



> 问题是trojan分享连接是不带用户名信息的，即使你这边面板用username:password来确认唯一用户，trojan核心还是只读password来确认用户

[看看这个](https://github.com/trojan-gfw/trojan-panel/blob/95630f48491f9c1a57101a511c513d3b614c4c4a/app/Http/Controllers/Auth/RegisterController.php#L74)

**Comment by Jrohy** [comment]
字段值不是说改就改的，改的必要性，和之前版本的兼容性都要考虑，还要涉及到无感升级

**Comment by MargaretteMoss** [comment]
> 字段值不是说改就改的，改的必要性，和之前版本的兼容性都要考虑，还要涉及到无感升级

如果考虑的是与本项目旧版的兼容性没有问题，那更没必要了。我们仅仅修改了新的`password`字段生成方式，不会导致原有用户失效，因为数据库中存储的数据没有被修改。原有用户仍然使用`password`认证，新添加的用户使用`username:password`认证。原有用户一旦修改密码，其数据库会被修改，以后都将使用`username:password`认证。

**Comment by MargaretteMoss** [comment]
> > 字段值不是说改就改的，改的必要性，和之前版本的兼容性都要考虑，还要涉及到无感升级
> 
> 如果考虑的是与本项目旧版的兼容性的问题，那更没必要了。我们仅仅修改了新的`password`字段生成方式，不会导致原有用户失效，因为数据库中存储的数据没有被修改。原有用户仍然使用`password`认证，新添加的用户使用`username:password`认证。原有用户一旦修改密码，其数据库会被修改，以后都将使用`username:password`认证。

**Comment by Jrohy** [comment]
重点是有没有必要用username:password来认证，你用了这种, trojan核心也不会认的，只会读取password来判断用户

**Comment by MargaretteMoss** [comment]
> 重点是有没有必要用username:password来认证，你用了这种, trojan核心也不会认的，只会读取password来判断用户

会认的，在trojan客户端的密码框里面直接填`username:password`即可。

实现逻辑是这样的：

1. web管理界面申请账户为`username`和`password`的用户。

2. 数据库中保存三个字段：username=username，passShow=password，password=username:password的编码。

3. 客户端的password字段填写username:password。

4. trojan客户端拿到password=username:password，将其编码并发送给服务器。

5. trojan服务端拿到password的编码并不知道其是通过什么编码得到的，只知道与配置文件中的密码的编码不一致，于是将此编码与数据库中的password字段做比较。正好，我们数据库中password字段存储了username:password这个值，所以认证通过。

从始至终，trojan服务端和客户端都不知道数据库是如何保存的密码。顶多客户端看这个密码里面有一个:，但是trojan的密码不会认为:是非法字符。

**Comment by Jrohy** [comment]
确实可以，只是界面写着密码(原始密码)， 别人手填此字段到客户端可能会用不了，隐藏掉改字段又改变用户习惯了

**Comment by MargaretteMoss** [comment]
> 确实可以，只是界面写着密码(原始密码)， 别人手填此字段到客户端可能会用不了，隐藏掉改字段又改变用户习惯了

这个问题与服务器和服务器管理软件都没有关系。这在于，现有的客户端均没有提供两个框让用户分别输入username和password，然后后台合并成username:password的逻辑。但是咱不能避重就轻对吧？

在客户端没有升级支持面板的逻辑之前，唯一的解决方案是在面板上提醒用户密码框该如何输入。

例如用高亮语法加上这样一个提醒：客户端配置文件中的密码填写注册的用户信息："username:password"。

**Comment by MargaretteMoss** [comment]
> 确实可以，只是界面写着密码(原始密码)， 别人手填此字段到客户端可能会用不了，隐藏掉改字段又改变用户习惯了

现在客户端基本都支持从剪切板导入链接了，其实也可以隐藏掉该字段，直接给trojan链接即可。

**Comment by MargaretteMoss** [comment]
> 添加用户只有管理员有权限

这个逻辑其实也可以有优化的空间，可以让用户自己申请账户，但是默认情况下quota为0。用户完成注册之后通知管理员审核，管理员确认这个账户是自己授权注册的之后，将quota改为正值或-1即可。
