### ISSUE TITLE
登录一直提示授权失败，无法登录

### ISSUE THREAD

**Issue by VaterZ** [Jrohy/trojan#352]
登录一直提示授权失败，无法登录

**Comment by Jrohy** [comment]
密码错误了吧，忘记密码可以去输入trojan命令web管理那里重置admin密码

**Comment by om0504** [comment]
我share下經驗
OS:Debian 9.11
先安裝了trojan再裝BBRplus，
剛裝完，使用正常，但過了幾小時後，web會不時跳出授權失敗，此時trojan還能正常使用
再過一段時間(一小時內)，web完全登不進，然後連VPS也登不進，VPS宣布陣亡

重新來過，先裝BBRplus再裝trojan
已經兩小時，登進登出，reflash，都沒問題

**Comment by youjiajia-wc** [comment]
> 登录一直提示授权失败，无法登录

我也遇到了这个情况，但是瞎折腾解决了，给你做个参考；
Ubentu 18.04系统，因为系统设置的字体有问题。重新设置了字体(命令不说了，不知道我们系统是不是一样，情况也不知道是不是一样)，重启，再清空admin的密码文件夹 rm -rf /var/lib/trojan-manager/*
再设置admin的密码就行了。
