### ISSUE TITLE
用户无法登录界面

### ISSUE THREAD

**Issue by jackxin900** [Jrohy/trojan#354]
用户无法使用用户名和密码登录系统，提示“授权失败，请重新登录”

**Comment by Jrohy** [comment]
估计密码错误了，如果是admin密码运行命令trojan，web管理那里重置下密码

**Comment by jackxin900** [comment]
admin账户是正常的，但是所有用户账户无法登录了。version: v2.9.7.1

**Comment by Jrohy** [comment]
确实，我明天修复下

**Comment by Jrohy** [comment]
2972已修复, 升级下

**Comment by jackxin900** [comment]
谢谢，已升级测试登录成功！
