### ISSUE TITLE
安装数据库卡主了

### ISSUE THREAD

**Issue by po888375** [Jrohy/trojan#356]
docker run --name trojan-mariadb --restart=always -p 22276:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=eLBpq -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
Unable to find image 'mariadb:10.2' locally
10.2: Pulling from library/mariadb
f22ccc0b8772: Pulling fs layer
3cf8fb62ba5f: Pulling fs layer
e80c964ece6a: Pulling fs layer
12260b0e97bc: Pulling fs layer
1e2a55695dfa: Pulling fs layer
9b965e29cfef: Pulling fs layer
013e2bd9bdd9: Pulling fs layer
c4bd8c33d274: Pulling fs layer
ebc8e1642af6: Pulling fs layer
ec0cf031acec: Pulling fs layer
6e6de340383f: Pulling fs layer
e1a0c815551a: Pulling fs layer
aa568cd01c08: Pulling fs layer
12260b0e97bc: Waiting
1e2a55695dfa: Waiting
9b965e29cfef: Waiting
013e2bd9bdd9: Waiting
c4bd8c33d274: Waiting
ebc8e1642af6: Waiting
ec0cf031acec: Waiting
6e6de340383f: Waiting
e1a0c815551a: Waiting
aa568cd01c08: Waiting
3cf8fb62ba5f: Verifying Checksum
3cf8fb62ba5f: Download complete
e80c964ece6a: Verifying Checksum
e80c964ece6a: Download complete
12260b0e97bc: Verifying Checksum
12260b0e97bc: Download complete
1e2a55695dfa: Verifying Checksum
1e2a55695dfa: Download complete
9b965e29cfef: Retrying in 5 seconds
013e2bd9bdd9: Verifying Checksum
013e2bd9bdd9: Download complete
9b965e29cfef: Retrying in 4 seconds
9b965e29cfef: Retrying in 3 seconds
9b965e29cfef: Retrying in 2 seconds
9b965e29cfef: Retrying in 1 second
9b965e29cfef: Verifying Checksum
9b965e29cfef: Download complete
c4bd8c33d274: Verifying Checksum
c4bd8c33d274: Download complete
ebc8e1642af6: Verifying Checksum
ebc8e1642af6: Download complete
ec0cf031acec: Verifying Checksum
ec0cf031acec: Download complete
e1a0c815551a: Verifying Checksum
e1a0c815551a: Download complete
aa568cd01c08: Verifying Checksum
aa568cd01c08: Download complete

**Comment by Jrohy** [comment]
拉不了镜像，国内VPS?还是网络比较差

**Comment by po888375** [comment]
> 拉不了镜像，国内VPS?还是网络比较差

甲骨文韩国vps，网络能跑满50m

**Comment by Jrohy** [comment]
可以先手动下载镜像先， docker pull mariadb:10.2, 下载成功再运行docker run

**Comment by po888375** [comment]
> 可以先手动下载镜像先， docker pull mariadb:10.2, 下载成功再运行docker run

下载失败了，真的是网络问题，docker下载超级慢

**Comment by Jrohy** [comment]
配置下镜像源试试，参考下: https://github.com/Jrohy/k8s-install/blob/master/install.sh#L217

**Comment by po888375** [comment]
> 配置下镜像源试试，参考下: https://github.com/Jrohy/k8s-install/blob/master/install.sh#L217

谢谢，换了源之后就正常了

**Comment by CNBOY239** [comment]
怎么更换的，兄弟？我在你发出问题3个小时后，也遇到同样麻烦了
