### ISSUE TITLE
数据库导入提示 expiryDate 值 Null

### ISSUE THREAD

**Issue by trojson** [Jrohy/trojan#357]
嗨 Jrohy 数据库通过导出 再导入后提示 expiryDate 数值为 Null 看了下是原来没有设置逾期日期的项目（就是原默认无限制）需要手动填写数据库数值后才能 面板刷新才看到数据，要不就一直提示错误。操作前后面板 版本是最新的 V2.9.7.2

**Comment by Jrohy** [comment]
下个版本修复下

**Comment by trojson** [comment]
> 下个版本修复下

谢谢 Jrohy

**Comment by Jrohy** [comment]
测试了没发现有问题，导出的sql insert语句expiryDate为空字符串

**Comment by Jrohy** [comment]
检查下导出的sql insert语句里是不是都是空字符串(不是Null)

**Comment by trojson** [comment]
> 检查下导出的sql insert语句里是不是都是空字符串(不是Null)

嗨 Jrohy  我是通过 Navicat 15 for MySQL 登录数据库导出 一个 txt 文本，同样方法 登录到新的数据库 导入，看了下文本里面没有设置期限的 是没有赋值 （空白字段）

**Comment by Jrohy** [comment]
导出不需要用其他软件的，只需要trojan export xxx即可导出

**Comment by trojson** [comment]
> 导出不需要用其他软件的，只需要trojan export xxx即可导出， 用其他软件导出不保证兼容性

原来都自带 导出导入了，应该是兼容性问题导致，晚点回去拿另一个试试看，谢谢 Jrohy 新年元旦快乐，身体健康。
