### ISSUE TITLE
更新版本到了version: v2.9.5，设置了每月1号重置流量，但是没有生效，请问下是怎么回事？

### ISSUE THREAD

**Issue by rickartmiriam** [Jrohy/trojan#358]
更新版本到了version: v2.9.5，设置了每月1号重置流量，但是没有生效，请问下是怎么回事？

**Comment by Jrohy** [comment]
得设置了到期日期，且没有停用的用户(流量上限为0)才会重置流量

**Comment by rickartmiriam** [comment]
不好意思，还是没有理解您的意思，我设置了每个trojan用户的限制流量，也设置了每月1号自动清空重置每个用户的总流量，但是发现每月1号并没有重置每个用户的总流量来达到重新统计下个月流量的目的。要去手动全选重置来清空上个月所有用户的总流量。
![QQ截图20210102011439](https://user-images.githubusercontent.com/66523919/103443239-31d95a00-4c98-11eb-89f8-f346a14f6ee9.png)
![QQ截图20210102011114](https://user-images.githubusercontent.com/66523919/103443241-330a8700-4c98-11eb-82c2-015c6ca8711c.png)
![QQ截图20210102011035](https://user-images.githubusercontent.com/66523919/103443242-33a31d80-4c98-11eb-8c1f-2c440c91d16c.png)

**Comment by rickartmiriam** [comment]
不好意思，还是没有理解您的意思，我设置了每个trojan用户的限制流量，也设置了每月1号自动清空重置每个用户的总流量，但是发现每月1号并没有重置每个用户的总流量来达到重新统计下个月流量的目的。要去手动全选重置来清空上个月所有用户的总流量。
![QQ截图20210102012404](https://user-images.githubusercontent.com/66523919/103443353-787b8400-4c99-11eb-8f00-b1f389d248f0.png)
![QQ截图20210102012441](https://user-images.githubusercontent.com/66523919/103443355-7c0f0b00-4c99-11eb-9c9c-6908297d1aa4.png)
![QQ截图20210102012524](https://user-images.githubusercontent.com/66523919/103443357-7dd8ce80-4c99-11eb-83be-308b983ee98b.png)

**Comment by Jrohy** [comment]
设置一下到期日期才行

**Comment by Jrohy** [comment]
如果想账号一直能用，你可以设置大一点到期日期的天数，比如设个1000天

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/103448757-e4311180-4cd8-11eb-824a-8ad5cbd0bf45.png)

**Comment by trojson** [comment]
意思是分配到每个用户的的期限必须要设定一个值，要不整体赋值日期到期自动清空流量不会生效?

**Comment by Jrohy** [comment]
是的只对设置了到期日期的才会重置流量

**Comment by rickartmiriam** [comment]
哦，明白了，谢谢。

**Comment by ckbkdj** [comment]
哪里有流量重置日.我没找到
