### ISSUE TITLE
在centos 7下面一键安装，也没报错，为什么都打不开web

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#36]
打不开web管理界面。也不报错。但是，命令行管理界面，都能正常运行。

**Comment by Jrohy** [comment]
看下web服务状态 ，systemctl status trojan-web, 没启动的启动下

**Comment by totodata** [comment]
[root@ecs-Fwj ~]# systemctl status trojan-web
● trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-03-31 12:35:51 CST; 3s ago
     Docs: https://github.com/Jrohy/trojan
 Main PID: 24426 (trojan)
    Tasks: 5
   Memory: 8.4M
   CGroup: /system.slice/trojan-web.service
           └─24426 /usr/local/bin/trojan web


看服务，都正常的。
我是用二级域名安装的，用ip访问，能登陆web，输入域名就不行了。

**Comment by Jrohy** [comment]
trojan能用不

**Comment by totodata** [comment]
trojan也不能访问，http也不行。可能是那里问题呢。

**Comment by Jrohy** [comment]
证书都申请到了吗，systemctl status trojan看下状态

**Comment by totodata** [comment]
看着状态，很正常。应该是证书没正常。证书安装在哪个目录，我去看看。
[root@ecs-Fwj ~]# systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-03-31 13:02:38 CST; 1ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 27764 (trojan)
    Tasks: 1
   Memory: 120.0K
   CGroup: /system.slice/trojan.service
           └─27764 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

**Comment by totodata** [comment]
有没有电报交流群呢。方便截图。

**Comment by Jrohy** [comment]
申请的域名能解析到服务器ip吗

**Comment by Jrohy** [comment]
申请的域名能解析到服务器ip吗

**Comment by totodata** [comment]
域名没问题的，在安装这个程序之前，一直解析到这个服务器IP，正常使用的trojan的。我是重置了一个新环境，来安装这个面板程序的。

**Comment by totodata** [comment]
[Tue Mar 31 13:37:40 CST 2020] Installing from online archive.
[Tue Mar 31 13:37:40 CST 2020] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue Mar 31 13:37:59 CST 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 52
[Tue Mar 31 13:37:59 CST 2020] Download error.
bash: /root/.acme.sh/acme.sh: No such file or directory
重启trojan成功!

**Comment by totodata** [comment]
这个下载不成功。

**Comment by Jrohy** [comment]
申请证书可能没成功, 手动安装试下`curl  https://get.acme.sh | sh
`

**Comment by totodata** [comment]
这次换了一个顶级域名安装，通过域名能访问web管理后台了，但是，trojan服务好像没有成功。

[root@ecs-Fwj ~]# systemctl status trojan-web
● trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-03-31 13:49:53 CST; 3s ago
     Docs: https://github.com/Jrohy/trojan
 Main PID: 13728 (trojan)
    Tasks: 5
   Memory: 6.4M
   CGroup: /system.slice/trojan-web.service
           └─13728 /usr/local/bin/trojan web

Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] POST   /auth/refresh_token       --> github.com/appl...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] GET    /trojan/user              --> trojan/web.user...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] POST   /trojan/user              --> trojan/web.user...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] DELETE /trojan/user              --> trojan/web.user...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] POST   /trojan/data              --> trojan/web.data...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] DELETE /trojan/data              --> trojan/web.data...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] GET    /common/version           --> trojan/web.comm...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] GET    /common/serverInfo        --> trojan/web.comm...lers)
Mar 31 13:49:53 ecs-Fwj trojan[13728]: [GIN-debug] POST   /common/loginInfo         --> trojan/web.comm...lers)
Mar 31 13:49:55 ecs-Fwj trojan[13728]: [GIN-debug] Listening and serving HTTP on :80
Hint: Some lines were ellipsized, use -l to show in full.
[root@ecs-Fwj ~]# systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-03-31 13:50:18 CST; 1s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 13950 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 13950 (code=exited, status=1/FAILURE)

Mar 31 13:50:18 ecs-Fwj systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
Mar 31 13:50:18 ecs-Fwj systemd[1]: Unit trojan.service entered failed state.
Mar 31 13:50:18 ecs-Fwj systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
你先停了trojan systemctl stop trojan, 再直接这样运行/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json 看下报什么内容

**Comment by totodata** [comment]
重置系统再次一键安装，用了顶级域名，终于正常了。

有个问题，web后台创建的用户，两个不同用户，如果使用的密码相同，系统怎么区分的？因为trojan客户端配置的时候，没有可以定义用户名的地方。

**Comment by Jrohy** [comment]
https://trojan-gfw.github.io/trojan/authenticator 不知道是不是遇到第一个的就匹配上的。可以自己测下

**Comment by totodata** [comment]
要是web可以开放给普通用户注册，管理员在后台进行流量和有效期的设定，就完美了。
现在的流量，是总量了，用到什么时候完了，就完了对吧。

**Comment by Jrohy** [comment]
应该不会开放给普通用户注册，不是机场。只能管理员来增加用户，这个用户既是trojan用户也是web页面的普通用户

**Comment by LeoJiang1988** [comment]
应该是trojan-web占用了80端口，导致证书申请失败。先停下trojan-web  systemctl stop trojan-web. 然后申请证书，就解决了

**Comment by forjustice** [comment]
执行systemctl start trojan-web 即可启动管理页面
