### ISSUE TITLE
web 無法管理用戶

### ISSUE THREAD

**Issue by om0504** [Jrohy/trojan#360]
2021/1/5安裝，debian 9
安裝過程無報錯
但webui沒有用戶管理功能，僅有管理員帳號，該帳號正常工作
但無法從web新增/刪除用戶
從command中增加的用戶在web中也無法看到

![issue](https://user-images.githubusercontent.com/30120929/103609601-28324980-4f59-11eb-8302-556d15a25c9b.PNG)
![issue2](https://user-images.githubusercontent.com/30120929/103609656-48620880-4f59-11eb-9bd3-ca142bbb4622.PNG)

**Comment by Jrohy** [comment]
要用admin用户登录才有权限管理用户的

**Comment by om0504** [comment]
嗯，我是白癡，請close這issue，謝謝。
