### ISSUE TITLE
请问www root在什么位置？

### ISSUE THREAD

**Issue by bluevisor** [Jrohy/trojan#362]
我想放几个文件在上面用来下载，不知该放到哪个目录。

**Comment by Jrohy** [comment]
在二进制文件里面

**Comment by l3617** [comment]
> 在二进制文件里面

nat鸡能用这个脚本吗，可以修改web端口和传输443吗

**Comment by Jrohy** [comment]
修改web端口参考wiki, 改443端口就改trojan的配置文件

**Comment by totodata** [comment]
修改了后台admin访问地址，然后要配置nginx，装个web，怎么处理。

**Comment by Jrohy** [comment]
@totodata 参考wiki安装nginx和改端口
