### ISSUE TITLE
Web后台能不能增加一个导入导出功能。方便备份数据。

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#364]
Web后台能不能增加一个导入导出功能。经常重新安装更新版本，需要这种功能。

**Comment by Jrohy** [comment]
trojan export /trojan import 就是导入导出sql的

**Comment by totodata** [comment]
命令行操作还是麻烦了一点，整合在web后台，就好了。

**Comment by rickartmiriam** [comment]
> trojan export /trojan import 就是导入导出sql的

这个功能该怎么用？假设我要导出到D盘的PN文件夹里，该怎么输入后面的盘符？
