### ISSUE TITLE
证书到期后如何更新？

### ISSUE THREAD

**Issue by chinawzxsoft** [Jrohy/trojan#365]
证书到期后如何更新？我SSH中TROJAN-3安装管理-2证书申请后依然提示证书无效

**Comment by Jrohy** [comment]
如果用let's encrypt证书， acme.sh有自动续签的，你看下crontab -l就能看到定时任务了

**Comment by ancct** [comment]
SSH申请证书：trojan tls
如不行报错，那么：
1：停止NG: systemctl stop nginx
2：申请证书：trojan tls

**Comment by rickartmiriam** [comment]
> 如果用let's encrypt证书， acme.sh有自动续签的，你看下crontab -l就能看到定时任务了

:~# crontab -l
0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web

出来这个，意思是定时任务没有成功？每次隔三个月我要手动去更新一次才行。

**Comment by Jrohy** [comment]
这是定时任务规则 @rickartmiriam ，已经默认有设置定时任务了

**Comment by LoveForeverBoa** [comment]
> 
> 
> 这是定时任务规则 @rickartmiriam ，已经默认有设置定时任务了

膜拜大佬。。。  真方便啊

**Comment by LoveForeverBoa** [comment]
> 
> 
> 如果用let's encrypt证书， acme.sh有自动续签的，你看下crontab -l就能看到定时任务了

膜拜大佬。。。 真方便啊

**Comment by rickartmiriam** [comment]
> 这是定时任务规则 @rickartmiriam ，已经默认有设置定时任务了
但是为什么每次还是要我手动去弄，不然就用不了，显示SSL 证书过期。

**Comment by Jrohy** [comment]
手动运行下后面命令看看有没有报错就知道了

**Comment by Jrohy** [comment]
手动运行下后面命令看看有没有报错就知道了

**Comment by janeyee110** [comment]
> > 如果用let's encrypt证书， acme.sh有自动续签的，你看下crontab -l就能看到定时任务了
> 
> :~# crontab -l
> 0 15 * * * systemctl stop trojan-web; "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null; systemctl start trojan-web
> 
> 出来这个，意思是定时任务没有成功？每次隔三个月我要手动去更新一次才行。

遇到同样的问题，我是手动更新解决的
systemctl stop trojan-web
acme.sh --renew-all --force
reboot
