### ISSUE TITLE
搬瓦工DC3机房贼慢

### ISSUE THREAD

**Issue by 907904228** [Jrohy/trojan#366]
请问大佬，搬瓦工50美元DC3的机房，开了BBR加速，为啥看YouTube才几千kbps。。。

还比不上我阿里云香港的速度，有啥排查问题的方法不

以前搬瓦工用SSR还挺快的，现在咋这么拉胯

**Comment by Jrohy** [comment]
试试换成trojan-go有没有提速

**Comment by ancct** [comment]
> 请问大佬，搬瓦工50美元DC3的机房，开了BBR加速，为啥看YouTube才几千kbps。。。
> 
> 还比不上我阿里云香港的速度，有啥排查问题的方法不
> 
> 以前搬瓦工用SSR还挺快的，现在咋这么拉胯

bwh现在最快的是日本的软银，60元一个月，看油管能达到15W，香港太贵用不起。
![微信截图_20201225110742](https://user-images.githubusercontent.com/38551833/104534018-737de380-564e-11eb-922d-b5978631c348.png)

**Comment by ancct** [comment]
> > 请问大佬，搬瓦工50美元DC3的机房，开了BBR加速，为啥看YouTube才几千kbps。。。
> > 还比不上我阿里云香港的速度，有啥排查问题的方法不
> > 以前搬瓦工用SSR还挺快的，现在咋这么拉胯
> 
> bwh现在最快的是日本的软银，60元一个月，看油管能达到15W，香港太贵用不起。你换一下机房吧，后台能换机房，换到JP。
> ![微信截图_20210114095922](https://user-images.githubusercontent.com/38551833/104534545-73321800-564f-11eb-90b1-6604078747bb.png)
> 
![微信截图_20210114084710](https://user-images.githubusercontent.com/38551833/104534689-b42a2c80-564f-11eb-9005-870a3444fe1e.png)

**Comment by Houtx** [comment]
> 试试换成trojan-go有没有提速

支持一键切换trojan-go么

**Comment by ancct** [comment]
> > 试试换成trojan-go有没有提速
> 
> 支持一键切换trojan-go么
更新到最新版，就能切换了。

![微信截图_20210114152439](https://user-images.githubusercontent.com/38551833/104557738-b3f45600-567c-11eb-9cd7-de02b8969eb1.png)

**Comment by Houtx** [comment]
切换之后直接不能代理了....




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jrohy/trojan"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月14日(星期四) 下午3:26
收件人:&nbsp;"Jrohy/trojan"<trojan@noreply.github.com&gt;;
抄送:&nbsp;"Hou"<97028415@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Jrohy/trojan] 搬瓦工DC3机房贼慢 (#366)





   
试试换成trojan-go有没有提速
  
支持一键切换trojan-go么
 更新到最新版，就能切换了。

**Comment by Houtx** [comment]
![image](https://user-images.githubusercontent.com/17922172/104664913-5ce99200-570b-11eb-97a7-76c6463d2f23.png)
切换到trojan-go 代理直接不能用了, 还要设置什么么?
@Jrohy @ancct

**Comment by Jrohy** [comment]
@Houtx 是不是有改过trojan-web端口

**Comment by Jrohy** [comment]
检查下/usr/local/etc/trojan/config.json配置文件，如果改过端口就试下将配置文件的remote_port端口改成对应端口试试

**Comment by fengmikaelson** [comment]
> > > 请问大佬，搬瓦工50美元DC3的机房，开了BBR加速，为啥看YouTube才几千kbps。。。
> > > 还比不上我阿里云香港的速度，有啥排查问题的方法不
> > > 以前搬瓦工用SSR还挺快的，现在咋这么拉胯
> > 
> > 
> > bwh现在最快的是日本的软银，60元一个月，看油管能达到15W，香港太贵用不起。你换一下机房吧，后台能换机房，换到JP。
> > ![微信截图_20210114095922](https://user-images.githubusercontent.com/38551833/104534545-73321800-564f-11eb-90b1-6604078747bb.png)
> 
> ![微信截图_20210114084710](https://user-images.githubusercontent.com/38551833/104534689-b42a2c80-564f-11eb-9005-870a3444fe1e.png)

看了下后台也没有jp的切换啊，都是美国的不是。
![微信截图_20210115095023](https://user-images.githubusercontent.com/10394327/104670608-23b71f00-5717-11eb-9d34-3a5cfef3d248.png)

**Comment by Houtx** [comment]
> 检查下/usr/local/etc/trojan/config.json配置文件，如果改过端口就试下将配置文件的remote_port端口改成对应端口试试

![image](https://user-images.githubusercontent.com/17922172/104672790-68dd5000-571b-11eb-96fc-f6f67e4cdd5b.png)
没改过端口 @Jrohy

**Comment by Houtx** [comment]
我机房里也是全美国, 19刀一年买的
