### ISSUE TITLE
可否增加一个屏蔽指定网站的功能

### ISSUE THREAD

**Issue by zhucaidan** [Jrohy/trojan#367]
因为担心连接trojan的人上一些敏感网站

可否增加一个屏蔽域名功能？

当客户端请求某个网站以后直接不返回数据drop或者解析空IP返回

**Comment by zhucaidan** [comment]
比如日志处：requested connection to twitter.com
当遇到这条信息的时候，直接不返回数据给客户端return 444这样

**Comment by Jrohy** [comment]
只能trojan核心才能做这种功能

**Comment by zhucaidan** [comment]
> 只能trojan核心才能做这种功能

核心支持吗？我想试一下看看。。

**Comment by ancct** [comment]
> > 只能trojan核心才能做这种功能
> 
> 核心支持吗？我想试一下看看。。

假如有了这个功能，我第一时间就把百度360给屏蔽掉！开着代理用百度看腾讯视频也是没谁了。

**Comment by zhucaidan** [comment]
> > > 只能trojan核心才能做这种功能
> > 
> > 
> > 核心支持吗？我想试一下看看。。
> 
> 假如有了这个功能，我第一时间就把百度360给屏蔽掉！开着代理用百度看腾讯视频也是没谁了。

同+1 总有些ZZ用节点搞事情

**Comment by Tim-tse** [comment]
同求...

**Comment by zhucaidan** [comment]
找到了一个贴切描述“审计系统”不知道可否实现：
![QQ截图20210130055822](https://user-images.githubusercontent.com/47970938/106358323-77ea0380-62c0-11eb-9a0a-73d05fd3289b.png)

**Comment by zhucaidan** [comment]
> 只能trojan核心才能做这种功能
大神不知道这两种会不会生效呢？能不能提供下思路融合进面板审计功能。。
https://doubibackup.com/3--didfb-3.html
https://doubibackup.com/tfma58rb.html
