### ISSUE TITLE
用户名大小写的bug

### ISSUE THREAD

**Issue by chasenn** [Jrohy/trojan#368]
目前两个用户出现这个问题，第一次没在意，第二次我远程看了下确实有这个问题，我尝试清空他浏览器缓存、改密码都无效，最后发现是首字母大小写的问题，账号创建时首字母大写，但登陆用小写方式登陆就在用户列表出现所有用户，看了下代码 是用户列表接口判断有问题

**Comment by Jrohy** [comment]
确实存在，下个版本修复下

**Comment by Jrohy** [comment]
2.9.7.4已修复，感谢反馈

**Comment by chasenn** [comment]
> 2.9.7.4已修复，感谢反馈

辛苦了,不过我发现这样改还会有一个问题，假如账号登录的情况下管理员删了该账户，该用户访问人员接口的时候还是会获取到所有人员

**Comment by Jrohy** [comment]
@chasenn 下个版本修复

**Comment by Jrohy** [comment]
@chasenn 2.9.7.5已修复，更新下
