### ISSUE TITLE
BBR魔改版启动失败

### ISSUE THREAD

**Issue by 907904228** [Jrohy/trojan#369]
大佬您好，用的是您推荐的BBR链接，但只有BBR和BBR PLUS能启动成功，魔改版不行。截图如下

系统debian9，搬瓦工

请问是不是我哪里设置错了哈哈

![QQ20210115-112454](https://user-images.githubusercontent.com/24412137/104677613-a98d9700-5724-11eb-998d-5baefe4192c8.png)
![QQ20210115-112718](https://user-images.githubusercontent.com/24412137/104677626-b27e6880-5724-11eb-9502-62ae8e20f5c2.png)

**Comment by Jrohy** [comment]
这个得自己测试了，我也经验不多
