### ISSUE TITLE
[希望] 後續有機會生成 dockerfile的模板 json嗎？

### ISSUE THREAD

**Issue by vlpeng** [Jrohy/trojan#37]
您好，後續會有計畫生成這個嗎？
https://raw.githubusercontent.com/jrohy/dockerfile/master/templates.json

謝謝

**Comment by Jrohy** [comment]
有什么用呢不太了解这个

**Comment by vlpeng** [comment]
就方便可以在帶起 portainer > setting > App Templates > 裡面去調用大大的神作 XD

**Comment by Jrohy** [comment]
直接用docker run 就好 @vlpeng

**Comment by vlpeng** [comment]
好的 @Jrohy
