### ISSUE TITLE
是否存在挖矿后门？谷歌云关停了我的虚拟机

### ISSUE THREAD

**Issue by biowr** [Jrohy/trojan#373]
![image](https://user-images.githubusercontent.com/31007267/106555993-961e6080-6559-11eb-817f-f91e1068b79e.png)
截图如下，不知道还能不能接着用了？

**Comment by Jrohy** [comment]
不放心可以自己编译，前后端源码都是公开的

**Comment by Jrohy** [comment]
不想常驻服务的话也可以systemctl stop trojan-web; systemctl disable trojan-web停了web服务，这样就只有命令行可使用，没有常驻后台了(当然每月流量重置等后台功能也会停了)

**Comment by biowr** [comment]
了解，可能谷歌云误伤，识别流量有问题，谢谢解答
