### ISSUE TITLE
请求增加限速功能

### ISSUE THREAD

**Issue by gn73679** [Jrohy/trojan#375]
有些用户都一直滥用，真不知该说什么
建议 大佬 增加限速功能

**Comment by Jrohy** [comment]
trojan不支持

**Comment by ancct** [comment]
> 有些用户都一直滥用，真不知该说什么
> 建议 大佬 增加限速功能

限制流量不就完事儿了……开启BBR的VPS，就算是滥用也能保证其他人的带宽啊……
