### ISSUE TITLE
搭建了N次登录后台管理只有刷新那个按钮其他的比如添加新用户限制新用户流量什么的操作都没有

### ISSUE THREAD

**Issue by zjqzjq110** [Jrohy/trojan#376]
搭建了N次登录后台管理只有刷新那个按钮其他的比如添加新用户限制新用户流量什么的操作都没有

**Comment by zjqzjq110** [comment]
除了自己本来的一个用户以外就是一个刷新，没有新增加用户的按钮也没有限制流量等那些操作的按钮

**Comment by Jrohy** [comment]
用admin用户登录才有
