### ISSUE TITLE
不变域名，更改DNS后还能正常使用吗

### ISSUE THREAD

**Issue by 907904228** [Jrohy/trojan#377]
请教大佬，我想从阿里云轻量服务器换成腾讯云轻量服务器，不想重新搭一遍Trojan，可以直接改DNS吗

**Comment by Jrohy** [comment]
你可以导出sql备份还原，用原来的域名绑定新的服务器

**Comment by rickartmiriam** [comment]
导出SQL会了，但是不知道怎么导入，该导入到那个目录下面？请大神帮忙解答下。
