### ISSUE TITLE
能否安装caddy2

### ISSUE THREAD

**Issue by gcphym** [Jrohy/trojan#378]
请问这个脚本和caddy可以共存吗 想用caddy反代进行伪装 但是不知道443端口会不会和trojan冲突

**Comment by gcphym** [comment]
我是这样配置caddyfile的

mydomain:80 {
reverse_proxy http://amazon.com {
    header_up Host amazon.com
    }
}
这样trojan正常使用的情况下 访问mydomain能正常跳转到amazon,不知道这样能不能起到伪装效果，求指教...

**Comment by MichaelPan1026** [comment]
想请问一下如果用这种方法的话，那`/admin`页面的反代配置怎么写？
