### ISSUE TITLE
问个小白问题：域名指向trojan面板，那伪装网站在哪里？

### ISSUE THREAD

**Issue by longmanqhx** [Jrohy/trojan#379]
这种翻墙方式不需要一个伪装的页面吗？只要有域名起到混淆作用就可以了？反正GFW不会点开每个网址去检查。所以无需担心是吗？

**Comment by Jrohy** [comment]
你可以参考wiki加个nginx， 默认的'/'路由给其他伪装页面

**Comment by longmanqhx** [comment]
谢谢！
“假定请求web后台的访问路径为/admin, 启动端口为81，这里提供基本的nginx proxy_pass例子仅供参考:”

这个web后台的访问路径是什么？

**Comment by longmanqhx** [comment]
> 你可以参考wiki加个nginx， 默认的'/'路由给其他伪装页面

谢谢！
“假定请求web后台的访问路径为/admin, 启动端口为81，这里提供基本的nginx proxy_pass例子仅供参考:”

这个web后台的访问路径是什么？

**Comment by Jrohy** [comment]
就是https://域名/admin
