### ISSUE TITLE
Vue静态资源请求的CDN有点儿慢

### ISSUE THREAD

**Issue by juilletVent** [Jrohy/trojan#381]
观察了一下后台面板的Vue相关静态资源走的unpkg.com，着实有点儿慢啊，主体响应300ms以内，这几个Vue的静态资源，最差的情况能到10多秒...大佬有空能不能提提供本地部署静态资源，或者更换好一点儿的CDN啊

感谢，Luv you

**Comment by Jrohy** [comment]
你升级下新版，旧的版本才是unpkg.com cdn源，新的是cdn.jsdelivr.net

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan-web/blob/master/public/index.html

**Comment by juilletVent** [comment]
使用工具自带的更新，更新到2.8.5了，仍然请求的unpkg.com，最新版只能重新安装吗？覆盖安装是否安全？

~~~
Version: v2.8.5

BuildDate: 20200731-0917

GoVersion: go1.14 linux/amd64

GitVersion: 4492d539935e2170611157ee4307145af8e76f0a

TrojanVersion: v0.8.2

TrojanRunTime: 00:15
~~~

**Comment by Jrohy** [comment]
trojan updateWeb这样更新么

**Comment by juilletVent** [comment]
不好意思，是我的问题，看到有独立的Web管理端更新命令了，更新之后CDN已切换，快多了，非常感谢！

**Comment by ckbkdj** [comment]
> 不好意思，是我的问题，看到有独立的Web管理端更新命令了，更新之后CDN已切换，快多了，非常感谢！

能套CF 上网?

**Comment by juilletVent** [comment]
> > 不好意思，是我的问题，看到有独立的Web管理端更新命令了，更新之后CDN已切换，快多了，非常感谢！
> 
> 能套CF 上网?

Trojan本身对外的协议流就是HTTPS流，自然是可以走CF的，但是现在CF的效果...
