### ISSUE TITLE
用户名的作用？

### ISSUE THREAD

**Issue by QQ794763733** [Jrohy/trojan#382]
因为连接只需要密码，如果用户名只作为一个备注的话，是否可以添加对中文的支持。

**Comment by Jrohy** [comment]
这是默认mysql字符集不是utf8导致插入不了中文，我看看现有的和全新安装的可以怎么处理

**Comment by QQ794763733** [comment]
我看到安装的时候使用docker安装的，看是否允许容器的时候指定字符集。
建表的时候也可以直接表字符集或者列字符集。
再不济的话脚本可否写exec进入容器去改。

**Comment by QQ794763733** [comment]
谢谢回复。

**Comment by Jrohy** [comment]
2.9.8以支持用户名为中文， 运行`trojan updateWeb`升级下就支持了

**Comment by Amos-Dan** [comment]
> 这是默认mysql字符集不是utf8导致插入不了中文，我看看现有的和全新安装的可以怎么处理

所以大佬是怎么处理的？

**Comment by Amos-Dan** [comment]
这个太给力了。
> 2.9.8以支持用户名为中文， 运行`trojan updateWeb`升级下就支持了

**Comment by Amos-Dan** [comment]
另外，这个username的设置规则是啥啊？长度？字母数字字符的支持？

**Comment by Jrohy** [comment]
好像没什么限制吧，只要和已有的不要重复就行
