### ISSUE TITLE
使用脚本成功安装后登录网页出现 Error 521

### ISSUE THREAD

**Issue by eren997** [Jrohy/trojan#384]
作者你好！

我最近在使用脚本成功安装后登录网页出现 Error 521 错误。安装过程很顺利，提示安装成功，但是登录域名地址出现 Error 521，无法进入管理面板。之前使用这款脚本能正常使用，但是后来域名过期了，于是在更换新的域名之后就出现这样的错误。 

试过重启过新建vps，但都不行。使用其他翻墙脚本能正常运行翻墙程序。

感谢解答！
![image](https://user-images.githubusercontent.com/70304031/109842964-90658900-7c85-11eb-99c2-3b8ab2aa6d1f.png)

<img width="787" alt="Snipaste_2021-03-04_01-03-08" src="https://user-images.githubusercontent.com/70304031/109842826-6dd37000-7c85-11eb-8a86-fd8748fe2ca6.png">

**Comment by Jrohy** [comment]
用ip直接访问能登录进页面吗，安装了的trojan能否翻

**Comment by eren997** [comment]
输入ip可以进入登录页面，无法翻墙。
查看日志出现如下错误，证书那些已经在ssl申请了，已经验证匹配。

‘Welcome to trojan 1.16.0
[2021-03-08 09:06:28] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2021-03-08 09:06:28] [FATAL] exiting. . .
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Unit entered failed state.
trojan.service: Failed with result 'exit-code'.
trojan.service: Service hold-off time over, scheduling restart.
Stopped trojan.
Started trojan.
Welcome to trojan 1.16.0
[2021-03-08 09:06:31] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2021-03-08 09:06:31] [FATAL] exiting. . .
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Unit entered failed state.
trojan.service: Failed with result 'exit-code'.’

**Comment by Jrohy** [comment]
申请证书失败，获取不到证书
