### ISSUE TITLE
关于DNS的问题

### ISSUE THREAD

**Issue by SpaceCZ** [Jrohy/trojan#387]
你好，我在进行配置DNS解锁服务时，发现脚本默认会修改DNS。然后解锁服务就会不可用，请问有地方可以设置脚本有关DNS的设置么

**Comment by Jrohy** [comment]
程序本身没有改dns的(没必要)，不知道调用的申请证书的脚本(acme.sh)会不会改就是

**Comment by SpaceCZ** [comment]
> 程序本身没有改dns的（没必要），不知道调用的申请证书的脚本（acme.sh）会不会改就是

现在是我在更改DNS设置后重启服务器DNS设置又会变成原来的样子，不重启又不会生效......

**Comment by SpaceCZ** [comment]
我通过新建DNS缓存配置解决了QAQ
