### ISSUE TITLE
为什么我网站是这样的

### ISSUE THREAD

**Issue by ebisuxx** [Jrohy/trojan#389]
<img width="1390" alt="截屏2021-03-06 下午8 07 09" src="https://user-images.githubusercontent.com/71274020/110206355-1b2dca00-7eb8-11eb-8076-f35a1b6bf58c.png">
<img width="1376" alt="截屏2021-03-06 下午8 07 16" src="https://user-images.githubusercontent.com/71274020/110206356-1d902400-7eb8-11eb-9bb0-63f8bf47ec13.png">

**Comment by ebisuxx** [comment]
同时，我在shell里面添加了新用户，网站也不显示

**Comment by ebisuxx** [comment]
会不会是和我频繁更换dns有关 一下cf一下dnspod

**Comment by youjiajia-wc** [comment]
1.服务器shell的用户与trojan的用户完全没关系；
2.只有admin登录才有对用户的编辑权限，而你登录的非admin，是EBISUXX.
