### ISSUE TITLE
添加或删除用户后，需要手动重启才能生效

### ISSUE THREAD

**Issue by BrunuhVille** [Jrohy/trojan#391]
使用的trojan-go版本，v0.8.2
添加或删除用户后，需要手动重启才能生效
希望添加自动重启生效

**Comment by Jrohy** [comment]
添加用户可以马上生效，就是删除用户不能马上生效要重启才行，下个版本修复下

**Comment by Jrohy** [comment]
新版以支持删除后自动重启了，更新下

**Comment by trojson** [comment]
Jrohy 请问更新之后删除了的用户 是否还会看到 链接但提示 not a trojan request connection error
