### ISSUE TITLE
trojan-go配置文件的问题

### ISSUE THREAD

**Issue by kongbai39** [Jrohy/trojan#397]
在使用trojan-go时，在面板修改日志等级会把配置文件自己加入的字段去除比如:

"websocket": {
    "enabled": true,
    "path": "/XXX",
    "host": "XXXXXX"
  },
  "mux": {
    "enabled": true,
    "concurrency": 8,
    "idle_timeout": 60
  }

**Comment by kongbai39** [comment]
还有希望添加对trojan-go特性的配置文件生成，谢谢大大

**Comment by kongbai39** [comment]
https://p4gefau1t.github.io/trojan-go/

**Comment by kongbai39** [comment]
十分希望添加并完善对trojan-go特性的配置文件生成，十分感谢！
这里有Trojan-Go的文档:https://p4gefau1t.github.io/trojan-go/

**Comment by Jrohy** [comment]
我看下怎么优化好

**Comment by Jrohy** [comment]
2.9.8.3版本已修复此问题， 自己加的json配置项不会再丢失了

**Comment by kongbai39** [comment]
谢谢大佬，已经不会丢失了
