### ISSUE TITLE
大佬的这个是未完工状态吗？

### ISSUE THREAD

**Issue by MicMAO** [Jrohy/trojan#4]
代码跑完以后，分享链接是非常短的一个（相比于v2ray的链接），但是复制了这个分享链接以后没地方去导入呢？导入到v2ray以后是不出现东西的

**Comment by Jrohy** [comment]
v2rayN不支持的，https://github.com/TheWanderingCoel/Trojan-Qt5 你可以用这个

**Comment by MicMAO** [comment]
> v2rayN不支持的，https://github.com/TheWanderingCoel/Trojan-Qt5你可以用这个

谢谢大佬 孩子能用了。
但是我还有个小问题，我看有的人搭建以后，2级域名是可以访问的，据说是trojan运行时，利用购买后的域名搭建了一个虚拟的页面。但是我发现我的域名还是没法访问的。
他那个教程还牵扯到了ssl证书什么的，能给小弟解惑一下吗？

**Comment by Jrohy** [comment]
暂时不支持web页面，有能力的可以自己加下nginx或者caddy

**Comment by MicMAO** [comment]
> 暂时不支持web页面，有能力的可以自己加下nginx或者caddy

好的 再次感谢

**Comment by Jrohy** [comment]
@MicMAO 2.0版本支持web页面了
