### ISSUE TITLE
墙外美国洛杉矶vps，一键安装都不行了，是不是下载源挂了。

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#40]
[root@HostKvm-625635 ~]# source <(curl -sL https://git.io/trojan-install)
正在安装trojan管理程序..
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.plustech.de
 * extras: ftp.wrz.de
 * updates: mirror.plustech.de
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package 1:bash-completion-2.1-6.el7.noarch already installed and latest version
Nothing to do
正在下载管理程序版本...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Peer reports incompatible or unsupported protocol version.
chmod: cannot access '/usr/local/bin/trojan': No such file or directory
-bash: trojan: command not found
安装trojan管理程序成功!

运行命令trojan可进行trojan管理

-bash: /usr/local/bin/trojan: No such file or directory

**Comment by Jrohy** [comment]
没下载到管理程序

**Comment by Jrohy** [comment]
curl -L "https://github.com/Jrohy/trojan/releases/download/v2.4.1/trojan" -o /usr/local/bin/trojan

**Comment by Jrohy** [comment]
手动运行试试

**Comment by totodata** [comment]
[root@HostKvm-625635 ~]# curl -L "https://github.com/Jrohy/trojan/releases/download/v2.4.1/trojan" -o /usr/local/bin/trojan
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Peer reports incompatible or unsupported protocol version.

**Comment by Jrohy** [comment]
网络有没有出问题，下不了github的这文件

**Comment by totodata** [comment]
搞不清楚了，我下载别人的github上面的文件，秒开呢。
https://raw.githubusercontent.com/atrandys/trojan/master/trojan_centos7.sh

**Comment by Jrohy** [comment]
https://blog.csdn.net/qq_40460909/article/details/82287090  试下行不行

**Comment by totodata** [comment]
还是不行，这次能到后面了。还是启动不起来。

请选择: 3
Failed to issue method call: Unit trojan.service failed to load: Invalid argument. See system logs and 'systemctl status trojan.service' for details.
重启trojan失败!

欢迎使用trojan管理程序

1.trojan管理       	2.用户管理           

3.安装管理           	4.web管理          

5.查看配置           	6.生成json         

请选择: 
[root@HostKvm-625635 ~]# systemctl status trojan.service
trojan.service - trojan
   Loaded: error (Reason: Invalid argument)
   Active: inactive (dead)
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/

Apr 01 16:28:51 HostKvm-625635 systemd[1]: [/etc/systemd/system/trojan.service:9] Executabl...on"
Apr 01 16:28:51 HostKvm-625635 systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Apr 01 16:28:51 HostKvm-625635 systemd[1]: [/etc/systemd/system/trojan.service:9] Executabl...on"
Apr 01 16:28:51 HostKvm-625635 systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Apr 01 16:28:51 HostKvm-625635 systemd[1]: [/etc/systemd/system/trojan.service:9] Executabl...on"
Apr 01 16:28:51 HostKvm-625635 systemd[1]: trojan.service lacks ExecStart setting. Refusing.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by totodata** [comment]
web 管理后台，出来了，连接mhsql 失败。

**Comment by totodata** [comment]
应该是docker没安装成功，然后导致mysql也安装不成功。

**Comment by totodata** [comment]
source <(curl -sL https://git.io/trojan-install)         
正在安装trojan管理程序..
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.fau.de
 * extras: centos.mirrors.as250.net
 * updates: mirror.alpix.eu
Package socat-1.7.3.2-2.el7.x86_64 already installed and latest version
Package 1:bash-completion-2.1-6.el7.noarch already installed and latest version
Nothing to do
正在下载管理程序v2.4.1版本...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   597  100   597    0     0    494      0  0:00:01  0:00:01 --:--:--   495
100 14.5M  100 14.5M    0     0  3163k      0  0:00:04  0:00:04 --:--:-- 4542k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   384  100   384    0     0    355      0  0:00:01  0:00:01 --:--:--   355
安装trojan管理程序成功!

运行命令trojan可进行trojan管理

本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.KNqu3r225g...
Downloading trojan 1.15.1...
######################################################################## 100.0%
Unpacking trojan 1.15.1...
Installing trojan 1.15.1 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.KNqu3r225g...
Done!
Failed to issue method call: Unit trojan.service failed to load: Invalid argument. See system logs and 'systemctl status trojan.service' for details.

**Comment by Jrohy** [comment]
看下trojan状态，systemctl status troian

**Comment by totodata** [comment]
就是服务没安装上去。安装源改一下吧。放到 https://raw.githubusercontent.com  这样的引用去。都很顺利。
systemctl status troian
Unit troian.service could not be found.

**Comment by Jrohy** [comment]
release的下载包没有这样的https://raw.githubusercontent.com
