### ISSUE TITLE
trojan后台配置/usr/local/etc/trojan/config.json的logvel为3，用命令行生成json的里面值是1

### ISSUE THREAD

**Issue by JoneJay** [Jrohy/trojan#400]
trojan后台配置/usr/local/etc/trojan/config.json的logvel为3，用命令行生成json的里面值是1

**Comment by Jrohy** [comment]
命令行怎么生成json

**Comment by JoneJay** [comment]
1.trojan管理            2.用户管理           

3.安装管理              4.web管理          

5.查看配置              6.生成json

**Comment by Jrohy** [comment]
这两个json不一样，一个服务端，一个客户端json,客户端json自己修改，两个独立的

**Comment by JoneJay** [comment]
好的，我还以为是生成的单独用户的服务端的配置。
