### ISSUE TITLE
trojan export 加路径导出后，提示导出成功但没有找到SQL文件

### ISSUE THREAD

**Issue by keengrass** [Jrohy/trojan#402]
瓦工的服务器，用的Jrohy大神的代码搭建的TROJAN Go. 已升级到最新版。
最近不知道怎么回事，总是隔半小时，或是1到2个小时就不能上网了。前台管理页面也打不开。
IP没有被墙，也能PING通网址。
但重启瓦工的服务器后就能恢复，不知道是否是什么原因？

打算重装系统，看看是否能解决这个问题。
想备份下用户数据，方便到时候再导入回来。
但用了trojan export +路径  命令（比如我写的是 trojan export c:）后，显示导出成功，但在C盘下并不能发现SQL文件。
是我的命令里的路径写错了吗？还是什么原因？
其实这是两个问题，求解！

不胜感谢！
![sql](https://user-images.githubusercontent.com/65809838/111607014-cfade100-8812-11eb-8fd9-ad2d6964c0d0.jpg)

另外还有个问题就是，以前的版本，分享的链接里是大写的网址，
升级了新版本后，分享链接的网址变成了小写。
这导致以前的大写链接不能上网。很不方便。

**Comment by Jrohy** [comment]
别这样写，直接trojan export xxx.sql就好了

**Comment by keengrass** [comment]
请问这样写是导出到什么地方呢？好像没有找到。

**Comment by Jrohy** [comment]
就是当前执行命令的目录

**Comment by keengrass** [comment]
找到了，非常感谢！原来是导出在服务器上，我一直以为导出是到本地电脑上。

**Comment by rickartmiriam** [comment]
> 找到了，非常感谢！原来是导出在服务器上，我一直以为导出是到本地电脑上。

导出来明白了，但如何导入呢？导入到那个目录下呢？麻烦帮忙解答下。

**Comment by Jrohy** [comment]
@rickartmiriam 导入就是trojan import xxx.sql就行， 只要导入的文件存在即可
