### ISSUE TITLE
是否有发觉升级到最新版本之后流量面板统计有点不正确？

### ISSUE THREAD

**Issue by trojson** [Jrohy/trojan#403]
远远小于实际使用量

**Comment by JoneJay** [comment]
是的，不知道是不是因为更新的慢了。

**Comment by Jrohy** [comment]
流量统计和写入都是trojan核心做的，面板只是读数据库里的值然后显示出来而已

**Comment by trojson** [comment]
刚开始 MB 统计的时候就比较快，几乎是同步，到达 GB 的时候就开始慢了好多，跟实际输出的 使用率不符，不知道最终是不是用户实际使用的情况 （ 该用户有设置限制流量）暂无留意未限制用户，稍微看看。
