### ISSUE TITLE
最近封ip严重，问下Trojan 有被封吗

### ISSUE THREAD

**Issue by Hikpy** [Jrohy/trojan#406]

**Comment by Jrohy** [comment]
看线路和vps商吧，我搬瓦工搭的trojan-go还都能用

**Comment by ckbkdj** [comment]
...我搬瓦工的go 封了好三四次了,我都是迁移机房换个那种IP....继续用

**Comment by Hikpy** [comment]
> ...我搬瓦工的go 封了好三四次了,我都是迁移机房换个那种IP....继续用

你搬瓦工的cn2 gia 机房吗  换ip 岂不是 很不划算。
是这个面板搭的吗？

**Comment by ckbkdj** [comment]
是啊

**Comment by JoneJay** [comment]
别用搬瓦工家的了，他家的IP属于重点部控对象，有些属于19年被封的那波里释放出来的。

**Comment by ckbkdj** [comment]
😭

**Comment by 907904228** [comment]
我用阿里云的一年多了，很正常

**Comment by ancct** [comment]
用COM域名，主域放上业务，二级搭建上。

**Comment by fengmikaelson** [comment]
搬瓦工用了一年了没问题，前几天又新买了一个。。。目前都没问题就是了

**Comment by Viweday** [comment]
trojan不是用https伪装了么，还会被封ip呀

**Comment by ancct** [comment]
主域跳转到www，然后www做一个WEB服务，各种搜索引擎收录上上。然后站点开二级域名，video放视频，img放图片，m是移动版，最后开个二级域名cdn做梯子。
