### ISSUE TITLE
今天新编的版本运行后web无法访问报404

### ISSUE THREAD

**Issue by JoneJay** [Jrohy/trojan#408]
Version: v2.9.8.3

BuildDate: 20210320-0310

GoVersion: go1.16.2 linux/amd64

GitVersion: a28981b8107c55dad07ee60b364824b062e3ffdd

TrojanVersion: v0.8.2

是我编译有问题吗？过程也没有报错，替换回2.9.8.2就没问题。

**Comment by Jrohy** [comment]
自己编译的话还要编译前端的，要将编译好的前端放在web/templates下面再来编译

**Comment by JoneJay** [comment]
> 自己编译的话还要编译前端的，要将编译好的前端放在web/templates下面再来编译

好的，谢谢，我再试一下
