### ISSUE TITLE
通过手动安装，web正常，trojan也正常了，web提示无法连接mysql

### ISSUE THREAD

**Issue by totodata** [Jrohy/trojan#41]
trojan配置文件在哪里？
如何修改mysql的连接和密码？

**Comment by Jrohy** [comment]
/usr/local/etc/trojan/config.json这个，你看下mysql有没有正常启动能否使用

**Comment by totodata** [comment]
看配置文件，密码是null 
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": null,
    "log_level": 1,

**Comment by Jrohy** [comment]
不用配置文件的password字段的，是连Mysql来读用户密码的

**Comment by totodata** [comment]
查看mysql配置，没有开通，密码也没正常。

    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "db": "",
        "username": "trojan",
        "password": ""
    }
}

**Comment by totodata** [comment]
mysql 能卸载，重新用安装程序安装吗？

**Comment by Jrohy** [comment]
rm -rf /home/mysql 
docker rm -f trojan-mysql
这样卸载mysql
然后去安装管理那里安装mysql

**Comment by totodata** [comment]
重新手动安装一遍，web管理页面正常了。trojan连不上。折腾啊。

systemctl status trojan
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-04-02 14:13:15 UTC; 2s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 1609 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 1609 (code=exited, status=1/FAILURE)

Apr 02 14:13:15 HostKvm-625635 trojan[1609]: [2020-04-02 14:13:15] [FATAL] exi....
Apr 02 14:13:15 HostKvm-625635 systemd[1]: trojan.service: main process exited...E
Apr 02 14:13:15 HostKvm-625635 systemd[1]: Unit trojan.service entered failed ....
Apr 02 14:13:15 HostKvm-625635 systemd[1]: trojan.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by Jrohy** [comment]
你可以先stop了trojan, systemctl stop trojan, 然后直接命令行运行trojan: `/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json`, 这样看日志可能清晰点

**Comment by totodata** [comment]
[root@HostKvm-625635 ~]# systemctl stop trojan
[root@HostKvm-625635 ~]# /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
Welcome to trojan 1.15.1
[2020-04-02 14:42:41] [FATAL] fatal: bind: Address already in use
[2020-04-02 14:42:41] [FATAL] exiting. . .

**Comment by Jrohy** [comment]
443被占用了么

**Comment by totodata** [comment]
netstat -anp |grep 443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1114/trojan         
tcp        0      0 92.118.188.187:443      183.250.143.168:8445    ESTABLISHED 1114/trojan

**Comment by Jrohy** [comment]
先kill掉这个，再起看看日志正不正常

**Comment by totodata** [comment]
杀掉进程，重启后，还是报着个错

[root@HostKvm-625635 ~]# systemctl restart trojan
[root@HostKvm-625635 ~]# systemctl status trojan 
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-04-02 14:55:43 UTC; 1s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 5458 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 5458 (code=exited, status=1/FAILURE)

Apr 02 14:55:43 HostKvm-625635 systemd[1]: Unit trojan.service entered failed state.
Apr 02 14:55:43 HostKvm-625635 systemd[1]: trojan.service failed.

**Comment by Jrohy** [comment]
这个看不出什么的，你直接运行/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

**Comment by totodata** [comment]
一样的。
[root@HostKvm-625635 ~]# /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
Welcome to trojan 1.15.1
[2020-04-02 14:58:47] [FATAL] fatal: bind: Address already in use
[2020-04-02 14:58:47] [FATAL] exiting. . .

**Comment by Jrohy** [comment]
你先停了吗trojan, systemctl stop trojan

**Comment by totodata** [comment]
[root@HostKvm-625635 ~]# systemctl stop trojan
[root@HostKvm-625635 ~]# systemctl stop trojan
[root@HostKvm-625635 ~]# /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
Welcome to trojan 1.15.1
[2020-04-02 14:59:50] [FATAL] fatal: bind: Address already in use
[2020-04-02 14:59:50] [FATAL] exiting. . .

**Comment by Jrohy** [comment]
你当初kill掉后应该直接/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json， 不要重启trojan.service先

**Comment by totodata** [comment]
[root@HostKvm-625635 ~]# ps -ef | grep trojan
root      1293     1  0 14:11 ?        00:00:01 /usr/local/bin/trojan web
root      6513  6334  0 15:06 ?        00:00:00 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
root      6734  1494  0 15:08 pts/0    00:00:00 grep --color=auto trojan
[root@HostKvm-625635 ~]# kill 6513
[root@HostKvm-625635 ~]# /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
Welcome to trojan 1.15.1
[2020-04-02 15:09:55] [INFO] connecting to MySQL server 127.0.0.1:3306
[2020-04-02 15:09:55] [INFO] connected to MySQL server
[2020-04-02 15:09:55] [WARN] trojan service (server) started at 0.0.0.0:443

**Comment by totodata** [comment]
这样，启动后，可以使用trojan了，能连上。服务器重启后，还是处于不可连接状态。必需杀掉进程，重新手动启动。

**Comment by Jrohy** [comment]
你之前有没有是安装过trojan的，可能和本程序安装的路径不同

**Comment by totodata** [comment]
已经安装好的系统，如何更改域名呢？

**Comment by Jrohy** [comment]
更改域名的话证书也得更改是不是，安装管理那里证书申请那里改

**Comment by totodata** [comment]
限制流量，设置的是终身流量吧？不是按照指定周期？如何让它每个月重置流量呢。

**Comment by Jrohy** [comment]
暂时不支持周期重置流量
