### ISSUE TITLE
限期设置的功能建议

### ISSUE THREAD

**Issue by Hikpy** [Jrohy/trojan#417]
为啥限期的每个月初自动清0流量呢？这个很鸡肋因为服务器流量多半不是月初 重新清零的

**Comment by Jrohy** [comment]
可以修改重置日的

**Comment by Hikpy** [comment]
> 可以修改重置日的

牛逼了 搞定

**Comment by fengmikaelson** [comment]
> > 可以修改重置日的
> 
> 牛逼了 搞定

请问在哪？我找了下，只找到修改期限，没看到重置日。。。
