### ISSUE TITLE
升级到 v2.10.1 以后页面空白

### ISSUE THREAD

**Issue by 5139** [Jrohy/trojan#418]
管理程序为 v2.9.8.3 时，一切正常。
使用 trojan updateWeb 升级到 v2.10.1 后，访问管理页面，是空白的。
页面没有访问失败，页面源码有内容，但就是没有显示任何可见的内容。
在另一台服务器上重复这个更新操作，结果依旧，web 没有显示了。
请问如何恢复到 v2.9.8.3 版本？

**Comment by trojson** [comment]
我的正常没问题，updateWeb 之后 systemctl restart trojan-web

**Comment by 5139** [comment]
> 我的正常没问题，updateWeb 之后 systemctl restart trojan-web

不行，重新启动服务器都不行。
页面显示空白。
获取到的页面内容是：
`<!DOCTYPE html><html><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1"><meta name=renderer content=webkit><meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><link rel=icon href="data:;base64,="><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.css><link rel=stylesheet href=https://cdn.jsdelivr.net/npm/element-ui@2.15.1/lib/theme-chalk/index.css><script src=https://cdn.jsdelivr.net/npm/vue@2.6.12></script><script src=https://cdn.jsdelivr.net/npm/vue-router@3.5.1></script><script src=https://cdn.jsdelivr.net/npm/vuex@3.6.2></script><script src=https://cdn.jsdelivr.net/npm/vue-i18n@8.24.2/dist/vue-i18n.min.js></script><script src=https://cdn.jsdelivr.net/npm/axios@0.21.1></script><script src=https://cdn.jsdelivr.net/npm/crypto-js@4.0.0/crypto-js.min.js></script><script src=https://cdn.jsdelivr.net/npm/qrcodejs2@0.0.2/qrcode.min.js></script><script src=https://cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js></script><script src=https://cdn.jsdelivr.net/npm/dayjs@1.10.4/dayjs.min.js></script><script src=https://cdn.jsdelivr.net/npm/element-ui@2.15.1/lib/index.js></script><script src=https://cdn.jsdelivr.net/npm/element-ui@2.15.1/lib/umd/locale/en.js></script><script src=https://cdn.jsdelivr.net/npm/element-ui@2.15.1/lib/umd/locale/zh-CN.js></script><link href=/static/css/app.a0caa73b.css rel=preload as=style><link href=/static/js/app.7f7ce170.js rel=preload as=script><link href=/static/js/chunk-vendors.d21e2e1f.js rel=preload as=script><link href=/static/css/app.a0caa73b.css rel=stylesheet></head><body><noscript><strong>Please enable javascript to use.</strong></noscript><div id=app></div><script src=/static/js/chunk-vendors.d21e2e1f.js></script><script src=/static/js/app.7f7ce170.js></script></body></html>`

**Comment by 5139** [comment]
请问有办法回退版本吗？
我想先恢复一下，暂时先把问题解决了。

**Comment by Jrohy** [comment]
要回滚的话去release里下载对应版本的文件，替换到/usr/local/bin/就行，替换前停了trojan-web，替换完再启动

**Comment by Jrohy** [comment]
用的什么版本浏览器，我看看是否有兼容性问题

**Comment by 5139** [comment]
> 要回滚的话去release里下载对应版本的文件，替换到/usr/local/bin/就行，替换前停了trojan-web，替换完再启动

谢谢！替换 /usr/local/bin/trojan 后，一切恢复正常。
是不是新版本要用到的 cdn 里的 js 文件还没准备好。

谢谢！

**Comment by trojson** [comment]
估计是 Firefox Nightly 吧，我这测试用 微软 Edge 谷歌 Chrome 都可以就火狐一遍空白 （更新火狐前）


Sent from Yahoo Mail for iPhone


On Saturday, April 3, 2021, 10:54 AM, Jrohy ***@***.***> wrote:




用的什么版本浏览器，我看看是否有兼容性问题

**Comment by trojson** [comment]
估计是 Firefox Nightly 吧，我这测试用 微软 Edge 谷歌 Chrome 都可以就火狐一遍空白 （更新火狐前）

**Comment by Jrohy** [comment]
@trojson 感谢反馈，我去安装测试下

**Comment by 5139** [comment]
> 用的什么版本浏览器，我看看是否有兼容性问题

用的以下两个浏览器，看到的效果是一样的，都是回退到 2.9.8.3 就正常了。
火狐 78.9.0esr (64 位)
Chrome 版本 89.0.4389.114（正式版本） （64 位）

**Comment by trojson** [comment]
我的确实没问题，刚用火狐 测试不行 看下是在更新状态，点击更新重启火狐即可，后续看下有没有其他反馈再具体沟通。

**Comment by Jrohy** [comment]
我这边开发也是用Chrome 版本 89.0.4389.114没问题，就火狐没测过

**Comment by Jrohy** [comment]
我用火狐最新版87和Nightly 89.0a1都测试可以

**Comment by Jrohy** [comment]
@trojson 你用火狐f12看能加载到cdn的那些资源么

**Comment by trojson** [comment]
> @trojson 你用火狐f12看能加载到cdn的那些资源么

狐火 + ABP 不行，Edge + ABP 可以，估计 Chrome 没装 ABP，估计是 ABP 在狐火那边 把页面代码屏蔽了所以打开一遍空白。

**Comment by 5139** [comment]
又试了一遍：
在火狐上禁用了Ghostery、uBlock Origin、隐私獾以后，还是空白。（ 但 2.9.8.3 正常）
Chrome上没有安装任何与保护隐私有关的插件，也是空白。（ 但 2.9.8.3 正常）
怀疑与路由器上的广告拦截有关，因此关闭路由器，电脑连接手机热点，仍然空白。（ 但 2.9.8.3 正常）

**Comment by Jrohy** [comment]
@5139  f12能看到什么呢，能否加载到什么资源

**Comment by trojson** [comment]
开启广告拦截，例如我这里的ABP电脑客户端情况 火狐按 F12 看到的代码跟楼主发的完全一致。

**Comment by 5139** [comment]
@Jrohy 😂 刚出门，那请等一下，十几分钟，我回去把服务器再重新升级为 2.10.1

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/113467218-33234a00-9474-11eb-8d00-7a4a7c48936b.png)
f12的这种网络图，我火狐装了adblock都可以发😂

**Comment by 5139** [comment]
火狐：
![ff](https://user-images.githubusercontent.com/50733782/113467645-f2790000-9476-11eb-87ad-efb37dec073e.png)
Chrome：
![chrome](https://user-images.githubusercontent.com/50733782/113467657-091f5700-9477-11eb-84f1-3a2951f8c206.png)

**Comment by 5139** [comment]
您辛苦了，不急，慢慢来，2.9.8.3 能用就行 @Jrohy

**Comment by Jrohy** [comment]
[trojan.zip](https://github.com/Jrohy/trojan/files/6251985/trojan.zip)
@5139 可以帮测试下么，编译了个新版，去掉了text/html的header，看看还会不会报错, 下载后去掉.zip后缀(github上传必须带后缀)

**Comment by Jrohy** [comment]
你可以停了原来的systemctl stop trojan-web, 再放到服务器里(任意目录)直接运行./trojan web即可运行, 这样就不用替换原来的安装包，也可以测测新编译的

**Comment by 5139** [comment]
感谢！效率这么高。
我在哪儿下载测试版？没有看到 pre-release 之类的发布

**Comment by Jrohy** [comment]
> [trojan.zip](https://github.com/Jrohy/trojan/files/6251985/trojan.zip)
> @5139 可以帮测试下么，编译了个新版，去掉了text/html的header，看看还会不会报错, 下载后去掉.zip后缀(github上传必须带后缀)

就点击这里trojan.zip文件下载，懒得弄pre-release了

**Comment by 5139** [comment]
仍旧空白.....
FF:
![ff](https://user-images.githubusercontent.com/50733782/113472613-092f4f00-9497-11eb-9530-5fcfcb01ca45.png)
Chrome:
![chrome](https://user-images.githubusercontent.com/50733782/113472624-13e9e400-9497-11eb-9cf4-f82b519b23e4.png)

**Comment by trojson** [comment]
慢慢检查下，估计是个案，要不昨晚放出更新之后都会有很用户跑来咨询，观望ING。

**Comment by Jrohy** [comment]
资源请求竟然是404，有没有试过清了浏览器缓存来测

**Comment by 5139** [comment]
> 慢慢检查下，估计是个案，要不昨晚放出更新之后都会有很用户跑来咨询，观望ING。

好的，劳烦您了。

**Comment by 5139** [comment]
> 资源请求竟然是404，有没有试过清了浏览器缓存来测

试过的，仍然有 4 个 404
也想过是不是改了 port 的原因，但应该没有关系呀， 404 的 js 文件已经指定到 8181。
nginx 是按 wiki 上的标准范例写的，如果这些基本的都错了，2.9.8.3 也应该不会工作呀：
```
server {
     listen 127.0.0.1:80 default_server;
 
     server_name sample.com;
 
     location / {
         proxy_pass https://baidu.com;
     }
 
     location /admin {
         proxy_pass   http://localhost:8181/;
     }
 
     location ~* ^/(js|css|vendor|common|auth|trojan)/ {
         proxy_pass  http://localhost:8181;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection "Upgrade";
         proxy_set_header Host $host;
     }
 
     if ( $remote_addr != 127.0.0.1 ){
         rewrite ^/(.*)$ https://sample.com/$1 redirect;
     }
 }
```

**Comment by 5139** [comment]
把 location / 的 proxy_pass 去掉，只留下 /admin，结果也是一样：
![chrome2](https://user-images.githubusercontent.com/50733782/113476726-da71a280-94af-11eb-8b0e-cd61b764a81d.png)
好，看看其他人是否遇到吧。

**Comment by Jrohy** [comment]
噢原来是加了nginx，得改下nginx配置才行，因为前端路由变了

**Comment by 5139** [comment]
> 噢原来是加了nginx，得改下nginx配置才行，因为前端路由变了
请指教应该怎么改。
如果不加，那么首页就是管理页面了。首页就有《trojan 管理平台》几个大字摆着，会不会太容易被有心的机构扫描到了。
所以就想着尽量低调一些，让他们也过得去，大家都方便。

**Comment by 5139** [comment]
> 噢原来是加了nginx，得改下nginx配置才行，因为前端路由变了

请指教应该怎么改。
如果不加，那么首页就是管理页面了。首页就有《trojan 管理平台》几个大字摆着，会不会太容易被有心的机构扫描到了。
所以就想着尽量低调一些，让他们也过得去，大家都方便。

**Comment by Jrohy** [comment]
nginx配置将js|css|vendor 换成static就行了，wiki已更新https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

**Comment by Jrohy** [comment]
首页标题可以进系统里面改的

**Comment by 5139** [comment]
👍
解决了，感谢！

**Comment by 5139** [comment]
修改 nginx 配置后解决了，感谢！
