### ISSUE TITLE
密码为什么存在本地的leveldb？

### ISSUE THREAD

**Issue by sakz** [Jrohy/trojan#42]
那如果我想要搭2个节点，共用一个数据库就不方便了

**Comment by sakz** [comment]
或者服务器过期，需要换个服务器，迁移就不方便了，拷贝那些ldb文件？

**Comment by Jrohy** [comment]
可以拷贝那些ldb文件的

**Comment by sakz** [comment]
> 可以拷贝那些ldb文件的

我知道可以，就不能全部存在mysql吗

**Comment by Jrohy** [comment]
主要是存储比较方便，不用像存配置文件那样还要关心位于文件的那部分，不用自己管理配置文件

**Comment by Jrohy** [comment]
trojan本身的数据库不想动他，尽量不加新表和改表结构。独立数据库的好处是就算mysql连不成功，web界面还是能独立运行

**Comment by Jrohy** [comment]
trojan在mysql里存的密码都是经过SHA224加密不可逆的，要在页面展示给用户原始密码，只能加密前存一份原始密码(存到leveldb)

**Comment by sakz** [comment]
我是想批量导入一批用户，这样也能实现多节点，如果存在mysql就可以很方便做到了
