### ISSUE TITLE
建议增加用户导入功能

### ISSUE THREAD

**Issue by 5139** [Jrohy/trojan#422]
这个库最强大和吸引人的地方（之一），是便捷的用户管理。
但是主机崩溃重装时，以前设置的用户和密码没有了。
如果说备份数据库，那似乎麻烦了些，因为不能在 web 页面完成，还得 ssh 吧。
能不能增加一个用户导入功能，比如，导入这种格式的 csv 文件：
```
user1, pwd1
user2, pwd2
user3, pwd3
...
```

**Comment by Jrohy** [comment]
v2.10.3版本已添加在线导入导出csv文件，更新下

**Comment by 5139** [comment]
> v2.10.3版本已添加在线导入导出csv文件，更新下

1、测试导出后，删除所有用户，再将数据导入原来的主机，成功恢复所有用户；
2、导出文件的第4列（密码base64后面那一列）是什么？比如，想要线下编辑，增加一个新用户后上传，需要知道这一列的意义；
3、不支持选择性导出和增量导入，导入的数据会覆盖原有的全部用户数据。能否改为增量导入方式（不覆盖原有数据）？

**Comment by Jrohy** [comment]
那是加密后的密码，不支持选择性导入导出

**Comment by 5139** [comment]
OK. 谢谢

**Comment by rickartmiriam** [comment]
请教下：如何导入？具体步骤和命令是什么？

**Comment by rickartmiriam** [comment]
> > v2.10.3版本已添加在线导入导出csv文件，更新下
> 
> 1、测试导出后，删除所有用户，再将数据导入原来的主机，成功恢复所有用户；
> 2、导出文件的第4列（密码base64后面那一列）是什么？比如，想要线下编辑，增加一个新用户后上传，需要知道这一列的意义；
> 3、不支持选择性导出和增量导入，导入的数据会覆盖原有的全部用户数据。能否改为增量导入方式（不覆盖原有数据）？

请教下：如何导入？具体步骤和命令是什么？

**Comment by rickartmiriam** [comment]
> v2.10.3版本已添加在线导入导出csv文件，更新下

请教下：如何导入？具体步骤和命令是什么？

**Comment by Jrohy** [comment]
在web节目admin登录后系统设置里能看到导入导出
