### ISSUE TITLE
总是出现driver: bad connection

### ISSUE THREAD

**Issue by FirstPo** [Jrohy/trojan#423]
![image](https://user-images.githubusercontent.com/62851736/114050010-7f301d80-98be-11eb-8cce-6845e716ea49.png)
Azure 1h1g contos7 总是出现这种情况
能解决吗

**Comment by FirstPo** [comment]
现在ssh都无法连接，一台机器装好半个月左右都会出现这种情况，正常吗

**Comment by youjiajia-wc** [comment]
被黑客扫描成肉鸡了。最简单的办法，重装系统，设置复杂的root密码，重新装这个面板。
不信，你top看一下占用cpu的进程，绝不可能是trojan

**Comment by FirstPo** [comment]
> 被黑客扫描成肉鸡了。最简单的办法，重装系统，设置复杂的root密码，重新装这个面板。
> 不信，你top看一下占用cpu的进程，绝不可能是trojan

我现在都连不上服务器了..

**Comment by ckbkdj** [comment]
那就是你买的服务器是超售的垃圾小鸡呗

**Comment by youjiajia-wc** [comment]
> > 被黑客扫描成肉鸡了。最简单的办法，重装系统，设置复杂的root密码，重新装这个面板。
> > 不信，你top看一下占用cpu的进程，绝不可能是trojan
> 
> 我现在都连不上服务器了..

控制面板，重装系统。不是连接服务器XXXX
如果再不懂，我也不想再多解释了，累。
