### ISSUE TITLE
docker 的问题

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#425]
Failed to restart trojan.service: Failed to activate service 'org.freedesktop.systemd1': timed out
See system logs and 'systemctl status trojan.service' for details.
重启trojan失败!
Failed to restart trojan-web.service: Failed to activate service 'org.freedesktop.systemd1': timed out
See system logs and 'systemctl status trojan-web.service' for details.

**Comment by Jrohy** [comment]
测试没问题，用最新的docker镜像

**Comment by Potterli20** [comment]
> 测试没问题，用最新的docker镜像

我改了改端口就好了，想一个问题，一个机器可以用两个trojan两个不同的数据库。但是我测了，trojan-go用不了cdn（部署环境是作者的docker），太奇怪了

**Comment by Jrohy** [comment]
我试过不用docker,trojan-go也用不了cf的cdn，不知道是不是有限制了

**Comment by Potterli20** [comment]
> 我试过不用docker,trojan-go也用不了cf的cdn，不知道是不是有限制了

我用trojan-go，把SSL证书设置完全，是可以的，现在是我用两个机器，一个可以在本地设置Trojan-go ,另一个在docker设置Trojan-go设置不行。两个Trojan-go都是手动编译的dev
