### ISSUE TITLE
关于用户管理的问题

### ISSUE THREAD

**Issue by coolqinf** [Jrohy/trojan#43]
管理员登录后，能否直接修改用户的用户名、密码？现在好像只能删除重建。

**Comment by Jrohy** [comment]
只能删除重建

**Comment by Jrohy** [comment]
后面版本增加下

**Comment by coolqinf** [comment]
辛苦了，非常好的一键搭建和web管理

**Comment by Jrohy** [comment]
@coolqinf 2.5.0版本已添加，更新下`source <(curl -sL https://git.io/trojan-install)`
