### ISSUE TITLE
Trojan安装数据库连接有问题。

### ISSUE THREAD

**Issue by gimgoo** [Jrohy/trojan#430]
如题，仅仅是修改了安装脚本的数据库密码而已：
`docker run --name trojan-mariadb --restart=always -p 3306:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=自定义密码 -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2`

进入容器后，输入trojan初始化安装直接就装不上

![image](https://user-images.githubusercontent.com/31849284/115987208-9ffab180-a5e6-11eb-9157-52075487e0fa.png)

**Comment by Jrohy** [comment]
自己用工具能否连呢，比如用navicat试下连

**Comment by RalstonLiu** [comment]
同样遇到了这个问题，纯净的Debian10系统，官网安装的docker环境，连接失败。删除容器后重新尝试了也不行，RN的服务器

**Comment by juilletVent** [comment]
> 同样遇到了这个问题，纯净的Debian10系统，官网安装的docker环境，连接失败。删除容器后重新尝试了也不行，RN的服务器

对问题的猜测：docker 容器之间默认情况下网络是互相不通的，db与trojan跑在两个docker容器中，如果没有创建子网，则肯定不通

解决方案：
1、简单暴力，将trojan所属的容器使用特权模式运行，trojan将有能力访问宿主机的整个网络，自然也就能访问db容器映射到宿主机上的3306服务
2、为两个容器创建专用子网，并将他们加入子网内，这样两个容器就能够互访了，问题就解决了

当然了，以上是基于对网络不通的猜测，mysql本身是默认不允许root用户远程连接的，需要你修改root在user表下的host字段为%来允许连接的。

以上，Good luck
