### ISSUE TITLE
SSL自动续期

### ISSUE THREAD

**Issue by ericghost** [Jrohy/trojan#431]
大佬,能不能添加SSL自动续期

**Comment by Jrohy** [comment]
有定时任务自动续期的，运行crontab -l可以看到任务

**Comment by ericghost** [comment]
> 有定时任务自动续期的，运行crontab -l可以看到任务

我之前确实没有自动续期,我刚才运行了脚本重新申请了证书,后来我刚通过ssh看文件夹里的配置文件上面有说什么时间续期.

**Comment by Jrohy** [comment]
可以手动运行下定时任务看看能否申请成功，看有没报错
