### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by ajiter** [Jrohy/trojan#432]
大佬我vps正常。但节点不能用。用http可以上管理界面。用ip地址也可以上管理界面。但用了https 就上不了管理界面。然后用ssh连vpn后。运行trojan tls 重新申请证书。所有问题解决。但过了半小时又复现上面的问题。谢谢大佬帮分析下什么问题。

**Comment by ajiter** [comment]
最近一直出现这个问题。难道没有其它人碰到过？我重新全新安装也是出现这个问题。我现在出现这问题。运行trojan tls 重新申请证书立马一切正常。有时不重新申请证书重启vps也可以解决。但治标不治本。过一天又会出现同样问题。大神能看看什么原因么。谢谢

**Comment by keengrass** [comment]
不是你一个人，我一直都遇到这样的问题，时间或长或短，都是重启VPS后解决。但今天无论是否重启VPS， 重申证书，都无法解决。同样的http可以访问，而https不能访问，我在想是不是问题出在Let's Encrypt 证书上面。

**Comment by keengrass** [comment]
另外我看到了不止一个人在反馈这个问题了。麻烦jrohy关注一下这个问题。

**Comment by Jrohy** [comment]
我也是用的Let's Encrypt证书没问题, 续签过几次了 @keengrass

**Comment by keengrass** [comment]
> 我也是用的Let's Encrypt证书没问题, 续签过几次了 @keengrass

发现在全局代理模式下，可以访问https面板. 
这应该不是证书问题。
而非代理下可以访问http，不能访问https
这是否说明https下的域名已经挂了？

**Comment by keengrass** [comment]
鉴于发现有这种情况的人挺多的，是不是这个项目已被G..FW发现并针对了？

**Comment by Jrohy** [comment]
@keengrass 会不会软件设置问题， 用的v2rayN吗

**Comment by keengrass** [comment]
> @keengrass 会不会软件设置问题， 用的v2rayN吗

我PC用的v2rayN
但不应该是软件问题。
手机上也无法访问。
关键是浏览器打开https的面板地址也打不开啊。

**Comment by Jrohy** [comment]
主要我用搬瓦工搭建的年付(18刀一年)的trojan没出现过这种情况,  包括今天也是正常使用, 网页https访问没问题，既作为开发环境又做梯子😂， 域名买的是namecheap的

**Comment by keengrass** [comment]
我也是BWG的， 自己注册的收费域名。能有什么方法联xi到您帮我看下原因吗？这个问题我看好几个网友和我的问题是一样的，之前都是断断续续出现，后来我重装系统和您的代码后解决了，最近又偶尔出现，基本上重启一下VPS就能解决。但今天就是无论什么方法都用不了。我打算换个域名再试试。

**Comment by Jrohy** [comment]
@keengrass 联系就不便了，什么操作系统呢，我用的是Centos7.8的

**Comment by keengrass** [comment]
理解。Centos 7 x86_64 bbr  
我想说的是，之前一切正常，就突然不能访问了。
感觉不是操作系统原因吧。

**Comment by Jrohy** [comment]
@keengrass 有试过用同样的域名下搭建xray可以么

**Comment by keengrass** [comment]
没有试过，我有空的时候试下看。

**Comment by Jrohy** [comment]
@keengrass 是不是trojan和trojan-go切换着来都是一样不行，打开页面时看日志有请求进来吗

**Comment by keengrass** [comment]
可否请教你一个问题，就是https下的面板，在全局代理情况下是可以访问的。这是否说明是DNS污染了https域名，而和软件无关啊。

**Comment by Jrohy** [comment]
ping域名是返回vps ip吗

**Comment by keengrass** [comment]
是的，返回的vps ip.

**Comment by Jrohy** [comment]
介意留言下服务器信息帮你看下么，我看到留意就帮你删了

**Comment by keengrass** [comment]
不介意，你要哪个信息，PING的截图吗

**Comment by Jrohy** [comment]
vps主机连接信息，如果不行，可以建个trojan用户我这边试试

**Comment by keengrass** [comment]
可以发给你的。不过我刚重装了系统
216.24.183.55
29943
PKHx35fYq1kK
域名你可以用  c.sakas.vip

**Comment by keengrass** [comment]
麻烦尽快删除，谢谢

**Comment by Jrohy** [comment]
域名我漏了copy，能再发多次吗😂， 域名

**Comment by keengrass** [comment]
c.sakas.vip

**Comment by Jrohy** [comment]
确实不行，我搭建下xray看看

**Comment by keengrass** [comment]
之前重启VPS就可以恢复。
或是重装一次，就很长时间不会反复上不了（如一楼楼主所说）。
今天是彻底不行。重装系统和软件也不行了。

**Comment by Jrohy** [comment]
装了xray, 搭建443端口的fq都不行，非443就能连

**Comment by keengrass** [comment]
因为443的https被河协了。

**Comment by keengrass** [comment]
奇怪的是http的网址能正常访问。我估计是不是过了这几天，会恢复。

**Comment by Jrohy** [comment]
不测试了，443的感觉都被阻断了，到不了服务器后台，http是80就没问题

**Comment by Jrohy** [comment]
过了特殊日子后情况应该会好点

**Comment by keengrass** [comment]
麻烦你了。其他人的是不是也是被G.F..W干扰所致。估计流量大的有可能吧

**Comment by ancct** [comment]
> 过了特殊日子后情况应该会好点



> 麻烦你了。其他人的是不是也是被G.F..W干扰所致。估计流量大的有可能吧

前台做一个网站，天天更新。二级域名多一些，然后挑一个域名混在正常域名里。

**Comment by keengrass** [comment]
> > 过了特殊日子后情况应该会好点
> 
> > 麻烦你了。其他人的是不是也是被G.F..W干扰所致。估计流量大的有可能吧
> 
> 前台做一个网站，天天更新。二级域名多一些，然后挑一个域名混在正常域名里。

感谢。我感觉这种不搭建正常网站的将来都是这样大面积被BL.OCK
