### ISSUE TITLE
nginx设置反向代理不显示日志

### ISSUE THREAD

**Issue by EndlessJY** [Jrohy/trojan#434]
nginx设置反向代理后，在web管理界面，日志处空白，无法显示，取消反向代理正常，求解，谢谢！

**Comment by Jrohy** [comment]
是不是nginx配置有问题，参考下wiki修改https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

**Comment by EndlessJY** [comment]
在宝塔面板新建站点，设置的反向代理，检查了很多遍，没有问题撒.尴尬...
