### ISSUE TITLE
用Caddy转发请求，浏览器会直接下载web html文件

### ISSUE THREAD

**Issue by heziheng** [Jrohy/trojan#435]
改了web端口为81,用caddy转发请求，Caddyfile中配置如下
http://example.com:80 {
    gzip
    proxy / localhost:81 {
        transparent
    }
}
访问http://example.com会直接下载html
访问http://example.com:81没有问题，正常显示网页
老版本没有问题，今天更新到最新版之后出了这个问题

**Comment by Jrohy** [comment]
新版路由变了，参考下nginx的wiki配置来对应修改下: https://github.com/Jrohy/trojan/wiki/nginx%E9%85%8D%E7%BD%AE

**Comment by heziheng** [comment]
跟路由没什么关系，上面的配置不用考虑路由，是直接把web放到二级域名根路径了。我再查一下吧
