### ISSUE TITLE
关于导入导出问题

### ISSUE THREAD

**Issue by EndlessJY** [Jrohy/trojan#439]
由于实际需求，需要批量导入用户，手动输入效率实在太低，想请问Jrohy大神：
导出的“passwordShow”这一项是base64编码后的密码；
“password”这一长串是什么？对长度有要求么(还是必须56位)？导入时这一项应该怎么处理？
望解答，谢谢！

**Comment by Jrohy** [comment]
导入导出不是用来建用户的，是备份还原的

**Comment by Jrohy** [comment]
password是ssha224加密过后的字段

**Comment by EndlessJY** [comment]
> password是ssha224加密过后的字段

明白，谢谢！
