### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by xiran2018** [Jrohy/trojan#440]
go语言的小白，请教一下为什么整个代码知识看到了后段的代码，前段的代码放到哪里了，是怎么集成进来的？我也看到了trojan-web整个github项目，但是不明白trojan和trojan-web是如何集成起来的，请指教

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan/blob/817af4ee36acd1991f76ea89a0d57d5602a04a7a/web/web.go#L148-L156
这里指明了前端文件的路由处理

**Comment by xiran2018** [comment]
谢谢回复哈！
也就是说，编译trojan代码的时候，需要把trojan-web整个项目先编译好，然后把编译好的trojan-web项目的文件放到trojan项目的templates目录，再编译trojan项目，对吗？

**Comment by Jrohy** [comment]
是的前端编译好将文件放到trojan/web/templates目录下面就可以编译后端了

**Comment by xiran2018** [comment]
好的，谢谢您的答复，受教了
