### ISSUE TITLE
设置到期日期不起作用

### ISSUE THREAD

**Issue by xiran2018** [Jrohy/trojan#441]
我设置了到期日期，但是不知道为什么不起作用呢，比如今天是2021-5-20，为了测试该功能是否可用，我通过数据库直接把到期日期设置为了2021-5-19，但是依然可以跳到外面上google，不知道为什么，是我不能自己该数据库设置吗，还是说我哪里设置的不对？

**Comment by Jrohy** [comment]
每天北京时间0点才去检测是否过期的，过期了的会将流量上限设置为0

**Comment by xiran2018** [comment]
哦，好的，谢谢回复，回复的好及时

**Comment by Jrohy** [comment]
而且是进行字符串的对比，等到今晚21号0点时，会将到期日期是20号的置0，20号前(比如19号)的并不会处理，因为正常来说都处理过了

**Comment by Jrohy** [comment]
> 而且是进行字符串的对比，等到今晚21号0点时，会将到期日期是20号的置0，20号前(比如19号)的并不会处理，因为正常来说都处理过了

2.10.3.2版本做了优化，现在20号前都会处理了
