### ISSUE TITLE
[FATAL] fatal: use_certificate_chain_file: No such file or directory

### ISSUE THREAD

**Issue by MarsGao** [Jrohy/trojan#442]
甲骨文云，Canonical-Ubuntu-20.04-2021.04.15-0，CentOS也试过，同样的感觉证书没有正常取得。Trojan不停重启。无法使用。才疏学浅，还请大佬们指导。

**Comment by Jrohy** [comment]
没申请到证书，看下申请证书的日志

**Comment by feodorren** [comment]
> 甲骨文云，Canonical-Ubuntu-20.04-2021.04.15-0，CentOS也试过，同样的感觉证书没有正常取得。Trojan不停重启。无法使用。才疏学浅，还请大佬们指导。
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

同样的问题，等待大佬协助解决！
