### ISSUE TITLE
请问大佬可以支持下ARM设备吗？

### ISSUE THREAD

**Issue by zhucaidan** [Jrohy/trojan#443]
正在安装trojan管理程序..
Please run this script on x86_64 machine.

**Comment by Jrohy** [comment]
trojan核心不支持arm, 所以顺带也没编译arm版了。https://github.com/trojan-gfw/trojan/releases

**Comment by zhucaidan** [comment]
啊。。这。。

**Comment by zhucaidan** [comment]
trojan go好像支持啊
https://github.com/p4gefau1t/trojan-go/releases

**Comment by Jrohy** [comment]
![image](https://user-images.githubusercontent.com/12463263/119611755-b1291f00-be2d-11eb-9efe-f49a3c6bcd8e.png)
是aarch64的架构吗

**Comment by zhucaidan** [comment]
对的，aarch64

**Comment by Jrohy** [comment]
2.10.3.3已添加arm64的包了，试试能否安装呗，在arm64的机器上

**Comment by zhucaidan** [comment]
> 2.10.3.3已添加arm64的包了，试试能否安装呗，在arm64的机器上

刚安装后后台管理HTTPS进不去说不受支持的协议，http可以进去

**Comment by Jrohy** [comment]
证书申请成功了吗

**Comment by zhucaidan** [comment]
Trojan客户端连上打开网页提示 ERR_CONNECTION_CLOSED
日志：tls handshake failed | tls: unsupported certificate curve (P-256)

证书是申请成功的，我看到ssh界面出来key了

**Comment by zhucaidan** [comment]
trojan-go 启动日志：
[INFO]  2021/05/26 08:52:13 trojan-go v0.10.2 initializing
[WARN]  2021/05/26 08:52:13 empty tls fallback port
[WARN]  2021/05/26 08:52:13 empty tls http response
[INFO]  2021/05/26 08:52:13 buffered data has been written into the database
[INFO]  2021/05/26 08:52:13 buffered data has been written into the database
[ERROR] 2021/05/26 08:52:13 github.com/p4gefau1t/trojan-go/tunnel/router.NewClient:client.go:317 open /usr/bin/trojan/geoip.dat: no such file or directory
[ERROR] 2021/05/26 08:52:27 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | EOF
[ERROR] 2021/05/26 08:52:27 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | EOF
[ERROR] 2021/05/26 08:52:27 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | EOF
[ERROR] 2021/05/26 08:52:27 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | EOF
[ERROR] 2021/05/26 08:52:27 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | EOF
[ERROR] 2021/05/26 08:52:31 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed

trojan点切换类型无反应，没有在切换

**Comment by Jrohy** [comment]
数据库是你自己手动安装的吗，我发现源码里mariadb还是x86架构的😂，还有docker软件也是自己手动安装的吗

**Comment by zhucaidan** [comment]
> 数据库是你自己手动安装的吗，我发现源码里mariadb还是x86架构的😂，还有docker软件也是自己手动安装的吗

不是啊，都是一件安装命令自动装的😂

**Comment by Jrohy** [comment]
那看来mariadb镜像是支持多架构的，无需改代码😂， 切换肯定切换不了，因为trojan没有arm架构，现在默认安装都是trojan-go, 应该报错消息提示有问题

**Comment by Jrohy** [comment]
看下/usr/local/etc/trojan/config.json, 里面有写证书路径的

**Comment by zhucaidan** [comment]
证书文件都在，但是这俩不存在：
    "geoip": "/usr/share/trojan-go/geoip.dat",
    "geosite": "/usr/share/trojan-go/geosite.dat"

**Comment by Jrohy** [comment]
这是配置文件里面写着的吗

**Comment by zhucaidan** [comment]
是的，全文件如下：

{
  "run_type": "server",
  "local_addr": "0.0.0.0",
  "local_port": 443,
  "remote_addr": "127.0.0.1",
  "remote_port": 80,
  "password": null,
  "ssl": {
    "cert": "/root/.acme.sh/xxx_ecc/fullchain.cer",
    "key": "/root/.acme.sh/xxx_ecc/cdn-kr3.juzi.gq.key",
    "sni": "xxx"
  },
  "router": {
    "enabled": true,
    "block": ["geoip:private"],
    "geoip": "/usr/share/trojan-go/geoip.dat",
    "geosite": "/usr/share/trojan-go/geosite.dat"
  },
  "mysql": {
    "enabled": true,
    "server_addr": "127.0.0.1",
    "server_port": 3xxxx,
    "database": "trojan",
    "username": "root",
    "password": "xxx",
    "cafile": ""
  }
}

**Comment by zhucaidan** [comment]
> 这是配置文件里面写着的吗

是的，全文件如下：

{
"run_type": "server",
"local_addr": "0.0.0.0",
"local_port": 443,
"remote_addr": "127.0.0.1",
"remote_port": 80,
"password": null,
"ssl": {
"cert": "/root/.acme.sh/xxx_ecc/fullchain.cer",
"key": "/root/.acme.sh/xxx_ecc/xxx.key",
"sni": "xxx"
},
"router": {
"enabled": true,
"block": ["geoip:private"],
"geoip": "/usr/share/trojan-go/geoip.dat",
"geosite": "/usr/share/trojan-go/geosite.dat"
},
"mysql": {
"enabled": true,
"server_addr": "127.0.0.1",
"server_port": 3xxxx,
"database": "trojan",
"username": "root",
"password": "xxx",
"cafile": ""
}
}

**Comment by Jrohy** [comment]
确实有问题，可能现在全新安装都安装不了了，包括x86架构的，我紧急修复下😂

**Comment by Jrohy** [comment]
运行trojan updateWeb更新新版后，删掉这个trojan配置文件，再运行trojan update试试

**Comment by Jrohy** [comment]
source <(curl -sL https://git.io/trojan-install) --remove

**Comment by Jrohy** [comment]
还有切换trojan失败的消息提示也一起更新了

**Comment by zhucaidan** [comment]
卸载后重装，安装时候有几处失败，然后就最后也装不上。。
---
Installing trojan server config to /usr/local/etc/trojan/config.json...
bash: line 89: /usr/local/etc/trojan/config.json: No such file or directory
Failed to restart trojan.service: Unit trojan.service not found.
Failed to enable unit: Unit file trojan.service does not exist.
open /usr/local/etc/trojan/config.json: no such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
---
open /usr/local/etc/trojan/config.json: no such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
Failed to restart trojan.service: Unit trojan.service not found.
重启trojan失败!
---
生成随机用户名: xxx, 使用直接回车, 否则输入自定义用户名: 
open /usr/local/etc/trojan/config.json: no such file or directory
unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3d636c]
---
goroutine 1 [running]:
trojan/core.GetMysql(...)
        /home/go/trojan/core/server.go:76
trojan/trojan.AddUser()
        /home/go/trojan/trojan/user.go:41 +0x11c
trojan/trojan.InstallMysql()
        /home/go/trojan/trojan/install.go:193 +0x538
trojan/cmd.check()
        /home/go/trojan/cmd/root.go:35 +0xb0
trojan/cmd.mainMenu()
        /home/go/trojan/cmd/root.go:41 +0x20
trojan/cmd.glob..func9(0xc2f140, 0xc69940, 0x0, 0x0)
        /home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0xc2f140, 0x40001041f0, 0x0, 0x0, 0xc2f140, 0x40001041f0)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0xc2f140, 0x158fc, 0x400003e768, 0x44c78)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
trojan/cmd.Execute()
        /home/go/trojan/cmd/root.go:23 +0x30
main.main()
        /home/go/trojan/main.go:6 +0x20
浏览器访问'https://域名'可在线trojan多用户管理

**Comment by zhucaidan** [comment]
卸载后安装的，安装后有几处错误，之后就装不上了：
Installing trojan 0.10.2 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
bash: line 89: /usr/local/etc/trojan/config.json: No such file or directory
Failed to restart trojan.service: Unit trojan.service not found.
Failed to enable unit: Unit file trojan.service does not exist.
open /usr/local/etc/trojan/config.json: no such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory


Add '--force' to force to renew.
open /usr/local/etc/trojan/config.json: no such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
Failed to restart trojan.service: Unit trojan.service not found.
重启trojan失败!

生成随机用户名: xxx, 使用直接回车, 否则输入自定义用户名: xxx
open /usr/local/etc/trojan/config.json: no such file or directory
unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3d636c]

goroutine 1 [running]:
trojan/core.GetMysql(...)
        /home/go/trojan/core/server.go:76
trojan/trojan.AddUser()
        /home/go/trojan/trojan/user.go:41 +0x11c
trojan/trojan.InstallMysql()
        /home/go/trojan/trojan/install.go:193 +0x538
trojan/cmd.check()
        /home/go/trojan/cmd/root.go:35 +0xb0
trojan/cmd.mainMenu()
        /home/go/trojan/cmd/root.go:41 +0x20
trojan/cmd.glob..func9(0xc2f140, 0xc69940, 0x0, 0x0)
        /home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0xc2f140, 0x40001041f0, 0x0, 0x0, 0xc2f140, 0x40001041f0)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0xc2f140, 0x158fc, 0x400003e768, 0x44c78)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
trojan/cmd.Execute()
        /home/go/trojan/cmd/root.go:23 +0x30
main.main()
        /home/go/trojan/main.go:6 +0x20
浏览器访问

**Comment by Jrohy** [comment]
嗯我也发现了

**Comment by Jrohy** [comment]
好了现在版本安装没问题了脚本

**Comment by zhucaidan** [comment]
![image](https://user-images.githubusercontent.com/47970938/119641008-0e8d8380-bdce-11eb-996e-eae7bb928209.png)
![image](https://user-images.githubusercontent.com/47970938/119641264-53b1b580-bdce-11eb-9444-74bf3ee61536.png)

又恢复了第一次的故障🤣

**Comment by Jrohy** [comment]
arm架构的是能安装上了，不知道为啥trojan-go翻不了，trojan就可以翻

**Comment by zhucaidan** [comment]
不应该啊，按道理trojan-go是可以跑在arm64软路由上的，trojan以前可以现在好像不行，有可能是xray落地转的trojan

**Comment by Jrohy** [comment]
唉换成上一个版本的trojan-go就可以了，感觉今天发布的082版本有问题😨, 你可以试下

**Comment by Jrohy** [comment]
下载这个https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.0, 解压出来名字改成trojan， 替换到/usr/bin/trojan,目录后，再授权chmod +x trojan, 再重启trojan restart 就好了

**Comment by zhucaidan** [comment]
可以了，难不成新版有什么bug😁

**Comment by Jrohy** [comment]
应该是，相同配置文件新版就不行了，按着新版的配置文件配ssl那一组都不行

**Comment by Jrohy** [comment]
我还是改下全新安装的trojan安装逻辑，x86的默认安装trojan,arm64才默认安装trojan-go

**Comment by BrunuhVille** [comment]
> 下载这个https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.0, 解压出来名字改成trojan， 替换到/usr/bin/trojan/目录后，再授权chmod +x trojan, 再重启trojan restart 就好了

大佬，这个是下载trojan-go-linux-arm.zip还是arm有带v的版本，有armv6 v7 v8的

**Comment by Jrohy** [comment]
v8的, arm64版本 @BrunuhVille

**Comment by hc050817** [comment]
大佬这个支持ARM是不是，昨天的甲骨文云新增的免费机是ARM架构的缘故啊，感觉好多兄弟都撸了甲骨文云

**Comment by mzt1988** [comment]
> 数据库是你自己手动安装的吗，我发现源码里mariadb还是x86架构的😂，还有docker软件也是自己手动安装的吗

ARM机器，有时候账户信息无法写入数据库

**Comment by zhucaidan** [comment]
> > 数据库是你自己手动安装的吗，我发现源码里mariadb还是x86架构的😂，还有docker软件也是自己手动安装的吗
> 
> ARM机器，有时候账户信息无法写入数据库

DD个干净的Debian系统，没有什么问题
