### ISSUE TITLE
面板升级到最新，trojan-go升级到0.10.2之后，登录web控制面板崩了。

### ISSUE THREAD

**Issue by pprice2018** [Jrohy/trojan#444]
面板升级到最新，trojan-go升级到0.10.2之后，登录web控制面板提示ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by pprice2018** [comment]
重新把Trojan-go降级到0.10.0，重启Trojan，web面板又重新正常。

**Comment by Jrohy** [comment]
trojan-go不建议升到0.10.2版本，我试了按着给的模板json配置都没法使用

**Comment by ZichengLouche** [comment]
> 重新把Trojan-go降级到0.10.0，重启Trojan，web面板又重新正常。

1，你是怎么重新把Trojan-go降级到0.10.0的？是通过Jrohy一键脚本先完全卸载，然后再通过一键脚本重新执行一遍安装的吗？

2，不知道能不能不通过一键脚本全部卸载，就像通过trojan update命令局部升级一样，也能有个命令来局部降级到指定版本？

**Comment by Jrohy** [comment]
@ZichengLouche 新版已经支持回退版本了, `trojan update 0.10.0`就行

**Comment by ZichengLouche** [comment]
> 
> 
> @ZichengLouche 新版已经支持回退版本了, `trojan update 0.10.0`就行

非常感谢您及时、快速响应的提供的新版本功能，赞！
