### ISSUE TITLE
切换trojan-go无法翻墙了

### ISSUE THREAD

**Issue by gwhcn** [Jrohy/trojan#445]
Started trojan-go.
[INFO]  2021/05/27 02:24:51 trojan-go v0.10.2 initializing
[WARN]  2021/05/27 02:24:51 empty tls fallback port
[WARN]  2021/05/27 02:24:51 empty tls http response
[INFO]  2021/05/27 02:24:51 buffered data has been written into the database
[INFO]  2021/05/27 02:24:51 buffered data has been written into the database
[INFO]  2021/05/27 02:24:52 tcp connection from xxx.34.xxx.xxx:49857
[ERROR] 2021/05/27 02:24:52 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:142 tls handshake failed | tls: unsupported certificate curve (P-256)

而且开启后https://xxxx无法访问web控制页面，使用了不受支持的协议。用http://可以访问web控制页面
切换trojan一切正常

Version: v2.10.3.6

BuildDate: 20210526-1847

GoVersion: go1.16.4 linux/amd64

TrojanVersion: 1.16.0

TrojanRunTime: 04:22

**Comment by Jrohy** [comment]
v0.10.2版本有问题, 回退回旧版就没问题

**Comment by gwhcn** [comment]
> v0.10.2版本有问题, 回退回旧版就没问题

怎么回退？求教

**Comment by Jrohy** [comment]
下载这个https://github.com/p4gefau1t/trojan-go/releases/tag/v0.10.0, 解压出来名字改成trojan， 替换到/usr/bin/trojan/目录后，再授权chmod +x trojan, 再重启trojan restart 就好了
