### ISSUE TITLE
可以添加一个选择内核版本的功能吗？

### ISSUE THREAD

**Issue by kongbai39** [Jrohy/trojan#446]

**Comment by kongbai39** [comment]
或者是回退上一个版本的功能

**Comment by Jrohy** [comment]
下个版本加下通过命令行回滚

**Comment by Jrohy** [comment]
新版已支持命令行安装指定版本了， 比如`trojan update v0.10.0`

**Comment by kongbai39** [comment]
不用区分原版和go版吗

**Comment by Jrohy** [comment]
本来安装了什么就更新什么的，要切换进去trojan管理那里切换

**Comment by kongbai39** [comment]
好的，谢谢

**Comment by hc050817** [comment]
> 本来安装了什么就更新什么的，要切换进去trojan管理那里切换

大佬，trojan-go有没有可能实现在web面板内实现套CDN的功能（我只是假想一下），这样操作的话会非常方便。

**Comment by Jrohy** [comment]
@hc050817 不考虑，套cdn可以用v2ray/xray
