### ISSUE TITLE
请问可以添加账号限速功能

### ISSUE THREAD

**Issue by lqh9724** [Jrohy/trojan#447]
J大您好，添加账号限速功能是否能够实现呢。
共享给太多人用了，流量消耗太快了点，夜间高峰期看后台的数据，下行流量都消耗的很快，主要还是速度太快了，寻思着能给一些用户账号限速一下也许会好一些

**Comment by Jrohy** [comment]
trojan-go的api功能才能实现，但目前看反馈有bug: https://github.com/p4gefau1t/trojan-go/issues/216

**Comment by hc050817** [comment]
> J大您好，添加账号限速功能是否能够实现呢。
> 共享给太多人用了，流量消耗太快了点，夜间高峰期看后台的数据，下行流量都消耗的很快，主要还是速度太快了，寻思着能给一些用户账号限速一下也许会好一些

直接设置多个账号，进行限制流量使用，跑的多就用的时间就短，前提是分享的人不多的情况下，如果你是做公益的话还是要等限速功能完善...

**Comment by lqh9724** [comment]
> trojan-go的api功能才能实现，但目前看反馈有bug: [p4gefau1t/trojan-go#216](https://github.com/p4gefau1t/trojan-go/issues/216)

了解，感谢J大解答

**Comment by lqh9724** [comment]
> > J大您好，添加账号限速功能是否能够实现呢。
> > 共享给太多人用了，流量消耗太快了点，夜间高峰期看后台的数据，下行流量都消耗的很快，主要还是速度太快了，寻思着能给一些用户账号限速一下也许会好一些
> 
> 直接设置多个账号，进行限制流量使用，跑的多就用的时间就短，前提是分享的人不多的情况下，如果你是做公益的话还是要等限速功能完善...

半公益吧，都是熟识的朋友同事在用。目前就是分配单人单账号限制流量
