### ISSUE TITLE
使用了不受支持的协议

### ISSUE THREAD

**Issue by linkea131** [Jrohy/trojan#448]
使用了不受支持的协议
![Screenshot_20210531_062822](https://user-images.githubusercontent.com/50718406/120122229-23a55080-c1da-11eb-900f-32395963aab0.jpg)

**Comment by linkea131** [comment]
切换为Trojan-Go后无法使用 网页也打不开 麻烦修复一下 Trojan正常

**Comment by Jrohy** [comment]
回退一下trojan-go版本就行, https://github.com/p4gefau1t/trojan-go/issues/349

**Comment by linkea131** [comment]
怎么回退?

**Comment by Jrohy** [comment]
新版支持'trojan update 0.10.0'回退版本
