### ISSUE TITLE
请问和multi-v2ray一起安装，可以共用443端口吗？

### ISSUE THREAD

**Issue by oyanli** [Jrohy/trojan#45]
感谢大神在我提出请求后，这么快就做出了trojan的安装项目，感谢、感谢！！

在这里有个问题，想请问一下和大神你的multi-v2ray一起安装，可以共用443端口吗？

**Comment by Jrohy** [comment]
不可以的，trojan要用443端口

**Comment by oyanli** [comment]
好的，我现在用一键安装命令装不上，提示

Creating trojan install directory
Entering temp directory /tmp/tmp.VYIi4apDgH...
Downloading trojan 1.15.1...
######################################################################## 100.0%
Unpacking trojan 1.15.1...
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to restart trojan.service: Unit trojan.service not found.
Failed to enable unit: File trojan.service: No such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x89ad83]

请问怎么解决？

**Comment by Jrohy** [comment]
安裝一下xz-utils

**Comment by oyanli** [comment]
安装了xz-utils后可以了，一键脚本可以正常安装了，但是获取完证书以后提示安装mysql，请问mysql是一定要安装的吗

[Sun Apr  5 01:26:24 EDT 2020] _on_issue_success
重启trojan成功!


1.安装docker版mysql

2.输入自定义mysql连接

请选择:

**Comment by Jrohy** [comment]
多用户需要的
