### ISSUE TITLE
升级后，Web管理面板https无法打开，http正常

### ISSUE THREAD

**Issue by hackenwu** [Jrohy/trojan#450]
升级后，Web管理面板https无法打开，http正常可管理用户，由于https不正常，连接也无法使用。重新安装证书也一样不行。

**Comment by Jrohy** [comment]
trojan可以使用吗, https是trojan提供的

**Comment by hackenwu** [comment]
> trojan可以使用吗, https是trojan提供的

trojan无法使用

**Comment by Jrohy** [comment]
证书有问题

**Comment by keengrass** [comment]
我也遇到这个问题，是今天6.4的原因吗？

**Comment by keengrass** [comment]
> 证书有问题

请问有解决方法吗？

**Comment by hackenwu** [comment]
> 我也遇到这个问题，是今天6.4的原因吗？

上周我就遇见了，但后面重新安装证书就可以，问题在昨天突然又不行了。

**Comment by keengrass** [comment]
> > 我也遇到这个问题，是今天6.4的原因吗？
> 
> 上周我就遇见了，但后面重新安装证书就可以，问题在昨天突然又不行了。

我之前曾反反复复遇到这个问题，基本上重启或是重申证书解决。但有时就是隔半天或一天就重复。我觉得不止我们，还有很多人都会遇到这个问题。我今天trojan又不行了。重启VPS无用。重装证书无用。不清楚是什么原因？http能打开，https不能，我感觉问题出在证书上。

**Comment by jackxin900** [comment]
同样遇到了这个问题，证书在有效期内，但是无法打开https的页面，也无法连接trojan

**Comment by earth-5G** [comment]
> 同样遇到了这个问题，证书在有效期内，但是无法打开https的页面，也无法连接trojan

操 我也是遇到了 看来Trojan这个技术被找到漏洞了！  大神快来更新下呢！

**Comment by Jrohy** [comment]
@earth-5G 我试了下 搭建xray也不行， 阻断了443的连接，请求不到服务端，非443端口的协议就可以连

**Comment by kongbai39** [comment]
现在443被大面积阻断了

**Comment by earth-5G** [comment]
> @earth-5G 我试了下 搭建xray也不行， 阻断了443的连接，请求不到服务端，非443端口的协议就可以连

大佬又没什么办法能解决下呢！！封锁越来越严重了！这是无差别大面积封锁嘛？

**Comment by earth-5G** [comment]
> @earth-5G 我试了下 搭建xray也不行， 阻断了443的连接，请求不到服务端，非443端口的协议就可以连

通过http其实也是能访问后台的，并且看上去一切都正常！甚至网速哪里还有流量在上下走动！

并且我如果是手机用纯4G网络也是可以上后台。

当然翻墙依然不行！

吾等小白也只能等大神们想想办法。别的事想帮忙也是有心无力了！

**Comment by Jrohy** [comment]
@earth-5G 等这两天特殊日子过去

**Comment by earth-5G** [comment]
> @earth-5G 等这两天特殊日子过去

好，收到 谢谢！

**Comment by fengmikaelson** [comment]
> 我也遇到这个问题，是今天6.4的原因吗？

刚反应过来今天4号。。。trojan之前不管什么节日都没问题，没想到今天遭殃了= =
