### ISSUE TITLE
刚部署完重启log里会有mysql连接失败错误？

### ISSUE THREAD

**Issue by fengmikaelson** [Jrohy/trojan#451]
Welcome to trojan 1.16.0
[2021-06-04 11:36:27] [FATAL] fatal: Can't connect to MySQL server on '127.0.0.1' (115)
[2021-06-04 11:36:27] [FATAL] exiting. . .
trojan.service: main process exited, code=exited, status=1/FAILURE
Unit trojan.service entered failed state.
trojan.service failed.
trojan.service holdoff time over, scheduling restart.
Started trojan.
Welcome to trojan 1.16.0
Starting trojan...
[2021-06-04 11:36:31] [FATAL] fatal: Lost connection to MySQL server at 'handshake: reading initial communication packet', system error: 11
[2021-06-04 11:36:31] [FATAL] exiting. . .
trojan.service: main process exited, code=exited, status=1/FAILURE
Unit trojan.service entered failed state.
trojan.service failed.
trojan.service holdoff time over, scheduling restart.
Started trojan.
Starting trojan...
Welcome to trojan 1.16.0

今天早上突然一直报SSL证书错误，重新生成证书也不行，无奈备份重装了。

结果一开机就这个错误了。

现在也依旧无法访问。。

装的是docker版的mariadb
![image](https://user-images.githubusercontent.com/10394327/120742565-b40cc980-c529-11eb-8290-a25e4cd1328a.png)
![image](https://user-images.githubusercontent.com/10394327/120742577-bb33d780-c529-11eb-8bdb-82cea298de77.png)
![image](https://user-images.githubusercontent.com/10394327/120742636-d43c8880-c529-11eb-96ec-022dd150ed29.png)

**Comment by Qlmuby** [comment]
我也是，问题和你一模一样

**Comment by fengmikaelson** [comment]
> 我也是，问题和你一模一样

另一台服务器目前一模一样的配置，是正常的。。。
我都不敢去动了。。。

**Comment by fengmikaelson** [comment]
![image](https://user-images.githubusercontent.com/10394327/120751027-e6bebe00-c539-11eb-9e96-2eaac19d3058.png)

**Comment by fengmikaelson** [comment]
![image](https://user-images.githubusercontent.com/10394327/120751140-15d52f80-c53a-11eb-880c-a98ac91a008f.png)
