### ISSUE TITLE
关于今天出现的问题的猜想和建议

### ISSUE THREAD

**Issue by Qlmuby** [Jrohy/trojan#454]
今天新提的那几个问题都是同一个问题，症状都一样，应该的特殊的日子被阻断了没错，但所幸应该不是被识别了，根据我自身的情况猜测，应该是根据使用流量多少来阻断的，我用的少的两台机器没事，用的多的两台被阻断了，而且只针对443端口，也就是https，通过这次的情况，大佬会不会在下个版本中更新自定义端口的功能？我以前用过一个叫v2-ui的综合面板，它那个就是可以直接自定义端口，大佬有空可以去了解一下它那个面板，我觉得应该会有值得借鉴的地方，比如它那个复制节点链接是个按钮，咱这个是先选中再复制，虽然是个小细节，但是真的方便很多，它不如trojan面板的地方是没有流量控制，而且新建节点太繁琐，要是能设定个模板，批量新建节点就好了。总体俩种面板各有千秋，要是能把两者的优点融合一下就完美了。

**Comment by earth-5G** [comment]
我这里还没好贵州贵阳，你那里好了没！

**Comment by Qlmuby** [comment]
> 我这里还没好贵州贵阳，你那里好了没！

我这里好了

**Comment by earth-5G** [comment]
> > 我这里还没好贵州贵阳，你那里好了没！
> 
> 我这里好了

wo我这里晚上开始也恢复了！

但是我觉得这个技术是不是也需要升级跟进了呢！！

至少Trojan这个技术之前是没有任何问题的！不管什么时间节点！

这次会不会是这个技术被突破的一个前兆呢？

**Comment by Jrohy** [comment]
@earth-5G 我试了xray建443端口都是一样被阻断。

**Comment by earth-5G** [comment]
> @earth-5G 我试了xray建443端口都是一样被阻断。

wozhe我这里手机上使用和iPad使用都没有任何问题！

电脑上使用，gmail能用，电报能用，但是谷歌主页打不开，YouTube能开网页，视频无法加载！

估计恢复还要等等！

**Comment by fengmikaelson** [comment]
我这里昨天恢复了，今天又不行了

**Comment by Hikpy** [comment]
> 我这里昨天恢复了，今天又不行了

今天恢复了吗

**Comment by ckbkdj** [comment]
兄弟 好好看看是不是申请了https的证书



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月10日(星期四) 下午3:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [Jrohy/trojan] 关于今天出现的问题的猜想和建议 (#454)





  
我这里昨天恢复了，今天又不行了
  
今天恢复了吗
 
&mdash;

**Comment by ancct** [comment]
主域跳转到www.，然后www.做一个WEB服务，各种搜索引擎收录上上。然后站点开二级域名，video.放视频，img.放图片，m.是移动版，最后开个二级域名cdn.做梯子。现在主域权3，每日流量3000+，梯子服务器流量很大也非常稳。

**Comment by earth-5G** [comment]
> 主域跳转到www.，然后www.做一个WEB服务，各种搜索引擎收录上上。然后站点开二级域名，video.放视频，img.放图片，m.是移动版，最后开个二级域名cdn.做梯子。现在主域权3，每日流量3000+，梯子服务器流量很大也非常稳。

有没有一些具体的操作教程呢，这个不太看懂勒！

我们是伸手党  小白菜，大佬们能否搞细致点！
