### ISSUE TITLE
还是证书问题

### ISSUE THREAD

**Issue by xuubear** [Jrohy/trojan#456]
vps一切正常，节点用不了。用http不管是域名还是ip可以直接进web管理界面 但一用https后进不了web管理界面。用trojan tls重新申请证书无用.重启vps也无用.全新安装也是无法使用.大佬如果在我给我vps的管理权你帮看下是什么问题.谢谢.

**Comment by ajiter** [comment]
[INFO]  2021/06/07 11:48:14 trojan-go v0.10.4 initializing
[WARN]  2021/06/07 11:48:14 empty tls fallback port
[WARN]  2021/06/07 11:48:14 empty tls http response
[FATAL] 2021/06/07 11:48:14 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Failed with result 'exit-code'.
trojan.service: Scheduled restart job, restart counter is at 183.
Stopped trojan-go.
Started trojan-go.
[INFO]  2021/06/07 11:48:18 trojan-go v0.10.4 initializing
[WARN]  2021/06/07 11:48:18 empty tls fallback port
[WARN]  2021/06/07 11:48:18 empty tls http response
[FATAL] 2021/06/07 11:48:18 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 tls failed to load key pair
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Failed with result 'exit-code'.

**Comment by Jrohy** [comment]
没申请到证书

**Comment by ajiter** [comment]
大佬。我之前是能用的啊。怎么突然证书就消失了呢。

**Comment by Jrohy** [comment]
重新申请证书看看申请日志

**Comment by ajiter** [comment]
我又重新申请过二级域名。重新申请证书问题已经解决了。好纳闷。用着好好的不用能。然后证书没有了。

**Comment by ajiter** [comment]
我又重新绑定一个全新的二级域名。重新申请证书问题已经解决了。好纳闷。用着好好的不用能。然后证书没有了。

**Comment by ajiter** [comment]
用着好好的。又复现一楼问题。这是日志。谢谢大佬
[INFO]  2021/06/10 02:30:42 trojan-go v0.10.0 initializing
[WARN]  2021/06/10 02:30:42 empty tls fallback port
[WARN]  2021/06/10 02:30:42 empty tls http response
[FATAL] 2021/06/10 02:30:42 github.com/p4gefau1t/trojan-go/proxy.(*Node).BuildNext:stack.go:29 invalid redirect address. check your http server: 127.0.0.1:80 | dial tcp 127.0.0.1:80: connect: connection refused
trojan.service: Main process exited, code=exited, status=1/FAILURE
trojan.service: Failed with result 'exit-code'.
trojan.service: Service RestartSec=3s expired, scheduling restart.
trojan.service: Scheduled restart job, restart counter is at 1.

**Comment by Jrohy** [comment]
@ajiter 要启动个80端口的服务(nginx或者trojan-web都行), trojan-go检测到redirect 地址连不通的话就会启动失败的

**Comment by ajiter** [comment]
> @ajiter 要启动个80端口的服务(nginx或者trojan-web都行), trojan-go检测到redirect 地址连不通的话就会启动失败的

7.1这几天根本不能用。我的ip没有被墙。现在被劫流了。
[2021-07-01 22:06:16] [ERROR] 8.45.41.232:35258 SSL handshake failed: stream truncated
