### ISSUE TITLE
证书申请失败，acme有变动

### ISSUE THREAD

**Issue by BrunuhVille** [Jrohy/trojan#459]
trojan申请证书失败
“acme.sh 签 ZeroSSL 要多加个参数”
“现在很多依赖 acme.sh 的项目还没反应过来 (”
“这次改得，措手不及”
听群里大佬说的，不知道具体什么情况
。。。
acme.sh --set-default-ca --server letsencrypt
大佬说申请letsencrypt用这个

**Comment by BrunuhVille** [comment]
./acme.sh --set-default-ca --server letsencrypt
手动申请试了下，先设置默认ca为letsencrypt
再去申请就正常了

**Comment by pirately** [comment]
> ./acme.sh --set-default-ca --server letsencrypt
> 手动申请试了下，先设置默认ca为letsencrypt
> 再去申请就正常了
> root@doable:~/.acme.sh# ./acme.sh --set-default-ca --server letsencrypt
> [Mon 14 Jun 2021 05:36:35 PM HKT] Changed default CA to: https://acme-v02.api.letsencrypt.org/directory

这个可以。感谢。

**Comment by Jrohy** [comment]
新版已做优化

**Comment by leo-je** [comment]
> 新版已做优化

docker 版本还是报无法找到证书

**Comment by leo-je** [comment]
> > 新版已做优化
> 
> docker 版本还是报无法找到证书
部署docker镜像之后，进入容器，更新管理程序后开始自动安装，但是还是报证书问题
![image](https://user-images.githubusercontent.com/29834148/122635283-8de44d80-d115-11eb-8d1e-f8d673dc14e7.png)
然后无限重试

**Comment by leo-je** [comment]
> > > 新版已做优化
> > 
> > 
> > docker 版本还是报无法找到证书
> > 部署docker镜像之后，进入容器，更新管理程序后开始自动安装，但是还是报证书问题
> > ![image](https://user-images.githubusercontent.com/29834148/122635283-8de44d80-d115-11eb-8d1e-f8d673dc14e7.png)
> > 然后无限重试

已解决

**Comment by feodorren** [comment]
> > > > 新版已做优化
> 
> > > 
> 
> > > 
> 
> > > docker 版本还是报无法找到证书
> 
> > > 部署docker镜像之后，进入容器，更新管理程序后开始自动安装，但是还是报证书问题
> 
> > > ![image](https://user-images.githubusercontent.com/29834148/122635283-8de44d80-d115-11eb-8d1e-f8d673dc14e7.png)
> 
> > > 然后无限重试
> 
> 
> 
> 已解决

您好，这个问题还是再报，是否是证书文件夹权限没给？ 目前还未解决该问题，谢谢！

**Comment by Jrohy** [comment]
@feodorren  这是没申请到证书，看申请证书的报文日志

**Comment by XfZGGG** [comment]
> 
> 
> @feodorren 这是没申请到证书，看申请证书的报文日志

大佬你好 麻烦更新一下docker镜像

**Comment by Jrohy** [comment]
有更新的docker镜像，没申请到证书报什么呢
