### ISSUE TITLE
证书发行错误

### ISSUE THREAD

**Issue by kenablezhou** [Jrohy/trojan#460]
疑似因变更发行政策所致
![1623602272](https://user-images.githubusercontent.com/31434060/121815384-ca90ee80-cca8-11eb-9ea1-4b11c19d9722.png)

**Comment by BrunuhVille** [comment]
acme.sh --set-default-ca --server letsencrypt
听说是证书变了，要加参数指定letsencrypt

**Comment by vichen2021** [comment]
我也是

**Comment by Jrohy** [comment]
@vichen2021 试下刚发布的新版，做了相关优化了

**Comment by vichen2021** [comment]
> @vichen2021试下刚发布的新版，再相关优化了
好了好了，终于不是超时了，芜湖~

**Comment by vichen2021** [comment]
> @vichen2021试下刚发布的新版，再相关优化了

好了，终于不是超时了，芜湖~
