### ISSUE TITLE
测试还是不行

### ISSUE THREAD

**Issue by ckbkdj** [Jrohy/trojan#462]
申请证书几分钟之内可以上后面就上不去了

**Comment by ckbkdj** [comment]
重启一下又能用,不知道坚持多久,不知道哪里出了问题

**Comment by earth-5G** [comment]
> 重启一下又能用,不知道坚持多久,不知道哪里出了问题

我估计需要换域名

我的这里的情况是电脑上无法使用，能用电报，但是网页是打不开的！

手机上和平板上又是一点问题都没有！

非常的奇怪！
