### ISSUE TITLE
I want to know if the docker --privileged  command could cause some safe problem?

### ISSUE THREAD

**Issue by HillCat** [Jrohy/trojan#463]
I noticed that the trojan container has most all privileges,It is can get the host server root privilege.I want to konw if this is safe?
![image](https://user-images.githubusercontent.com/41800196/122513393-f57a9a00-d03c-11eb-9b98-5c11be6005ce.png)

**Comment by Jrohy** [comment]
因为需要在容器里面能操控systemctl的命令，得加上才行的
