### ISSUE TITLE
时间限制问题

### ISSUE THREAD

**Issue by mccyz233** [Jrohy/trojan#466]
大佬我想问一下，假如我给用户设置了一天的时间限制，那么从现在开始到时间到期是怎么算的？是24小时后过期吗？还是第二天的几点统一过期

**Comment by Jrohy** [comment]
0点检查是否过期，过期了的流量上限设置为0

**Comment by mccyz233** [comment]
> 0点检查是否过期，过期了的流量设置为0
收到，感谢

**Comment by mccyz233** [comment]
> > 0点检查是否过期，已经过期了
> > ，感谢
还有就是今天安装的时候证书申请失败显示lookup 00.xiaoh.cf on xxx server misbe1having，服务器行为异常咋整

**Comment by Jrohy** [comment]
可以换个域名看看

**Comment by mccyz233** [comment]
换了域名还是不行，但是换了vps之后却可以了，这是服务器黑了吗？

**Comment by mccyz233** [comment]
> 可以换个域名看看

换了域名还是不行，但是换了vps之后却可以了，这是服务器黑了吗？

**Comment by mccyz233** [comment]
> > 可以换个域名看看
> 
> 换了域名还是不行，但是换了vps之后却可以了，这是服务器黑了吗？

解决了，阿里云dns问题
