### ISSUE TITLE
我面板可以进，但是进去了trojan总是用不了

### ISSUE THREAD

**Issue by c455025066** [Jrohy/trojan#471]
使用的gcp安装的trojan，但是现在可以进面板，却无法翻墙出去，提示如下：
Welcome to trojan 1.16.0
[2021-06-29 07:38:51] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2021-06-29 07:38:51] [FATAL] exiting. . .
trojan.service: main process exited, code=exited, status=1/FAILURE
Unit trojan.service entered failed state.
trojan.service failed.
这是什么原因？我看有人说需要修改端口，请问大佬修改端口到底是改哪个配置文件里面的端口号？我改成445可以不？外面搜了一圈没搜到，所以求教，好人一生平安！

**Comment by Jrohy** [comment]
没申请到证书，改端口的话，运行trojan status 看到配置文件位置来改

**Comment by c455025066** [comment]
> 没申请到证书，改端口的话，运行trojan status 看到配置文件位置来改

那大佬我想问一下，我使用trojan管理命令里面的3安装管理来重新申请证书出现如下提示：
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  201k  100  201k    0     0   624k      0 --:--:-- --:--:-- --:--:--  624k
[Tue Jun 29 07:46:06 UTC 2021] Installing from online archive.
[Tue Jun 29 07:46:06 UTC 2021] Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
[Tue Jun 29 07:46:07 UTC 2021] Extracting master.tar.gz
[Tue Jun 29 07:46:07 UTC 2021] Please install openssl first. ACME_OPENSSL_BIN=openssl
[Tue Jun 29 07:46:07 UTC 2021] We need openssl to generate keys.
[Tue Jun 29 07:46:07 UTC 2021] Pre-check failed, can not install.
bash: /root/.acme.sh/acme.sh: No such file or directory
还是会一直使用不了，但是我换一个gcp账号去新建实例用你的脚本搭建的trojan就可以正常使用，是不是因为我这个gcp账号已经被封了？只能换号使用

**Comment by Jrohy** [comment]
openssl没安装，先手动安装下先

**Comment by dtfuture** [comment]
我也是同样的问题，trojan日志提示：
Welcome to trojan 1.16.0
trojan.service: main process exited, code=exited, status=1/FAILURE
[2024-06-26 08:13:15] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2024-06-26 08:13:15] [FATAL] exiting. . .
Unit trojan.service entered failed state.
trojan.service failed.
trojan.service holdoff time over, scheduling restart.
Stopped trojan.
Started trojan.
Welcome to trojan 1.16.0
trojan.service: main process exited, code=exited, status=1/FAILURE
[2024-06-26 08:13:18] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2024-06-26 08:13:18] [FATAL] exiting. . .
Unit trojan.service entered failed state.
trojan.service failed.
trojan.service holdoff time over, scheduling restart.
Stopped trojan.
Started trojan.
trojan.service: main process exited, code=exited, status=1/FAILURE
Welcome to trojan 1.16.0
[2024-06-26 08:13:22] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2024-06-26 08:13:22] [FATAL] exiting. . .
Unit trojan.service entered failed state.
trojan.service failed.
trojan.service holdoff time over, scheduling restart.
Stopped trojan.
Started trojan.

请问各位大佬这个怎么解决呢
