### ISSUE TITLE
SSL handshake failed: stream truncated

### ISSUE THREAD

**Issue by 907904228** [Jrohy/trojan#472]
报这个错是因为被墙了吗，trojan-go

**Comment by Jrohy** [comment]
后台有请求进来的日志吗，估计最近敏感日子到有加严了，可能比月初还严

**Comment by 907904228** [comment]
> 后台有请求进来的日志吗，估计最近敏感日子到有加严了，可能比月初还严

没有，请问怎么看呀，小白。。。。

**Comment by Jrohy** [comment]
trojan log, 然后运行这个节点翻翻墙看看后台有没有日志请求进来

**Comment by 907904228** [comment]
> trojan log, 然后运行这个节点翻翻墙看看后台有没有日志请求进来

报告大佬，试了几次，没有请求进来

**Comment by Jrohy** [comment]
443端口阻断了吧，换端口试试: /usr/local/etc/trojan/config.json

**Comment by 907904228** [comment]
> 443端口阻断了吧，换端口试试: /usr/local/etc/trojan/config.json

没问题，感谢！

**Comment by latermarch** [comment]
换端口也报同样的错误，但是网页能打开，telnet ip 端口号是也通的
