### ISSUE TITLE
卸载重新安装的时候 web面板无法访问 节点正常使用

### ISSUE THREAD

**Issue by misskiki** [Jrohy/trojan#474]
卸载重新安装的时候 web面板无法访问 节点正常使用

**Comment by misskiki** [comment]
还有就是 我看了docker默认启动数据库的时候是配置映射到了宿主机上。我在docker数据库里面也查看了配置了远程访问
但是我用 navicat 链接超时

**Comment by Jrohy** [comment]
访问端口和密码对不对，数据库的，得参考trojan 配置文件里面写的

**Comment by misskiki** [comment]
访问对的。我就想在外网登陆docker mardb  因为我为这个面板写了一个会员中心功能

**Comment by misskiki** [comment]
还有就是需要安装nginx吗？

**Comment by Jrohy** [comment]
改过trojan端口吗

**Comment by misskiki** [comment]
没有了。解决了这个问题。但是 还是无法解决本地链接 mardb 
  "mysql": {
    "enabled": true,
    "server_addr": "127.0.0.1",
    "server_port": 61931,
    "database": "trojan",
    "username": "root",
    "password": "uSJNQ",
    "cafile": ""
  }
![image](https://user-images.githubusercontent.com/41108094/123896761-bdf0e380-d994-11eb-8851-8452f705f98e.png)


tcp        0      0 0.0.0.0:61931           0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      off (0.00/0/0)

**Comment by Jrohy** [comment]
會不會防火墻的問題

**Comment by misskiki** [comment]
可是我的 梯子正常使用呀不应该

**Comment by misskiki** [comment]
ok 解决了 服务器商的端口没开

**Comment by misskiki** [comment]
xiexie zuozhe

**Comment by misskiki** [comment]
对了再次问一下。作者 添加用户加密的方式用的什么

**Comment by misskiki** [comment]
对了再次问一下。作者添加用户的时候加密的方式用的什么

**Comment by Jrohy** [comment]
SHA224
