### ISSUE TITLE
是什么原因，好像大家都被墙了？

### ISSUE THREAD

**Issue by sunrisely** [Jrohy/trojan#475]
我6.29，6.30这两天连续两个服务器443端口被墙，过来一看大家都被墙了。。。是出现什么问题了吗，容易被GFW发现了？只能换ip解决了吗，，，，

**Comment by Jrohy** [comment]
明天就特殊日期了，我的搬瓦工443端口还没问题(搭建trojan)

**Comment by sunrisely** [comment]
可能是因为特殊日期缘故，GFW好像变厉害了，。。。。

**Comment by Jrohy** [comment]
443端口阻断了可以换下其他端口都行

**Comment by sunrisely** [comment]
那请问一下是在哪修改配置文件，把端口位置换一下

**Comment by Jrohy** [comment]
trojan status 查看配置文件位置

**Comment by keengrass** [comment]
trojan应该只能运行在443端口下吧，请大佬明示下如何更换端口？

**Comment by sunrisely** [comment]
默认安装下，是哪个配置文件下，更改端口？我实在好像找不到是哪个。。。。😓

**Comment by Jrohy** [comment]
/usr/local/etc/trojan/config.json

**Comment by sunrisely** [comment]
然后更改端口号后，在防火墙里开启放行的那个端口号是吗？还是更改完后就直接生效？

**Comment by Jrohy** [comment]
你升级新版后就会自动放行端口的了， `trojan updateWeb`

**Comment by sunrisely** [comment]
谢谢啦，现在已经更改完端口号成功了

**Comment by ckbkdj** [comment]
换端口是不是就等于裸奔了

**Comment by keengrass** [comment]
> 谢谢啦，现在已经更改完端口号成功了

到时候反馈下，更换了端口是不是IP容易被ban.

**Comment by ckbkdj** [comment]
换端口感觉是往枪口上撞.已经封了，后面就是不停的扫描直到IP被ban

**Comment by earth-5G** [comment]
muqi目前我也没问题 贵州贵阳  之前64被阻断了2天！

**Comment by sunrisely** [comment]
> > 谢谢啦，现在已经更改完端口号成功了
> 
> 到时候反馈下，失效了端口是不是IP容易被ban。

目前还行，正常使用。。。。

**Comment by HillCat** [comment]
我想问下怎么启用trojan-go，cdn加速对于目前docker启动的貌似无效啊。443被ban之后，开启cloudfare的加速，检测到443是可以Ping了，但是v2rayN这边还是上不了。

**Comment by Jrohy** [comment]
@HillCat admin登录到web界面, trojan管理那里切换

**Comment by HillCat** [comment]
Trojan-go切换之后，docker镜像里面是需要修改什么配置不，原来的/usr/local/etc/trojan 这个路径下面config.json，和切换后的trojan-go应该不是同一个配置吧

**Comment by HillCat** [comment]
> 默认安装下，是哪个配置文件下，更改端口？我实在好像找不到是哪个。。。。😓

改端口这种做法是很傻的方法。不推荐。迟早导致你的整个IP被干掉。

**Comment by Jrohy** [comment]
@HillCat 同一个配置文件

**Comment by weweyes** [comment]
> > 默认安装下，是哪个配置文件下，更改端口？我实在好像找不到是哪个。。。。😓
> 
> 改端口这种做法是很傻的方法。不推荐。迟早导致你的整个IP被干掉。

套CDN是不是比改端口安全一点？我的443端口刚刚也被封了，改了其它端口后又可以用了

**Comment by sunrisely** [comment]
> > 默认安装下，是哪个配置文件下，更改了端口？我好像找不到那个人了。。。。😓
> 
> 改端口接口习惯是很傻的方法。不推荐。迟早导致你的整个IP被干掉。

那就直接换别的协议，加伪装？

**Comment by sunrisely** [comment]
> > > 默认安装下，是哪个配置文件下，更改了端口？我好像找不到那个人了。。。。😓
> > 
> > 
> > 改端口接口习惯是很傻的方法。不推荐。迟早导致你的整个IP被干掉。
> 
> 套CDN是不是比改端口安全一点？我的443端口也被封了，改了其他端口后又用了

目前还好，不知道哪天就被封了。。。。
