### ISSUE TITLE
请问你们的域名打开直接就是web管理端吗？

### ISSUE THREAD

**Issue by cmmchina** [Jrohy/trojan#479]
这个trojan管理页面明晃晃的写着不好吧？不是应该弄个网站伪装一下吗？请问有会伪装的吗？要怎么配置呢？

**Comment by Jrohy** [comment]
用admin登录进去可以改标题的

**Comment by cmmchina** [comment]
嗯，谢谢。但是还是觉得能够挂个网站在上面比较好。
