### ISSUE TITLE
关于输入自定义mysql连接 

### ISSUE THREAD

**Issue by lpn418** [Jrohy/trojan#48]
请问这个是支持远程访问其它vps的mysql数据吗？
如果是的话   访问 IP:3306   默认密码 trojan
提示 连接mysql失败, 请重新输入
能指点下原因吗？

**Comment by Jrohy** [comment]
确定mysql连接是否正确，可以自己修改trojan的配置文件/usr/local/etc/trojan/config.json, 同时要确保连的数据库users表要存在，创表语句参考: https://trojan-gfw.github.io/trojan/authenticator

**Comment by lpn418** [comment]
搞定了，是默认的随机生成的密码搞错了，感谢！

**Comment by lpn418** [comment]
还有个问题，用第二台VPS连接第一台VPS的数据库，登入第二台VPS的web页面，看不到所有用户的密码，其它都可见，这是BUG，还是就这样的哈？

**Comment by Jrohy** [comment]
要将/var/lib/trojan-manager目录也拷贝过去才行， 本地用leveldb存了一份原始密码的，因为mysql里面存的密码经过sha224加密无法获取原始密码，所以加密前得存下原始密码

**Comment by lpn418** [comment]
再请教下，如何备份数据库信息，如果服务器重装了，如何恢复？

**Comment by Jrohy** [comment]
备份/var/lib/trojan-manager目录 和 导出mysql里面的users表数据即可

**Comment by lpn418** [comment]
又遇到一个问题  有一台VPS连接远程服务器数据库，提示无法连接服务器，可是两台设备互相PING都没问题呢，其它的VPS都可以正常连接，两台设备都是圣何塞的，但不是同一个运行商的,IP也不是同一段的，还是远程连接有VPS数量限制呢？

**Comment by Jrohy** [comment]
其他vps能连的话，这个得自己排查了
