### ISSUE TITLE
尝试更换端口，但没什么用而且问题更奇怪。

### ISSUE THREAD

**Issue by MicMAO** [Jrohy/trojan#487]
端口443的情况下，日志是这样的
Jul 03 09:13:00 hwsrv-685044.这里本来是vps网址 systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
Jul 03 09:13:00 hwsrv-685044这里本来是vps网址 systemd[1]: Stopped trojan.
Jul 03 09:13:00 hwsrv-685044.这里本来是vps网址 systemd[1]: Started trojan.
Jul 03 09:13:00 hwsrv-685044.这里本来是vps网址 trojan[29493]: Welcome to trojan 1.16.0
Jul 03 09:13:00 hwsrv-685044.这里本来是vps网址 trojan[29493]: [2021-07-03 09:13:00] [WARN] trojan service (server) started at 0.0.0.0:443

把端口从443改为22以后日志如下
Jul 03 09:07:52 hwsrv-685044.这里本来是vps网址 systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 09:07:52 hwsrv-685044.这里本来是vps网址 systemd[1]: trojan.service: Unit entered failed state.
Jul 03 09:07:52 hwsrv-685044.这里本来是vps网址systemd[1]: trojan.service: Failed with result 'exit-code'.

不管在哪个端口下选择5-6都看不到具体的信息。
目前web也进不去了。在之前是完全没问题的。已经尝试过重装trojan也没有效果。
1.trojan管理       	2.用户管理           

3.安装管理           	4.web管理          

5.查看配置           	6.生成json         

请选择: 5
dial tcp 127.0.0.1:3306: connect: connection timed out
dial tcp 127.0.0.1:3306: connect: connection timed out

**Comment by Jrohy** [comment]
连不上3306的数据库

**Comment by MicMAO** [comment]
> 连不上3306的数据库

大佬 要怎么修复呢？

**Comment by Jrohy** [comment]
检查数据库能否连

**Comment by MicMAO** [comment]
> 检查数据库能否连

大佬你好，我又去重装了一下，但是有个问题就是进行到下面这里时一直会 mariadb启动中,请稍等.

1.安装docker版mysql(mariadb)

2.输入自定义mysql连接

请选择: 1
docker run --name trojan-mariadb --restart=always -p 9622:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=oLUkD -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
setenforce: SELinux is disabled
4727364be7ed8c1a0f6479ca677b91867fd2d64f390dc37faf6c47f67d43bc55
2021-07-03 12:28:18 mariadb启动中,请稍等...
2021-07-03 12:30:31 mariadb启动中,请稍等...

**Comment by Jrohy** [comment]
@MicMAO 操作系统有重新安装吗

**Comment by MicMAO** [comment]
> @MicMAO 操作系统有重新安装吗
我在xshell中把trojan卸载了，把整个xshell也清空了，vps端没做任何操作，因为vps那边ip是ping的通的

**Comment by Jrohy** [comment]
这个目录/home/mariadb建议删了，还有对应的原来数据库容器也删了，不会操作的话建议重装系统

**Comment by MicMAO** [comment]
> 这个目录/home/mariadb建议删了，还有对应的原来数据库容器也删了，不会操作的话建议重装系统

mariadb已经删掉了，对应的数据库容器我不太明白啥意思。您说的重装系统指的是重装vps上面的那个吗？那个我是Debian9的
ps我从您的v2ray时期就跟着一路过来，到现在也有4-5年了。上面管的严了，您这边还能继续耕耘也不容易。非常感谢。
我转用trojan也一年多了，以前都没遇到过这些问题，也没学会啥深层次的内容，没想到这次这么难搞。

**Comment by Jrohy** [comment]
docker rm -f trojan-mariadb, 卸载原来的数据库， rm -rf /home/mariadb

**Comment by MicMAO** [comment]
> docker rm -f trojan-mariadb, 卸载原来的数据库， rm -rf /home/mariadb

我把vps端的服务器又重装了一次 现在报这个了 这个要怎么操作
安装trojan管理程序成功!

运行命令trojan可进行trojan管理

-bash: /usr/local/bin/trojan: No such file or directory
root@hwsrv-685044:~# trojan
-bash: trojan: command not found
