### ISSUE TITLE
443还是没解

### ISSUE THREAD

**Issue by YANGY8365** [Jrohy/trojan#489]
不知道什么时候解   我是不行了   开了个新谷歌号  撸了个谷歌云台湾  速度还行 
再封就换IP 反正多

推荐大家这样过度吧

**Comment by ajiter** [comment]
为什么一定要用443 换别的端口不行吗？

**Comment by MicMAO** [comment]
> 为什么一定要用443 换别的端口不行吗？

有的老哥说换端口是往枪口上撞，而且我换到22也不行

**Comment by ajiter** [comment]
> > 为什么一定要用443 换别的端口不行吗？
> 
> 有的老哥说换端口是往枪口上撞，而且我换到22也不行

笑了。我被封后立马换了端口。一直用着好好的。不过现在我443也解封了。

**Comment by MicMAO** [comment]
> > > 为什么一定要用443 换别的端口不行吗？
> > 
> > 
> > 有的老哥说换端口是往枪口上撞，而且我换到22也不行
> 
> 笑了。我被封后立马换了端口。一直用着好好的。不过现在我443也解封了。

厉害了老哥，我这边还没动静呢

**Comment by YANGY8365** [comment]
> > > 为什么一定要用443 换别的端口不行吗？
> > 
> > 
> > 有的老哥说换端口是往枪口上撞，而且我换到22也不行
> 
> 笑了。我被封后立马换了端口。一直用着好好的。不过现在我443也解封了。

哥们 不用443 就很好被发现了啊  看看trojan原理啊    只是看想不想管而已

**Comment by HillCat** [comment]
> 不知道什么时候解 我是不行了 开了个新谷歌号 撸了个谷歌云台湾 速度还行
> 再封就换IP 反正多
> 
> 推荐大家这样过度吧

套cdn啊，不会吗
