### ISSUE TITLE
trojan-go如何配置ws？

### ISSUE THREAD

**Issue by onlyJinx** [Jrohy/trojan#491]
我在web面板看不到设置入口，只能添加账号密码，无法做多余配置，是需要我自己去修改trojan-go的config.json吗

**Comment by Jrohy** [comment]
是的，自己手动改json

**Comment by onlyJinx** [comment]
搞定了，谢谢。

另外问一下，可以修改程序监听端口吗？我原服务器上本来是用nginx进行SNI分流，按照SNI分流给trijan/v2ray/web server，现在443给了trojan的话那其他程序就不能跑了。

**Comment by Jrohy** [comment]
trojan-web改端口的话参考项目wiki

**Comment by onlyJinx** [comment]
默认web的监听端口是放在trojan的回落端口(remote_port)上吗？如果是的话我就知道怎么玩了。

我这样改trojan-go端口应该不会影响到流量统计吧

**Comment by Jrohy** [comment]
不一定是回落端口的，回落端口你可以换成nginx的端口也行。改trojan-go端口和流量统计没关系

**Comment by onlyJinx** [comment]
好的，明白，直接把web放在回落端口算了，伪装网站都省了。多谢耐心解答。
