### ISSUE TITLE
更换trojan-go之后，用户监控面板失效的问题怎么解决啊

### ISSUE THREAD

**Issue by HillCat** [Jrohy/trojan#493]
更换了trojan-go之后，流量监控面板的界面好像就失效了。对于每个用户，使用了多少流量就再也无法监控到了。

443之后，切换到trojan-go，套了cloudfare的cdn。但是为啥user监控面板里面，用户的流量这些数据都停滞了？难道只支持trojan的流量监控的吗？

![image](https://user-images.githubusercontent.com/41800196/124502896-ecd4e280-ddf6-11eb-9574-fb27037da199.png)

Is there anybody know  how to solve this problem?

**Comment by Jrohy** [comment]
支持的，得翻了才有数据更新，而且数据更新是trojan-go才能操控的

**Comment by HillCat** [comment]
> 支持的，得翻了才有数据更新，而且数据更新是trojan-go才能操控的

嗯，看到了。
