### ISSUE TITLE
面板没有了增加用户等功能

### ISSUE THREAD

**Issue by xiran2018** [Jrohy/trojan#496]
我用 version: v2.10.7 的版本，但是没有了用户管理中的增加、删除功能，没有了系统cpu、内存的监控，也没有trojan日志的监控，请问怎么才能加上这些功能呢，或者怎么才能实现版本的回退呢？

**Comment by Jrohy** [comment]
用admin用户登录就有

**Comment by xiran2018** [comment]
好的，谢谢
