### ISSUE TITLE
我这两天发现电信宽带电信卡网络无法对我的trojan-go提供上网服务

### ISSUE THREAD

**Issue by misskiki** [Jrohy/trojan#498]
我这两天发现电信宽带电信卡网络无法对我的trojan-go提供上网服务
我很奇怪 我切换成联通 移动网络就可以上网。
还有就是我自己开发了一套基于trojango的的会员中心，后台就用的作者开发的
![image](https://user-images.githubusercontent.com/41108094/124791185-68ad6700-df7e-11eb-9b4f-c6cfe1b2f003.png)

![image](https://user-images.githubusercontent.com/41108094/124791367-92ff2480-df7e-11eb-9feb-0f07a210806e.png)
代码xi写的很烂。基于php写的
主要就是 充值
订阅 
到期续费

**Comment by ckbkdj** [comment]
这个misskiki你想表达什么?要别人买你的面板?

**Comment by misskiki** [comment]
不会 我会开源出来 我没有说要卖
