### ISSUE TITLE
到了后面,安装docker mysql出错

### ISSUE THREAD

**Issue by lqhorochi** [Jrohy/trojan#5]
5.7: Pulling from mysql/mysql-server

c7127dfa6d78: Pulling fs layer

cb7ddde5230b: Pulling fs layer

1528bee07386: Pulling fs layer

cca3f8362bb0: Pulling fs layer

cca3f8362bb0: Waiting

1528bee07386: Verifying Checksum

1528bee07386: Download complete
cca3f8362bb0: Verifying Checksum
cca3f8362bb0: Download complete
c7127dfa6d78: Verifying Checksum
c7127dfa6d78: Download complete
cb7ddde5230b: Verifying Checksum
cb7ddde5230b: Download complete
c7127dfa6d78: Pull complete
cb7ddde5230b: Pull complete
1528bee07386: Pull complete
cca3f8362bb0: Pull complete
Digest: sha256:5a5c0841346322ed514a48a7c2ab5409a8106e35718f3195467e7cf52343f25a
Status: Downloaded newer image for mysql/mysql-server:5.7
d2dc6ff7739e3e46e4ec52c0807c69d2f134af27462b755908432b641dc8351f
mysql启动中, 请稍等...
[mysql] 2020/03/01 08:02:20 packets.go:36: unexpected EOF
[mysql] 2020/03/01 08:02:20 packets.go:36: unexpected EOF

nat的vps安装的

**Comment by Jrohy** [comment]
这不是出错，这是等mysql启动完自动建表建用户的，等一下就好

**Comment by lqhorochi** [comment]
> 这不是出错，这是等mysql启动完自动建表建用户的，等一下就好

等了半小时,正常吗?

**Comment by Jrohy** [comment]
什么系统安装的呢, 可以docker ps -a看看容器状态trojan-mysql容器

**Comment by lqhorochi** [comment]
> 什么系统安装的呢, 可以docker ps -a看看容器状态trojan-mysql容器

CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                          PORTS               NAMES
405f8f62c7bd        mysql/mysql-server:5.7   "/entrypoint.sh mysq…"   5 hours ago         Restarting (1) 58 seconds ago                       trojan-mysql

还是一样.
Ubuntu 18.04系统,
anyhk的nat vps

**Comment by Jrohy** [comment]
你试下删掉容器`docker rm -f trojan-mysql`, 清掉mysql目录 rm -rf /home/mysql,然后运行下
`docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7`

**Comment by Jrohy** [comment]
试试手动运行能否起

**Comment by lqhorochi** [comment]
> 试试手动运行能否起

欢迎使用trojan管理程序

1.trojan管理            2.用户管理           

3.安装管理              4.查看配置           

5.生成客户端配置文件            

请选择: 4
[mysql] 2020/03/02 18:49:01 packets.go:36: unexpected EOF
[mysql] 2020/03/02 18:49:01 packets.go:36: unexpected EOF
[mysql] 2020/03/02 18:49:01 packets.go:36: unexpected EOF
driver: bad connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x858dde]

goroutine 1 [running]:
trojan/trojan.UserList(0x0, 0x0, 0x0, 0xc00000ee20)
        /home/go/trojan/trojan/user.go:81 +0xae
trojan/cmd.mainMenu()
        /home/go/trojan/cmd/root.go:79 +0x4c4
trojan/cmd.glob..func5(0xd58660, 0xd89850, 0x0, 0x0)
        /home/go/trojan/cmd/root.go:31 +0x20
github.com/spf13/cobra.(*Command).execute(0xd58660, 0xc0000201d0, 0x0, 0x0, 0xd58660, 0xc0000201d0)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd58660, 0x44366a, 0xd1c100, 0xc000000180)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
        /home/go/trojan/cmd/root.go:38 +0x31
main.main()
        /home/go/trojan/main.go:21 +0x20

**Comment by Jrohy** [comment]
mysql手动起来了吗，如果手动起来了的，去安装管理那里选择mysql安装，再选自定义mysql连接

**Comment by Jrohy** [comment]
nat vps是不是有限制端口数量的，如果是起的mysql端口要在其范围内
