### ISSUE TITLE
能在添加新账户的时候加一个端口号吗？谢谢

### ISSUE THREAD

**Issue by xuubear** [Jrohy/trojan#506]
大神能不能在添加新账户的时候加一个端口号。这样防止端口被封。其实好多人根本没有用cdn 所以固定在443也没有太多意义。

**Comment by Jrohy** [comment]
多端口不支持吧

**Comment by ajiter** [comment]
想想办法让他支持嘛。谢谢啦。

**Comment by Jrohy** [comment]
主要是trojan核心只支持一个端口生效，不像v2ray/xray可以生效无限端口

**Comment by ajiter** [comment]
哦。这样啊..大神有想过把核心换成Xray么。现在Xray支持trojan所有一切的功能。当然只是和你探讨下。还是谢谢大神

**Comment by Jrohy** [comment]
这个项目: https://github.com/Jrohy/multi-v2ray

**Comment by ajiter** [comment]
这个没有面板啊.。没有这个管理方便。我们是同学几个合租的。

**Comment by ajiter** [comment]
前段时间封443 没有办法换到隔壁家X ui 但有断流现象 特别是电报软件。总是断。一会又好。现在443解了。就又换回了大神的trojan面板了。
