### ISSUE TITLE
希望能添加修改publicPath的功能

### ISSUE THREAD

**Issue by 12f23eddde** [Jrohy/trojan#51]
vps的防火墙只打开80、443端口，希望能够修改前端页面的publicPath，让前端能够通过nginx分流到example.com/trojan-web

**Comment by Jrohy** [comment]
管理程序可以不用80端口启动, 然后nginx用80，可以试试分流过去

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3 修改web端口
