### ISSUE TITLE
能否添加限制ip等功能

### ISSUE THREAD

**Issue by Konsn666** [Jrohy/trojan#510]
现在的管理面板做的已经挺不错了，如果在管理面板里的添加用户那一栏里面加上限制个人IP连接数量，每个IP对应哪台设备等。如果加上这个功能那真是锦上添花，支持你。

**Comment by Jrohy** [comment]
trojan-go有限制ip,但试了不生效，不然就加上了

**Comment by awds888** [comment]
同求
