### ISSUE TITLE
安装后的疑问🤔️

### ISSUE THREAD

**Issue by dajibaxiao** [Jrohy/trojan#516]
我新机子。用了这个脚本后tr0jan-install。为啥访问域名没有面板？是一个movie Hunter的html页？我想用web管理。不想用命令行

**Comment by Jrohy** [comment]
安装后能翻吗节点, 你可以访问ip来访问web面板的，如果证书没申请到https是没法访问

**Comment by dajibaxiao** [comment]
> 安装后能翻吗节点, 你可以访问ip来访问web面板的，如果证书没申请到https是没法访问



> 安装后能翻吗节点, 你可以访问ip来访问web面板的，如果证书没申请到https是没法访问

已经解决了。看了wiki自定义端口解决了。
