### ISSUE TITLE
我这里在申请证书步骤一直申请不下来，请留下联系方式。

### ISSUE THREAD

**Issue by vpsceo** [Jrohy/trojan#52]
我这里在申请证书步骤一直申请不下来，请留下联系方式。
我把服务器信息给你，麻烦帮我看看，可以吗？

**Comment by Jrohy** [comment]
报什么日志呢，申请证书

**Comment by vpsceo** [comment]
作者您好，我的意思是把香港的VPS信息给你登陆上去安装最直接  你看是否可行  推特方式给你信息还是怎么给你？

**Comment by Jrohy** [comment]
留下tg号，我联系你

**Comment by vpsceo** [comment]
https://t.me/vpsceo
