### ISSUE TITLE
服务器启动trojan失败,这是什么问题

### ISSUE THREAD

**Issue by pertance** [Jrohy/trojan#520]
![image](https://user-images.githubusercontent.com/35564076/129679187-0714c681-d27d-427e-86d0-7a3370bf928c.png)

启动trojan 失败,总是连接mysql 出现问题
trojan.service: Failed with result 'exit-code'.

**Comment by pertance** [comment]
![image](https://user-images.githubusercontent.com/35564076/129679398-1e515d21-e660-4323-8b9b-3c6741f5bbe1.png)

**Comment by Jrohy** [comment]
mysql连不了

**Comment by pertance** [comment]
我能看出来是mysql 连接不上, 这个要怎么解决呢?重新安装mysql吗?

**Comment by Jrohy** [comment]
嗯docker版mysql重新安装下，能连后运行trojan 到安装管理->mysql安装mysql那里自定义mysql地址就好

**Comment by pertance** [comment]
好的 谢谢您

**Comment by pertance** [comment]
![image](https://user-images.githubusercontent.com/35564076/129686277-0536061b-6145-4e00-9550-79decf8a43e3.png)

您好重装mariadb 后,启不来,

**Comment by Jrohy** [comment]
先删了原来容器和数据目录再来起吧

**Comment by pertance** [comment]
我已经删过了,删过后,重新安装 docker mysql  启不来

**Comment by Jrohy** [comment]
不行就自己换下mysql镜像来安装
