### ISSUE TITLE
docker 安装失败

### ISSUE THREAD

**Issue by HillCat** [Jrohy/trojan#525]
**报错信息**：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: conta.

**docker的版本号**：
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**有解决办法吗？**

**Comment by HillCat** [comment]
不管什么版本的Ubuntu还是debian,  版本不同的Docker也是安装失败。

**Comment by micnp** [comment]
> 实质换成了`source <(curl -sL https://docker-install.netlify.app/install.sh)`这个命令来安装，用二进制包来安装docker

多谢 找了一圈 这个解决了
