### ISSUE TITLE
管理面板显示的流量和搬瓦工页面显示的出入很大

### ISSUE THREAD

**Issue by vstar37** [Jrohy/trojan#526]
![image](https://user-images.githubusercontent.com/70553922/131062063-ff5715a1-bc63-4401-9e9d-0cd96aa9c713.png)
![image](https://user-images.githubusercontent.com/70553922/131062131-bd415962-3914-4313-8ffa-523067ccd027.png)

**Comment by jackxin900** [comment]
网页端只计算了出站和入站的总计流量，不过对于vps的出站和入站是需要乘以二的
