### ISSUE TITLE
希望可以增加配置的备份与恢复

### ISSUE THREAD

**Issue by alegoho** [Jrohy/trojan#53]
希望可以增加配置的备份与恢复

**Comment by Jrohy** [comment]
直接备份/var/lib/trojan-manager目录和恢复就好

**Comment by alegoho** [comment]
> 直接备份/var/lib/trojan-manager目录和恢复就好

大哥，没用啊，我将/var/lib/trojan-manager整个目录备份，我重装再装后恢复这个目录，我之前建的用户都在不啊

**Comment by Jrohy** [comment]
数据库也是要用回原来的，/home/mysql目录或者/home/mariadb

**Comment by alegoho** [comment]
> 数据库也是要用回原来的，/home/mysql目录或者/home/mariadb

意思是两个目录一起备份吗？

**Comment by Jrohy** [comment]
是的
