### ISSUE TITLE
请问not a valid websocket handshake怎么解决

### ISSUE THREAD

**Issue by whynotjinx** [Jrohy/trojan#531]
抱歉多次修改问题

现在启动之后会有ERROR`(*Server).acceptLoop:server.go:130 trojan failed to accept conn | not a valid websocket handshake`出现
使用普通的trojan客户端在不开启CDN的情况下可以连接，但是使用CDN会就会无法联网；

使用trojan-go客户端Qv2ray的时候，管理面板日志显示：
`(*Redirector).worker.func1:redirector.go:73 failed to redirect | readfrom tcp 127.0.0.1:55124->127.0.0.1:80: read tcp 45.86.74.146:443->61.69.220.136:32018: read: connection reset by peer`
客户端显示：
`(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | simplesocks failed to dial using underlying tunnel | no available mux client found | mux failed to dial | websocket failed to handshake with server | bad status`

不知道需要提供什么信息帮助解决？

**Comment by whynotjinx** [comment]
● trojan.service - trojan-go
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-08-31 06:51:30 EDT; 9min ago
 Main PID: 31454 (trojan)
    Tasks: 4 (limit: 545)
   Memory: 6.8M
   CGroup: /system.slice/trojan.service
           └─31454 /usr/bin/trojan/trojan -config /usr/local/etc/trojan/config.json

Aug 31 07:00:20 vps61921645.hosteons.com trojan[31454]: [ERROR] 2021/08/31 07:00:20 github.com/p4gefau1t/trojan-go/tunnel/trojan.(*Server).acceptLoop:server.go:130 trojan failed to accept conn | websocket is disabled. redirecting http request from 172.70.98.128:12674
Aug 31 07:00:20 vps61921645.hosteons.com trojan[31454]: [WARN]  2021/08/31 07:00:20 redirecting connection from 172.70.98.128:12674 to 127.0.0.1:80
Aug 31 07:00:20 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:20 user ab15252f2ab355d7c83acfaaed8a406214e312b57443cbec81273249 from 124.168.24.84:8312 tunneling to hosteons.whynotjinx.ga:443 closed sent: 2.49 KiB recv: 517 B
Aug 31 07:00:23 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:23 tcp connection from 124.168.24.84:1063
Aug 31 07:00:23 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:23 tls connection from 124.168.24.84:1063
Aug 31 07:00:30 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:30 buffered data has been written into the database
Aug 31 07:00:31 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:31 buffered data has been written into the database
Aug 31 07:00:31 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:31 redirection done
Aug 31 07:00:31 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:31 user ab15252f2ab355d7c83acfaaed8a406214e312b57443cbec81273249 from 124.168.24.84:1044 tunneling to hosteons.whynotjinx.ga:443 closed sent: 33.90 KiB recv: 1.48 KiB
Aug 31 07:00:47 vps61921645.hosteons.com trojan[31454]: [INFO]  2021/08/31 07:00:47 user ab15252f2ab355d7c83acfaaed8a406214e312b57443cbec81273249 from 124.168.24.84:1998 tunneling to github.com:443 closed sent: 10.12 KiB recv: 2.88 KiB

**Comment by whynotjinx** [comment]
**大概几分钟之后会变成这个样子：**
● trojan.service - trojan-go
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-08-31 14:36:03 EDT; 2s ago
  Process: 9240 ExecStart=/usr/bin/trojan/trojan -config /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 9240 (code=exited, status=1/FAILURE)

Aug 31 14:36:03 vps61921645.hosteons.com systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 14:36:03 vps61921645.hosteons.com systemd[1]: trojan.service: Failed with result 'exit-code'.


**同时查看日志会有这个句式：**
acceptLoop:server.go:130 trojan failed to accept conn | websocket is disabled

这个时候用域名进入的管理面板也会无法打开，尝试用其他服务器重新操作了一遍也是同样的结果，所以我觉得应该不是服务器。

**防火墙：**
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:49655
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:49655
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:80
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:443
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443

Chain FORWARD (policy DROP)
target     prot opt source               destination         
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0           
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:49655
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spt:49655
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:80
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spt:80
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:443
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spt:443

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  0.0.0.0/0            172.17.0.2           tcp dpt:3306

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

**Comment by paulyu666** [comment]
我的有同样的问题，我的是tls handshake failed，之后是bad certification，现在是from ip:33736 tunneling to ip:443 closed sent，大佬也看下我的问题
