### ISSUE TITLE
不知道为什么这两天经常连接失败..有时候能上油管能看视频但是就是没法打开谷歌..

### ISSUE THREAD

**Issue by Dameko27r** [Jrohy/trojan#534]
[TrojanGo] [INFO]  2021/09/04 00:20:19 socks connection from 127.0.0.1:5928 metadata 96.43.165.27:1044
[TrojanGo] [INFO]  2021/09/04 00:20:19 socks connection from 127.0.0.1:5950 metadata 183.89.162.166:30005
[TrojanGo] [INFO]  2021/09/04 00:20:19 socks connection from 127.0.0.1:5929 metadata 112.204.56.232:1
[TrojanGo] [INFO]  2021/09/04 00:20:19 socks connection from 127.0.0.1:5948 metadata 154.3.40.205:6881
[TrojanGo] [ERROR] 2021/09/04 00:20:19 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to dial conn | transport failed to connect to remote server | dial tcp 2.56.241.179:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[TrojanGo] [ERROR] 2021/09/04 00:20:19 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to dial conn | transport failed to connect to remote server | dial tcp 2.56.241.179:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[TrojanGo] [ERROR] 2021/09/04 00:20:19 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to dial conn | transport failed to connect to remote server | dial tcp 2.56.241.179:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[TrojanGo] [ERROR] 2021/09/04 00:20:19 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | tls failed to dial conn | transport failed to connect to remote server | dial tcp 2.56.241.179:443: connectex: A connection attempt faile
看了一下好像也只有我有这种情况.不知道为什么.

**Comment by Dameko27r** [comment]
无法连接的时候是有去程没有回程的..

**Comment by LoveForeverBoa** [comment]
我这 移动 也无法连接。。。估计又升级了

**Comment by Dameko27r** [comment]
> 我这 移动 也无法连接。。。估计又升级了

虽然我现在也是在用移动,但是我之前用的广州联通也一样...

**Comment by whynotjinx** [comment]
请问用的是Qv2ray吗，我也遇到了类似的error #531，稍有不同：
`[TrojanGo] [ERROR] 2021/09/05 07:26:25 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | simplesocks failed to dial using underlying tunnel | no available mux client found | mux failed to dial | websocket failed to handshake with server | bad status`

**Comment by Dameko27r** [comment]
> 请问用的是Qv2ray吗，我也遇到了类似的error #531，稍有不同：
> `[TrojanGo] [ERROR] 2021/09/05 07:26:25 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | simplesocks failed to dial using underlying tunnel | no available mux client found | mux failed to dial | websocket failed to handshake with server | bad status`

是用的Qv2ray,你那边用cdn不行可能是没有优选好ip
