### ISSUE TITLE
自动申请 Let's Encrypt 证书失败

### ISSUE THREAD

**Issue by iflycn** [Jrohy/trojan#537]
Installing from online archive.
Downloading https://github.com/acmesh-official/acme.sh/archive/master.tar.gz
Extracting master.tar.gz
Please install openssl first. ACME_OPENSSL_BIN=openssl
We need openssl to generate keys.
Pre-check failed, can not install.

**Comment by Jrohy** [comment]
先安装openssl，再来申请
