### ISSUE TITLE
到期时间能不能到期后就进行用户的流量阻断

### ISSUE THREAD

**Issue by WillZaan** [Jrohy/trojan#539]
到期时间能不能到期后就进行流量阻断，刚开始我以为到期时间的作用是有这个的，后来我测试了一下，9.17到期，但是我9.18还是正常使用，才发现没有阻断操作，jrohy可不可以加一个这个功能，感觉可以省不少事情，谢谢！

**Comment by Jrohy** [comment]
到期后应该是流量上限变为0了，变为0阻断上网是trojan做的操作

**Comment by WillZaan** [comment]
![image](https://user-images.githubusercontent.com/34828163/133869889-eab3adea-a6cd-40ab-af26-e85505374c01.png)

这是到期后的现状

**Comment by WillZaan** [comment]
如果到期时间是  9.17   是指 9.17 24：00  后上限设置为0，还是9.16 24：00 上限设置为0？

可能是这个有问题导致的

**Comment by Jrohy** [comment]
我看下

**Comment by Jrohy** [comment]
9.18号0点就会执行这个设置了，有没有0点重启过trojan-web服务

**Comment by WillZaan** [comment]
![image](https://user-images.githubusercontent.com/34828163/133870470-ee4d1bb3-0bdc-44ea-9779-fa63bce9f727.png)

**Comment by WillZaan** [comment]
因为我是昨天晚上设置，想看看效果，我以为是因为我当天到期当天设置的原因，服务没有重启过

**Comment by WillZaan** [comment]
我设置的是凌晨三点重启服务器

**Comment by Jrohy** [comment]
昨天晚上几点设置的

**Comment by Jrohy** [comment]
可以看看 `ps -Ao etime,args|grep -v grep|grep /usr/local/bin/trojan`运行时间

**Comment by Jrohy** [comment]
当然每天0点都会将已经过期的节点流量上限未设置为0的设为0，错过了今天0点的，明天0点也会设置的

**Comment by WillZaan** [comment]
![image](https://user-images.githubusercontent.com/34828163/133870747-13f00ce0-b83b-44a1-8b4f-61e4c5ed956d.png)

**Comment by WillZaan** [comment]
那我明天再看看
9.17的会不会置为0
昨天晚上搞得有点晚，但是很大可能是没有过0点的

**Comment by Jrohy** [comment]
发现如果设置限期天数为0天的话就不会执行设置流量上限为0(即使已过期)，确实有问题，下个版本修复下

**Comment by WillZaan** [comment]
重置了，但是时间明显延后了，我查看了服务器上的时间和本地时间一样的，没有什么问题。
