### ISSUE TITLE
mariadb未能正常启动

### ISSUE THREAD

**Issue by PeterPan0106** [Jrohy/trojan#548]
centos8，无其他服务运行。运行脚本后卡在“mariadb启动中，请稍后”这里，大概每两秒会提示一下启动中，但等了半小时仍未能启动。网页管理界面可以进去，但无法增加用户。

**Comment by PeterPan0106** [comment]
机器配置为1vcore，512M，10G SSD。过往使用过多种脚本测试，性能还可以。之前也曾成功安装过您的Trojan脚本，所以本次未能成功启动数据库令我觉得有些奇怪。如需排查补充其他信息欢迎联系我

**Comment by u0024window** [comment]
安装sudo dnf install @mariadb
然后启动
然后在一件脚本
就可以了

**Comment by u0024window** [comment]
你的mariadb估计没有暴露在shell里
