### ISSUE TITLE
本地连不上Trojan面板域名

### ISSUE THREAD

**Issue by Visors** [Jrohy/trojan#55]
日志如下，似乎是我本地IP被ban了？
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-10 15:39:24 UTC; 6min ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 2777 (trojan)
    Tasks: 2 (limit: 1125)
   CGroup: /system.slice/trojan.service
           └─2777 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

Apr 10 15:39:24 vultr.guest systemd[1]: Stopped trojan.
Apr 10 15:39:24 vultr.guest systemd[1]: Started trojan.
Apr 10 15:39:24 vultr.guest trojan[2777]: Welcome to trojan 1.15.1
Apr 10 15:39:24 vultr.guest trojan[2777]: [2020-04-10 15:39:24] [INFO] connecting to MySQL server 127.0.0.1:17747
Apr 10 15:39:24 vultr.guest trojan[2777]: [2020-04-10 15:39:24] [INFO] connected to MySQL server
Apr 10 15:39:24 vultr.guest trojan[2777]: [2020-04-10 15:39:24] [WARN] trojan service (server) started at 0.0.0.0:443
Apr 10 15:39:36 vultr.guest trojan[2777]: [2020-04-10 15:39:36] [INFO] 我的本地IP:38957 authenticated by authenticator (8ef077a)
Apr 10 15:39:36 vultr.guest trojan[2777]: [2020-04-10 15:39:36] [INFO] 我的本地IP:38957 requested connection to www.youtube.com:443
Apr 10 15:42:48 vultr.guest trojan[2777]: [2020-04-10 15:42:48] [WARN] 我的本地IP:39265 not trojan request, connecting to 127.0.0.1:80

我直连域名也打不开面板，但是挂梯子换了IP却可以。

**Comment by Visors** [comment]
而且使用Trojan-Qt5能ping通，连接上后打不开网页

**Comment by Jrohy** [comment]
systemctl status trojan-web看下有没启动

**Comment by Visors** [comment]
> systemctl status trojan-web看下有没启动

root@vultr:~# systemctl status trojan-web
● trojan-web.service - trojan-web
   Loaded: loaded (/etc/systemd/system/trojan-web.service; enabled; vendor pr   Active: active (running) since Fri 2020-04-10 16:08:12 UTC; 1h 12min ago
     Docs: https://github.com/Jrohy/trojan
 Main PID: 1012 (trojan)
    Tasks: 6 (limit: 1125)
   CGroup: /system.slice/trojan-web.service
           └─1012 /usr/local/bin/trojan web

应该是启动了的

**Comment by Jrohy** [comment]
Ip能访问到不，是不是用的二级域名

**Comment by Visors** [comment]
> Ip能访问到不，是不是用的二级域名

是用的二级域名，搭之前IP可以ping通，搭之后就ping不通了。但是trojan日志里面出现了我的IP，应该不是被墙的。

**Comment by Jrohy** [comment]
直接用ip能否访问web面板呢， 二级域名其实没测过，可以的话推荐用一级域名

**Comment by Visors** [comment]
> 直接用ip能否访问web面板呢， 二级域名其实没测过，可以的话推荐用一级域名

刚刚访问了一下，开始可以连接，我还登录进了面板，然后几秒之后就不能访问了。一直显示“花了太长时间进行响应”

**Comment by Jrohy** [comment]
本机连服务器ip的连接性如何,会不会有连接超时呢， ping下

**Comment by Visors** [comment]
ping过了，全部超时。搭之前是可以ping通的。

**Comment by Jrohy** [comment]
被墙就只能走v2 cdn了

**Comment by Visors** [comment]
> 被墙就只能走v2 cdn了

我感觉应该不是被墙的问题，就是现在我尝试连接域名，服务端日志里面都会出现我的IP。dalao可以留个tg吗？

**Comment by Jrohy** [comment]
你留下我不方便留，我联系你

**Comment by Visors** [comment]
> 你留下我不方便留，我联系你

https://t.me/CNVisors
