### ISSUE TITLE
安装失败，无法启动docker

### ISSUE THREAD

**Issue by TanZhiwen2001** [Jrohy/trojan#553]
无法启动docker，安装卡在mariadb启动中。从log中可以看到docker启动不了系统重装过很多次了，Ubuntu和centos都试过
![Screenshot_20211018-172453014](https://user-images.githubusercontent.com/20763257/137705649-c80bf771-8e73-4fb6-9717-b630defbeb36.jpg)

**Comment by TanZhiwen2001** [comment]
安装成功了
![Screenshot_20211018-194309071](https://user-images.githubusercontent.com/20763257/137723979-1d019272-f4ce-49d6-a85e-64363a0e6062.jpg)

**Comment by Jrohy** [comment]
那就继续安装trojan
