### ISSUE TITLE
我提个需求，token时效希望加长

### ISSUE THREAD

**Issue by WillZaan** [Jrohy/trojan#554]
频繁的失效和登录有点麻烦，感觉没有必要将过期时间设置的很短，希望token失效时间可以加长到12小时。

**Comment by Jrohy** [comment]
我加个传参，可以自定义超时时间吧

**Comment by Jrohy** [comment]
2.11.3 则可设置，`trojan updateWeb`更新下, 修改cat /etc/systemd/system/trojan-web.service配置文件， 在/usr/local/bin/trojan web 后面 加入 -t xxx分钟 则可自定义了

**Comment by WillZaan** [comment]
收到，感谢
