### ISSUE TITLE
一个非常严重的问题！——dial tcp 127.0.0.1:7702: connect: connection refused

### ISSUE THREAD

**Issue by earth-5G** [Jrohy/trojan#561]
dial tcp 127.0.0.1:7702: connect: connection refused

今天突然就上不去了，然后登录管理后台，发现已经上不去了，登录ssh后台，管理用户就出现这个错误代码！~

**Comment by earth-5G** [comment]
哪位知道的帮帮忙！

**Comment by Jrohy** [comment]
是不是连不上数据库了，看看7702端口通不通

**Comment by earth-5G** [comment]
我也不知道怎么去查看端口i，我直接重装了。。。。

不过我平时都不动这个，也不存在什么误操作导致问题！

反正昨天晚上就突然不行了！！

**Comment by earth-5G** [comment]
zh这个问题再一次出现！

**Comment by Jrohy** [comment]
nc 127.0.0.1 7702看看端口通不通，可能数据库有问题

**Comment by earth-5G** [comment]
> nc 127.0.0.1 7702看看端口通不通，可能数据库有问题

ZHGE zhge 这个要怎么查看呢，我又重装了！下次在遇到怎么查！

**Comment by puexine** [comment]
遇到同样的问题，重装了
