### ISSUE TITLE
443突然嗝屁，请问有更换端口的办法吗？

### ISSUE THREAD

**Issue by zhucaidan** [Jrohy/trojan#567]
443突然连不上一看被墙了，请问配置文件里有更换端口的办法吗？

**Comment by VinsonCai** [comment]
遇到同样的问题，同求方法

**Comment by BrunuhVille** [comment]
+1，今天443端口突然墙了两个

**Comment by keengrass** [comment]
+1 今天我也443端口被B，是什么情况？最近有什么重大事情吗？

**Comment by zazi0001** [comment]
+1 甚至在重新申请证书时报错Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 60

**Comment by zazi0001** [comment]
+1

**Comment by VinsonCai** [comment]
明天领导人开六中全会了。
我这边在服务器增加端口转发。
iptables -t nat -A PREROUTING -p tcp --dport 44443 -j REDIRECT --to-ports 443

然后在客户端把端口改为44443，测试成功。暂时先这么用了。

**Comment by Arecall** [comment]
> iptables -t nat -A PREROUTING -p tcp --dport 44443 -j REDIRECT --to-ports 443

在哪改？

**Comment by VinsonCai** [comment]
这个是直接服务器的命令行改的，就是添加iptable转发规则。

**Comment by Arecall** [comment]
> 这个是直接服务器的命令行改的，就是添加iptable转发规则。

cd 根目录操作 输入命令行回车不行

**Comment by VinsonCai** [comment]
需要root权限。前边加上sudo

**Comment by Arecall** [comment]
> 需要root权限。前边加上sudo

我是用的root权限

**Comment by VinsonCai** [comment]
那你搜索一下iptable端口转发的操作说明。
我的是ubuntu 20.04系统，可能跟你的不一样。

**Comment by keengrass** [comment]
楼上再帮忙分享下如何解除端口转发的命令？

**Comment by Jrohy** [comment]
修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口

**Comment by Arecall** [comment]
> 明天领导人开六中全会了。 我这边在服务器增加端口转发。 iptables -t nat -A PREROUTING -p tcp --dport 44443 -j REDIRECT --to-ports 443
> 
> 然后在客户端把端口改为44443，测试成功。暂时先这么用了。

你这端口我改了，还是被和谐了。

**Comment by Lookya** [comment]
> 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口

谢谢，暂时连接成功了

**Comment by Arecall** [comment]
> 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口

改了443端口 需要重新加载文件吗 直接reboot 后依旧不能访问。

**Comment by zhucaidan** [comment]
> 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口

大佬改过trojan端口以后，acme的更新证书脚本端口要改吗？

**Comment by zhucaidan** [comment]
> > 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口
> 
> 改了443端口 需要重新加载文件吗 直接reboot 后依旧不能访问。

trojan restart && systemctl restart trojan-web

**Comment by Arecall** [comment]
> > > 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口
> > 
> > 
> > 改了443端口 需要重新加载文件吗 直接reboot 后依旧不能访问。
> 
> trojan restart && systemctl restart trojan-web

好了，防火墙忘记开放端口了，感谢大家

**Comment by jaqueline-law** [comment]
> 楼上再帮忙分享下如何解除端口转发的命令？
查看iptable
iptables -t nat -vnL PREROUTING
删除
iptables -t nat -D PREROUTING 1
最后这个1是上面查看命令看到的iptable策略的行数，要删第几行的策略就写几。

**Comment by earth-5G** [comment]
> 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口

老大，我已经知道这个文件勒，把443改成什么合适，我改成4443，重启了 也不行！！能给个详细点的方法和流程吗？

**Comment by zhucaidan** [comment]
> > 修改/usr/local/etc/trojan/config.json配置文件里面的443来改trojan端口
> 
> 老大，我已经知道这个文件勒，把443改成什么合适，我改成4443，重启了 也不行！！能给个详细点的方法和流程吗？

改完执行 trojan updateWeb && trojan update，然后用域名+新端口进去就行了

**Comment by loyio** [comment]
可以mark

**Comment by Corezcy** [comment]
mark
