### ISSUE TITLE
证书显示获取成功但是前端网站始终是http

### ISSUE THREAD

**Issue by beckzjs** [Jrohy/trojan#568]
证书显示获取成功但是前端网站始终是http，  卸载重装，用acme.sh --renew-all --force，更新都没法解决。大家有遇到这样的情况不。

**Comment by Jrohy** [comment]
能翻不，能翻证书就能用

**Comment by beckzjs** [comment]
不行，应该是443端口被墙了吧

**Comment by 496407151** [comment]
443端口被封了，换个端口吧，不影响翻墙

**Comment by 496407151** [comment]
443端口被封了，换个端口吧，不影响翻墙
