### ISSUE TITLE
无法安装您的面板

### ISSUE THREAD

**Issue by Earlesscat** [Jrohy/trojan#569]
日志如下所示，不知道是不是要更新了？谢谢

本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.Qx63EDjpdi...
Downloading trojan 1.16.0...
######################################################################## 100.0%#=#=#                                                         ######################################################################## 100.0%
Unpacking trojan 1.16.0...
bash: line 95: tar: command not found
Failed to restart trojan.service: Unit trojan.service not found.
Failed to enable unit: Unit file trojan.service does not exist.
open /usr/local/etc/trojan/config.json: no such file or directory

**Comment by Jrohy** [comment]
系统没有tar命令? 什么系统这么精简

**Comment by Earlesscat** [comment]
> 系统没有tar命令? 什么系统这么精简

啊原来如此，我是centos8，我去检查一下

**Comment by Earlesscat** [comment]
谢谢
