### ISSUE TITLE
作者好，脚本应该有一些兼容性。

### ISSUE THREAD

**Issue by luobingwei** [Jrohy/trojan#575]
双11买了racknerd和cloudcone的11-12刀年付的vps.安装后后台是没有https的。
但是用隔壁八合一脚本安装是可以使用443端口，并且伪装的企业网站是有https的。

同样你的脚本在cn2网络的vps上我都成功安装。

![image](https://user-images.githubusercontent.com/10401816/141695317-706d0d3c-26ef-474b-8cf3-b5be6b8165f1.png)

**Comment by Jrohy** [comment]
看看证书申请成功没

**Comment by luobingwei** [comment]
> 看看证书申请成功没

请问证书申请成功是放到那个位置的呢？

**Comment by Jrohy** [comment]
看看配置文件里面写的位置: /usr/local/etc/trojan/config.json

**Comment by luobingwei** [comment]
> 看看配置文件里面写的位置: /usr/local/etc/trojan/config.json

感谢作者！我把老的服务器的同样名字下的证书传了一份就可以了。
