### ISSUE TITLE
ubuntu20，安装docker时可能需要一并安装iptables

### ISSUE THREAD

**Issue by alongL** [Jrohy/trojan#576]
在ubuntu 20.04上安装时发现最后运行maria的docker时失败，查看原因是docker服务没有启动成功，具体原因如下：
就是没有iptables，所以可能需要在安装docker时一并安装。

root@rack:~# journalctl _PID=5040
-- Logs begin at Mon 2021-11-15 03:00:30 GMT, end at Mon 2021-11-15 03:10:03 GMT. --
Nov 15 03:08:43 rack dockerd[5040]: time="2021-11-15T03:08:43.236001496Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
Nov 15 03:08:44 rack dockerd[5040]: failed to start daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: Iptables not found

**Comment by Jrohy** [comment]
依赖仓库已添加依赖: `https://github.com/Jrohy/docker-install`
