### ISSUE TITLE
报错，找不到p4gafult/trojan-go

### ISSUE THREAD

**Issue by sjkhsl** [Jrohy/trojan#579]
Nov 22 13:18:24 debian trojan[8447]: [INFO]  2021/11/22 13:18:24 tcp connection from 110.17.124.64:46766
Nov 22 13:18:24 debian trojan[8447]: [INFO]  2021/11/22 13:18:24 tcp connection from 110.17.124.64:46768
Nov 22 13:18:24 debian trojan[8447]: [ERROR] 2021/11/22 13:18:24 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:140 tls handshake failed | EOF
Nov 22 13:18:24 debian trojan[8447]: [INFO]  2021/11/22 13:18:24 tcp connection from 110.17.124.64:46764
Nov 22 13:18:37 debian trojan[8447]: [INFO]  2021/11/22 13:18:37 buffered data has been written into the database
Nov 22 13:18:37 debian trojan[8447]: [INFO]  2021/11/22 13:18:37 buffered data has been written into the database
Nov 22 13:19:07 debian trojan[8447]: [INFO]  2021/11/22 13:19:07 buffered data has been written into the database
Nov 22 13:19:07 debian trojan[8447]: [INFO]  2021/11/22 13:19:07 buffered data has been written into the database
Nov 22 13:19:37 debian trojan[8447]: [INFO]  2021/11/22 13:19:37 buffered data has been written into the database
Nov 22 13:19:37 debian trojan[8447]: [INFO]  2021/11/22 13:19:37 buffered data has been written into the database

出现这个错误，我去p4gefault的仓库看了看，像是清空仓库了？没有trojan-go～

**Comment by sjkhsl** [comment]
凌晨还能搜到p4gafult的用户，现在用户都没了～这是大佬删库跑路了？

**Comment by Jrohy** [comment]
https://github.com/p4gefau1t/trojan-go ,还在
