### ISSUE TITLE
mysql一直无限启动中.....

### ISSUE THREAD

**Issue by qler1423** [Jrohy/trojan#58]
按照代码运行到最后安装mysql就一直无法启动了

**Comment by Jrohy** [comment]
停止掉，看下mysql启动日志, docker logs -f trojan-mysql

**Comment by Jrohy** [comment]
另外vps内存有没有512m+呢, 如果低于512的估计mysql起不来。

**Comment by qler1423** [comment]
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Initialization of mysqld failed: 0
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15

内存没问题

**Comment by Jrohy** [comment]
failed启动不了，你可以卸载了手动安装看看
```
docker rm -f trojan-mysql
rm -rf /home/mysql
```
手动安装:
docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server:5.7
然后再看下日志有没有说failed

**Comment by wanghaisheng** [comment]
same here
```
root@wordpress-s-1vcpu-1gb-sfo2-01:~# docker logs -f trojan-mysql 
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

[Entrypoint] ignoring /docker-entrypoint-initdb.d/*

[Entrypoint] Server shut down

[Entrypoint] MySQL init process done. Ready for start up.

[Entrypoint] Starting MySQL 5.7.29-1.1.15
```

**Comment by liuxyon** [comment]
me too.
docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

[Entrypoint] ignoring /docker-entrypoint-initdb.d/*

[Entrypoint] Server shut down

[Entrypoint] MySQL init process done. Ready for start up.

[Entrypoint] Starting MySQL 5.7.29-1.1.15

**Comment by dylan-chen** [comment]
我用bbrplus加速重启后 docker 启动失败所以一只报连接数据库，应该是内核导致docker启动失败了。
