### ISSUE TITLE
在docker容器中安装trojan时有如下报错

### ISSUE THREAD

**Issue by dongyu66** [Jrohy/trojan#582]
本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.p02WOyQCdW...
Downloading trojan 1.16.0...
######################################################################## 100.0%
Unpacking trojan 1.16.0...
Installing trojan 1.16.0 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Failed to get D-Bus connection: No such file or directory
Failed to get D-Bus connection: No such file or directory
Failed to get D-Bus connection: No such file or directory

**Comment by impdx** [comment]
我也是有这个报错，请问是如何解决的

**Comment by Jrohy** [comment]
@impdx  新镜像解决了，也可以不换新镜像， 运行命令`curl -L https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -o /usr/bin/systemctl` 替换下systemctl就好
