### ISSUE TITLE
想问一下，有没有admin的操作记录日志输出

### ISSUE THREAD

**Issue by WillZaan** [Jrohy/trojan#587]
因为我看到我的账号的流量使用总量突然全部置为0了，想确定一下是我个人误操作还是哪里出了问题导致流量使用量清理

**Comment by Jrohy** [comment]
如果有流量限制, 且设置了限期，默认每月1号会自动重置流量的，可以去系统设置->改重置日那里关了

**Comment by WillZaan** [comment]
是这个原因，我记得我设置了0关闭，不知道什么时候又被打开了，谢谢。
