### ISSUE TITLE
clash订阅地址可以加个trojan for websocket？？？

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#588]
clash订阅地址可以加个trojan for websocket？？？

**Comment by Potterli20** [comment]
https://github.com/Dreamacro/clash/wiki/configuration#all-configuration-options   trojan-ws

**Comment by Jrohy** [comment]
新版已添加，可以升级试试

**Comment by k1349691865** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Potterli20** [comment]
> 新版已添加，可以升级试试

可以了

**Comment by Potterli20** [comment]
![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png)
![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)

**Comment by Potterli20** [comment]
所以，如果这个 #590 issues用trojan-go的ws就有问题了,这个问题我也是刚刚知道的

**Comment by Jrohy** [comment]
@Potterli20 unsupported rule type RULE-SET 这个是core不支持的规则吧， rule-providers和RULE-SET是premium-core才支持: https://github.com/Dreamacro/clash/wiki/premium-core-features

**Comment by Potterli20** [comment]
> @Potterli20 unsupported rule type RULE-SET 这个是core不支持的规则语法吧， rule-providers和RULE-SET是premium-core才支持: https://github.com/Dreamacro/clash/wiki/premium-core-features

其实还有一个问题就是hosts，无法生成正确的

**Comment by Jrohy** [comment]
host是读取配置文件里面的host值的: 
![image](https://user-images.githubusercontent.com/12463263/145606114-66761fd8-b2fb-41c8-8e34-548f35413627.png)

**Comment by Potterli20** [comment]
> host是读取配置文件里面的websocket.host值的: ![image](https://user-images.githubusercontent.com/12463263/145606114-66761fd8-b2fb-41c8-8e34-548f35413627.png)

其实我的host 没有写的我的remote_addr 是写了127.0.0.1 的 就sni 的就写了域名
https://github.com/p4gefau1t/trojan-go#websocket

**Comment by Jrohy** [comment]
是直接没有host一项是吗

**Comment by Potterli20** [comment]
> 配置文件是直接没有websocket.host一项是吗

是有的，服务端这个可以写可以不写，但是客户端host是要写的

**Comment by Potterli20** [comment]
{
  "run_type": "server",
  "local_addr": "::",
  "local_port": 2083,
  "remote_addr": "127.0.0.1",
  "remote_port": 82,
  "password": null,
  "log_level": 1,
  "ssl": {
    "cert": "/root/XXXX.XXXXX.online.pem",
    "key": "/root/XXXXX.XXXXi.online.key",
    "key_password": "",
    "fallback_addr": "127.0.0.1",
    "fallback_port": 82,
    "fingerprint": "chrome",
    "cipher": "EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+ECDSA+AES128:EECDH+aRSA+AES128:EECDH+ECDSA+AES256:EECDH+aRSA+AES256:!MD5:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS",
    "cipher_tls13": "TLS-AES-256-GCM-SHA384:TLS-CHACHA20-POLY1305-SHA256:TLS-AES-128-GCM-SHA256:TLS-AES-128-CCM-8-SHA256:TLS-AES-128-CCM-SHA256",
    "prefer_server_cipher": true,
    "alpn": [ "http/1.1"],
    "alpn_port_override": {
      "h2": 82
    },
    "reuse_session": true,
    "session_ticket": false,
    "session_timeout": 600,
    "plain_http_response": "",
    "curves": "ECC",
    "dhparam": "",
    "sni": "XXX.XXXi.online"
  },
  "tcp": {
    "prefer_ipv4": false,
    "no_delay": true,
    "keep_alive": true,
    "reuse_port": false,
    "fast_open": false,
    "fast_open_qlen": 10
  },
  "forward_proxy": {
    "enabled": true,
    "proxy_addr": "0.0.0.0",
    "proxy_port": 83,
    "username": "",
    "password": ""
  },
  "mux": {
    "enabled": true,
    "concurrency": 5,
    "idle_timeout": -1
  },
  "mysql": {
    "enabled": true,
    "server_addr": "localhost",
    "server_port": 3306,
    "database": "trojan",
    "username": "root",
    "password": "liguoyao",
    "cafile": ""
  },
  "websocket": {
    "enabled": true,
    "path": "/"
  }
}

**Comment by Jrohy** [comment]
当前版本确实存在服务端配置文件没写host但生成的配置还是会存在host项的问题，下个版本修复下

**Comment by Potterli20** [comment]
> 

okkk

**Comment by Jrohy** [comment]
@Potterli20 新版已做优化

**Comment by Potterli20** [comment]
正常了

**Comment by HUAHUAI23** [comment]
> ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)

这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密

**Comment by Potterli20** [comment]
> > ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)
> 
> 这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密
> 

用不了开启ss的
只能是ws协议和tcp协议

**Comment by HUAHUAI23** [comment]
> > > ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)
> > 
> > 
> > 这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密
> 
> 用不了开启ss的 只能是ws协议和tcp协议

这有点糟糕，因为我看到 trojan-go 文档上面是建议开ss，因为走了cdn后流量是透明的

**Comment by Potterli20** [comment]
> > > > ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)
> > > 
> > > 
> > > 这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密
> > 
> > 用不了开启ss的 只能是ws协议和tcp协议
> 
> 这有点糟糕，因为我看到 trojan-go 文档上面是建议开ss，因为走了cdn后流量是透明的

如果要用在clash就不行，但其他程序可以

**Comment by HUAHUAI23** [comment]
> > > > > ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)
> > > > 
> > > > 
> > > > 这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密
> > > 
> > > 
> > > 用不了开启ss的 只能是ws协议和tcp协议
> > 
> > 
> > 这有点糟糕，因为我看到 trojan-go 文档上面是建议开ss，因为走了cdn后流量是透明的
> 
> 如果要用在clash就不行，但其他程序可以

问一下 都有哪些 trojan的客服端

**Comment by Potterli20** [comment]
> > > > > > ![火狐截图_2021-12-10T15-00-04 629Z](https://user-images.githubusercontent.com/28734349/145594734-ab5aa139-e1f7-4ff1-bc03-36c24e53f582.png) ![2021-12-10 16-01-16屏幕截图](https://user-images.githubusercontent.com/28734349/145594765-532a5e0d-f365-40c1-8bc0-289409f4e5da.png)
> > > > > 
> > > > > 
> > > > > 这个配置如何在 trojan 开启 ss的 AES-128-GCM 加密
> > > > 
> > > > 
> > > > 用不了开启ss的 只能是ws协议和tcp协议
> > > 
> > > 
> > > 这有点糟糕，因为我看到 trojan-go 文档上面是建议开ss，因为走了cdn后流量是透明的
> > 
> > 如果要用在clash就不行，但其他程序可以
> 
> 问一下 都有哪些 trojan的客服端

v2rayng之类的
