### ISSUE TITLE
把Trojan安装在 google cloud的VPS后，一直收到 google 电邮说VPS 在挖矿，已确认过没开别的端口, 只开了 80,443 tcp

### ISSUE THREAD

**Issue by calvinciw** [Jrohy/trojan#589]
把这个安装在 google cloud后，一直收到 google 说VPS 在挖矿，已确认过没开别的端口, 只开了 80,443 tcp.
除TCP的80, 443外，其他端口我都没打开，而助我没安装别的服务，只有大大的Trojan. 不知道为什么一直收到 google 说那台VPS 在挖矿

**Comment by calvinciw** [comment]
> 把这个安装在 google cloud后，一直收到 google 说VPS 在挖矿，已确认过没开别的端口, 只开了 80,443 tcp. 除TCP的80, 443外，其他端口我都没打开，而助我没安装别的服务，只有大大的Trojan. 不知道为什么一直收到 google 说那台VPS 在挖矿

另外SSH是没允许 root 用户直接登入，也没有打开 密码登入，都是用public key 和 private key 来做登入认证

**Comment by Jrohy** [comment]
可能误报，你可以停了web端看看只留trojan核心在跑看看还会不会:
```
systemctl stop trojan-web
systemctl disable trojan-web
```

**Comment by Jrohy** [comment]
这样就只保留了命令行功能，用命令行操作都行的，只是一部分需要常驻后台的功能没法用(比如定时任务，每月流量重置之类的)

**Comment by calvinciw** [comment]
> 这样就只保留了命令行功能，用命令行操作都行的，只是一部分需要常驻后台的功能没法用(比如定时任务，每月流量重置之类的)

只要能用就行，因为都是自己在用，流量重置那些用不着

**Comment by calvinciw** [comment]
@Jrohy 
另外想请教一下, 我打开了 tcpdump, 发现了以下的封包, 有关于 Tor 的, 是否跟这个掘矿有关系?
`    exitrelay16.medvideos-tor.org.49656 > example.internal.https: Flags [S], cksum 0xb03f (correct), seq 2483429725, win 64240, options [mss 1400,sackOK,TS val 3772235367 ecr 0,nop,wscale 7], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49656: Flags [S.], cksum 0x84e3 (incorrect -> 0x4e8a), seq 348886109, ack 2483429726, win 28160, options [mss 1420,sackOK,TS val 3146746308 ecr 3772235367,nop,wscale 11], length 0
    exitrelay16.medvideos-tor.org.49656 > example.internal.https: Flags [.], cksum 0xe829 (correct), seq 1, ack 1, win 502, options [nop,nop,TS val 3772235642 ecr 3146746308], length 0
    metadata.google.internal.domain > example.internal.58472: [udp sum ok] 12977 q: PTR? 76.14.189.107.in-addr.arpa. 1/0/0 76.14.189.107.in-addr.arpa. PTR exitrelay16.medvideos-tor.org. (87)
    exitrelay16.medvideos-tor.org.49656 > example.internal.https: Flags [P.], cksum 0xd694 (correct), seq 1:244, ack 1, win 502, options [nop,nop,TS val 3772238715 ecr 3146746308], length 243
    example.internal.https > exitrelay16.medvideos-tor.org.49656: Flags [.], cksum 0x84db (incorrect -> 0xd008), seq 1, ack 244, win 15, options [nop,nop,TS val 3146749656 ecr 3772238715], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49656: Flags [P.], cksum 0x84e2 (incorrect -> 0x65f4), seq 1:8, ack 244, win 15, options [nop,nop,TS val 3146749656 ecr 3772238715], length 7
    example.internal.https > exitrelay16.medvideos-tor.org.49656: Flags [F.], cksum 0x84db (incorrect -> 0xd000), seq 8, ack 244, win 15, options [nop,nop,TS val 3146749656 ecr 3772238715], length 0
    exitrelay16.medvideos-tor.org.49656 > example.internal.https: Flags [.], cksum 0xcd06 (correct), seq 244, ack 8, win 502, options [nop,nop,TS val 3772238991 ecr 3146749656], length 0
    exitrelay16.medvideos-tor.org.49656 > example.internal.https: Flags [F.], cksum 0xcd04 (correct), seq 244, ack 9, win 502, options [nop,nop,TS val 3772238991 ecr 3146749656], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49656: Flags [.], cksum 0x84db (incorrect -> 0xcdd8), seq 9, ack 245, win 15, options [nop,nop,TS val 3146749931 ecr 3772238991], length 0
    exitrelay16.medvideos-tor.org.49986 > example.internal.https: Flags [S], cksum 0x4638 (correct), seq 3240447633, win 64240, options [mss 1400,sackOK,TS val 3772239057 ecr 0,nop,wscale 7], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49986: Flags [S.], cksum 0x84e3 (incorrect -> 0x8d14), seq 1298310347, ack 3240447634, win 28160, options [mss 1420,sackOK,TS val 3146749997 ecr 3772239057,nop,wscale 11], length 0
    exitrelay16.medvideos-tor.org.49986 > example.internal.https: Flags [.], cksum 0x26b5 (correct), seq 1, ack 1, win 502, options [nop,nop,TS val 3772239331 ecr 3146749997], length 0
        Client, Leap indicator:  (0), Stratum 0 (unspecified), poll 10 (1024s), precision 32
          Originator Timestamp: 0.000000000
            Originator - Receive Timestamp:  0.000000000
            Originator - Transmit Timestamp: 1176668027.418976865 (2073/05/22 10:42:03)
        Server, Leap indicator:  (0), Stratum 2 (secondary reference), poll 10 (1024s), precision -20
          Originator Timestamp: 1176668027.418976865 (2073/05/22 10:42:03)
            Originator - Receive Timestamp:  -1623188139.101839665
            Originator - Transmit Timestamp: -1623188139.101839665
    exitrelay16.medvideos-tor.org.49986 > example.internal.https: Flags [P.], cksum 0x82ed (correct), seq 1:227, ack 1, win 502, options [nop,nop,TS val 3772242408 ecr 3146749997], length 226
    example.internal.https > exitrelay16.medvideos-tor.org.49986: Flags [.], cksum 0x84db (incorrect -> 0x0e9e), seq 1, ack 227, win 15, options [nop,nop,TS val 3146753348 ecr 3772242408], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49986: Flags [F.], cksum 0x84db (incorrect -> 0x0e9d), seq 1, ack 227, win 15, options [nop,nop,TS val 3146753348 ecr 3772242408], length 0
    exitrelay16.medvideos-tor.org.49986 > example.internal.https: Flags [F.], cksum 0x0ba3 (correct), seq 227, ack 2, win 502, options [nop,nop,TS val 3772242682 ecr 3146753348], length 0
    example.internal.https > exitrelay16.medvideos-tor.org.49986: Flags [.], cksum 0x84db (incorrect -> 0x0c78), seq 2, ack 228, win 15, options [nop,nop,TS val 3146753622 ecr 3772242682], length 0
    tor-exit-13.zbau.f3netze.de.11336 > example.internal.https: Flags [S], cksum 0x8cd4 (correct), seq 1622289661, win 42340, options [mss 1460,sackOK,TS val 2481691819 ecr 0,nop,wscale 12], length 0
    example.internal.https > tor-exit-13.zbau.f3netze.de.11336: Flags [S.], cksum 0x29a7 (incorrect -> 0x90fc), seq 2821613925, ack 1622289662, win 28160, options [mss 1420,sackOK,TS val 2765716710 ecr 2481691819,nop,wscale 11], length 0
    tor-exit-13.zbau.f3netze.de.11336 > example.internal.https: Flags [.], cksum 0x2d5c (correct), seq 1, ack 1, win 11, options [nop,nop,TS val 2481691881 ecr 2765716710], length 0
    tor-exit-13.zbau.f3netze.de.11336 > example.internal.https: Flags [F.], cksum 0x2d49 (correct), seq 1, ack 1, win 11, options [nop,nop,TS val 2481691899 ecr 2765716710], length 0
    example.internal.https > tor-exit-13.zbau.f3netze.de.11336: Flags [F.], cksum 0x299f (incorrect -> 0x2c03), seq 1, ack 2, win 14, options [nop,nop,TS val 2765717032 ecr 2481691899], length 0
    tor-exit-13.zbau.f3netze.de.11336 > example.internal.https: Flags [.], cksum 0x2bc8 (correct), seq 2, ack 2, win 11, options [nop,nop,TS val 2481691961 ecr 2765717032], length 0
    metadata.google.internal.domain > example.internal.25222: [udp sum ok] 63891 q: PTR? 240.100.220.185.in-addr.arpa. 1/0/0 240.100.220.185.in-addr.arpa. PTR tor-exit-13.zbau.f3netze.de. (87)
    tor-exit-7.zbau.f3netze.de.9226 > example.internal.https: Flags [S], cksum 0x3c01 (correct), seq 3437363773, win 42340, options [mss 1460,sackOK,TS val 2481828932 ecr 0,nop,wscale 12], length 0
    example.internal.https > tor-exit-7.zbau.f3netze.de.9226: Flags [S.], cksum 0x29ad (incorrect -> 0x40a4), seq 3823822821, ack 3437363774, win 28160, options [mss 1420,sackOK,TS val 2293227096 ecr 2481828932,nop,wscale 11], length 0
    tor-exit-7.zbau.f3netze.de.9226 > example.internal.https: Flags [.], cksum 0xdd03 (correct), seq 1, ack 1, win 11, options [nop,nop,TS val 2481828994 ecr 2293227096], length 0
    metadata.google.internal.domain > example.internal.56722: [udp sum ok] 9200 q: PTR? 246.100.220.185.in-addr.arpa. 1/0/0 246.100.220.185.in-addr.arpa. PTR tor-exit-7.zbau.f3netze.de. (86)
    tor-exit-7.zbau.f3netze.de.9226 > example.internal.https: Flags [P.], cksum 0x3b92 (correct), seq 1:45, ack 1, win 11, options [nop,nop,TS val 2481829897 ecr 2293227096], length 44
    example.internal.https > tor-exit-7.zbau.f3netze.de.9226: Flags [.], cksum 0x29a5 (incorrect -> 0xca3a), seq 1, ack 45, win 14, options [nop,nop,TS val 2293230955 ecr 2481829897], length 0
    example.internal.https > tor-exit-7.zbau.f3netze.de.9226: Flags [F.], cksum 0x29a5 (incorrect -> 0xca38), seq 1, ack 45, win 14, options [nop,nop,TS val 2293230956 ecr 2481829897], length 0
    tor-exit-7.zbau.f3netze.de.9226 > example.internal.https: Flags [.], cksum 0xc9fd (correct), seq 45, ack 2, win 11, options [nop,nop,TS val 2481829959 ecr 2293230956], length 0
    tor-exit-7.zbau.f3netze.de.9226 > example.internal.https: Flags [F.], cksum 0xc9fb (correct), seq 45, ack 2, win 11, options [nop,nop,TS val 2481829960 ecr 2293230956], length 0
    example.internal.https > tor-exit-7.zbau.f3netze.de.9226: Flags [.], cksum 0xc8ff (correct), seq 2, ack 46, win 14, options [nop,nop,TS val 2293231205 ecr 2481829960], length 0
        Client, Leap indicator:  (0), Stratum 0 (unspecified), poll 10 (1024s), precision 32
          Originator Timestamp: 0.000000000
            Originator - Receive Timestamp:  0.000000000
            Originator - Transmit Timestamp: 238507882.764456284 (2043/08/30 02:39:38)
        Server, Leap indicator:  (0), Stratum 2 (secondary reference), poll 10 (1024s), precision -20
          Originator Timestamp: 238507882.764456284 (2043/08/30 02:39:38)
            Originator - Receive Timestamp:  -685026956.651232128
            Originator - Transmit Timestamp: -685026956.651232128`

**Comment by Jrohy** [comment]
停了trojan-web还是会有报吗

**Comment by calvinciw** [comment]
> 停了trojan-web还是会有报吗

停了暂时没报, 但是有时候会发现有 Tor (Tor浏览器?) 的封包出现

**Comment by lyin888** [comment]
楼主有没有搭建破解版的宝塔面板

**Comment by lyin888** [comment]
前段时间也出现两次类似情况，第一次删了重建，用了一天，第二次直接把账号给暂停了，废了好大劲验证的账号通过后，删除所有虚拟机包括ssh密钥后重新搭建的，到现在暂时没有再出现过问题。

**Comment by calvinciw** [comment]
> 前几天也出现两次类似情况，第一次删了重建，用了一天，第二次直接把账号给暂停了，废了好大劲验证的账号通过后，删除所有虚拟机包括ssh密钥后重新搭建的，到现在暂时没有再出现过问题。

我遇到第一次后就把所有VM资源都删了，然后隔不了两天，又有一个挖矿警告，再次删了VM资源去重建，隔不了一天，再弹出来。最后我直接,连专案也删了，把所有都重建一次，到现在用了六天，暂时还没弹警告。
我是除了TCP 80, 443 外, 所有端口都没打开，然后只安装了大神 @Jrohy 的 trojan, 什么宝塔或者监控软件都没安装，SSH 是必需要使用 证书来认证，而且也没允许ROOT用户登入，所以我才上来问一下 @Jrohy 大神
