### ISSUE TITLE
mac导入clash 报托管配置文件格式不正确

### ISSUE THREAD

**Issue by 4640396** [Jrohy/trojan#590]
报托管配置文件格式不正确：rules[0][RULE-SET,applications,DIRECT]error:unsupported rule type RULE-SET

**Comment by Jrohy** [comment]
用的什么软件，是clash_for_windows吗，有没有修改过clash的规则

**Comment by Jrohy** [comment]
得用Clash Premium版本才行， https://github.com/Loyalsoldier/clash-rules，或者自己修改clash规则，可以自定义的

**Comment by sanmern** [comment]
只有Clash X Pro的clash内核是premium版，换pro就行了

**Comment by sanmern** [comment]
如果是clash x，你得使用pro，pro是clash premium

**Comment by luckylele666** [comment]
> 得用Clash Premium版本才行， https://github.com/Loyalsoldier/clash-rules ，或者自己修改clash规则，可以自定义的

请教为啥要用 ClashX Pro，这个常常要闪退……
