### ISSUE TITLE
流量重置不起作用

### ISSUE THREAD

**Issue by fr-guoqing** [Jrohy/trojan#592]
我的流量重置一直不起作用，设置了 10 号，但是流量一直没有重置。请问有可能是什么问题造成的？

**Comment by Jrohy** [comment]
只有这些用户才会重置流量: 
![image](https://user-images.githubusercontent.com/12463263/145744580-2cda99c6-6276-4182-8dd7-8221422bac00.png)
设置了到期日期和流量限制的才会重置

**Comment by fr-guoqing** [comment]
好的 了解了 感谢
