### ISSUE TITLE
clash规则在android上有问题

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#595]
修改clash规则

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY

这样android才正确使用

**Comment by Jrohy** [comment]
不支持RULE-SET则自己在web界面里修改下基本clash规则

**Comment by Potterli20** [comment]
> 自己在web界面里修改下基本clash规则就好

下面的规则就不能用也

**Comment by Jrohy** [comment]
不支持RULE-SET就没办法了，用的规则是这里的: https://github.com/Loyalsoldier/clash-rules, 得 Clash Premium内核才行

**Comment by Jrohy** [comment]
不清楚你用的什么安卓客户端， 实测 https://github.com/Kr328/ClashForAndroid 是支持的, 会导入rule-providers为外部资源

**Comment by Potterli20** [comment]
> 不清楚你用的什么安卓客户端， 实测 https://github.com/Kr328/ClashForAndroid 是支持的, 会导入rule-providers为外部资源

也是这个，但是不知道为为什么就是更新不了，要这样才可以更新
rules:

    DOMAIN,clash.razord.top,DIRECT
    DOMAIN,yacd.haishan.me,DIRECT
    GEOIP,,DIRECT
    GEOIP,CN,DIRECT
    MATCH,PROXY

**Comment by Potterli20** [comment]
规则重置也不行

**Comment by Jrohy** [comment]
是不是用错版本了，应该得Premium版本才行
![image](https://user-images.githubusercontent.com/12463263/147357361-83b22588-3c78-4246-8ad8-ea4e125d0cf1.png)

**Comment by Potterli20** [comment]
> 是不是用错版本了，应该得Premium版本才行 ![image](https://user-images.githubusercontent.com/12463263/147357361-83b22588-3c78-4246-8ad8-ea4e125d0cf1.png)

哈哈哈，我尴尬了
