### ISSUE TITLE
面板如何使用其他路径的ssl证书

### ISSUE THREAD

**Issue by LGinC** [Jrohy/trojan#599]
证书路径不在默认的/root/.acme.sh下，`/usr/local/bin/trojan web -p 2088 --ssl`如何指定证书路径

**Comment by Jrohy** [comment]
运行trojan tls选择自定义证书路径

**Comment by Why-Wt** [comment]
指定自定义证书后启动不成功
![image](https://user-images.githubusercontent.com/104899639/170855686-00f4a911-ef48-4eec-b1f0-e41b4fb30cba.png)
