### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by sunshine-rain-bow** [Jrohy/trojan#6]
多用户管理还是集成web界面比较好管理，命令行太糙了

**Comment by Jrohy** [comment]
后面会考虑下

**Comment by shengshengman0** [comment]
https://trojan-tutor.github.io/2019/06/08/p43.html
在网上搜了些资料，应该会有帮助

**Comment by Jrohy** [comment]
https://github.com/Jrohy/trojan-web

**Comment by shengshengman0** [comment]
好的，谢谢大佬

**Comment by shengshengman0** [comment]
> https://github.com/Jrohy/trojan-web
> 正在开发中，最近会发布新版，包括web功能
完全不知道怎么用？

**Comment by Jrohy** [comment]
@shengshengman0 这个只是前端开发单独一个源码项目而已， 到时使用还是在此项目里，前端编译出来的静态文件是放进后台二进制文件里的。预估今天发新版

**Comment by Jrohy** [comment]
@sunshine-rain-bow @shengshengman0  2.0版本已发布, 增加了web页面管理trojan用户,  运行`source <(curl -sL https://git.io/trojan-install)`即可更新
