### ISSUE TITLE
新安装报错docker: Connot connect to the Docker daemon at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by awds888** [Jrohy/trojan#602]
docker run --name trojan-mariadb --restart=always -p 45172:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=nqekW -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
2022-01-20 08:20:19 mariadb启动中,请稍等...
2022-01-20 08:20:21 mariadb启动中,请稍等...
2022-01-20 08:20:23 mariadb启动中,请稍等...

**Comment by awds888** [comment]
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-01-20 07:14:25 UTC; 1h 8min ago
     Docs: https://docs.docker.com
  Process: 4838 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 4838 (code=exited, status=1/FAILURE)

Jan 20 07:14:25 jp1 systemd[1]: docker.service: Service RestartSec=100ms expired, scheduling restart.
Jan 20 07:14:25 jp1 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Jan 20 07:14:25 jp1 systemd[1]: Stopped Docker Application Container Engine.
Jan 20 07:14:25 jp1 systemd[1]: docker.service: Start request repeated too quickly.
Jan 20 07:14:25 jp1 systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 20 07:14:25 jp1 systemd[1]: Failed to start Docker Application Container Engine.

**Comment by Jrohy** [comment]
什么系统

**Comment by awds888** [comment]
新安装的Debian 10.3

**Comment by Jrohy** [comment]
我用vultr的debian10测试没问题，你可以单独试试安装docker看看, 调用的是这个仓库的安装脚本: https://github.com/Jrohy/docker-install
