### ISSUE TITLE
求助：websocket连接返回401错误

### ISSUE THREAD

**Issue by Tucherry** [Jrohy/trojan#609]
今天换成Trojan-go后，也手动修改了配置文件，只加了下面的代码

    "websocket":` {
    "enabled": true,
    "path": "/tnndwsmbd",
    "host": "xxx.xxx"
    }
服务器端没有报错日志，但是日志里我客户端的连接请求也被当成了not a trojan request
客户端我用的是V2rayN，下面是客户端日志
`2022/02/02 17:28:06 [Warning] [2380106861] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxx.xxx/tnndwsmbd): 401 Unauthorized > websocket: bad handshake] > common/retry: all retry attempts failed`

请问是哪个地方不对？

**Comment by linguodong** [comment]
有解决么？我的vps今天也出现这个问题，ssh连接都正常，系统重新安装 重新装trojan也是一样。

**Comment by Tucherry** [comment]
> 有解决么？我的vps今天也出现这个问题，ssh连接都正常，系统重新安装 重新装trojan也是一样。

解决了，网页切换type是假的，不管选哪个都是原版trojan，我自己手动安装了trojan-go就可以用了
