### ISSUE TITLE
一键脚本创建数据库时建议可以自己输入用户名

### ISSUE THREAD

**Issue by CnSuperYoung** [Jrohy/trojan#61]
我用的阿里云的数据库，root不允许使用，另外我一般会便于管理自己先创建好数据库以及用户名及密码，希望能直接输入对应的参数

**Comment by Jrohy** [comment]
修改下trojan配置文件就好， /usr/local/etc/trojan/config.json 这个文件

**Comment by CnSuperYoung** [comment]
那我到安装数据库那一步是直接安装本机后再改文件还是ctrl+c终止？

**Comment by Jrohy** [comment]
可以直接回车跳过，然后去改trojan配置文件，改为配置文件重启下trojan, systemctl restart trojan

**Comment by Jrohy** [comment]
不过数据库方面要先创建个users表， 数据库名其实就没所谓，就是必须要有这个表在 https://trojan-gfw.github.io/trojan/authenticator

**Comment by Jrohy** [comment]
trojan在国外服务器，但数据库在国内阿里云的话，就要特别关注下国内和国外的网络延迟了。

**Comment by CnSuperYoung** [comment]
感谢指导，数据库配置我改了，延迟是香港服务器ping国内数据库，延时在138MS左右，没超过200，数据库地址是用的域名映射，因为阿里的数据库不给数字的ip，也是给的一串域名
`
"mysql": {
        "enabled": true,
        "server_addr": "mysql.db.yzj.link",
        "server_port": 3306,
        "db": "vpn_trojan",
        "username": "****",
        "password": "****"
    }
`
上面是配置文件的连接，重启trojan还是提示mysql连接失败
dial tcp 127.0.0.1:3306: connect: connection refused
连接mysql失败!

**Comment by Jrohy** [comment]
你改了mysql的连接地址了吗，不是127.0.0.1了

**Comment by CnSuperYoung** [comment]
是的，我已经改了啊，在/usr/local/etc/trojan/config.json文件的最后那边mysql为key的对象里改了，server_addr改成了"mysql.db.yzj.link"

**Comment by Jrohy** [comment]
改了的话重启下trojan, 然后看下状态systemctl status trojan

**Comment by Jrohy** [comment]
不要先看面板，面板连接的mysql地址都是读trojan配置文件的，trojan如果能连上数据库就ok了

**Comment by CnSuperYoung** [comment]
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 六 2020-04-11 16:58:48 CST; 319ms ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
  Process: 20681 ExecStart=/usr/bin/trojan/trojan /usr/local/etc/trojan/config.json (code=exited, status=1/FAILURE)
 Main PID: 20681 (code=exited, status=1/FAILURE)

4月 11 16:58:48 VPN-US systemd[1]: trojan.service: main process exited, code=exited, status=1/FAILURE
4月 11 16:58:48 VPN-US systemd[1]: Unit trojan.service entered failed state.
4月 11 16:58:48 VPN-US systemd[1]: trojan.service failed.


这是查看状态的返回

**Comment by Jrohy** [comment]
你有创建users表吗

**Comment by CnSuperYoung** [comment]
创建了，
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password CHAR(56) NOT NULL,
    quota BIGINT NOT NULL DEFAULT 0,
    download BIGINT UNSIGNED NOT NULL DEFAULT 0,
    upload BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX (password)
);

**Comment by Jrohy** [comment]
可能空表没用户导致trojan无法运作，你用trojan命令来创建用户看下能否创建

**Comment by CnSuperYoung** [comment]
可以了，我重置了无数次的系统，感谢大佬不厌其烦的回答，谢谢

**Comment by Jrohy** [comment]
后面版本我加入下用户名输入吧，不输入回车的话就是默认root用户

**Comment by CnSuperYoung** [comment]
再打扰一下，现在我的https证书签发不了，是不是我今天重置安装，同一个域名签发次数太多了导致的？管理web界面只能通过80端口访问，墙也出不去

**Comment by Jrohy** [comment]
有可能的一天签发太多就签不了的，签证书时会报这个错，要不就第二天再试下签或者换域名

**Comment by CnSuperYoung** [comment]
手动证书部署，用哪个容器的证书？tomcat、Apache、iis、nginx

**Comment by Jrohy** [comment]
手动部署证书自己尝试了
