### ISSUE TITLE
在docker容器中安装trojan时有如下报错

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#610]
这个我也有问题
https://github.com/Jrohy/trojan/issues/582

是否更换一下系统？？

**Comment by Potterli20** [comment]
![图片](https://user-images.githubusercontent.com/28734349/152372689-aa26ad3b-6ea5-449c-b9e6-d2a352db6044.png)

**Comment by kpzhao** [comment]
> ![图片](https://user-images.githubusercontent.com/28734349/152372689-aa26ad3b-6ea5-449c-b9e6-d2a352db6044.png)

系统是debian11？

**Comment by benzBrake** [comment]
同样有这个问题，系统也是 debian 11

**Comment by Potterli20** [comment]
系统是debian 11和debian testing

**Comment by Jrohy** [comment]
测了下ubuntu21.10也有这个问题，无法在docker容器内使用systemctl

**Comment by Potterli20** [comment]
> 测了下ubuntu21.10也有这个问题，无法在docker容器内使用systemd

![2022-02-07 13-43-37 的屏幕截图](https://user-images.githubusercontent.com/28734349/152731143-95b4fca8-92f7-4409-8cc8-437c22d540a2.png)

**Comment by Jrohy** [comment]
用docker buildx才能编译镜像的

**Comment by Potterli20** [comment]
> 用docker buildx才能编译镜像的

FROM --platform=$TARGETPLATFORM debian:latest

LABEL maintainer="Jrohy <euvkzx@Jrohy.com>"

ARG TARGETARCH

ARG VERSION_CHECK="https://api.github.com/repos/Jrohy/trojan/releases/latest"

ARG DOWNLAOD_URL="https://github.com/Jrohy/trojan/releases/download/"

ARG SERVICE_URL="https://raw.githubusercontent.com/Jrohy/trojan/master/asset/trojan-web.service"

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install socat bash-completion cron iptables openssl unzip curl -y && \
    LATEST_VERSION=`curl -H 'Cache-Control: no-cache' -s "$VERSION_CHECK" | grep 'tag_name' | cut -d\" -f4` && \
    [[ $TARGETARCH =~ "arm64" ]] && ARCH="arm64" || ARCH="amd64" && \
    curl -fL "$DOWNLAOD_URL/$LATEST_VERSION/trojan-linux-$ARCH" -o /usr/local/bin/trojan && \
    curl -L $SERVICE_URL -o /etc/systemd/system/trojan-web.service && \
    chmod +x /usr/local/bin/trojan && \
    echo "source <(trojan completion bash)" >> ~/.bashrc && \
    apt-get clean all

**Comment by Potterli20** [comment]
![2022-02-07 14-44-27屏幕截图](https://user-images.githubusercontent.com/28734349/152738275-bbc73baa-1379-4392-9900-b022e633d653.png)

**Comment by Potterli20** [comment]
![image_2022-02-07_14-45-22](https://user-images.githubusercontent.com/28734349/152738364-c186c513-b950-4706-9e6f-8dff658e73a5.png)

**Comment by Jrohy** [comment]
不是镜像本身的问题

**Comment by Potterli20** [comment]
> 不是镜像本身的问题

现在我有个问题，本身我服务器上有数据库，但是如何在docker上连接本地的服务器？

**Comment by Jrohy** [comment]
输入mysql ip就行

**Comment by Potterli20** [comment]
> 数据库安装那里输入mysql ip就行

不是外网ip哦，而是那种127.0.0.1那种哦

**Comment by Jrohy** [comment]
安装mysql -> 输入自定义mysql连接

**Comment by Potterli20** [comment]
> 命令行里, 安装mysql -> 输入自定义mysql连接

先解决docker问题吧😂
后面我慢慢研究

**Comment by Jrohy** [comment]
重新下新镜像试试， 应该可以在debian11上运行了

**Comment by Potterli20** [comment]
> 重新下新镜像试试， 应该可以在debian11上运行了
![2022-02-17 20-52-05 的屏幕截图](https://user-images.githubusercontent.com/28734349/154485954-c254cc1d-2112-4cd6-95bc-5183b7821bd5.png)
![2022-02-17 20-54-36 的屏幕截图](https://user-images.githubusercontent.com/28734349/154486006-c57ad234-f0c0-431a-b4c0-49154f690506.png)

**Comment by Potterli20** [comment]
> docker rmi jrohy/trojan

是的，也是一样

**Comment by Jrohy** [comment]
@Potterli20 运行``docker images|grep jrohy/trojan`` 看看镜像id是不是下面的
jrohy/trojan   latest    da38f986a946   5 hours ago   249MB

我用vultr的debian11重启服务没问题

**Comment by Potterli20** [comment]
> @Potterli20 运行`docker images|grep jrohy/trojan` 看看镜像id是不是下面的 jrohy/trojan latest da38f986a946 5 hours ago 249MB
> 
> 我用vultr的debian11重启服务没问题

是这个

 docker images|grep jrohy/trojan
jrohy/trojan    latest    da38f986a946   5 hours ago    249MB

**Comment by Jrohy** [comment]
@Potterli20 试试在容器内运行, systemctl restart trojan-web看看有没报错

**Comment by Potterli20** [comment]
> @Potterli20 试试在容器内运行, systemctl restart trojan-web看看有没报错

更改了端口不生效
好像整个服务没有启动
也看不了trojan的日志
因为我切换了trojan-go的

**Comment by Jrohy** [comment]
主要看在容器内运行systemctl命令有没有报failed to get d-bus connection的错误，包括systemctl status trojan和systemctl restart trojan-web,其他先不用管

**Comment by Potterli20** [comment]
> 主要看在容器内运行systemctl命令有没有报failed to get d-bus connection的错误，包括systemctl status trojan和systemctl restart trojan-web,其他先不用管
![2022-02-17 22-04-21 的屏幕截图](https://user-images.githubusercontent.com/28734349/154497726-29b12368-d00c-47f1-94f5-b67e34315332.png)

**Comment by Jrohy** [comment]
cat /usr/bin/systemctl 看看内容是不是python脚本，因为是替换过的

**Comment by Potterli20** [comment]
> cat /usr/bin/systemctl 看看内容是不是python脚本，因为是替换过的

![2022-02-17 22-10-13 的屏幕截图](https://user-images.githubusercontent.com/28734349/154498807-9c08c747-2b24-44ef-a38d-64129aa3fbec.png)

**Comment by Jrohy** [comment]
你确实用的是新镜像?新镜像这个是一个python2脚本来的，/usr/bin/systemctl: 
![image](https://user-images.githubusercontent.com/12463263/154499583-27f3b729-7610-4a9d-be82-cddacf1e9f94.png)

**Comment by Potterli20** [comment]
> 你确实用的是新镜像?新镜像这个是一个python2脚本来的，/usr/bin/systemctl: ![image](https://user-images.githubusercontent.com/12463263/154499583-27f3b729-7610-4a9d-be82-cddacf1e9f94.png)
![2022-02-17 22-17-08 的屏幕截图](https://user-images.githubusercontent.com/28734349/154500086-9a3d6954-7d45-4bcf-ad23-0eacbcef6dec.png)

**Comment by Jrohy** [comment]
截个图看看镜像id, docker images|grep jrohy/trojan

**Comment by Jrohy** [comment]
还有docker ps |grep trojan-ad顺便看看用什么镜像

**Comment by Potterli20** [comment]
> 还有docker ps |grep trojan-ad顺便看看用什么镜像

原因我知道了
是因为进到了镜像不能更新源，一更新源就出问题了，系统默认的systemctl就有问题了

**Comment by Potterli20** [comment]
![2022-02-17 22-26-34 的屏幕截图](https://user-images.githubusercontent.com/28734349/154501950-bf474c7d-e76a-46fc-943b-5ff22f0ee943.png)

**Comment by Jrohy** [comment]
新版本发现报failed to get d-bus报错的话会自动替换systemctl了

**Comment by Potterli20** [comment]
> 新版本发现报failed to get d-bus报错的话会自动替换systemctl了

好像是重启程序也会有🌝

**Comment by Jrohy** [comment]
只要用到systemctl命令就会触发的，有报错就替换后再运行一次命令

**Comment by Potterli20** [comment]
> 只要用到systemctl命令就会触发的，有报错就替换后再运行一次命令

Okkk
