### ISSUE TITLE
[bug]网页端切换trojan-go无效，仍然是原版trojan

### ISSUE THREAD

**Issue by Tucherry** [Jrohy/trojan#612]
如下图，切换后仍然是trojan1.16.0，而不是trojan-go的版本号
<img width="502" alt="image" src="https://user-images.githubusercontent.com/62337688/152470798-6c54602e-4487-47fa-aab1-c8af022923ea.png">

**Comment by Jrohy** [comment]
可以切换的，在线或者命令行切换

**Comment by Tucherry** [comment]
> 可以切换的，在线或者命令行切换

请问命令怎么切换，我在菜单里没看见，谢谢

**Comment by merlinHan** [comment]
> > 可以切换的，在线或者命令行切换
> 
> 请问命令怎么切换，我在菜单里没看见，谢谢

1. 先在终端输入trojan，按enter
2. 选择选项1.trojan管理
3. 然后选择选项6.切换成trojan-go

**Comment by Tucherry** [comment]
> > > 可以切换的，在线或者命令行切换
> > 
> > 
> > 请问命令怎么切换，我在菜单里没看见，谢谢
> 
> 1. 先在终端输入trojan，按enter
> 2. 选择选项1.trojan管理
> 3. 然后选择选项6.切换成trojan-go

谢谢，解决了
