### ISSUE TITLE
建议 能做到和multi-v2ray共存

### ISSUE THREAD

**Issue by SMG0208** [Jrohy/trojan#62]
先安装好trojan后再安装v2ray,申请v2ray证书的时候应该是80端口去监听trojan了导致v2ray申请证书失败

> [Sat Apr 11 08:53:29 UTC 2020] LISTEN     0      128         :::80                      :::*                   user
s:(("trojan",pid=8306,fd=3))
[Sat Apr 11 08:53:29 UTC 2020] tcp port 80 is already used by 80                      
[Sat Apr 11 08:53:29 UTC 2020] Please stop it first
[Sat Apr 11 08:53:29 UTC 2020] _on_before_issue.
restarting v2ray...
v2ray restart fail !

**Comment by Jrohy** [comment]
面板用了80端口，先停了 systemctl stop trojan-web

**Comment by SMG0208** [comment]
> 面板用了80端口，先停了systemctl stop trojan-web

可以了 谢谢
