### ISSUE TITLE
关于useDays和expiryDate字段的实现代码在哪里？

### ISSUE THREAD

**Issue by winderbro** [Jrohy/trojan#622]
没找到Trojan官方代码中没有这两个字段的相关代码实现呢

**Comment by Jrohy** [comment]
官方没有，本项目实现的

**Comment by winderbro** [comment]
我在本项目的源码中没找到相关实现，只有DB相关的操作，能把代码片段贴出来吗?

**Comment by Jrohy** [comment]
因为只有quota设为0才能让此用户上不了网

**Comment by winderbro** [comment]
> 因为只有quota设为0才能让此用户上不了网
quota = download + upload 应该也很快不能上网了，这样可以直接统计出到期时的流量总额。不过结果都一样👍

**Comment by winderbro** [comment]
Hey @Jrohy , 非常感谢您贡献的代码，我想对本项目提供一些赞助，能否留下Telegram联系方式。

**Comment by oncecrossover** [comment]
> @winderbro tg名字和github用户名一样的

Hello, 不知道哪一个是你，麻烦set一下Username

**Comment by winderbro** [comment]
> @winderbro tg名字和github用户名一样的

Hello, 不知道哪一个是你，麻烦set一下Username

**Comment by Jrohy** [comment]
@winderbro Jrohy_105
