### ISSUE TITLE
奥运结束了

### ISSUE THREAD

**Issue by keengrass** [Jrohy/trojan#626]
你的443还好吗？
我的瓦工216段仍然在等待。从过年到现在了，这次是最长的一次。
大家都反馈下

**Comment by keengrass** [comment]
那看来好像不是按IP段ban的，奇怪的是，我另一台瓦工74开头的已经恢复。不明白具体原因。

**Comment by ancct** [comment]
解了，我也是瓦工！就特么躺枪！冬奥期间我在瓦工的正常网站都无法访问了，无奈解除了https证书……冬奥刚过，443就正常了 。也是没谁了……

**Comment by keengrass** [comment]
等两。会结束看看还放不放trojan的443， 不放的话，只能彻底弃用trojan了。

**Comment by Jie-baobao** [comment]
> 

是因为trojan加密不行的原因吗，威兔瑞是挺稳，就是速度没trojan快

**Comment by keengrass** [comment]
加密没问题，所以IP还是安全的。感觉就是流量特征（端口外网流量异常）被识别了。
