### ISSUE TITLE
在 Docker 中无法启动 trojan

### ISSUE THREAD

**Issue by zhgqthomas** [Jrohy/trojan#629]
我使用 Vultr  Debian 11 的 VPS， 安装 trojan 的时候报 重启 trojan 失败的错误

已经使用 命令 `curl -L https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -o /usr/bin/systemctl` 更新了 systemctl

<img width="879" alt="image" src="https://user-images.githubusercontent.com/1124507/155912194-ed2b5552-07f2-4aaa-802b-44036d89f90c.png">

**Comment by Jrohy** [comment]
先不用管，因为一开始没有证书重启肯定失败的

**Comment by Jrohy** [comment]
新镜像不用手动替换systemctl了，会自动替换的

**Comment by zhgqthomas** [comment]
确实设置证书后 trojan 启动正常了 感谢回复
