### ISSUE TITLE
装了这个面板会不会不存在伪装了，这样搜索引擎直接能搜索到"trojan管理平台“就被屏蔽 IP

### ISSUE THREAD

**Issue by windowstool** [Jrohy/trojan#63]
装了这个面板会不会不存在伪装了，这样搜索引擎直接能搜索到"trojan管理平台“ 就被屏蔽 IP

**Comment by Jrohy** [comment]
可以修改标题的，进入web界面里面修改，没修改就是默认的trojan管理平台

**Comment by ancct** [comment]
> 可以修改标题的，进入web界面里面修改，没修改就是默认的trojan管理平台

请问网页文件在哪个目录呀？找了半天没找到，我想改图标与关键词拒绝蜘蛛抓取……

**Comment by Jrohy** [comment]
前端文件是嵌进去二进制文件(变为字符串)里面找不到的，请求什么接口经过gzip压缩后返回

**Comment by Jrohy** [comment]
@ancct 前端网页没有设置任何关键词的.

**Comment by windowstool** [comment]
图标怎么改？

**Comment by Jrohy** [comment]
暂时不支持修改

**Comment by ancct** [comment]
> 前端文件是嵌进去二进制文件(变为字符串)里面找不到的，请求什么接口经过gzip压缩后返回

了解了，因为以前you2php 习惯的要给首页加密码，拒绝蜘蛛抓取。用以前的trojan脚本，伪装的网页我都会进行大改。
希望以后会越来越完善，能够发现这个真是解决了多用户的大问题！
1：希望增加月归零（或时间清零）
2：希望增加 分用户 改密码功能
3：可惜不能DIY，如果可以我希望在个人登录后的界面 加入 各个系统客户端的下载与教程。
4：目前多用户问题尚未发现解决办法
5：希望面板越做越好，可以仿照BT，加入升级按钮，实施监控，历史日志。
6：我以前的Trojan是正儿八经的网站，BT + LNMP。咱们这个可不可以呢？把网页二级路径面板管理。当然我不是专业的，也仅仅有这个想法，安全问题也不清楚，当下还是要乐于尝试新鲜的事物。
7：折腾使我快乐，感谢大大的脚本！
