### ISSUE TITLE
命令行建议和分布式管理

### ISSUE THREAD

**Issue by awds888** [Jrohy/trojan#631]
希望命令行可以省去交互式输入，比如trojan add user password，这样方便跑脚本批量添加某个账号。另外就是多台这样的，能不能进行流量汇总统计，比如专门有一台做数据库。分布式扩容怎么才方便管理呢？

**Comment by mccyz233** [comment]
多个vps共用一个外部数据库，通过添加外部数据库实现多个vps共同享用
