### ISSUE TITLE
如何自定义端口在clash的配置文件上ws

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#632]
proxies:
  - {name: x.x.x.x:xxx, server: x.x.x.x, port: 自定义, type: trojan, password: xxxxxx, sni: x.x.x.x, network: ws, udp: true, ws-opts: {path: /}}

只想把端口自定义

**Comment by Jrohy** [comment]
修改trojan端口试试

**Comment by Potterli20** [comment]
> 修改trojan端口试试

因为我的443已经占用了，然后我想复用443，但是在clash上没有办法改变，但是可以用sn那种自定义可以

**Comment by Potterli20** [comment]
> 修改trojan端口试试

我的trojan-go已经别反代理了可是，如何在sub订阅上更改端口和ws的路径？就是域名没变🌝

**Comment by Potterli20** [comment]
感觉这个功能变机。。。🌝了
