### ISSUE TITLE
请问如何干净的删除trojan

### ISSUE THREAD

**Issue by huabin** [Jrohy/trojan#636]
我在执行

```
source <(curl -sL https://git.io/trojan-install) --remove
```

命令后，重启服务器，依旧能够访问 web 管理页面。请问如果我手动删除，应该删除哪些内容？

**Comment by Jrohy** [comment]
systemctl status trojan-web还有trojan命令都应该没了，可以试试

**Comment by earth-5G** [comment]
重新安装vps系统，还有比这个还干净的？反正我都是这样的！

**Comment by huabin** [comment]
@Jrohy 多谢
