### ISSUE TITLE
建议提高trojan-web的密码强弱问题

### ISSUE THREAD

**Issue by Potterli20** [Jrohy/trojan#639]
https://github.com/p4gefau1t/trojan-go/issues/59#issuecomment-1062478943

**Comment by Jrohy** [comment]
开源代码，信不过release编译的也可以自己编译，具体参考下build.sh脚本(得先编译好trojan-web前端)

**Comment by Potterli20** [comment]
> 开源代码，信不过release编译的也可以自己编译，具体参考下build.sh脚本(得先编译好trojan-web前端)

我就编译trojan-go的内核

**Comment by Jrohy** [comment]
已出新版做了优化，密码输错3次会限制会锁ip限制登录

**Comment by Jrohy** [comment]
本来想通过ip限制登录接口登录失败多就锁ip来防止穷举出用户密码的(代码都写好了)，后面发现经过https trojan转发后根本获取不到用户ip(经过转发后都是127.0.0.1)😥.

**Comment by Potterli20** [comment]
> 本来想通过ip限制登录接口登录失败多就锁ip来防止穷举出用户密码的(代码都写好了)，后面发现经过https trojan转发后根本获取不到用户ip(经过转发后都是127.0.0.1)😥.

可我用nginx的话是可以的，我是反代理了

**Comment by Jrohy** [comment]
nginx 是可以加些参数就行，但如果没用nginx用trojan或者trojan-go来转发代理https就获取不到实际ip了，除非访问trojan-web用http

**Comment by Potterli20** [comment]
> nginx 是可以加些参数就行，但如果没用nginx用trojan或者trojan-go来转发代理https就获取不到实际ip了，除非访问trojan-web用http

为什么我反代理会出现401？？
