### ISSUE TITLE
请问，如果手动修改密码，在哪个文件？

### ISSUE THREAD

**Issue by pirately** [Jrohy/trojan#64]
请问，如果手动修改密码，在哪个文件？usr/src下面好像没有，/local/etc的是预设mysql的吧，也不是设置

**Comment by Jrohy** [comment]
修改什么密码呢，admin密码？

**Comment by pirately** [comment]
一个是admin密码，一个是trojan本身服务端的密码。虽然web都可以实现。但是如果想手动改，我这儿找不到在哪儿

**Comment by Jrohy** [comment]
trojan命令web管理那里可以改admin密码

**Comment by Jrohy** [comment]
trojan服务端密码就是新建用户设置的密码

**Comment by Jrohy** [comment]
用户建的密码也可以在界面修改的

**Comment by pirately** [comment]
嗯，是的。请问，那如果手动用配置文件改，可以改不？

**Comment by Jrohy** [comment]
管理程序没有用到配置文件的，用的leveldb来存数据

**Comment by pirately** [comment]
好的
