### ISSUE TITLE
MYSQL连接一直失败。

### ISSUE THREAD

**Issue by bbsir2022** [Jrohy/trojan#644]
打算自己安装MYSQL。可是一直提示连接失败。试了端口和用户名密码没有输错阿。用的是mysql5.5的。请问有什么好的解决办法吗？或在哪里能看到设置时的日志，也没有显示出具体的原因。或者说是不是需要在数据库里建什么指定的库名称？

**Comment by Jrohy** [comment]
看看mysql配置对不对: /usr/local/etc/trojan/config.json, 不对改下重启下trojan和trojan-web

**Comment by bbsir2022** [comment]
> 看看mysql配置对不对: /usr/local/etc/trojan/config.json, 不对改下重启下trojan和trojan-web

多谢。另外想问一下网站的根目录在哪呢？

**Comment by Jrohy** [comment]
@bbsir2022 不存在的，前端文件嵌进去二进制文件里面

**Comment by bbsir2022** [comment]
好吧。多谢了。感谢你~
