### ISSUE TITLE
来个夜间模式吧，很喜欢一直开着

### ISSUE THREAD

**Issue by mofond** [Jrohy/trojan#65]

**Comment by Jrohy** [comment]
美化等功能完善了再说，发现界面还有bug😂

**Comment by mofond** [comment]
发现新版2.5.2界面简洁了，是不是等着到时候一起都弄回来？ 
感谢大神的辛勤付出哦，我把两台vps都换完了

**Comment by mofond** [comment]
新版2.5.2用**http://**进入网页是正常的，用**https://**进去不正常，少了4个仪表盘，用户管理少了彩色功能按钮，编辑和删除。
