### ISSUE TITLE
上海电信，由于无法访问cdn.jsdelivr.net，导致管理页面无法打开

### ISSUE THREAD

**Issue by youjiajia-wc** [Jrohy/trojan#661]
![image](https://user-images.githubusercontent.com/63731955/169042175-a534b95f-3bc4-42ea-a728-cbee282d0f67.png)
![image](https://user-images.githubusercontent.com/63731955/169042331-351e9f21-6016-4e33-9d93-8868db0f36ee.png)
![image](https://user-images.githubusercontent.com/63731955/169042587-f2c1c2db-89ff-4e10-85e9-5bc2befddfc4.png)
如图，直连无法打开管理页面，白屏，至少4个服务器都一样。
全局后正常访问。
请作者帮忙确认下。截图为https。
虽然http也一样白屏，没有再研究。

**Comment by Jrohy** [comment]
这个前端cdn地址可能受墙影响了，我看看换成其他的cdn

**Comment by youjiajia-wc** [comment]
> 可能受墙的影响，国内不知还有什么顺畅的js cdn

![image](https://user-images.githubusercontent.com/63731955/169277338-a9f7abdd-4ede-4e08-a89c-aa80903f95e3.png)
考虑放到vps里来吗，类似这个js

**Comment by mhy851108** [comment]
js可否放到本地？

**Comment by Jrohy** [comment]
其实已找到国内比较稳定点的:
字节: http://cdn.bytedance.com/

**Comment by Jrohy** [comment]
新版已变更cdn地址
