### ISSUE TITLE
请问如何升级和查看trojan-go的版本

### ISSUE THREAD

**Issue by cineph** [Jrohy/trojan#666]
web里面看到trojan版本是1.16.0，切换到go后版本是v0.10.6，脚本说明中升级go版本到1.18.2，请问这些版本号有什么区别，如何升级和查看呢？问题比较小白，谢谢~~

**Comment by youjiajia-wc** [comment]
trojan、trojan-go、go是三个完全不同的东西。
trojan和trojan-go是我们使用的协议，其实现的脚本是go脚本。
至于go的版本不知道，trojan和trojan-go的版本，面板有。不出意外的话，trojan是1.16，trojan-go是0.10.6

**Comment by cineph** [comment]
> 

谢谢，知道是最新的就放心了哈哈

> trojan、trojan-go、go是三个完全不同的东西。 trojan和trojan-go是我们使用的协议，其实现的脚本是go脚本。 至于go的版本不知道，trojan和trojan-go的版本，面板有。不出意外的话，trojan是1.16，trojan-go是0.10.6

谢谢，知道是最新的就放心了
