### ISSUE TITLE
想问下怎样把web文字部分更改

### ISSUE THREAD

**Issue by hmx27-daisuki** [Jrohy/trojan#673]
就是想把2处“trojan 管理平台”文字改为别的文字，看起来没有那么明显，日后会集成到“4.web管理”修改吗？谢谢

**Comment by youjiajia-wc** [comment]
admin登录，可以修改
![image](https://user-images.githubusercontent.com/63731955/174083316-9d484389-4dad-4619-8cef-46b8261904b8.png)

**Comment by hmx27-daisuki** [comment]
好的，多谢，找到了，如果web管理也集成就更好了，嘻嘻
