### ISSUE TITLE
一键安装脚本下载失败有无备用链接？

### ISSUE THREAD

**Issue by awds888** [Jrohy/trojan#675]
source <(curl -sL https://git.io/trojan-install)
之前一直用这个，但是今天发现部分vps连不上，有无备用方案？希望作者能搞个备用链接。这个repo作者可一定要继续优化下去啊，说实话还是非常良心和精练的，自主diy已经熟悉并习惯了，不想换其他用。

**Comment by youjiajia-wc** [comment]
> 你可以下载下来install.sh放到其他不能连的vps上，看看能否安装，一般不能访问应该就纯ipv6的vps

反对。ipv6不能访问，只能是不会设置。在你q其它的issue已经答复过如何使用ipv6和你的脚本搭建trojan
![image](https://user-images.githubusercontent.com/63731955/176197264-77d98126-18a7-4895-9047-26e8ea77db61.png)

**Comment by awds888** [comment]
> 

好的，VPS不是纯IPV6的VPS，我找到原因了，这家VPS开局就无法访问github，我试过下载repo里面的install.sh，一样无法安装，因为安装脚本里面需要下载的软件都是github的，根源还是github无法访问。
这家VPS就是：RFCHost
劝大家别买，工单回复也很慢。

**Comment by youjiajia-wc** [comment]
> > 
> 
> 好的，VPS不是纯IPV6的VPS，我找到原因了，这家VPS开局就无法访问github，我试过下载repo里面的install.sh，一样无法安装，因为安装脚本里面需要下载的软件都是github的，根源还是github无法访问。 这家VPS就是：RFCHost 劝大家别买，工单回复也很慢。

更改一下dns试试看。
 vi /etc/resolv.conf
如果你的有127.0.0.1:53，建议停止服务，并手动指定dns服务器。
systemctl stop systemd-resolved
systemctl disable systemd-resolved
rm /etc/resolv.conf
echo "nameserver 8.8.8.8">/etc/resolv.conf
echo "nameserver 1.1.1.1">>/etc/resolv.conf

如果你的没有。则加入以下放在文件最前面
nameserver 8.8.8.8

**Comment by Jrohy** [comment]
@awds888 其实每次有更新肯定都更新go版本，只不过得有新的东西才好一起更😂
