### ISSUE TITLE
安装完成后无法打开 trojan-web

### ISSUE THREAD

**Issue by predators46** [Jrohy/trojan#676]
@Jrohy 

[GIN-debug] [ERROR] listen tcp 0.0.0.0:80: bind: address already in use

**Comment by Jrohy** [comment]
端口占用了80

**Comment by predators46** [comment]
> 端口占用了80

`tcp6       0      0 :::80                   :::*                    LISTEN      12433/trojan                                                                              udp6   34944      0 fe80::39:ffff:fe5c::546 :::*                                5139/systemd-networ                                                                       unix  3      [ ]         DGRAM                    30480    5139/systemd-networ                                                                                            unix  3      [ ]         STREAM     CONNECTED     16480    732/dbus-daemon`

**Comment by predators46** [comment]
@Jrohy 

我已经尝试安装，但无法打开 trojan-web。你可以尝试使用你的vps安装吗？

**Comment by predators46** [comment]
@Jrohy 

Fix thanks
