### ISSUE TITLE
密码正确但invalid hash

### ISSUE THREAD

**Issue by awds888** [Jrohy/trojan#679]
同一个账号，多台VPS，有的出现invalid hash 密码不正确，有的是对的。反复检查过好多次以前从来没出现过。
而且确实hash值跟正确的sha224哈希值确实不一样，客户端用的clashx，确实很奇怪，这是什么原因。是clash的问题？

**Comment by Jrohy** [comment]
没用过clashx,可以试试clash for windows行不行，支持导入clash订阅链接到clash for windows的

**Comment by awds888** [comment]
是我看错了
