### ISSUE TITLE
搭建完trojan，连不上google，试了很多个脚本了

### ISSUE THREAD

**Issue by pertance** [Jrohy/trojan#68]
搭建完成连接不上， 查看日志提示
无法解析远程主机
cannot resolve remote server hostname emaspoc-adash emas-ha.cn

**Comment by Jrohy** [comment]
换个平台的客户端或者网络环境试试

**Comment by Jrohy** [comment]
服务器ip 本地ping值如何

**Comment by pertance** [comment]
> ping 没问题  节点连接测试 也是通的

**Comment by Jrohy** [comment]
本地ping的域名能否解释到服务器ip呢，还有在服务器上ping域名

**Comment by pertance** [comment]
可以的 219.hsxc.ml 您可以看下

**Comment by Jrohy** [comment]
报无法解释远程主机的这个日志的一端, dns解释检查下

**Comment by pertance** [comment]
您好这个要怎么检查 我用的debian 9

**Comment by Jrohy** [comment]
如果在vps上ping 219.hsxc.ml 解释到vps ip应该就没问题

**Comment by pertance** [comment]
> 没问题 的刚才已经试过了

**Comment by pertance** [comment]
您稍等下我截图给您

**Comment by Jrohy** [comment]
如果其他部署脚本也这样那确实不清楚了😂

**Comment by pertance** [comment]
![Uploading 2020412093858dama.png…]()
![1586655658(1)](https://user-images.githubusercontent.com/35564076/79058539-f0d08e00-7ca1-11ea-990d-591131e911ec.jpg)
![1586655668(1)](https://user-images.githubusercontent.com/35564076/79058540-f29a5180-7ca1-11ea-85f6-de883a9e32c7.jpg)

**Comment by pertance** [comment]
![2020412093858dama](https://user-images.githubusercontent.com/35564076/79058549-12317a00-7ca2-11ea-95f9-32a418c63ac8.png)

**Comment by Jrohy** [comment]
要不要换个非ml的域名试试

**Comment by pertance** [comment]
好 我试试换个 域名

**Comment by pertance** [comment]
我创建完成好在在服务器上就ping不通 google

**Comment by Jrohy** [comment]
服务器的网络问题?

**Comment by pertance** [comment]
Destination unreachable: Address unreachable       地址不可达什么鬼

**Comment by Jrohy** [comment]
得提工单问下vps商怎么解决无法ping通google.com的问题

**Comment by pertance** [comment]
好吧，但是我用v2ray就没事  也是无语了 我重置下vps 直接ping一下试试

**Comment by pertance** [comment]
cannot establish connection to remote server yt3.ggpht.com:443: No route to host
无法建立到远程服务器yt3的连接。ggpht.com:443:没有到主机的路由 
重新整完 还是有问题，报了个这个

**Comment by pertance** [comment]
怪异 安装上trojan 就ping不同 google 了 这什么鬼

**Comment by Jrohy** [comment]
其他部署脚本也会这样吗 @pertance

**Comment by pertance** [comment]
不好意思 刚刚换了条电信的宽带，师傅刚来安装了， 其他部署我没注意，或许应该是这样，因为其他trojan也都连不上， 只有v2ray 可是使用，以前都是用的v2ray

**Comment by pertance** [comment]
搞了一天 找到问题了 vps的问题，vps刚重启的时候可以ping google，稍等一会儿就ping 不通了，没看过v2ray的源码，v2ray搭建好了可以使用，trojan就不行

**Comment by xiazhaoyang** [comment]
> 搞了一天 找到问题了 vps的问题，vps刚重启的时候可以ping google，稍等一会儿就ping 不通了，没看过v2ray的源码，v2ray搭建好了可以使用，trojan就不行

我遇到的问题和你类似，你后来解决了嘛？

**Comment by geraldhk** [comment]
我也是這個問題....

**Comment by Ghosign** [comment]
I met the same problem, and here was why:
The system image didn't configured with correct IPv6 network (mine is Debian 10 provided by RackNerd).
Have no interest on it now, so I just simply disable it. Maybe you can fix it by yourself or asking help from your service provider.
