### ISSUE TITLE
能不能增加trojan rust作为另一个服务端的选择？

### ISSUE THREAD

**Issue by fallenyang** [Jrohy/trojan#681]
因为看到trojan-go的作者也长时间没有更新了，另外看到trojan-rust的项目有进展
https://github.com/cty123/TrojanRust 也更新了不少版本，据说用rust作为服务端性能还会有不少的提升，所以问一下脚本能不能增加trojan-rust作为另一个服务端的选择？

**Comment by Jrohy** [comment]
没发现有写入数据库，看起来不太兼容原版的，建议还是单独部署
