### ISSUE TITLE
可否增加速度限制和用户ip限制

### ISSUE THREAD

**Issue by zichen2333386** [Jrohy/trojan#682]
可否增加速度限制和用户ip限制，我看trojan-go 是支持这个的

**Comment by Jrohy** [comment]
测试过不生效的

**Comment by fallenyang** [comment]
手动替换trojan-go可执行文件换成这个别人修复版本
https://github.com/fregie/trojan-go
再用原版的api限制upload-speed-limit和download-speed-limit，亲测是可以生效的。但是需要用命令行
https://p4gefau1t.github.io/trojan-go/advance/api/

**Comment by dyqnaruto** [comment]
> 

大佬，我替换https://github.com/fregie/trojan-go，再修改config.json后，重启trojan-go有报错，大佬可以给看看嘛
![config](https://user-images.githubusercontent.com/16442934/221539926-b24b9c67-b7e7-4839-9658-dda33d30c499.PNG)
![error](https://user-images.githubusercontent.com/16442934/221539949-fa54faa1-814d-4915-a547-4211d115d7d0.PNG)

**Comment by fallenyang** [comment]
10000端口号后面不需要逗号
@dyqnaruto 

我是把一个二进制执行文件放在用户目录，简单写个sh
#!/bin/sh
./trojan-go -api-addr 127.0.0.1:1000 -api set -modify-profile -target-password XXXX_1234     -upload-speed-limit 3000000     -download-speed-limit 3000000

**Comment by dyqnaruto** [comment]
> 10000端口号后面不需要逗号 @dyqnaruto
> 
> 我是把一个二进制执行文件放在用户目录，简单写个sh #!/bin/sh ./trojan-go -api-addr 127.0.0.1:1000 -api set -modify-profile -target-password XXXX_1234 -upload-speed-limit 3000000 -download-speed-limit 3000000

收到，谢谢！
