### ISSUE TITLE
容器的运行命令没有带端口映射，请问端口映射是在哪里做的，或者容器是直接在监听宿主机的端口？

### ISSUE THREAD

**Issue by txbx** [Jrohy/trojan#683]
机器的80和443有其他用处，我用docker容器方式的运行，有方法可以在启动容器的时候自定义web的端口还有trojan的端口吗？

**Comment by Jrohy** [comment]
--net=host ，你也可以换成-p xxx:443之类的

**Comment by Jrohy** [comment]
但申请证书可能用到80端口，可以先停了原来的80端口的服务，来申请下证书

**Comment by txbx** [comment]
> 但申请证书可能用到80端口，可以先停了原来的80端口的服务，来申请下证书

明白了。感谢回复
