### ISSUE TITLE
web页面无法打开

### ISSUE THREAD

**Issue by zhaokelei** [Jrohy/trojan#69]
安装成功之后trojan和web页面都可以打开，过了一夜无法进入web管理页面，但是trojan可以连接使用，证书检查了没有问题。

**Comment by Jrohy** [comment]
systemctl status trojan-web看下web页面有没有在运行

**Comment by zhaokelei** [comment]
查了下是在运行中 但是web页面无法访问

**Comment by zhaokelei** [comment]
我执行了 systemctl restart trojan-web 重启了这个服务，然后就可以访问WEB页面了，是程序假死了吗

**Comment by Jrohy** [comment]
应该是定时任务写得有问题，申请证书的时候必须先停了trojan-web(占了80端口)才能申请，可能是停了后后面执行启动

**Comment by Jrohy** [comment]
crontab -l可以看定时任务，估计是申请证书那里有问题导致后面启动没执行

**Comment by Jrohy** [comment]
已修复，更新下`source <(curl -sL https://git.io/trojan-install)`, 会自动优化cron任务

**Comment by zhaokelei** [comment]
好的，我更新试一下
