### ISSUE TITLE
建议增加使用配置文件 而非mysql文档

### ISSUE THREAD

**Issue by wanghaisheng** [Jrohy/trojan#70]
建议使用ssdb而非mysql来减少内存损耗

**Comment by Jrohy** [comment]
这个得向官方提意见，官方改了会一并修改的，mysql确实耗点内存，没有512m的vps难以跑整套

**Comment by liuxyon** [comment]
太费内存了..  mysql启动不起来. 进程里却看到Mysql在运行. ubuntu19.10 

 Status: Downloaded newer image for mysql/mysql-server:5.7
b747b67ea5d24d94293c1944b9e65e3fba6b0d0fdf6e2cdc9717f1239dccd215
time="2020-04-12T21:42:36+08:00" level=error msg="error waiting for container: context canceled"
2020-04-12 21:42:37 mysql启动中,请稍等...
2020-04-12 21:43:01 mysql启动中,请稍等...

**Comment by Jrohy** [comment]
docker logs -f trojan-mysql 得看mysql日志的 @liuxyon

**Comment by Jrohy** [comment]
vps 有没有512m+内存呢 @liuxyon , 单独mysql启动内存将近200m的

**Comment by liuxyon** [comment]
trojan info
driver: bad connection
连接mysql失败!
root@changeme:~# docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Initializing database
[Entrypoint] Database initialized
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.

[Entrypoint] ignoring /docker-entrypoint-initdb.d/*

[Entrypoint] Server shut down

[Entrypoint] MySQL init process done. Ready for start up.

[Entrypoint] Starting MySQL 5.7.29-1.1.15
