### ISSUE TITLE
mysql的作用是啥

### ISSUE THREAD

**Issue by shadowsyuan** [Jrohy/trojan#71]
我想问下mysql作用在哪，所有密码都存在leveldb上了，那为啥还要mysql.,.  我现在是多节点用的ssr，想升级为trojan，可是想同步用户资料的时候发现mysql貌似和服务器本身运行的数据关系不大，只是在数据库上记录了用户名称加密后的密码还有流量情况..

**Comment by Jrohy** [comment]
trojan要用到mysql

**Comment by shadowsyuan** [comment]
那mysql的数据会同步到leveldb上么？

**Comment by Jrohy** [comment]
不会的，leveldb存的明文密码是为了能在web界面展示

**Comment by shadowsyuan** [comment]
那除了密码字段，我修改了流量限制会同步过去么，还是说这个纯粹是单向同步的……

**Comment by Jrohy** [comment]
leveldb只是记录下原始密码，包括admin的，其他都是读mysql里面的数据

**Comment by shadowsyuan** [comment]
等等等……   那是不是说，如果我不用你的web界面端控制的话……   是不是也可以直接通过修改数据库来完成……  比如直接修改密码字段或者流量限制   只要密码字段是sha224加密就行了  trojan也能识别出来

**Comment by shadowsyuan** [comment]
换句话说，就是我自己开发了一个web端，只要能修改数据库并按原先的格式写入数据，也是可以控制服务器端的咯？

**Comment by shadowsyuan** [comment]
那是不是只要不考虑你的web控制台……  就可以通过一个数据库来控制多个节点？

**Comment by Jrohy** [comment]
控制多个用户而已
