### ISSUE TITLE
go的版本没有升级成功啊

### ISSUE THREAD

**Issue by token361** [Jrohy/trojan#724]
安装的docker版本 把脚本更新完之后选择3 更新版本 go的版本还是0.10.6 问一下日志不是说已经更新到1.19了吗  这个怎么升级

**Comment by Jrohy** [comment]
`trojan updateWeb`试试

**Comment by token361** [comment]
> `trojan updateWeb`试试
root@VPS82015663:~# docker exec -it trojan bash
[root@VPS82015663 /]# trojan updateWeb
正在更新trojan管理程序..
正在下载管理程序v2.14.3版本...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 12.5M  100 12.5M    0     0  9983k      0  0:00:01  0:00:01 --:--:-- 16.0M
更新trojan管理程序成功!

[root@VPS82015663 /]# trojan

欢迎使用trojan管理程序

1.trojan管理       	2.用户管理           

3.安装管理           	4.web管理          

5.查看配置           	6.生成json         

请选择: 3

1.更新trojan

2.证书申请

3.安装mysql

请选择: 1

Creating trojan install directory
Entering temp directory /tmp/tmp.imwIQhsNJy...
Downloading trojan 0.10.6...
######################################################################## 100.0%
Unpacking trojan 0.10.6...
Archive:  trojan-go-linux-amd64.zip
  inflating: trojan-go               
  inflating: example/client.json     
  inflating: example/client.yaml     
  inflating: example/server.json     
  inflating: example/server.yaml     
  inflating: example/trojan-go.service  
  inflating: example/trojan-go@.service  
  inflating: geoip-only-cn-private.dat  
  inflating: geoip.dat               
  inflating: geosite.dat             
Installing trojan 0.10.6 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Skipping installing trojan server config...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.imwIQhsNJy...
Done!
Connection closing...Socket close.

Connection closed by foreign host.
 还是不行

**Comment by WHJmaxne** [comment]
> > `trojan updateWeb`试试
> > root@VPS82015663:~# docker exec -it trojan bash
> > [root@VPS82015663 /]# trojan updateWeb
> > 正在更新trojan管理程序..
> > 正在下载管理程序v2.14.3版本...
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> > 100 12.5M  100 12.5M    0     0  9983k      0  0:00:01  0:00:01 --:--:-- 16.0M
> > 更新trojan管理程序成功!
> 
> [root@VPS82015663 /]# trojan
> 
> 欢迎使用trojan管理程序
> 
> 1.trojan管理 2.用户管理
> 
> 3.安装管理 4.web管理
> 
> 5.查看配置 6.生成json
> 
> 请选择: 3
> 
> 1.更新trojan
> 
> 2.证书申请
> 
> 3.安装mysql
> 
> 请选择: 1
> 
> Creating trojan install directory Entering temp directory /tmp/tmp.imwIQhsNJy... Downloading trojan 0.10.6... ######################################################################## 100.0% Unpacking trojan 0.10.6... Archive: trojan-go-linux-amd64.zip inflating: trojan-go inflating: example/client.json inflating: example/client.yaml inflating: example/server.json inflating: example/server.yaml inflating: example/trojan-go.service inflating: example/[trojan-go@.service](mailto:trojan-go@.service) inflating: geoip-only-cn-private.dat inflating: geoip.dat inflating: geosite.dat Installing trojan 0.10.6 to /usr/bin/trojan/trojan... Installing trojan server config to /usr/local/etc/trojan/config.json... Skipping installing trojan server config... Installing trojan systemd service to /etc/systemd/system/trojan.service... Reloading systemd daemon... Deleting temp directory /tmp/tmp.imwIQhsNJy... Done! Connection closing...Socket close.
> 
> Connection closed by foreign host. 还是不行

1.19.3是go语言版本，trojan-go最新版本是0.10.6，可以参考trojan-go仓库
