### ISSUE TITLE
新版本trojan无法启动

### ISSUE THREAD

**Issue by zichen2333386** [Jrohy/trojan#726]
trojan.service holdoff time over, scheduling restart.
Stopped trojan.
Started trojan.
Welcome to trojan 1.16.0
[2022-11-14 21:54:18] [FATAL] fatal: use_certificate_chain_file: No such file or directory
[2022-11-14 21:54:18] [FATAL] exiting. . .
trojan.service: main process exited, code=exited, status=1/FAILURE
Unit trojan.service entered failed state.
trojan.service failed.

**Comment by jjyou-github** [comment]
申请证书失败了，检查你的防火墙或者80端口
