### ISSUE TITLE
登录显示三个授权失败，但密码正确，登录不上

### ISSUE THREAD

**Issue by 807562379** [Jrohy/trojan#73]
我在用docker安装了speed test测速后出现的，不知道是不是什么端口6688：80什么的问题。关键我还不会卸载这个speedtest

**Comment by Jrohy** [comment]
密码是不是错了，才授权失败的

**Comment by Jrohy** [comment]
可以在终端web管理重置admin密码

**Comment by Jrohy** [comment]
docker rm -f容器名来卸载
