### ISSUE TITLE
远端mysql连接

### ISSUE THREAD

**Issue by liuxyon** [Jrohy/trojan#74]
连接远端mysql失败, 在远端看不到有网络连接进来.  并且也不支持ipv6 ip连接.

2.输入自定义mysql连接

请选择: 2
请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址: 185.208.191.12:3306
请输入mysql的用户名(回车使用root):
请输入mysql root用户的密码: m1256862548
连接mysql失败, 请重新输入

**Comment by liuxyon** [comment]
对端Mysql v8.0.19版本

**Comment by Jrohy** [comment]
我用docker版mysql8.0 版本没问题，直接这样起:
docker run --name trojan-mysql --restart=always -p 3306:3306 -v /home/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mysql/mysql-server

**Comment by Jrohy** [comment]
mysql版本就是v8.0.19

**Comment by liuxyon** [comment]
你这是连接远程的mysql服务器么? 因为我本机内存可能不够,所以我连接外部的远程的mysql. 可是看不见连接.

**Comment by Jrohy** [comment]
你可以用mariadb数据库耗内存比mysql少一半，70m左右

**Comment by om0504** [comment]
請問有沒有計劃出一個前後端的功能和腳本呢?
前端可以放面板和資料庫
後端是實際Trojan服務端，去跟前端對接
謝謝。
