### ISSUE TITLE
申请了阿里云的免费SSL证书，但是有好几种，哪个才适合放到trojan呢？

### ISSUE THREAD

**Issue by rossroma** [Jrohy/trojan#741]
![image](https://user-images.githubusercontent.com/6183683/217526421-cc17f1dc-57f9-4d6d-be44-d811a53ebe35.png)

我试了nginx的证书，发现无法正确启动

**Comment by ancct** [comment]
同求，腾讯云的免费证书也无法启动

**Comment by deartonyz** [comment]
我选的Nginx的就可以

**Comment by earth-5G** [comment]
n那你为啥非要用这些国内的东西呢？既然要翻墙就不要用国内的任何东西！
