### ISSUE TITLE
前段界面显示的管理功能缺失

### ISSUE THREAD

**Issue by Corezcy** [Jrohy/trojan#748]
请问一下管理功能是需要开启什么端口吗？
界面只显示这么多功能
也无法在前端添加用户
求教！！！
![image](https://user-images.githubusercontent.com/33271784/221360108-2cccb3b5-fce5-4c71-95ec-9dbb4d480502.png)

**Comment by Corezcy** [comment]
我换了一个服务器，安装还是这个样子……

**Comment by Jrohy** [comment]
用管理员账号登陆

**Comment by Corezcy** [comment]
是我傻了，sorry sorry
