### ISSUE TITLE
debian 9 x64解压trojan出错

### ISSUE THREAD

**Issue by chouxiang99** [Jrohy/trojan#75]
Creating trojan install directory
Entering temp directory /tmp/tmp.Q55R1CTDTo...
Downloading trojan 1.15.1...
######################################################################## 100.0%
Unpacking trojan 1.15.1...
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed to restart trojan.service: Unit trojan.service not found.
Failed to enable unit: File trojan.service: No such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x89bb13]

goroutine 1 [running]:
trojan/core.WritePassword(0x0, 0x0, 0x0, 0x1)
	/home/go/trojan/core/server.go:96 +0x33
trojan/cmd.check()
	/home/go/trojan/cmd/root.go:33 +0xbd
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:40 +0x34
trojan/cmd.glob..func6(0x128aa20, 0x12c11b0, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x128aa20, 0xc0000201d0, 0x0, 0x0, 0x128aa20, 0xc0000201d0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x128aa20, 0x443a4a, 0x1249a40, 0xc000000180)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20

**Comment by Jrohy** [comment]
apt-get install xz-utils -y

**Comment by Jrohy** [comment]
再安装trojan, 后面我完善下安装脚本添加这个依赖

**Comment by chouxiang99** [comment]
谢谢大佬解答，已经可以了

**Comment by Jrohy** [comment]
安装脚本已添加xz依赖
