### ISSUE TITLE
我搭建成功了访问 http://我的域名，访问不了

### ISSUE THREAD

**Issue by chouxiang99** [Jrohy/trojan#76]
d查看日志，Apr 13 00:08:07 debian systemd[1]: trojan.service: Unit entered failed state.
Apr 13 00:08:07 debian systemd[1]: trojan.service: Failed with result 'exit-code'.
Apr 13 00:08:10 debian systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
Apr 13 00:08:10 debian systemd[1]: Stopped trojan.
Apr 13 00:08:10 debian trojan[8922]: Welcome to trojan 1.15.1
Apr 13 00:08:10 debian systemd[1]: Started trojan.
Apr 13 00:08:10 debian trojan[8922]: [2020-04-13 00:08:10] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Apr 13 00:08:10 debian trojan[8922]: [2020-04-13 00:08:10] [FATAL] exiting. . .
Apr 13 00:08:10 debian systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 00:08:10 debian systemd[1]: trojan.service: Unit entered failed state.
Apr 13 00:08:10 debian systemd[1]: trojan.service: Failed with result 'exit-code'.
Apr 13 00:08:13 debian systemd[1]: trojan.service: Service hold-off time over, scheduling restart.
Apr 13 00:08:13 debian systemd[1]: Stopped trojan.
Apr 13 00:08:13 debian systemd[1]: Started trojan.
Apr 13 00:08:13 debian trojan[8949]: Welcome to trojan 1.15.1
Apr 13 00:08:13 debian trojan[8949]: [2020-04-13 00:08:13] [FATAL] fatal: use_certificate_chain_file: No such file or directory
Apr 13 00:08:13 debian trojan[8949]: [2020-04-13 00:08:13] [FATAL] exiting. . .
Apr 13 00:08:13 debian systemd[1]: trojan.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 00:08:13 debian systemd[1]: trojan.service: Unit entered failed state.
Apr 13 00:08:13 debian systemd[1]: trojan.service: Failed with result 'exit-code'.
不知道是什么原因

**Comment by Jrohy** [comment]
没申请到证书，去安装管理那里证书申请

**Comment by chouxiang99** [comment]
免费的域名申请好像不行，我是用阿里的域名证书申请，然后路径写“/root/key/3753510_888.wwjzx.top_public.crt”，这样子可以嘛，还是路径有什么要求

**Comment by Jrohy** [comment]
只要文件存在就行，证书能不能用trojan核心说了算

**Comment by chouxiang99** [comment]
好的  我来研究研究  谢谢

**Comment by chouxiang99** [comment]
new-nonce'
[Mon Apr 13 01:21:08 EDT 2020] ACME_VERSION='2'
[Mon Apr 13 01:21:08 EDT 2020] Le_NextRenewTime
[Mon Apr 13 01:21:09 EDT 2020] _on_before_issue
[Mon Apr 13 01:21:09 EDT 2020] _chk_main_domain='222.wwjzx.top'
[Mon Apr 13 01:21:09 EDT 2020] _chk_alt_domains
[Mon Apr 13 01:21:09 EDT 2020] Le_LocalAddress
[Mon Apr 13 01:21:09 EDT 2020] d='222.wwjzx.top'
[Mon Apr 13 01:21:09 EDT 2020] Check for domain='222.wwjzx.top'
[Mon Apr 13 01:21:09 EDT 2020] _currentRoot='no'
[Mon Apr 13 01:21:09 EDT 2020] Standalone mode.
[Mon Apr 13 01:21:09 EDT 2020] _checkport='80'
[Mon Apr 13 01:21:09 EDT 2020] _checkaddr
[Mon Apr 13 01:21:09 EDT 2020] Using: ss
[Mon Apr 13 01:21:09 EDT 2020] LISTEN     0      128         :::80                      :::*                   users:(("trojan",pid=8379,fd=3))
[Mon Apr 13 01:21:09 EDT 2020] tcp port 80 is already used by 80                      
[Mon Apr 13 01:21:09 EDT 2020] Please stop it first



就是我已经停止了trojan，但是我申请自定义证书，还是提示我端口被占用，这种情况应该怎么处理

**Comment by Jrohy** [comment]
systemctl stop trojan-web

**Comment by chouxiang99** [comment]
[Mon Apr 13 01:32:19 EDT 2020] payload
[Mon Apr 13 01:32:19 EDT 2020] POST
[Mon Apr 13 01:32:19 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929201466/hIgbRw'
[Mon Apr 13 01:32:19 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:32:20 EDT 2020] _ret='0'
[Mon Apr 13 01:32:20 EDT 2020] code='200'
[Mon Apr 13 01:32:20 EDT 2020] Pending
[Mon Apr 13 01:32:20 EDT 2020] sleep 2 secs to verify
[Mon Apr 13 01:32:22 EDT 2020] checking
[Mon Apr 13 01:32:22 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929201466/hIgbRw'
[Mon Apr 13 01:32:22 EDT 2020] payload
[Mon Apr 13 01:32:22 EDT 2020] POST
[Mon Apr 13 01:32:22 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929201466/hIgbRw'
[Mon Apr 13 01:32:22 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:32:23 EDT 2020] _ret='0'
[Mon Apr 13 01:32:23 EDT 2020] code='200'
[Mon Apr 13 01:32:23 EDT 2020] 222.wwjzx.top:Verify error:Fetching http://222.wwjzx.top/.well-known/acme-challenge/W_pA6Mky2zPcSKQ9_6lAeOmjqm85f8D-CMJzRyN07iQ: Timeout during connect (likely firewall problem)
[Mon Apr 13 01:32:23 EDT 2020] Debug: get token url.
[Mon Apr 13 01:32:23 EDT 2020] GET
[Mon Apr 13 01:32:23 EDT 2020] url='http://222.wwjzx.top/.well-known/acme-challenge/W_pA6Mky2zPcSKQ9_6lAeOmjqm85f8D-CMJzRyN07iQ'
[Mon Apr 13 01:32:23 EDT 2020] timeout=1
[Mon Apr 13 01:32:23 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Mon Apr 13 01:32:24 EDT 2020] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 28
[Mon Apr 13 01:32:24 EDT 2020] ret='28'
[Mon Apr 13 01:32:24 EDT 2020] Skip for removelevel:
[Mon Apr 13 01:32:24 EDT 2020] pid='18659'
[Mon Apr 13 01:32:24 EDT 2020] No need to restore nginx, skip.
[Mon Apr 13 01:32:24 EDT 2020] _clearupdns
[Mon Apr 13 01:32:24 EDT 2020] dns_entries
[Mon Apr 13 01:32:24 EDT 2020] skip dns.
[Mon Apr 13 01:32:24 EDT 2020] _on_issue_err
[Mon Apr 13 01:32:24 EDT 2020] Please add '--debug' or '--log' to check more details.
[Mon Apr 13 01:32:24 EDT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Apr 13 01:32:24 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929201466/hIgbRw'
[Mon Apr 13 01:32:24 EDT 2020] payload='{}'
[Mon Apr 13 01:32:24 EDT 2020] POST
[Mon Apr 13 01:32:24 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929201466/hIgbRw'
[Mon Apr 13 01:32:24 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:32:25 EDT 2020] _ret='0'
[Mon Apr 13 01:32:25 EDT 2020] code='400'


现在自定义申请证书   好像还是报错

**Comment by Jrohy** [comment]
会不会防火墙的原因，80端口没开放?

**Comment by chouxiang99** [comment]
阿里云国际版这个服务器  还真的没有80端口  我把80的端口打开了   现在好像变成dns有什么问题   
[Mon Apr 13 01:46:18 EDT 2020] payload
[Mon Apr 13 01:46:18 EDT 2020] POST
[Mon Apr 13 01:46:18 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:18 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:46:19 EDT 2020] _ret='0'
[Mon Apr 13 01:46:19 EDT 2020] code='200'
[Mon Apr 13 01:46:19 EDT 2020] Pending
[Mon Apr 13 01:46:19 EDT 2020] sleep 2 secs to verify
[Mon Apr 13 01:46:21 EDT 2020] checking
[Mon Apr 13 01:46:21 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:21 EDT 2020] payload
[Mon Apr 13 01:46:21 EDT 2020] POST
[Mon Apr 13 01:46:21 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:21 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:46:22 EDT 2020] _ret='0'
[Mon Apr 13 01:46:22 EDT 2020] code='200'
[Mon Apr 13 01:46:22 EDT 2020] Pending
[Mon Apr 13 01:46:22 EDT 2020] sleep 2 secs to verify
[Mon Apr 13 01:46:24 EDT 2020] checking
[Mon Apr 13 01:46:24 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:24 EDT 2020] payload
[Mon Apr 13 01:46:24 EDT 2020] POST
[Mon Apr 13 01:46:24 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:24 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:46:25 EDT 2020] _ret='0'
[Mon Apr 13 01:46:25 EDT 2020] code='200'
[Mon Apr 13 01:46:25 EDT 2020] 222.wwjzx.top:Verify error:During secondary validation: DNS problem: SERVFAIL looking up CAA for wwjzx.top - the domain's nameservers may be malfunctioning
[Mon Apr 13 01:46:25 EDT 2020] Debug: get token url.
[Mon Apr 13 01:46:25 EDT 2020] GET
[Mon Apr 13 01:46:25 EDT 2020] url='http://222.wwjzx.top/.well-known/acme-challenge/RxIHUl3YtMlkqvL05z-HmG4B31sERjingN_sxYrYPL4'
[Mon Apr 13 01:46:25 EDT 2020] timeout=1
[Mon Apr 13 01:46:25 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g  --connect-timeout 1'
[Mon Apr 13 01:46:26 EDT 2020] ret='0'
[Mon Apr 13 01:46:26 EDT 2020] Skip for removelevel:
[Mon Apr 13 01:46:26 EDT 2020] pid='21234'
[Mon Apr 13 01:46:26 EDT 2020] No need to restore nginx, skip.
[Mon Apr 13 01:46:26 EDT 2020] _clearupdns
[Mon Apr 13 01:46:26 EDT 2020] dns_entries
[Mon Apr 13 01:46:26 EDT 2020] skip dns.
[Mon Apr 13 01:46:26 EDT 2020] _on_issue_err
[Mon Apr 13 01:46:26 EDT 2020] Please add '--debug' or '--log' to check more details.
[Mon Apr 13 01:46:26 EDT 2020] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Apr 13 01:46:26 EDT 2020] url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:26 EDT 2020] payload='{}'
[Mon Apr 13 01:46:26 EDT 2020] POST
[Mon Apr 13 01:46:26 EDT 2020] _post_url='https://acme-v02.api.letsencrypt.org/acme/chall-v3/3929382906/Lze_hw'
[Mon Apr 13 01:46:26 EDT 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Apr 13 01:46:27 EDT 2020] _ret='0'
[Mon Apr 13 01:46:27 EDT 2020] code='400'
RxIHUl3YtMlkqvL05z-HmG4B31sERjingN_sxYrYPL4.lFugletmUuGrKiKL4Bdg6csjKpQ63xacmu68Trl7AXU
[Mon Apr 13 01:46:27 EDT 2020] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.0l  10 Sep 2019
apache:
apache doesn't exists.
nginx:
nginx doesn't exists.
socat:
socat by Gerhard Rieger - see www.dest-unreach.org
socat version 1.7.3.1 on Jul 14 2017 13:52:03
   running on Linux version #1 SMP Debian 4.9.210-1 (2020-01-20), release 4.9.0-12-amd64, machine x86_64
features:
  #define WITH_STDIO 1
  #define WITH_FDNUM 1
  #define WITH_FILE 1
  #define WITH_CREAT 1
  #define WITH_GOPEN 1
  #define WITH_TERMIOS 1
  #define WITH_PIPE 1
  #define WITH_UNIX 1
  #define WITH_ABSTRACT_UNIXSOCKET 1
  #define WITH_IP4 1
  #define WITH_IP6 1
  #define WITH_RAWIP 1
  #define WITH_GENERICSOCKET 1
  #define WITH_INTERFACE 1
  #define WITH_TCP 1
  #define WITH_UDP 1
  #define WITH_SCTP 1
  #define WITH_LISTEN 1
  #define WITH_SOCKS4 1
  #define WITH_SOCKS4A 1
  #define WITH_PROXY 1
  #define WITH_SYSTEM 1
  #define WITH_EXEC 1
  #undef WITH_READLINE
  #define WITH_TUN 1
  #define WITH_PTY 1
  #define WITH_OPENSSL 1
  #undef WITH_FIPS
  #define WITH_LIBWRAP 1
  #define WITH_SYCLS 1
  #define WITH_FILAN 1
  #define WITH_RETRY 1
  #define WITH_MSGLEVEL 0 /*debug*/

**Comment by Jrohy** [comment]
阿里云服务器装代理不是很容易收到警告吗😂

**Comment by chouxiang99** [comment]
我把系统刷成dd的了    然后用了一段时间v2ray    到现在也没有收到警告。。。。这个证书的问题对小白还是有点头疼    我中午的时候还尝试了自定义证书路径，然后我从阿里云下载下来的证书是crt的   但我看要求的证书是cert的格式  不知道这两个格式是不是一样的   然后我就把crt的放到服务器上去   弄完之后，无法访问   不知道是不是这个证书格式不对

**Comment by chouxiang99** [comment]
我发现好像只是网页无法访问。。。。我直接用xshell新建用户    也能用，实在不行就先这样凑合用吧   也不是不能用    哈哈哈哈

**Comment by chouxiang99** [comment]
谢谢指导
