### ISSUE TITLE
使用clashX时订阅错误

### ISSUE THREAD

**Issue by zzsuki** [Jrohy/trojan#760]
# 使用clashX时订阅错误

## 错误信息

<img width="452" alt="截屏2023-04-03 11 09 24" src="https://user-images.githubusercontent.com/57662555/229402949-30d7603e-6669-448a-9edd-3232a307afd1.png">

如图，似乎和这个cdn的握手有关

## 具体内容

```bash
initial rule provider direct error: Get "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt": net/ http: TLS handshake timeout
```

**Comment by rainonline** [comment]
多试几次就行，连不上这个CDN
