### ISSUE TITLE
The QR code generated by the panel does not support pharos pro

### ISSUE THREAD

**Issue by GimmGoo** [Jrohy/trojan#78]
Hey bro! The QR code generated by the panel does not support pharos pro
This is the trojan log from server:
![image](https://user-images.githubusercontent.com/31849284/79178689-6bcbad00-7e38-11ea-927e-e0f2fcf4a249.png)

Pharos pro release page: https://github.com/PharosVip/Pharos-Android-Test/releases

**Comment by Jrohy** [comment]
only suport this format: https://github.com/trojan-gfw/trojan-url

**Comment by GimmGoo** [comment]
I see, but if I change it like this:  
trojan://password@domain:443?allowinsecure=0&tfo=1#remark
almost any software were supported----- tojan-qt5, pharos, igniter, v2rayN etc

**Comment by GimmGoo** [comment]
Maybe you can try to modify the sharing link like that

**Comment by Jrohy** [comment]
pharos should be support trojan://password@domain:443 link
