### ISSUE TITLE
小白问： 可以用docker部署在m2 的mac 上么

### ISSUE THREAD

**Issue by LumingWyy** [Jrohy/trojan#788]
想在本地部署试试 但没成功 一直启动trojan失败!
请问在哪可以查到错误信息呢 log里什么都没有
有公网ip 且已经做好端口转发 部署好ddns

**Comment by earth-5G** [comment]
部署了 你怎么翻墙呢？难不成你的电脑能上外网！！？

**Comment by LumingWyy** [comment]
> 部署了 你怎么翻墙呢？难不成你的电脑能上外网！！？

mac mini 在墙外

**Comment by earth-5G** [comment]
> > 部署了 你怎么翻墙呢？难不成你的电脑能上外网！！？
> 
> mac mini 在墙外

哪又何必如此折腾？买个vps来装不就得了！一个月能花几个钱？
