### ISSUE TITLE
“mysql启动中，请稍后...”无限循环

### ISSUE THREAD

**Issue by freenaser** [Jrohy/trojan#79]
您好，全新安装后一直卡在这个提示环节。之前安装的没有这个问题，应该是从使用更新后的代码安装开始就这样了。请问何解？

**Comment by Jrohy** [comment]
mysql启动可能有问题，看下mysql日志， docker logs -f trojan-mysql

**Comment by Jrohy** [comment]
最新版数据库换成了mariadb, 比mysql省一半以上的内存，可以试试

**Comment by freenaser** [comment]
> 
> 
> 最新版数据库换成了mariadb, 比mysql省一半以上的内存，可以试试

已测，感谢。现阶段还有些明显的问题，WEB端报错"服务端问题"频繁；标题修改成功但无法实际生效。

**Comment by Jrohy** [comment]
报服务端连接失败之类是接口请求超时，看下本机ping vps IP的情况
