### ISSUE TITLE
部署在Oracle云服务，代理不了GPT

### ISSUE THREAD

**Issue by wobushijuzi** [Jrohy/trojan#807]
在oracle云服务上搭建了一个trojan代理，其他网站都没问题，访问GPT就不行。防火墙也关了，安全规则也设置了全通过。

![1690867799459](https://github.com/Jrohy/trojan/assets/24470313/1b1320e0-171b-40e4-b497-f29cefcb0c7c)

**Comment by royalyu** [comment]
这个大概率是IP被OpenAI屏蔽了

**Comment by wobushijuzi** [comment]
> 这个大概率是IP被OpenAI屏蔽了
换了几个IP都不行

**Comment by qingkediguo** [comment]
同问题。感觉不一定是 ip 问题吧？请问解决了么？
