### ISSUE TITLE
建议保留mysql，让用户选择用哪种数据库

### ISSUE THREAD

**Issue by CnSuperYoung** [Jrohy/trojan#82]
建议mysql和mariadb保留，安装的时候用户选择

**Comment by Jrohy** [comment]
我也想过，如果两个列出来，然后标明mariadb耗内存小点，感觉都会去选mariadb.

**Comment by Jrohy** [comment]
docker版mariadb测试耗70m 左右， mysql5.7 耗150m左右, 少至少一半， 用mariadb可以减少很多因内存不足起不了数据库的问题

**Comment by CnSuperYoung** [comment]
因为我使用的是阿里云的mysql-RDS，应该也有其他人也是使用的RDS，阿里的Maria目前还有点贵，同时有多台服务器，所以还是希望能保留mysql

**Comment by Jrohy** [comment]
这个自定义mysql连接就好了，用阿里云的， 自定义mysql的连接支持mysql5,8和mariadb的

**Comment by CnSuperYoung** [comment]
ok，管理面板也是正常可以支持mysql查询数据就行，

**Comment by EKDJ** [comment]
![image](https://user-images.githubusercontent.com/63694650/79296839-2201c600-7f0f-11ea-9bc2-5b042d9a7d82.png)
这个是mysql在修改容器内/etc/my.cnf后的内存占用  从150降到了50   觉得也可以作为一种解决方案
[mysqld] 
performance_schema_max_table_instances=400  
table_definition_cache=400  
table_open_cache=256
performance_schema = off

**Comment by Jrohy** [comment]
@EKDJ 这个得动手能力强的人自己来优化了
