### ISSUE TITLE
这个还稳定么，有用过的说下么

### ISSUE THREAD

**Issue by bbhxwl** [Jrohy/trojan#829]
v2有的不太稳定了，容易封端口，还没用过这个，不知道效果怎么样。

**Comment by alinkwok** [comment]
封端口简单啊，直接更换就好，而且换起来很简单

**Comment by bbhxwl** [comment]
> 封端口简单啊，直接更换就好，而且换起来很简单

trojan封么？目前看v2普通ws协议是不稳

**Comment by raybeneth** [comment]
还好，用了一年多，就被封了一次端口。命令直接更换就好了很方便

**Comment by raybeneth** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。
