### ISSUE TITLE
不停地mariadb启动中,请稍等...

### ISSUE THREAD

**Issue by dagai233** [Jrohy/trojan#83]
docker run --name trojan-mariadb --restart=always -p 31129:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=SZYiA -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
/usr/bin/docker-current: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker-current run --help'.
2020-04-15 11:22:34 mariadb启动中,请稍等...
2020-04-15 11:22:36 mariadb启动中,请稍等...
2020-04-15 11:22:38 mariadb启动中,请稍等...
2020-04-15 11:22:40 mariadb启动中,请稍等...

怎么解决啊

**Comment by Jrohy** [comment]
应该是docker安装失败，没有在运行

**Comment by Jrohy** [comment]
source <(curl -sL https://git.io/docker-install)
可以试下这个脚本来安装docker, 跑完后要docker info命令能运行才行

**Comment by dagai233** [comment]
root@MyCloudServer ~]# docker info
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
[root@MyCloudServer ~]#
好像还是失败…

**Comment by Jrohy** [comment]
装不了Docker的话就自己手动安装mysql，然后自定义数据库链接就好

**Comment by liuxyon** [comment]
我也遇到同样问题. 看起来Docker运行着,进程中能看到mysqld 和docker

**Comment by yuanzhidao** [comment]
请选择: 1
docker run --name trojan-mariadb --restart=always -p 60100:3306 -v /home/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=sAZoI -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan -d mariadb:10.2
docker: Error response from daemon: Conflict. The container name "/trojan-mariadb" is already in use by container "c69827f8cbc04a7ea6193e51e185371e7759edce44a545577d9b5038380db5ee". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
2020-04-23 11:34:37 mariadb启动中,请稍等...
2020-04-23 11:34:39 mariadb启动中,请稍等...
2020-04-23 11:34:41 mariadb启动中,请稍等...
2020-04-23 11:34:43 mariadb启动中,请稍等...
2020-04-23 11:34:45 mariadb启动中,请稍等...
2020-04-23 11:34:47 mariadb启动中,请稍等...
2020-04-23 11:34:49 mariadb启动中,请稍等...
2020-04-23 11:34:51 mariadb启动中,请稍等...

我这里也不可以，进程里有mysqld
![image](https://user-images.githubusercontent.com/37867590/80057730-eba0f800-8559-11ea-8811-1ee4e45b28f3.png)

**Comment by Jrohy** [comment]
容器名相同，先删了之前起的
docker rm -f trojan-mariadb 
rm -rf /home/mariadb

**Comment by zhongqiujie13** [comment]
我也遇到这个问题了docker和mysql都是运行正常的！centos7系统重置好几次还是这个问题！

**Comment by Jrohy** [comment]
@mysql启动失败就会这样，检查下其状态
