### ISSUE TITLE
更换域名，更换证书失败

### ISSUE THREAD

**Issue by tinymoon2017** [Jrohy/trojan#85]
停止trojan后trojan tls，最后报错如下：
[Wed Apr 15 06:32:37 UTC 2020] tcp port 80 is already used by (("trojan",pid=6808,fd=3))                                               
[Wed Apr 15 06:32:37 UTC 2020] Please stop it first
是不是trojan的web无法停止，kill进程后会自动起。
请问如何更换域名，生成新的证书？

**Comment by Jrohy** [comment]
systemctl stop trojan-web 这样停，换证书在证书安装那里换

**Comment by tinymoon2017** [comment]
可以了，成功！
多谢！

**Comment by daxiaamo** [comment]
请问证书文件在哪个目录呢？

**Comment by Jrohy** [comment]
@daxiaamo 如果是用脚本自带的acme.sh来签，默认都在/root/.acme.sh下面的

**Comment by daxiaamo** [comment]
找到了，谢谢！
