### ISSUE TITLE
用户管理能不能换成分页加载，用户量一多就卡死

### ISSUE THREAD

**Issue by sakz** [Jrohy/trojan#86]

**Comment by Jrohy** [comment]
建了多少用户呢导致页面卡死

**Comment by sakz** [comment]
mysql整了16000多条，用户管理页面提示，连接服务器失败。换为几条就正常。

**Comment by Jrohy** [comment]
极限测试确实需要分页，不只查mysql还查leveldb

**Comment by Jrohy** [comment]
2.7做了优化，查询用户不会去查leveldb了，直接取mysql的密码
