### ISSUE TITLE
在clash上面用不了

### ISSUE THREAD

**Issue by notiis** [Jrohy/trojan#87]

**Comment by Jrohy** [comment]
其他平台能否使用呢，相同节点

**Comment by notiis** [comment]
> 其他平台能否使用呢，相同摘要

Trojan-Qt5没问题

**Comment by Jrohy** [comment]
会不会网络问题呢手机端的

**Comment by notiis** [comment]
> 会不会网络问题呢手机端的

我用的电脑端

**Comment by notiis** [comment]
![image](https://user-images.githubusercontent.com/39907609/79320377-5344bb00-7f3c-11ea-8160-2c528eb35917.png)

**Comment by Jrohy** [comment]
我用windows版的clash使用没问题，会不会配置得有问题
