### ISSUE TITLE
部署疑问

### ISSUE THREAD

**Issue by FenghenHome** [Jrohy/trojan#9]
有没有不部署mysql，且能统计流量的方式

**Comment by Jrohy** [comment]
没有的，统计流量必须依赖于mysql,或者你可以自己安装mysql都行

**Comment by shengshengman0** [comment]
> 有没有不部署mysql，且能统计流量的方式

你可以去看trojan的文档

**Comment by FenghenHome** [comment]
我之前部署过，如果多个节点，那么就存在远程数据库校验问题，远程数据库校验是很耗时的
有没有打算重写trojan，支持api统计流量和用户管理

**Comment by Jrohy** [comment]
@FenghenHome 这个向官方仓库反馈

**Comment by FenghenHome** [comment]
我试试
