### ISSUE TITLE
安装好面板没有上面四个圈

### ISSUE THREAD

**Issue by oyyj1965** [Jrohy/trojan#91]
安装好可以使用，就是面板上部的四个圈和添加用户等没有，哪里可以开启呢？

**Comment by Jrohy** [comment]
默认都有的，只有接口请求拿不到数据才会没有显示，是不是请求超时了

**Comment by oyyj1965** [comment]
没超时吧，纯净的系统，安装了两次都这样，其他上网啥都挺好。

**Comment by Jrohy** [comment]
你在浏览器f12看下请求，有没有接口异常的

**Comment by Jrohy** [comment]
有没有可能浏览器兼容性问题

**Comment by oyyj1965** [comment]
用户管理里只出来一个刷新，F12看不懂，外行的角度看有2个进程在某个时间轴中间，像是触发不到。

**Comment by Jrohy** [comment]
刷不出用户感觉是不是连不了后台

**Comment by mofond** [comment]
admin登陆都有，第一个用户名登陆就没有。

**Comment by Jrohy** [comment]
@mofond 普通用户没权限查看服务器资源信息的，只有admin有

**Comment by mofond** [comment]
是的，我之前也发现没有四个圈，后面检查是没有用admin登陆的原因

**Comment by oyyj1965** [comment]
谢谢楼上2位

**Comment by tsukiikekaoru** [comment]
感谢楼上几位。我一开始还以为安装的时候要求设置的用户就是管理员。
原来admin才是管理员，安装时随机给的那位只是第一个用户。
