### ISSUE TITLE
请问trojan面板仅仅统计用户的下行流量吗？

### ISSUE THREAD

**Issue by inpowerchiu** [Jrohy/trojan#92]
今天给几台vps安装了这套脚本，想测试下流量限制功能，是否会大量中断时，发现trojan面板仅仅统计了下载流量，不统计上传流量。因为和多vps都采取双向流量计费的，我接触搭梯子不久，只听别人说过阿里云是单向上行计费，其他不知道，这个面板统计流量方式跟探针不同，请问是脚本设计成这样还是有bug啊？

**Comment by Jrohy** [comment]
这个向官方仓库反馈，什么时候算作流量来叠加以及限制，都是官方trojan核心说了算。面板只是方便来读取trojan处理后写到数据库里的结果
