### ISSUE TITLE
请问在已有trojan服务运行的vps上如何开启此面板

### ISSUE THREAD

**Issue by ChenNotFoundException** [Jrohy/trojan#93]

**Comment by Jrohy** [comment]
不支持

**Comment by aceslup** [comment]
> 不支持

确切的说是非完美支持。下载您的二进制管理程序，指定好配置文件/usr/local/etc/trojan/config.json（trojan-web写死去读这个文件了），同时也配置好mysql，使用 /usr/local/bin/trojan web，随后就能进入web面板进行用户管理了，但也仅仅能用用户管理。

同时想建议能给trojan管理程序加个读取trojan配置文件的参数，和用于面板是否对外提供服务的参数类似-h 127.0.0.1 -p 8080。
