### ISSUE TITLE
与宝塔面板不兼容

### ISSUE THREAD

**Issue by qq495679584** [Jrohy/trojan#94]
嗨~，VPS上安装宝塔，并使用了宝塔的lnmp环境。使用你的脚本后，无法登入您的trojan面板，提示没有内容。

**Comment by Jrohy** [comment]
最好独立环境安装

**Comment by qq495679584** [comment]
好的，谢谢您。

**Comment by zhiapp-com** [comment]
有没有并存解决方案呢？

**Comment by taochangle** [comment]
参考这个，改下端口即可
[go](https://github.com/Jrohy/trojan/wiki/%E4%BF%AE%E6%94%B9web%E7%AB%AF%E5%8F%A3)
