### ISSUE TITLE
关闭 重启 更新trojan遇到问题

### ISSUE THREAD

**Issue by AquariusCZ** [Jrohy/trojan#96]
大神您好 这个我已经安装好了 但是按照脚本提示关闭 重启 更新Trojan的时候会提示防火墙问题 具体是
“Failed to stop trojan.service: Interactive authentication required.
See system logs and 'systemctl status trojan.service' for details.”
这应该怎么设置呢
还有一个问题是 这个我装到了二级域名里 但这个域名和下面的所有二级域名都可以访问管理页面 是因为这些域名都在一个服务器上的缘故吗 ？（可能是弱智问题 小白提问 打扰了见谅）

**Comment by AquariusCZ** [comment]
我查过有人提到是root的问题 但我尝试使用 “sudo -i”获取root权限后 再次输入“trojan” 却显示命令无效

**Comment by Jrohy** [comment]
最好登录进去就是root用户来操作

**Comment by AquariusCZ** [comment]
> 最好登录进去就是root用户来操作

但是 您好 我用【sudo -i】获取root权限以后 trojan 的命令无效了
图一是没有root权限 图二是获得root权限后
真是不好意思 麻烦您了 望回复
<img width="681" alt="1" src="https://user-images.githubusercontent.com/48451231/79685360-e2b6da80-826a-11ea-8a52-737c2a6f4a08.png">
<img width="692" alt="2" src="https://user-images.githubusercontent.com/48451231/79685361-e3e80780-826a-11ea-8884-f59abbf14995.png">

**Comment by Jrohy** [comment]
用root用户来安装以及使用，没测试过非root用户

**Comment by aceslup** [comment]
> > 最好登录进去就是root用户来操作
> 
> 但是 您好 我用【sudo -i】获取root权限以后 trojan 的命令无效了
> 图一是没有root权限 图二是获得root权限后
> 真是不好意思 麻烦您了 望回复
> <img alt="1" width="681" src="https://user-images.githubusercontent.com/48451231/79685360-e2b6da80-826a-11ea-8a52-737c2a6f4a08.png">
> <img alt="2" width="692" src="https://user-images.githubusercontent.com/48451231/79685361-e3e80780-826a-11ea-8884-f59abbf14995.png">

切换root无命令，就使用命令的绝对路径执行：/usr/local/bin/trojan

**Comment by DaedalusT** [comment]
acme.sh的github有声明不要在sudo下运行，也就是签发证书，所以最好用root登陆，安装完毕，如果怕不安全，之后再禁止RootLogin就行了，不过自动续签证书的功能可能也无效了
