### ISSUE TITLE
重置web管理员密码有问题，2.6.5版本

### ISSUE THREAD

**Issue by sakz** [Jrohy/trojan#97]
欢迎使用trojan管理程序

1.trojan管理       	2.用户管理

3.安装管理           	4.web管理

5.查看配置           	6.生成json

请选择: 4

1.重置web管理员密码

请选择: 1
请输入admin用户密码: xxxxxxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x83c87e]

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x17, 0x0)
	/home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:1117 +0x3e
trojan/core.SetValue(0xbd3d95, 0xa, 0xc0001ed100, 0x38, 0xd33300, 0x11af818)
	/home/go/trojan/core/leveldb.go:28 +0xc5
trojan/trojan.ResetAdminPass()
	/home/go/trojan/trojan/web.go:27 +0x1c5
trojan/trojan.WebMenu()
	/home/go/trojan/trojan/web.go:16 +0xd1
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:62 +0x48c
trojan/cmd.glob..func6(0x11f7a20, 0x122e1b0, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x11f7a20, 0xc0000201d0, 0x0, 0x0, 0x11f7a20, 0xc0000201d0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x11f7a20, 0x443a4a, 0x11b6a40, 0xc000000300)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20

**Comment by Jrohy** [comment]
有没有在页面设置过Web密码呢

**Comment by Jrohy** [comment]
测了就算没在web页面设置密码也是能在终端重置密码的。

**Comment by Jrohy** [comment]
/var/lib/trojan-manager 你看下leveldb有没有创建到这个目录

**Comment by sakz** [comment]
> /var/lib/trojan-manager

创建到了。刚安装完是web页面进不去，然后我在终端重置报错，过一会web页面进去了，就设置密码，后面终端也能重置密码了。不知道为什么这样，没能复现。复现再反馈。

**Comment by seanhk** [comment]
我也出现了这个错误，具体还体现在无法连接trojan服务器，
会出现这样的[WAR]not trojan request, connecting to 127.0.0.1:80

**Comment by jmysr118** [comment]
> / var / lib / trojan-manager你看下leveldb有没有创建到这个目录

目前使用正常，但是你说的那个目录里的文件 没有哦。
