### ISSUE TITLE
如果两个用户的密码都一样就会出现问题

### ISSUE THREAD

**Issue by hudingwen** [Jrohy/trojan#98]
统计流量就成了翻倍了
还有就是用户1和用户2都是用的同一个连接

**Comment by Jrohy** [comment]
是的不要设置成同一个密码，trojan区分不出具体是哪个用户的

**Comment by hudingwen** [comment]
> 是的不要设置成同一个密码，trojan区分不出具体是哪个用户的

网站里面建议设计成用户的唯一值比如说guid对应的某个用户 然后再去对应Trojan 这样就好一些

**Comment by hudingwen** [comment]
> 是的不要设置成同一个密码，trojan区分不出具体是哪个用户的

想换Trojan感觉他还是不太完善  比如转发  cdn这些都不支持  一旦ip被强就没办法了 必须换服务器或者IP
